# Credit Card Fraud (ULB) - E2 weight sensitivity
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/MuhammadDevX/ML-Research-Dataset-Imbalance/blob/main/creditfraud/e2_weight_sensitivity/creditfraud_e2_weight_sensitivity.ipynb)

Answers reviewer R3 (one weighting configuration only) and tests the over-correction mechanism.

* Classifiers: LR, RF, XGB.
* Resampling ratio: [0.0, 0.5, 1.0] (0 = none; otherwise SMOTETomek to that minority:majority ratio).
* Positive-class weight = IR ** power, power in [0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0]
  (0 = none, 0.5 = sqrt-inverse, 1 = inverse frequency), plus weights recomputed after resampling.
* Each setting with and without threshold tuning (C).
* Hyperparameters are reused from `c0_none` (no resampling) and `c1_A_smotetomek` (with resampling).
  **Run those two notebooks first**; missing folds are tuned here, which is slower.
* Each row records `rho_eff`, the positive:negative loss mass the classifier sees.

**How to run on Colab**
1. Click the badge, then *Runtime > Run all*. Allow Google Drive access when asked.
2. Results are appended to Google Drive after every classifier/fold:
   `MyDrive/ML-Research-Dataset-Imbalance/creditfraud/e2_weight_sensitivity/results/creditfraud__e2_weight_sensitivity.csv`.
3. If the runtime disconnects, just *Run all* again: finished folds are skipped.
4. When it is complete, copy the CSV into the same path in the repository and commit it.

In [1]:
# ---- Setup: identical in every notebook. Do not edit. ----
import os, sys, subprocess
REPO_URL = "https://github.com/MuhammadDevX/ML-Research-Dataset-Imbalance.git"
BRANCH = "main"
try:
    import google.colab  # noqa: F401
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    REPO_ROOT = "/content/ML-Research-Dataset-Imbalance"
    if not os.path.isdir(REPO_ROOT):
        subprocess.run(["git", "clone", "--branch", BRANCH, REPO_URL, REPO_ROOT], check=True)
    else:
        subprocess.run(["git", "-C", REPO_ROOT, "pull", "--ff-only"], check=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r",
                    f"{REPO_ROOT}/requirements.txt"], check=True)
    from google.colab import drive
    drive.mount("/content/drive")
    # Results go to Google Drive so they survive a disconnect.
    os.environ.setdefault("RESULTS_ROOT", "/content/drive/MyDrive/ML-Research-Dataset-Imbalance")
else:
    REPO_ROOT = os.path.abspath(os.getcwd())
    while not os.path.isdir(os.path.join(REPO_ROOT, "common")):
        parent = os.path.dirname(REPO_ROOT)
        if parent == REPO_ROOT:
            raise RuntimeError("Open this notebook from inside the repository.")
        REPO_ROOT = parent

sys.path.insert(0, REPO_ROOT)
os.chdir(REPO_ROOT)
from common.env import check_environment
check_environment()

Environment OK: scikit-learn 1.9.1, imbalanced-learn 0.14.2, xgboost 3.4.1, lightgbm 4.7.0

In [2]:
DATASET = "creditfraud"
# Quick test run (2 folds, fewer classifiers and candidates): change the next line
# to  SMOKE = True . Its results go to a separate *__SMOKE.csv file and must never
# be used in the paper. Leave it as it is for the real run.
SMOKE = os.environ.get("SMOKE", "0") == "1"

In [3]:
from common.cv import run_e2
results = run_e2(DATASET, smoke=SMOKE)

Hyperparameters found: c0 70 folds, c1 70 folds. Missing ones are tuned here once with the same seed.
Writing to C:\Users\LENOVO\Desktop\Semester 6\Machine Learning\research\creditfraud\e2_weight_sensitivity\results\creditfraud__e2_weight_sensitivity.csv

[989/1560] RF        repeat 4 fold 1  macro-F1=0.8972  P1=0.896 R1=0.714  (29s)  [ratio 0.0, orig^0.0, C=0, rho=0.00]

[990/1560] RF        repeat 4 fold 1  macro-F1=0.9165  P1=0.833 R1=0.833  (77s)  [ratio 0.0, orig^0.0, C=1, rho=0.00]

[991/1560] RF        repeat 4 fold 1  macro-F1=0.9150  P1=0.880 R1=0.786  (31s)  [ratio 0.0, orig^0.25, C=0, rho=0.01]

[992/1560] RF        repeat 4 fold 1  macro-F1=0.9150  P1=0.880 R1=0.786  (83s)  [ratio 0.0, orig^0.25, C=1, rho=0.01]

[993/1560] RF        repeat 4 fold 1  macro-F1=0.9139  P1=0.890 R1=0.774  (26s)  [ratio 0.0, orig^0.5, C=0, rho=0.04]

[994/1560] RF        repeat 4 fold 1  macro-F1=0.9258  P1=0.885 R1=0.821  (72s)  [ratio 0.0, orig^0.5, C=1, rho=0.04]

[995/1560] RF        repeat 4 fold 1  macro-F1=0.9113  P1=0.878 R1=0.774  (22s)  [ratio 0.0, orig^0.75, C=0, rho=0.20]

[996/1560] RF        repeat 4 fold 1  macro-F1=0.9124  P1=0.868 R1=0.786  (57s)  [ratio 0.0, orig^0.75, C=1, rho=0.20]

[997/1560] RF        repeat 4 fold 1  macro-F1=0.9128  P1=0.901 R1=0.762  (11s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[998/1560] RF        repeat 4 fold 1  macro-F1=0.9134  P1=0.859 R1=0.798  (31s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[999/1560] RF        repeat 4 fold 1  macro-F1=0.9087  P1=0.867 R1=0.774  (5s)  [ratio 0.0, orig^1.25, C=0, rho=4.95]

[1000/1560] RF        repeat 4 fold 1  macro-F1=0.9120  P1=0.840 R1=0.810  (14s)  [ratio 0.0, orig^1.25, C=1, rho=4.95]

[1001/1560] RF        repeat 4 fold 1  macro-F1=0.9098  P1=0.857 R1=0.786  (3s)  [ratio 0.0, orig^1.5, C=0, rho=24.52]

[1002/1560] RF        repeat 4 fold 1  macro-F1=0.9134  P1=0.859 R1=0.798  (9s)  [ratio 0.0, orig^1.5, C=1, rho=24.52]

[1003/1560] RF        repeat 4 fold 1  macro-F1=0.5627  P1=0.073 R1=0.869  (3s)  [ratio 0.0, orig^2.0, C=0, rho=601.41]

[1004/1560] RF        repeat 4 fold 1  macro-F1=0.8685  P1=0.776 R1=0.702  (8s)  [ratio 0.0, orig^2.0, C=1, rho=601.41]

[1005/1560] RF        repeat 4 fold 1  macro-F1=0.9124  P1=0.868 R1=0.786  (66s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1006/1560] RF        repeat 4 fold 1  macro-F1=0.9124  P1=0.868 R1=0.786  (191s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1007/1560] RF        repeat 4 fold 1  macro-F1=0.8998  P1=0.815 R1=0.786  (62s)  [ratio 0.5, orig^0.25, C=0, rho=2.48]

[1008/1560] RF        repeat 4 fold 1  macro-F1=0.8998  P1=0.815 R1=0.786  (175s)  [ratio 0.5, orig^0.25, C=1, rho=2.48]

[1009/1560] RF        repeat 4 fold 1  macro-F1=0.8449  P1=0.602 R1=0.810  (56s)  [ratio 0.5, orig^0.5, C=0, rho=12.26]

[1010/1560] RF        repeat 4 fold 1  macro-F1=0.9061  P1=0.855 R1=0.774  (159s)  [ratio 0.5, orig^0.5, C=1, rho=12.26]

[1011/1560] RF        repeat 4 fold 1  macro-F1=0.6724  P1=0.217 R1=0.869  (61s)  [ratio 0.5, orig^0.75, C=0, rho=60.72]

[1012/1560] RF        repeat 4 fold 1  macro-F1=0.8016  P1=0.517 R1=0.726  (173s)  [ratio 0.5, orig^0.75, C=1, rho=60.72]

[1013/1560] RF        repeat 4 fold 1  macro-F1=0.5154  P1=0.029 R1=0.893  (62s)  [ratio 0.5, orig^1.0, C=0, rho=300.70]

[1014/1560] RF        repeat 4 fold 1  macro-F1=0.8138  P1=0.561 R1=0.714  (166s)  [ratio 0.5, orig^1.0, C=1, rho=300.70]

[1015/1560] RF        repeat 4 fold 1  macro-F1=0.4027  P1=0.005 R1=0.929  (27s)  [ratio 0.5, orig^1.25, C=0, rho=1489.10]

[1016/1560] RF        repeat 4 fold 1  macro-F1=0.8017  P1=0.537 R1=0.690  (113s)  [ratio 0.5, orig^1.25, C=1, rho=1489.10]

[1017/1560] RF        repeat 4 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (16s)  [ratio 0.5, orig^1.5, C=0, rho=7374.23]

[1018/1560] RF        repeat 4 fold 1  macro-F1=0.7853  P1=0.531 R1=0.619  (82s)  [ratio 0.5, orig^1.5, C=1, rho=7374.23]

[1019/1560] RF        repeat 4 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (5s)  [ratio 0.5, orig^2.0, C=0, rho=180843.15]

[1020/1560] RF        repeat 4 fold 1  macro-F1=0.5371  P1=0.046 R1=0.631  (53s)  [ratio 0.5, orig^2.0, C=1, rho=180843.15]

[1021/1560] RF        repeat 4 fold 1  macro-F1=0.9109  P1=0.848 R1=0.798  (47s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1022/1560] RF        repeat 4 fold 1  macro-F1=0.9061  P1=0.855 R1=0.774  (161s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1023/1560] RF        repeat 4 fold 1  macro-F1=0.9087  P1=0.867 R1=0.774  (123s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1024/1560] RF        repeat 4 fold 1  macro-F1=0.9098  P1=0.857 R1=0.786  (310s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1025/1560] RF        repeat 4 fold 1  macro-F1=0.8950  P1=0.795 R1=0.786  (124s)  [ratio 1.0, orig^0.25, C=0, rho=4.95]

[1026/1560] RF        repeat 4 fold 1  macro-F1=0.8998  P1=0.815 R1=0.786  (307s)  [ratio 1.0, orig^0.25, C=1, rho=4.95]

[1027/1560] RF        repeat 4 fold 1  macro-F1=0.8144  P1=0.515 R1=0.810  (123s)  [ratio 1.0, orig^0.5, C=0, rho=24.52]

[1028/1560] RF        repeat 4 fold 1  macro-F1=0.8799  P1=0.747 R1=0.774  (306s)  [ratio 1.0, orig^0.5, C=1, rho=24.52]

[1029/1560] RF        repeat 4 fold 1  macro-F1=0.6262  P1=0.152 R1=0.833  (131s)  [ratio 1.0, orig^0.75, C=0, rho=121.44]

[1030/1560] RF        repeat 4 fold 1  macro-F1=0.7986  P1=0.508 R1=0.726  (303s)  [ratio 1.0, orig^0.75, C=1, rho=121.44]

[1031/1560] RF        repeat 4 fold 1  macro-F1=0.4907  P1=0.016 R1=0.893  (116s)  [ratio 1.0, orig^1.0, C=0, rho=601.41]

[1032/1560] RF        repeat 4 fold 1  macro-F1=0.7894  P1=0.488 R1=0.714  (230s)  [ratio 1.0, orig^1.0, C=1, rho=601.41]

[1033/1560] RF        repeat 4 fold 1  macro-F1=0.3620  P1=0.004 R1=0.964  (100s)  [ratio 1.0, orig^1.25, C=0, rho=2978.26]

[1034/1560] RF        repeat 4 fold 1  macro-F1=0.8207  P1=0.667 R1=0.619  (185s)  [ratio 1.0, orig^1.25, C=1, rho=2978.26]

[1035/1560] RF        repeat 4 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (26s)  [ratio 1.0, orig^1.5, C=0, rho=14748.76]

[1036/1560] RF        repeat 4 fold 1  macro-F1=0.7459  P1=0.415 R1=0.607  (128s)  [ratio 1.0, orig^1.5, C=1, rho=14748.76]

[1037/1560] RF        repeat 4 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (6s)  [ratio 1.0, orig^2.0, C=0, rho=361693.55]

[1038/1560] RF        repeat 4 fold 1  macro-F1=0.5084  P1=0.022 R1=0.679  (83s)  [ratio 1.0, orig^2.0, C=1, rho=361693.55]

[1039/1560] RF        repeat 4 fold 1  macro-F1=0.9087  P1=0.867 R1=0.774  (66s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1040/1560] RF        repeat 4 fold 1  macro-F1=0.9098  P1=0.857 R1=0.786  (204s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1041/1560] XGB       repeat 0 fold 0  macro-F1=0.9148  P1=0.953 R1=0.735  (2s)  [ratio 0.0, orig^0.0, C=0, rho=0.00]

[1042/1560] XGB       repeat 0 fold 0  macro-F1=0.9188  P1=0.954 R1=0.747  (7s)  [ratio 0.0, orig^0.0, C=1, rho=0.00]

[1043/1560] XGB       repeat 0 fold 0  macro-F1=0.9266  P1=0.955 R1=0.771  (2s)  [ratio 0.0, orig^0.25, C=0, rho=0.01]

[1044/1560] XGB       repeat 0 fold 0  macro-F1=0.9227  P1=0.955 R1=0.759  (7s)  [ratio 0.0, orig^0.25, C=1, rho=0.01]

[1045/1560] XGB       repeat 0 fold 0  macro-F1=0.9176  P1=0.880 R1=0.795  (2s)  [ratio 0.0, orig^0.5, C=0, rho=0.04]

[1046/1560] XGB       repeat 0 fold 0  macro-F1=0.9217  P1=0.969 R1=0.747  (7s)  [ratio 0.0, orig^0.5, C=1, rho=0.04]

[1047/1560] XGB       repeat 0 fold 0  macro-F1=0.9249  P1=0.883 R1=0.819  (3s)  [ratio 0.0, orig^0.75, C=0, rho=0.20]

[1048/1560] XGB       repeat 0 fold 0  macro-F1=0.9206  P1=0.852 R1=0.831  (7s)  [ratio 0.0, orig^0.75, C=1, rho=0.20]

[1049/1560] XGB       repeat 0 fold 0  macro-F1=0.9120  P1=0.829 R1=0.819  (2s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1050/1560] XGB       repeat 0 fold 0  macro-F1=0.9145  P1=0.840 R1=0.819  (7s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1051/1560] XGB       repeat 0 fold 0  macro-F1=0.8975  P1=0.753 R1=0.843  (2s)  [ratio 0.0, orig^1.25, C=0, rho=4.94]

[1052/1560] XGB       repeat 0 fold 0  macro-F1=0.9106  P1=0.812 R1=0.831  (6s)  [ratio 0.0, orig^1.25, C=1, rho=4.94]

[1053/1560] XGB       repeat 0 fold 0  macro-F1=0.8107  P1=0.493 R1=0.843  (2s)  [ratio 0.0, orig^1.5, C=0, rho=24.38]

[1054/1560] XGB       repeat 0 fold 0  macro-F1=0.9059  P1=0.817 R1=0.807  (6s)  [ratio 0.0, orig^1.5, C=1, rho=24.38]

[1055/1560] XGB       repeat 0 fold 0  macro-F1=0.5128  P1=0.027 R1=0.916  (2s)  [ratio 0.0, orig^2.0, C=0, rho=594.24]

[1056/1560] XGB       repeat 0 fold 0  macro-F1=0.7060  P1=0.273 R1=0.855  (5s)  [ratio 0.0, orig^2.0, C=1, rho=594.24]

[1057/1560] XGB       repeat 0 fold 0  macro-F1=0.9134  P1=0.848 R1=0.807  (29s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1058/1560] XGB       repeat 0 fold 0  macro-F1=0.9108  P1=0.952 R1=0.723  (71s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1059/1560] XGB       repeat 0 fold 0  macro-F1=0.8835  P1=0.742 R1=0.795  (29s)  [ratio 0.5, orig^0.25, C=0, rho=2.47]

[1060/1560] XGB       repeat 0 fold 0  macro-F1=0.9037  P1=0.863 R1=0.759  (72s)  [ratio 0.5, orig^0.25, C=1, rho=2.47]

[1061/1560] XGB       repeat 0 fold 0  macro-F1=0.8547  P1=0.607 R1=0.855  (29s)  [ratio 0.5, orig^0.5, C=0, rho=12.19]

[1062/1560] XGB       repeat 0 fold 0  macro-F1=0.9090  P1=0.887 R1=0.759  (70s)  [ratio 0.5, orig^0.5, C=1, rho=12.19]

[1063/1560] XGB       repeat 0 fold 0  macro-F1=0.7042  P1=0.270 R1=0.855  (30s)  [ratio 0.5, orig^0.75, C=0, rho=60.18]

[1064/1560] XGB       repeat 0 fold 0  macro-F1=0.9087  P1=0.855 R1=0.783  (71s)  [ratio 0.5, orig^0.75, C=1, rho=60.18]

[1065/1560] XGB       repeat 0 fold 0  macro-F1=0.5468  P1=0.056 R1=0.892  (28s)  [ratio 0.5, orig^1.0, C=0, rho=297.12]

[1066/1560] XGB       repeat 0 fold 0  macro-F1=0.8151  P1=0.500 R1=0.855  (70s)  [ratio 0.5, orig^1.0, C=1, rho=297.12]

[1067/1560] XGB       repeat 0 fold 0  macro-F1=0.4680  P1=0.010 R1=0.952  (4s)  [ratio 0.5, orig^1.25, C=0, rho=1466.97]

[1068/1560] XGB       repeat 0 fold 0  macro-F1=0.5403  P1=0.050 R1=0.867  (45s)  [ratio 0.5, orig^1.25, C=1, rho=1466.97]

[1069/1560] XGB       repeat 0 fold 0  macro-F1=0.1763  P1=0.002 R1=0.976  (4s)  [ratio 0.5, orig^1.5, C=0, rho=7242.87]

[1070/1560] XGB       repeat 0 fold 0  macro-F1=0.1763  P1=0.002 R1=0.976  (47s)  [ratio 0.5, orig^1.5, C=1, rho=7242.87]

[1071/1560] XGB       repeat 0 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (3s)  [ratio 0.5, orig^2.0, C=0, rho=176559.46]

[1072/1560] XGB       repeat 0 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (46s)  [ratio 0.5, orig^2.0, C=1, rho=176559.46]

[1073/1560] XGB       repeat 0 fold 0  macro-F1=0.9023  P1=0.815 R1=0.795  (5s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1074/1560] XGB       repeat 0 fold 0  macro-F1=0.9055  P1=0.967 R1=0.699  (47s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1075/1560] XGB       repeat 0 fold 0  macro-F1=0.9036  P1=0.833 R1=0.783  (49s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1076/1560] XGB       repeat 0 fold 0  macro-F1=0.8999  P1=0.935 R1=0.699  (117s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1077/1560] XGB       repeat 0 fold 0  macro-F1=0.8762  P1=0.705 R1=0.807  (50s)  [ratio 1.0, orig^0.25, C=0, rho=4.94]

[1078/1560] XGB       repeat 0 fold 0  macro-F1=0.9065  P1=0.910 R1=0.735  (116s)  [ratio 1.0, orig^0.25, C=1, rho=4.94]

[1079/1560] XGB       repeat 0 fold 0  macro-F1=0.8093  P1=0.490 R1=0.843  (50s)  [ratio 1.0, orig^0.5, C=0, rho=24.38]

[1080/1560] XGB       repeat 0 fold 0  macro-F1=0.9128  P1=0.889 R1=0.771  (115s)  [ratio 1.0, orig^0.5, C=1, rho=24.38]

[1081/1560] XGB       repeat 0 fold 0  macro-F1=0.6458  P1=0.178 R1=0.867  (49s)  [ratio 1.0, orig^0.75, C=0, rho=120.36]

[1082/1560] XGB       repeat 0 fold 0  macro-F1=0.8975  P1=0.753 R1=0.843  (114s)  [ratio 1.0, orig^0.75, C=1, rho=120.36]

[1083/1560] XGB       repeat 0 fold 0  macro-F1=0.5210  P1=0.033 R1=0.892  (50s)  [ratio 1.0, orig^1.0, C=0, rho=594.24]

[1084/1560] XGB       repeat 0 fold 0  macro-F1=0.7066  P1=0.274 R1=0.855  (113s)  [ratio 1.0, orig^1.0, C=1, rho=594.24]

[1085/1560] XGB       repeat 0 fold 0  macro-F1=0.4400  P1=0.007 R1=0.952  (5s)  [ratio 1.0, orig^1.25, C=0, rho=2933.94]

[1086/1560] XGB       repeat 0 fold 0  macro-F1=0.5115  P1=1.000 R1=0.012  (73s)  [ratio 1.0, orig^1.25, C=1, rho=2933.94]

[1087/1560] XGB       repeat 0 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (4s)  [ratio 1.0, orig^1.5, C=0, rho=14485.74]

[1088/1560] XGB       repeat 0 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (70s)  [ratio 1.0, orig^1.5, C=1, rho=14485.74]

[1089/1560] XGB       repeat 0 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (4s)  [ratio 1.0, orig^2.0, C=0, rho=353118.91]

[1090/1560] XGB       repeat 0 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (69s)  [ratio 1.0, orig^2.0, C=1, rho=353118.91]

[1091/1560] XGB       repeat 0 fold 0  macro-F1=0.9036  P1=0.833 R1=0.783  (6s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1092/1560] XGB       repeat 0 fold 0  macro-F1=0.8999  P1=0.935 R1=0.699  (69s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1093/1560] XGB       repeat 0 fold 1  macro-F1=0.9285  P1=0.896 R1=0.821  (2s)  [ratio 0.0, orig^0.0, C=0, rho=0.00]

[1094/1560] XGB       repeat 0 fold 1  macro-F1=0.9326  P1=0.851 R1=0.881  (6s)  [ratio 0.0, orig^0.0, C=1, rho=0.00]

[1095/1560] XGB       repeat 0 fold 1  macro-F1=0.9320  P1=0.897 R1=0.833  (2s)  [ratio 0.0, orig^0.25, C=0, rho=0.01]

[1096/1560] XGB       repeat 0 fold 1  macro-F1=0.9355  P1=0.899 R1=0.845  (6s)  [ratio 0.0, orig^0.25, C=1, rho=0.01]

[1097/1560] XGB       repeat 0 fold 1  macro-F1=0.9355  P1=0.899 R1=0.845  (2s)  [ratio 0.0, orig^0.5, C=0, rho=0.04]

[1098/1560] XGB       repeat 0 fold 1  macro-F1=0.9363  P1=0.889 R1=0.857  (6s)  [ratio 0.0, orig^0.5, C=1, rho=0.04]

[1099/1560] XGB       repeat 0 fold 1  macro-F1=0.9416  P1=0.911 R1=0.857  (2s)  [ratio 0.0, orig^0.75, C=0, rho=0.20]

[1100/1560] XGB       repeat 0 fold 1  macro-F1=0.9416  P1=0.911 R1=0.857  (6s)  [ratio 0.0, orig^0.75, C=1, rho=0.20]

[1101/1560] XGB       repeat 0 fold 1  macro-F1=0.9336  P1=0.878 R1=0.857  (2s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1102/1560] XGB       repeat 0 fold 1  macro-F1=0.9336  P1=0.878 R1=0.857  (6s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1103/1560] XGB       repeat 0 fold 1  macro-F1=0.9170  P1=0.802 R1=0.869  (2s)  [ratio 0.0, orig^1.25, C=0, rho=4.95]

[1104/1560] XGB       repeat 0 fold 1  macro-F1=0.9100  P1=0.777 R1=0.869  (6s)  [ratio 0.0, orig^1.25, C=1, rho=4.95]

[1105/1560] XGB       repeat 0 fold 1  macro-F1=0.8832  P1=0.679 R1=0.881  (2s)  [ratio 0.0, orig^1.5, C=0, rho=24.52]

[1106/1560] XGB       repeat 0 fold 1  macro-F1=0.9234  P1=0.837 R1=0.857  (6s)  [ratio 0.0, orig^1.5, C=1, rho=24.52]

[1107/1560] XGB       repeat 0 fold 1  macro-F1=0.5579  P1=0.068 R1=0.917  (2s)  [ratio 0.0, orig^2.0, C=0, rho=601.41]

[1108/1560] XGB       repeat 0 fold 1  macro-F1=0.7285  P1=0.309 R1=0.893  (5s)  [ratio 0.0, orig^2.0, C=1, rho=601.41]

[1109/1560] XGB       repeat 0 fold 1  macro-F1=0.9010  P1=0.763 R1=0.845  (27s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1110/1560] XGB       repeat 0 fold 1  macro-F1=0.9155  P1=0.841 R1=0.821  (66s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1111/1560] XGB       repeat 0 fold 1  macro-F1=0.8795  P1=0.689 R1=0.845  (27s)  [ratio 0.5, orig^0.25, C=0, rho=2.48]

[1112/1560] XGB       repeat 0 fold 1  macro-F1=0.9239  P1=0.905 R1=0.798  (66s)  [ratio 0.5, orig^0.25, C=1, rho=2.48]

[1113/1560] XGB       repeat 0 fold 1  macro-F1=0.8425  P1=0.571 R1=0.857  (27s)  [ratio 0.5, orig^0.5, C=0, rho=12.26]

[1114/1560] XGB       repeat 0 fold 1  macro-F1=0.9106  P1=0.821 R1=0.821  (66s)  [ratio 0.5, orig^0.5, C=1, rho=12.26]

[1115/1560] XGB       repeat 0 fold 1  macro-F1=0.7551  P1=0.355 R1=0.917  (28s)  [ratio 0.5, orig^0.75, C=0, rho=60.72]

[1116/1560] XGB       repeat 0 fold 1  macro-F1=0.9141  P1=0.824 R1=0.833  (65s)  [ratio 0.5, orig^0.75, C=1, rho=60.72]

[1117/1560] XGB       repeat 0 fold 1  macro-F1=0.5926  P1=0.107 R1=0.917  (27s)  [ratio 0.5, orig^1.0, C=0, rho=300.70]

[1118/1560] XGB       repeat 0 fold 1  macro-F1=0.8196  P1=0.511 R1=0.857  (65s)  [ratio 0.5, orig^1.0, C=1, rho=300.70]

[1119/1560] XGB       repeat 0 fold 1  macro-F1=0.5113  P1=0.027 R1=0.952  (2s)  [ratio 0.5, orig^1.25, C=0, rho=1489.10]

[1120/1560] XGB       repeat 0 fold 1  macro-F1=0.5994  P1=0.115 R1=0.917  (40s)  [ratio 0.5, orig^1.25, C=1, rho=1489.10]

[1121/1560] XGB       repeat 0 fold 1  macro-F1=0.4388  P1=0.007 R1=0.952  (2s)  [ratio 0.5, orig^1.5, C=0, rho=7374.23]

[1122/1560] XGB       repeat 0 fold 1  macro-F1=0.5281  P1=0.073 R1=0.048  (40s)  [ratio 0.5, orig^1.5, C=1, rho=7374.23]

[1123/1560] XGB       repeat 0 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (2s)  [ratio 0.5, orig^2.0, C=0, rho=180843.15]

[1124/1560] XGB       repeat 0 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (41s)  [ratio 0.5, orig^2.0, C=1, rho=180843.15]

[1125/1560] XGB       repeat 0 fold 1  macro-F1=0.8848  P1=0.699 R1=0.857  (3s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1126/1560] XGB       repeat 0 fold 1  macro-F1=0.9170  P1=0.861 R1=0.810  (41s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1127/1560] XGB       repeat 0 fold 1  macro-F1=0.8953  P1=0.753 R1=0.833  (48s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1128/1560] XGB       repeat 0 fold 1  macro-F1=0.9180  P1=0.852 R1=0.821  (109s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1129/1560] XGB       repeat 0 fold 1  macro-F1=0.8741  P1=0.658 R1=0.869  (48s)  [ratio 1.0, orig^0.25, C=0, rho=4.95]

[1130/1560] XGB       repeat 0 fold 1  macro-F1=0.9190  P1=0.843 R1=0.833  (108s)  [ratio 1.0, orig^0.25, C=1, rho=4.95]

[1131/1560] XGB       repeat 0 fold 1  macro-F1=0.8360  P1=0.549 R1=0.869  (47s)  [ratio 1.0, orig^0.5, C=0, rho=24.52]

[1132/1560] XGB       repeat 0 fold 1  macro-F1=0.9045  P1=0.787 R1=0.833  (109s)  [ratio 1.0, orig^0.5, C=1, rho=24.52]

[1133/1560] XGB       repeat 0 fold 1  macro-F1=0.6952  P1=0.250 R1=0.917  (47s)  [ratio 1.0, orig^0.75, C=0, rho=121.44]

[1134/1560] XGB       repeat 0 fold 1  macro-F1=0.8734  P1=0.670 R1=0.845  (108s)  [ratio 1.0, orig^0.75, C=1, rho=121.44]

[1135/1560] XGB       repeat 0 fold 1  macro-F1=0.5698  P1=0.081 R1=0.929  (47s)  [ratio 1.0, orig^1.0, C=0, rho=601.41]

[1136/1560] XGB       repeat 0 fold 1  macro-F1=0.7537  P1=0.362 R1=0.857  (107s)  [ratio 1.0, orig^1.0, C=1, rho=601.41]

[1137/1560] XGB       repeat 0 fold 1  macro-F1=0.4959  P1=0.018 R1=0.940  (3s)  [ratio 1.0, orig^1.25, C=0, rho=2978.26]

[1138/1560] XGB       repeat 0 fold 1  macro-F1=0.5341  P1=1.000 R1=0.036  (67s)  [ratio 1.0, orig^1.25, C=1, rho=2978.26]

[1139/1560] XGB       repeat 0 fold 1  macro-F1=0.3979  P1=0.005 R1=0.952  (3s)  [ratio 1.0, orig^1.5, C=0, rho=14748.76]

[1140/1560] XGB       repeat 0 fold 1  macro-F1=0.5292  P1=0.060 R1=0.060  (63s)  [ratio 1.0, orig^1.5, C=1, rho=14748.76]

[1141/1560] XGB       repeat 0 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (3s)  [ratio 1.0, orig^2.0, C=0, rho=361693.55]

[1142/1560] XGB       repeat 0 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (63s)  [ratio 1.0, orig^2.0, C=1, rho=361693.55]

[1143/1560] XGB       repeat 0 fold 1  macro-F1=0.8953  P1=0.753 R1=0.833  (3s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1144/1560] XGB       repeat 0 fold 1  macro-F1=0.9180  P1=0.852 R1=0.821  (63s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1145/1560] XGB       repeat 1 fold 0  macro-F1=0.9386  P1=0.944 R1=0.819  (3s)  [ratio 0.0, orig^0.0, C=0, rho=0.00]

[1146/1560] XGB       repeat 1 fold 0  macro-F1=0.9250  P1=0.845 R1=0.855  (9s)  [ratio 0.0, orig^0.0, C=1, rho=0.00]

[1147/1560] XGB       repeat 1 fold 0  macro-F1=0.9203  P1=0.892 R1=0.795  (3s)  [ratio 0.0, orig^0.25, C=0, rho=0.01]

[1148/1560] XGB       repeat 1 fold 0  macro-F1=0.9170  P1=0.850 R1=0.819  (9s)  [ratio 0.0, orig^0.25, C=1, rho=0.01]

[1149/1560] XGB       repeat 1 fold 0  macro-F1=0.9366  P1=0.920 R1=0.831  (3s)  [ratio 0.0, orig^0.5, C=0, rho=0.04]

[1150/1560] XGB       repeat 1 fold 0  macro-F1=0.9374  P1=0.909 R1=0.843  (9s)  [ratio 0.0, orig^0.5, C=1, rho=0.04]

[1151/1560] XGB       repeat 1 fold 0  macro-F1=0.9320  P1=0.886 R1=0.843  (3s)  [ratio 0.0, orig^0.75, C=0, rho=0.20]

[1152/1560] XGB       repeat 1 fold 0  macro-F1=0.9243  P1=0.820 R1=0.880  (10s)  [ratio 0.0, orig^0.75, C=1, rho=0.20]

[1153/1560] XGB       repeat 1 fold 0  macro-F1=0.9276  P1=0.855 R1=0.855  (3s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1154/1560] XGB       repeat 1 fold 0  macro-F1=0.9250  P1=0.845 R1=0.855  (9s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1155/1560] XGB       repeat 1 fold 0  macro-F1=0.9200  P1=0.826 R1=0.855  (3s)  [ratio 0.0, orig^1.25, C=0, rho=4.94]

[1156/1560] XGB       repeat 1 fold 0  macro-F1=0.9102  P1=0.789 R1=0.855  (9s)  [ratio 0.0, orig^1.25, C=1, rho=4.94]

[1157/1560] XGB       repeat 1 fold 0  macro-F1=0.8965  P1=0.723 R1=0.880  (3s)  [ratio 0.0, orig^1.5, C=0, rho=24.38]

[1158/1560] XGB       repeat 1 fold 0  macro-F1=0.9285  P1=0.847 R1=0.867  (8s)  [ratio 0.0, orig^1.5, C=1, rho=24.38]

[1159/1560] XGB       repeat 1 fold 0  macro-F1=0.5790  P1=0.091 R1=0.916  (3s)  [ratio 0.0, orig^2.0, C=0, rho=594.24]

[1160/1560] XGB       repeat 1 fold 0  macro-F1=0.7484  P1=0.346 R1=0.892  (8s)  [ratio 0.0, orig^2.0, C=1, rho=594.24]

[1161/1560] XGB       repeat 1 fold 0  macro-F1=0.9141  P1=0.814 R1=0.843  (29s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1162/1560] XGB       repeat 1 fold 0  macro-F1=0.9109  P1=0.838 R1=0.807  (72s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1163/1560] XGB       repeat 1 fold 0  macro-F1=0.9160  P1=0.800 R1=0.867  (29s)  [ratio 0.5, orig^0.25, C=0, rho=2.47]

[1164/1560] XGB       repeat 1 fold 0  macro-F1=0.9230  P1=0.904 R1=0.795  (72s)  [ratio 0.5, orig^0.25, C=1, rho=2.47]

[1165/1560] XGB       repeat 1 fold 0  macro-F1=0.8890  P1=0.706 R1=0.867  (29s)  [ratio 0.5, orig^0.5, C=0, rho=12.19]

[1166/1560] XGB       repeat 1 fold 0  macro-F1=0.9160  P1=0.859 R1=0.807  (72s)  [ratio 0.5, orig^0.5, C=1, rho=12.19]

[1167/1560] XGB       repeat 1 fold 0  macro-F1=0.8102  P1=0.480 R1=0.880  (29s)  [ratio 0.5, orig^0.75, C=0, rho=60.18]

[1168/1560] XGB       repeat 1 fold 0  macro-F1=0.9216  P1=0.843 R1=0.843  (71s)  [ratio 0.5, orig^0.75, C=1, rho=60.18]

[1169/1560] XGB       repeat 1 fold 0  macro-F1=0.6432  P1=0.173 R1=0.904  (29s)  [ratio 0.5, orig^1.0, C=0, rho=297.12]

[1170/1560] XGB       repeat 1 fold 0  macro-F1=0.9043  P1=0.758 R1=0.867  (71s)  [ratio 0.5, orig^1.0, C=1, rho=297.12]

[1171/1560] XGB       repeat 1 fold 0  macro-F1=0.5292  P1=0.040 R1=0.928  (4s)  [ratio 0.5, orig^1.25, C=0, rho=1466.97]

[1172/1560] XGB       repeat 1 fold 0  macro-F1=0.6836  P1=0.232 R1=0.916  (45s)  [ratio 0.5, orig^1.25, C=1, rho=1466.97]

[1173/1560] XGB       repeat 1 fold 0  macro-F1=0.4567  P1=0.008 R1=0.964  (4s)  [ratio 0.5, orig^1.5, C=0, rho=7242.87]

[1174/1560] XGB       repeat 1 fold 0  macro-F1=0.5111  P1=0.250 R1=0.012  (45s)  [ratio 0.5, orig^1.5, C=1, rho=7242.87]

[1175/1560] XGB       repeat 1 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (3s)  [ratio 0.5, orig^2.0, C=0, rho=176559.46]

[1176/1560] XGB       repeat 1 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (46s)  [ratio 0.5, orig^2.0, C=1, rho=176559.46]

[1177/1560] XGB       repeat 1 fold 0  macro-F1=0.9180  P1=0.841 R1=0.831  (5s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1178/1560] XGB       repeat 1 fold 0  macro-F1=0.9180  P1=0.841 R1=0.831  (47s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1179/1560] XGB       repeat 1 fold 0  macro-F1=0.9106  P1=0.812 R1=0.831  (51s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1180/1560] XGB       repeat 1 fold 0  macro-F1=0.9109  P1=0.838 R1=0.807  (119s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1181/1560] XGB       repeat 1 fold 0  macro-F1=0.9045  P1=0.778 R1=0.843  (50s)  [ratio 1.0, orig^0.25, C=0, rho=4.94]

[1182/1560] XGB       repeat 1 fold 0  macro-F1=0.9203  P1=0.892 R1=0.795  (119s)  [ratio 1.0, orig^0.25, C=1, rho=4.94]

[1183/1560] XGB       repeat 1 fold 0  macro-F1=0.8652  P1=0.632 R1=0.867  (51s)  [ratio 1.0, orig^0.5, C=0, rho=24.38]

[1184/1560] XGB       repeat 1 fold 0  macro-F1=0.9155  P1=0.831 R1=0.831  (118s)  [ratio 1.0, orig^0.5, C=1, rho=24.38]

[1185/1560] XGB       repeat 1 fold 0  macro-F1=0.7600  P1=0.371 R1=0.880  (51s)  [ratio 1.0, orig^0.75, C=0, rho=120.36]

[1186/1560] XGB       repeat 1 fold 0  macro-F1=0.9165  P1=0.824 R1=0.843  (118s)  [ratio 1.0, orig^0.75, C=1, rho=120.36]

[1187/1560] XGB       repeat 1 fold 0  macro-F1=0.6011  P1=0.117 R1=0.928  (51s)  [ratio 1.0, orig^1.0, C=0, rho=594.24]

[1188/1560] XGB       repeat 1 fold 0  macro-F1=0.8709  P1=0.649 R1=0.867  (116s)  [ratio 1.0, orig^1.0, C=1, rho=594.24]

[1189/1560] XGB       repeat 1 fold 0  macro-F1=0.5113  P1=0.027 R1=0.928  (5s)  [ratio 1.0, orig^1.25, C=0, rho=2933.94]

[1190/1560] XGB       repeat 1 fold 0  macro-F1=0.6058  P1=0.123 R1=0.928  (75s)  [ratio 1.0, orig^1.25, C=1, rho=2933.94]

[1191/1560] XGB       repeat 1 fold 0  macro-F1=0.4253  P1=0.006 R1=0.964  (5s)  [ratio 1.0, orig^1.5, C=0, rho=14485.74]

[1192/1560] XGB       repeat 1 fold 0  macro-F1=0.6323  P1=0.378 R1=0.205  (71s)  [ratio 1.0, orig^1.5, C=1, rho=14485.74]

[1193/1560] XGB       repeat 1 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (4s)  [ratio 1.0, orig^2.0, C=0, rho=353118.91]

[1194/1560] XGB       repeat 1 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (71s)  [ratio 1.0, orig^2.0, C=1, rho=353118.91]

[1195/1560] XGB       repeat 1 fold 0  macro-F1=0.9106  P1=0.812 R1=0.831  (6s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1196/1560] XGB       repeat 1 fold 0  macro-F1=0.9109  P1=0.838 R1=0.807  (71s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1197/1560] XGB       repeat 1 fold 1  macro-F1=0.9132  P1=0.939 R1=0.738  (7s)  [ratio 0.0, orig^0.0, C=0, rho=0.00]

[1198/1560] XGB       repeat 1 fold 1  macro-F1=0.9132  P1=0.939 R1=0.738  (19s)  [ratio 0.0, orig^0.0, C=1, rho=0.00]

[1199/1560] XGB       repeat 1 fold 1  macro-F1=0.9209  P1=0.941 R1=0.762  (8s)  [ratio 0.0, orig^0.25, C=0, rho=0.01]

[1200/1560] XGB       repeat 1 fold 1  macro-F1=0.9209  P1=0.941 R1=0.762  (21s)  [ratio 0.0, orig^0.25, C=1, rho=0.01]

[1201/1560] XGB       repeat 1 fold 1  macro-F1=0.9182  P1=0.928 R1=0.762  (8s)  [ratio 0.0, orig^0.5, C=0, rho=0.04]

[1202/1560] XGB       repeat 1 fold 1  macro-F1=0.9171  P1=0.940 R1=0.750  (22s)  [ratio 0.0, orig^0.5, C=1, rho=0.04]

[1203/1560] XGB       repeat 1 fold 1  macro-F1=0.9101  P1=0.889 R1=0.762  (8s)  [ratio 0.0, orig^0.75, C=0, rho=0.20]

[1204/1560] XGB       repeat 1 fold 1  macro-F1=0.9093  P1=0.938 R1=0.726  (22s)  [ratio 0.0, orig^0.75, C=1, rho=0.20]

[1205/1560] XGB       repeat 1 fold 1  macro-F1=0.9176  P1=0.892 R1=0.786  (8s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1206/1560] XGB       repeat 1 fold 1  macro-F1=0.9090  P1=0.900 R1=0.750  (21s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1207/1560] XGB       repeat 1 fold 1  macro-F1=0.9206  P1=0.863 R1=0.821  (7s)  [ratio 0.0, orig^1.25, C=0, rho=4.95]

[1208/1560] XGB       repeat 1 fold 1  macro-F1=0.9128  P1=0.901 R1=0.762  (20s)  [ratio 0.0, orig^1.25, C=1, rho=4.95]

[1209/1560] XGB       repeat 1 fold 1  macro-F1=0.8606  P1=0.636 R1=0.833  (7s)  [ratio 0.0, orig^1.5, C=0, rho=24.52]

[1210/1560] XGB       repeat 1 fold 1  macro-F1=0.9113  P1=0.878 R1=0.774  (19s)  [ratio 0.0, orig^1.5, C=1, rho=24.52]

[1211/1560] XGB       repeat 1 fold 1  macro-F1=0.5179  P1=0.031 R1=0.929  (6s)  [ratio 0.0, orig^2.0, C=0, rho=601.41]

[1212/1560] XGB       repeat 1 fold 1  macro-F1=0.6940  P1=0.252 R1=0.869  (16s)  [ratio 0.0, orig^2.0, C=1, rho=601.41]

[1213/1560] XGB       repeat 1 fold 1  macro-F1=0.9230  P1=0.917 R1=0.786  (33s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1214/1560] XGB       repeat 1 fold 1  macro-F1=0.9171  P1=0.940 R1=0.750  (83s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1215/1560] XGB       repeat 1 fold 1  macro-F1=0.9176  P1=0.892 R1=0.786  (33s)  [ratio 0.5, orig^0.25, C=0, rho=2.48]

[1216/1560] XGB       repeat 1 fold 1  macro-F1=0.9171  P1=0.940 R1=0.750  (84s)  [ratio 0.5, orig^0.25, C=1, rho=2.48]

[1217/1560] XGB       repeat 1 fold 1  macro-F1=0.8929  P1=0.764 R1=0.810  (33s)  [ratio 0.5, orig^0.5, C=0, rho=12.26]

[1218/1560] XGB       repeat 1 fold 1  macro-F1=0.9171  P1=0.940 R1=0.750  (82s)  [ratio 0.5, orig^0.5, C=1, rho=12.26]

[1219/1560] XGB       repeat 1 fold 1  macro-F1=0.8299  P1=0.542 R1=0.845  (32s)  [ratio 0.5, orig^0.75, C=0, rho=60.72]

[1220/1560] XGB       repeat 1 fold 1  macro-F1=0.9150  P1=0.880 R1=0.786  (82s)  [ratio 0.5, orig^0.75, C=1, rho=60.72]

[1221/1560] XGB       repeat 1 fold 1  macro-F1=0.6687  P1=0.212 R1=0.869  (32s)  [ratio 0.5, orig^1.0, C=0, rho=300.70]

[1222/1560] XGB       repeat 1 fold 1  macro-F1=0.8880  P1=0.767 R1=0.786  (81s)  [ratio 0.5, orig^1.0, C=1, rho=300.70]

[1223/1560] XGB       repeat 1 fold 1  macro-F1=0.5335  P1=0.044 R1=0.905  (7s)  [ratio 0.5, orig^1.25, C=0, rho=1489.10]

[1224/1560] XGB       repeat 1 fold 1  macro-F1=0.7097  P1=0.281 R1=0.845  (55s)  [ratio 0.5, orig^1.25, C=1, rho=1489.10]

[1225/1560] XGB       repeat 1 fold 1  macro-F1=0.4615  P1=0.009 R1=0.964  (7s)  [ratio 0.5, orig^1.5, C=0, rho=7374.23]

[1226/1560] XGB       repeat 1 fold 1  macro-F1=0.5271  P1=0.038 R1=0.881  (54s)  [ratio 0.5, orig^1.5, C=1, rho=7374.23]

[1227/1560] XGB       repeat 1 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (6s)  [ratio 0.5, orig^2.0, C=0, rho=180843.15]

[1228/1560] XGB       repeat 1 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (55s)  [ratio 0.5, orig^2.0, C=1, rho=180843.15]

[1229/1560] XGB       repeat 1 fold 1  macro-F1=0.9230  P1=0.917 R1=0.786  (9s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1230/1560] XGB       repeat 1 fold 1  macro-F1=0.9132  P1=0.939 R1=0.738  (59s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1231/1560] XGB       repeat 1 fold 1  macro-F1=0.9192  P1=0.915 R1=0.774  (55s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1232/1560] XGB       repeat 1 fold 1  macro-F1=0.9132  P1=0.939 R1=0.738  (133s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1233/1560] XGB       repeat 1 fold 1  macro-F1=0.9134  P1=0.859 R1=0.798  (56s)  [ratio 1.0, orig^0.25, C=0, rho=4.95]

[1234/1560] XGB       repeat 1 fold 1  macro-F1=0.9132  P1=0.939 R1=0.738  (132s)  [ratio 1.0, orig^0.25, C=1, rho=4.95]

[1235/1560] XGB       repeat 1 fold 1  macro-F1=0.8853  P1=0.726 R1=0.821  (55s)  [ratio 1.0, orig^0.5, C=0, rho=24.52]

[1236/1560] XGB       repeat 1 fold 1  macro-F1=0.9220  P1=0.929 R1=0.774  (131s)  [ratio 1.0, orig^0.5, C=1, rho=24.52]

[1237/1560] XGB       repeat 1 fold 1  macro-F1=0.7946  P1=0.450 R1=0.857  (55s)  [ratio 1.0, orig^0.75, C=0, rho=121.44]

[1238/1560] XGB       repeat 1 fold 1  macro-F1=0.9124  P1=0.868 R1=0.786  (129s)  [ratio 1.0, orig^0.75, C=1, rho=121.44]

[1239/1560] XGB       repeat 1 fold 1  macro-F1=0.6198  P1=0.142 R1=0.893  (55s)  [ratio 1.0, orig^1.0, C=0, rho=601.41]

[1240/1560] XGB       repeat 1 fold 1  macro-F1=0.8748  P1=0.690 R1=0.821  (124s)  [ratio 1.0, orig^1.0, C=1, rho=601.41]

[1241/1560] XGB       repeat 1 fold 1  macro-F1=0.5130  P1=0.028 R1=0.917  (9s)  [ratio 1.0, orig^1.25, C=0, rho=2978.26]

[1242/1560] XGB       repeat 1 fold 1  macro-F1=0.6253  P1=0.149 R1=0.869  (85s)  [ratio 1.0, orig^1.25, C=1, rho=2978.26]

[1243/1560] XGB       repeat 1 fold 1  macro-F1=0.4262  P1=0.006 R1=0.964  (9s)  [ratio 1.0, orig^1.5, C=0, rho=14748.76]

[1244/1560] XGB       repeat 1 fold 1  macro-F1=0.5924  P1=0.692 R1=0.107  (79s)  [ratio 1.0, orig^1.5, C=1, rho=14748.76]

[1245/1560] XGB       repeat 1 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (7s)  [ratio 1.0, orig^2.0, C=0, rho=361693.55]

[1246/1560] XGB       repeat 1 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (80s)  [ratio 1.0, orig^2.0, C=1, rho=361693.55]

[1247/1560] XGB       repeat 1 fold 1  macro-F1=0.9192  P1=0.915 R1=0.774  (11s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1248/1560] XGB       repeat 1 fold 1  macro-F1=0.9132  P1=0.939 R1=0.738  (81s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1249/1560] XGB       repeat 2 fold 0  macro-F1=0.9128  P1=0.889 R1=0.771  (3s)  [ratio 0.0, orig^0.0, C=0, rho=0.00]

[1250/1560] XGB       repeat 2 fold 0  macro-F1=0.9128  P1=0.889 R1=0.771  (9s)  [ratio 0.0, orig^0.0, C=1, rho=0.00]

[1251/1560] XGB       repeat 2 fold 0  macro-F1=0.9113  P1=0.867 R1=0.783  (3s)  [ratio 0.0, orig^0.25, C=0, rho=0.01]

[1252/1560] XGB       repeat 2 fold 0  macro-F1=0.9101  P1=0.877 R1=0.771  (9s)  [ratio 0.0, orig^0.25, C=1, rho=0.01]

[1253/1560] XGB       repeat 2 fold 0  macro-F1=0.9048  P1=0.825 R1=0.795  (3s)  [ratio 0.0, orig^0.5, C=0, rho=0.04]

[1254/1560] XGB       repeat 2 fold 0  macro-F1=0.9098  P1=0.846 R1=0.795  (10s)  [ratio 0.0, orig^0.5, C=1, rho=0.04]

[1255/1560] XGB       repeat 2 fold 0  macro-F1=0.9120  P1=0.829 R1=0.819  (3s)  [ratio 0.0, orig^0.75, C=0, rho=0.20]

[1256/1560] XGB       repeat 2 fold 0  macro-F1=0.9109  P1=0.838 R1=0.807  (10s)  [ratio 0.0, orig^0.75, C=1, rho=0.20]

[1257/1560] XGB       repeat 2 fold 0  macro-F1=0.9010  P1=0.775 R1=0.831  (3s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1258/1560] XGB       repeat 2 fold 0  macro-F1=0.9048  P1=0.825 R1=0.795  (9s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1259/1560] XGB       repeat 2 fold 0  macro-F1=0.8430  P1=0.585 R1=0.831  (3s)  [ratio 0.0, orig^1.25, C=0, rho=4.94]

[1260/1560] XGB       repeat 2 fold 0  macro-F1=0.9087  P1=0.855 R1=0.783  (9s)  [ratio 0.0, orig^1.25, C=1, rho=4.94]

[1261/1560] XGB       repeat 2 fold 0  macro-F1=0.6668  P1=0.209 R1=0.855  (3s)  [ratio 0.0, orig^1.5, C=0, rho=24.38]

[1262/1560] XGB       repeat 2 fold 0  macro-F1=0.9023  P1=0.815 R1=0.795  (9s)  [ratio 0.0, orig^1.5, C=1, rho=24.38]

[1263/1560] XGB       repeat 2 fold 0  macro-F1=0.4856  P1=0.014 R1=0.916  (3s)  [ratio 0.0, orig^2.0, C=0, rho=594.24]

[1264/1560] XGB       repeat 2 fold 0  macro-F1=0.6540  P1=0.191 R1=0.843  (9s)  [ratio 0.0, orig^2.0, C=1, rho=594.24]

[1265/1560] XGB       repeat 2 fold 0  macro-F1=0.9170  P1=0.850 R1=0.819  (30s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1266/1560] XGB       repeat 2 fold 0  macro-F1=0.9239  P1=0.893 R1=0.807  (71s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1267/1560] XGB       repeat 2 fold 0  macro-F1=0.9046  P1=0.800 R1=0.819  (29s)  [ratio 0.5, orig^0.25, C=0, rho=2.47]

[1268/1560] XGB       repeat 2 fold 0  macro-F1=0.9209  P1=0.928 R1=0.771  (71s)  [ratio 0.5, orig^0.25, C=1, rho=2.47]

[1269/1560] XGB       repeat 2 fold 0  macro-F1=0.8687  P1=0.663 R1=0.831  (29s)  [ratio 0.5, orig^0.5, C=0, rho=12.19]

[1270/1560] XGB       repeat 2 fold 0  macro-F1=0.9150  P1=0.868 R1=0.795  (71s)  [ratio 0.5, orig^0.5, C=1, rho=12.19]

[1271/1560] XGB       repeat 2 fold 0  macro-F1=0.7475  P1=0.352 R1=0.843  (29s)  [ratio 0.5, orig^0.75, C=0, rho=60.18]

[1272/1560] XGB       repeat 2 fold 0  macro-F1=0.9196  P1=0.861 R1=0.819  (71s)  [ratio 0.5, orig^0.75, C=1, rho=60.18]

[1273/1560] XGB       repeat 2 fold 0  macro-F1=0.5721  P1=0.084 R1=0.855  (29s)  [ratio 0.5, orig^1.0, C=0, rho=297.12]

[1274/1560] XGB       repeat 2 fold 0  macro-F1=0.8748  P1=0.683 R1=0.831  (71s)  [ratio 0.5, orig^1.0, C=1, rho=297.12]

[1275/1560] XGB       repeat 2 fold 0  macro-F1=0.4935  P1=0.017 R1=0.940  (4s)  [ratio 0.5, orig^1.25, C=0, rho=1466.97]

[1276/1560] XGB       repeat 2 fold 0  macro-F1=0.5894  P1=0.104 R1=0.855  (45s)  [ratio 0.5, orig^1.25, C=1, rho=1466.97]

[1277/1560] XGB       repeat 2 fold 0  macro-F1=0.3316  P1=0.003 R1=0.976  (4s)  [ratio 0.5, orig^1.5, C=0, rho=7242.87]

[1278/1560] XGB       repeat 2 fold 0  macro-F1=0.5914  P1=0.600 R1=0.108  (44s)  [ratio 0.5, orig^1.5, C=1, rho=7242.87]

[1279/1560] XGB       repeat 2 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (3s)  [ratio 0.5, orig^2.0, C=0, rho=176559.46]

[1280/1560] XGB       repeat 2 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (46s)  [ratio 0.5, orig^2.0, C=1, rho=176559.46]

[1281/1560] XGB       repeat 2 fold 0  macro-F1=0.9120  P1=0.829 R1=0.819  (5s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1282/1560] XGB       repeat 2 fold 0  macro-F1=0.9176  P1=0.880 R1=0.795  (47s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1283/1560] XGB       repeat 2 fold 0  macro-F1=0.9095  P1=0.819 R1=0.819  (50s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1284/1560] XGB       repeat 2 fold 0  macro-F1=0.9213  P1=0.882 R1=0.807  (117s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1285/1560] XGB       repeat 2 fold 0  macro-F1=0.9046  P1=0.800 R1=0.819  (51s)  [ratio 1.0, orig^0.25, C=0, rho=4.94]

[1286/1560] XGB       repeat 2 fold 0  macro-F1=0.9150  P1=0.868 R1=0.795  (116s)  [ratio 1.0, orig^0.25, C=1, rho=4.94]

[1287/1560] XGB       repeat 2 fold 0  macro-F1=0.8447  P1=0.590 R1=0.831  (49s)  [ratio 1.0, orig^0.5, C=0, rho=24.38]

[1288/1560] XGB       repeat 2 fold 0  macro-F1=0.9150  P1=0.868 R1=0.795  (115s)  [ratio 1.0, orig^0.5, C=1, rho=24.38]

[1289/1560] XGB       repeat 2 fold 0  macro-F1=0.7031  P1=0.269 R1=0.843  (51s)  [ratio 1.0, orig^0.75, C=0, rho=120.36]

[1290/1560] XGB       repeat 2 fold 0  macro-F1=0.9035  P1=0.807 R1=0.807  (115s)  [ratio 1.0, orig^0.75, C=1, rho=120.36]

[1291/1560] XGB       repeat 2 fold 0  macro-F1=0.5469  P1=0.057 R1=0.892  (49s)  [ratio 1.0, orig^1.0, C=0, rho=594.24]

[1292/1560] XGB       repeat 2 fold 0  macro-F1=0.7823  P1=0.429 R1=0.831  (113s)  [ratio 1.0, orig^1.0, C=1, rho=594.24]

[1293/1560] XGB       repeat 2 fold 0  macro-F1=0.4727  P1=0.011 R1=0.940  (5s)  [ratio 1.0, orig^1.25, C=0, rho=2933.94]

[1294/1560] XGB       repeat 2 fold 0  macro-F1=0.5663  P1=0.857 R1=0.072  (72s)  [ratio 1.0, orig^1.25, C=1, rho=2933.94]

[1295/1560] XGB       repeat 2 fold 0  macro-F1=0.1279  P1=0.002 R1=1.000  (4s)  [ratio 1.0, orig^1.5, C=0, rho=14485.74]

[1296/1560] XGB       repeat 2 fold 0  macro-F1=0.1279  P1=0.002 R1=1.000  (70s)  [ratio 1.0, orig^1.5, C=1, rho=14485.74]

[1297/1560] XGB       repeat 2 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (4s)  [ratio 1.0, orig^2.0, C=0, rho=353118.91]

[1298/1560] XGB       repeat 2 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (69s)  [ratio 1.0, orig^2.0, C=1, rho=353118.91]

[1299/1560] XGB       repeat 2 fold 0  macro-F1=0.9095  P1=0.819 R1=0.819  (6s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1300/1560] XGB       repeat 2 fold 0  macro-F1=0.9213  P1=0.882 R1=0.807  (69s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1301/1560] XGB       repeat 2 fold 1  macro-F1=0.9247  P1=0.942 R1=0.774  (5s)  [ratio 0.0, orig^0.0, C=0, rho=0.00]

[1302/1560] XGB       repeat 2 fold 1  macro-F1=0.9213  P1=0.893 R1=0.798  (15s)  [ratio 0.0, orig^0.0, C=1, rho=0.00]

[1303/1560] XGB       repeat 2 fold 1  macro-F1=0.9294  P1=0.931 R1=0.798  (5s)  [ratio 0.0, orig^0.25, C=0, rho=0.01]

[1304/1560] XGB       repeat 2 fold 1  macro-F1=0.9257  P1=0.930 R1=0.786  (15s)  [ratio 0.0, orig^0.25, C=1, rho=0.01]

[1305/1560] XGB       repeat 2 fold 1  macro-F1=0.9267  P1=0.875 R1=0.833  (5s)  [ratio 0.0, orig^0.5, C=0, rho=0.04]

[1306/1560] XGB       repeat 2 fold 1  macro-F1=0.9252  P1=0.822 R1=0.881  (15s)  [ratio 0.0, orig^0.5, C=1, rho=0.04]

[1307/1560] XGB       repeat 2 fold 1  macro-F1=0.9423  P1=0.901 R1=0.869  (5s)  [ratio 0.0, orig^0.75, C=0, rho=0.20]

[1308/1560] XGB       repeat 2 fold 1  macro-F1=0.9301  P1=0.841 R1=0.881  (15s)  [ratio 0.0, orig^0.75, C=1, rho=0.20]

[1309/1560] XGB       repeat 2 fold 1  macro-F1=0.9404  P1=0.881 R1=0.881  (5s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1310/1560] XGB       repeat 2 fold 1  macro-F1=0.9404  P1=0.881 R1=0.881  (15s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1311/1560] XGB       repeat 2 fold 1  macro-F1=0.9284  P1=0.824 R1=0.893  (5s)  [ratio 0.0, orig^1.25, C=0, rho=4.95]

[1312/1560] XGB       repeat 2 fold 1  macro-F1=0.9385  P1=0.862 R1=0.893  (14s)  [ratio 0.0, orig^1.25, C=1, rho=4.95]

[1313/1560] XGB       repeat 2 fold 1  macro-F1=0.8977  P1=0.710 R1=0.905  (5s)  [ratio 0.0, orig^1.5, C=0, rho=24.52]

[1314/1560] XGB       repeat 2 fold 1  macro-F1=0.9344  P1=0.869 R1=0.869  (14s)  [ratio 0.0, orig^1.5, C=1, rho=24.52]

[1315/1560] XGB       repeat 2 fold 1  macro-F1=0.5981  P1=0.114 R1=0.929  (4s)  [ratio 0.0, orig^2.0, C=0, rho=601.41]

[1316/1560] XGB       repeat 2 fold 1  macro-F1=0.8035  P1=0.458 R1=0.905  (13s)  [ratio 0.0, orig^2.0, C=1, rho=601.41]

[1317/1560] XGB       repeat 2 fold 1  macro-F1=0.9243  P1=0.830 R1=0.869  (29s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1318/1560] XGB       repeat 2 fold 1  macro-F1=0.9160  P1=0.870 R1=0.798  (71s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1319/1560] XGB       repeat 2 fold 1  macro-F1=0.8893  P1=0.698 R1=0.881  (29s)  [ratio 0.5, orig^0.25, C=0, rho=2.48]

[1320/1560] XGB       repeat 2 fold 1  macro-F1=0.9389  P1=0.900 R1=0.857  (71s)  [ratio 0.5, orig^0.25, C=1, rho=2.48]

[1321/1560] XGB       repeat 2 fold 1  macro-F1=0.8471  P1=0.574 R1=0.881  (29s)  [ratio 0.5, orig^0.5, C=0, rho=12.26]

[1322/1560] XGB       repeat 2 fold 1  macro-F1=0.9416  P1=0.911 R1=0.857  (71s)  [ratio 0.5, orig^0.5, C=1, rho=12.26]

[1323/1560] XGB       repeat 2 fold 1  macro-F1=0.7695  P1=0.383 R1=0.917  (29s)  [ratio 0.5, orig^0.75, C=0, rho=60.72]

[1324/1560] XGB       repeat 2 fold 1  macro-F1=0.9227  P1=0.813 R1=0.881  (70s)  [ratio 0.5, orig^0.75, C=1, rho=60.72]

[1325/1560] XGB       repeat 2 fold 1  macro-F1=0.6023  P1=0.119 R1=0.929  (29s)  [ratio 0.5, orig^1.0, C=0, rho=300.70]

[1326/1560] XGB       repeat 2 fold 1  macro-F1=0.8529  P1=0.607 R1=0.845  (71s)  [ratio 0.5, orig^1.0, C=1, rho=300.70]

[1327/1560] XGB       repeat 2 fold 1  macro-F1=0.5230  P1=0.035 R1=0.940  (4s)  [ratio 0.5, orig^1.25, C=0, rho=1489.10]

[1328/1560] XGB       repeat 2 fold 1  macro-F1=0.6478  P1=0.179 R1=0.905  (45s)  [ratio 0.5, orig^1.25, C=1, rho=1489.10]

[1329/1560] XGB       repeat 2 fold 1  macro-F1=0.4593  P1=0.009 R1=0.964  (4s)  [ratio 0.5, orig^1.5, C=0, rho=7374.23]

[1330/1560] XGB       repeat 2 fold 1  macro-F1=0.5376  P1=0.106 R1=0.060  (44s)  [ratio 0.5, orig^1.5, C=1, rho=7374.23]

[1331/1560] XGB       repeat 2 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (3s)  [ratio 0.5, orig^2.0, C=0, rho=180843.15]

[1332/1560] XGB       repeat 2 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (46s)  [ratio 0.5, orig^2.0, C=1, rho=180843.15]

[1333/1560] XGB       repeat 2 fold 1  macro-F1=0.9064  P1=0.755 R1=0.881  (4s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1334/1560] XGB       repeat 2 fold 1  macro-F1=0.9276  P1=0.831 R1=0.881  (46s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1335/1560] XGB       repeat 2 fold 1  macro-F1=0.9087  P1=0.763 R1=0.881  (50s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1336/1560] XGB       repeat 2 fold 1  macro-F1=0.9257  P1=0.930 R1=0.786  (116s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1337/1560] XGB       repeat 2 fold 1  macro-F1=0.8913  P1=0.705 R1=0.881  (50s)  [ratio 1.0, orig^0.25, C=0, rho=4.95]

[1338/1560] XGB       repeat 2 fold 1  macro-F1=0.9257  P1=0.930 R1=0.786  (116s)  [ratio 1.0, orig^0.25, C=1, rho=4.95]

[1339/1560] XGB       repeat 2 fold 1  macro-F1=0.8421  P1=0.556 R1=0.893  (50s)  [ratio 1.0, orig^0.5, C=0, rho=24.52]

[1340/1560] XGB       repeat 2 fold 1  macro-F1=0.9363  P1=0.889 R1=0.857  (117s)  [ratio 1.0, orig^0.5, C=1, rho=24.52]

[1341/1560] XGB       repeat 2 fold 1  macro-F1=0.7196  P1=0.293 R1=0.893  (50s)  [ratio 1.0, orig^0.75, C=0, rho=121.44]

[1342/1560] XGB       repeat 2 fold 1  macro-F1=0.8376  P1=0.553 R1=0.869  (114s)  [ratio 1.0, orig^0.75, C=1, rho=121.44]

[1343/1560] XGB       repeat 2 fold 1  macro-F1=0.5478  P1=0.058 R1=0.929  (51s)  [ratio 1.0, orig^1.0, C=0, rho=601.41]

[1344/1560] XGB       repeat 2 fold 1  macro-F1=0.5758  P1=0.087 R1=0.929  (114s)  [ratio 1.0, orig^1.0, C=1, rho=601.41]

[1345/1560] XGB       repeat 2 fold 1  macro-F1=0.5091  P1=0.025 R1=0.940  (5s)  [ratio 1.0, orig^1.25, C=0, rho=2978.26]

[1346/1560] XGB       repeat 2 fold 1  macro-F1=0.6022  P1=0.119 R1=0.929  (74s)  [ratio 1.0, orig^1.25, C=1, rho=2978.26]

[1347/1560] XGB       repeat 2 fold 1  macro-F1=0.4216  P1=0.006 R1=0.976  (5s)  [ratio 1.0, orig^1.5, C=0, rho=14748.76]

[1348/1560] XGB       repeat 2 fold 1  macro-F1=0.5492  P1=0.094 R1=0.107  (68s)  [ratio 1.0, orig^1.5, C=1, rho=14748.76]

[1349/1560] XGB       repeat 2 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (4s)  [ratio 1.0, orig^2.0, C=0, rho=361693.55]

[1350/1560] XGB       repeat 2 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (69s)  [ratio 1.0, orig^2.0, C=1, rho=361693.55]

[1351/1560] XGB       repeat 2 fold 1  macro-F1=0.9087  P1=0.763 R1=0.881  (5s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1352/1560] XGB       repeat 2 fold 1  macro-F1=0.9257  P1=0.930 R1=0.786  (68s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1353/1560] XGB       repeat 3 fold 0  macro-F1=0.9374  P1=0.909 R1=0.843  (2s)  [ratio 0.0, orig^0.0, C=0, rho=0.00]

[1354/1560] XGB       repeat 3 fold 0  macro-F1=0.9409  P1=0.910 R1=0.855  (6s)  [ratio 0.0, orig^0.0, C=1, rho=0.00]

[1355/1560] XGB       repeat 3 fold 0  macro-F1=0.9203  P1=0.892 R1=0.795  (2s)  [ratio 0.0, orig^0.25, C=0, rho=0.01]

[1356/1560] XGB       repeat 3 fold 0  macro-F1=0.9196  P1=0.861 R1=0.819  (6s)  [ratio 0.0, orig^0.25, C=1, rho=0.01]

[1357/1560] XGB       repeat 3 fold 0  macro-F1=0.9382  P1=0.899 R1=0.855  (2s)  [ratio 0.0, orig^0.5, C=0, rho=0.04]

[1358/1560] XGB       repeat 3 fold 0  macro-F1=0.9294  P1=0.918 R1=0.807  (6s)  [ratio 0.0, orig^0.5, C=1, rho=0.04]

[1359/1560] XGB       repeat 3 fold 0  macro-F1=0.9320  P1=0.886 R1=0.843  (2s)  [ratio 0.0, orig^0.75, C=0, rho=0.20]

[1360/1560] XGB       repeat 3 fold 0  macro-F1=0.9355  P1=0.887 R1=0.855  (6s)  [ratio 0.0, orig^0.75, C=1, rho=0.20]

[1361/1560] XGB       repeat 3 fold 0  macro-F1=0.9363  P1=0.878 R1=0.867  (2s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1362/1560] XGB       repeat 3 fold 0  macro-F1=0.9230  P1=0.904 R1=0.795  (6s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1363/1560] XGB       repeat 3 fold 0  macro-F1=0.9334  P1=0.833 R1=0.904  (2s)  [ratio 0.0, orig^1.25, C=0, rho=4.94]

[1364/1560] XGB       repeat 3 fold 0  macro-F1=0.9285  P1=0.847 R1=0.867  (6s)  [ratio 0.0, orig^1.25, C=1, rho=4.94]

[1365/1560] XGB       repeat 3 fold 0  macro-F1=0.8747  P1=0.641 R1=0.904  (2s)  [ratio 0.0, orig^1.5, C=0, rho=24.38]

[1366/1560] XGB       repeat 3 fold 0  macro-F1=0.9102  P1=0.789 R1=0.855  (6s)  [ratio 0.0, orig^1.5, C=1, rho=24.38]

[1367/1560] XGB       repeat 3 fold 0  macro-F1=0.5600  P1=0.070 R1=0.940  (2s)  [ratio 0.0, orig^2.0, C=0, rho=594.24]

[1368/1560] XGB       repeat 3 fold 0  macro-F1=0.7259  P1=0.302 R1=0.916  (5s)  [ratio 0.0, orig^2.0, C=1, rho=594.24]

[1369/1560] XGB       repeat 3 fold 0  macro-F1=0.9113  P1=0.783 R1=0.867  (33s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1370/1560] XGB       repeat 3 fold 0  macro-F1=0.9267  P1=0.864 R1=0.843  (82s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1371/1560] XGB       repeat 3 fold 0  macro-F1=0.8872  P1=0.685 R1=0.892  (33s)  [ratio 0.5, orig^0.25, C=0, rho=2.47]

[1372/1560] XGB       repeat 3 fold 0  macro-F1=0.8932  P1=0.720 R1=0.867  (82s)  [ratio 0.5, orig^0.25, C=1, rho=2.47]

[1373/1560] XGB       repeat 3 fold 0  macro-F1=0.8545  P1=0.575 R1=0.928  (32s)  [ratio 0.5, orig^0.5, C=0, rho=12.19]

[1374/1560] XGB       repeat 3 fold 0  macro-F1=0.9155  P1=0.831 R1=0.831  (82s)  [ratio 0.5, orig^0.5, C=1, rho=12.19]

[1375/1560] XGB       repeat 3 fold 0  macro-F1=0.7059  P1=0.266 R1=0.928  (32s)  [ratio 0.5, orig^0.75, C=0, rho=60.18]

[1376/1560] XGB       repeat 3 fold 0  macro-F1=0.9021  P1=0.769 R1=0.843  (81s)  [ratio 0.5, orig^0.75, C=1, rho=60.18]

[1377/1560] XGB       repeat 3 fold 0  macro-F1=0.5503  P1=0.060 R1=0.952  (32s)  [ratio 0.5, orig^1.0, C=0, rho=297.12]

[1378/1560] XGB       repeat 3 fold 0  macro-F1=0.7867  P1=0.416 R1=0.928  (80s)  [ratio 0.5, orig^1.0, C=1, rho=297.12]

[1379/1560] XGB       repeat 3 fold 0  macro-F1=0.4790  P1=0.013 R1=0.964  (7s)  [ratio 0.5, orig^1.25, C=0, rho=1466.97]

[1380/1560] XGB       repeat 3 fold 0  macro-F1=0.5391  P1=0.049 R1=0.940  (54s)  [ratio 0.5, orig^1.25, C=1, rho=1466.97]

[1381/1560] XGB       repeat 3 fold 0  macro-F1=0.2459  P1=0.002 R1=0.988  (6s)  [ratio 0.5, orig^1.5, C=0, rho=7242.87]

[1382/1560] XGB       repeat 3 fold 0  macro-F1=0.2459  P1=0.002 R1=0.988  (57s)  [ratio 0.5, orig^1.5, C=1, rho=7242.87]

[1383/1560] XGB       repeat 3 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (6s)  [ratio 0.5, orig^2.0, C=0, rho=176559.46]

[1384/1560] XGB       repeat 3 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (57s)  [ratio 0.5, orig^2.0, C=1, rho=176559.46]

[1385/1560] XGB       repeat 3 fold 0  macro-F1=0.9087  P1=0.755 R1=0.892  (8s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1386/1560] XGB       repeat 3 fold 0  macro-F1=0.9320  P1=0.886 R1=0.843  (57s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1387/1560] XGB       repeat 3 fold 0  macro-F1=0.9043  P1=0.758 R1=0.867  (56s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1388/1560] XGB       repeat 3 fold 0  macro-F1=0.9216  P1=0.843 R1=0.843  (132s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1389/1560] XGB       repeat 3 fold 0  macro-F1=0.8856  P1=0.667 R1=0.916  (55s)  [ratio 1.0, orig^0.25, C=0, rho=4.94]

[1390/1560] XGB       repeat 3 fold 0  macro-F1=0.9203  P1=0.892 R1=0.795  (131s)  [ratio 1.0, orig^0.25, C=1, rho=4.94]

[1391/1560] XGB       repeat 3 fold 0  macro-F1=0.8259  P1=0.503 R1=0.928  (56s)  [ratio 1.0, orig^0.5, C=0, rho=24.38]

[1392/1560] XGB       repeat 3 fold 0  macro-F1=0.9054  P1=0.753 R1=0.880  (131s)  [ratio 1.0, orig^0.5, C=1, rho=24.38]

[1393/1560] XGB       repeat 3 fold 0  macro-F1=0.6485  P1=0.179 R1=0.940  (55s)  [ratio 1.0, orig^0.75, C=0, rho=120.36]

[1394/1560] XGB       repeat 3 fold 0  macro-F1=0.8787  P1=0.673 R1=0.867  (128s)  [ratio 1.0, orig^0.75, C=1, rho=120.36]

[1395/1560] XGB       repeat 3 fold 0  macro-F1=0.5265  P1=0.038 R1=0.952  (55s)  [ratio 1.0, orig^1.0, C=0, rho=594.24]

[1396/1560] XGB       repeat 3 fold 0  macro-F1=0.6908  P1=0.242 R1=0.928  (126s)  [ratio 1.0, orig^1.0, C=1, rho=594.24]

[1397/1560] XGB       repeat 3 fold 0  macro-F1=0.4569  P1=0.009 R1=0.964  (9s)  [ratio 1.0, orig^1.25, C=0, rho=2933.94]

[1398/1560] XGB       repeat 3 fold 0  macro-F1=0.5202  P1=0.143 R1=0.024  (85s)  [ratio 1.0, orig^1.25, C=1, rho=2933.94]

[1399/1560] XGB       repeat 3 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (8s)  [ratio 1.0, orig^1.5, C=0, rho=14485.74]

[1400/1560] XGB       repeat 3 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (84s)  [ratio 1.0, orig^1.5, C=1, rho=14485.74]

[1401/1560] XGB       repeat 3 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (8s)  [ratio 1.0, orig^2.0, C=0, rho=353118.91]

[1402/1560] XGB       repeat 3 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (82s)  [ratio 1.0, orig^2.0, C=1, rho=353118.91]

[1403/1560] XGB       repeat 3 fold 0  macro-F1=0.9043  P1=0.758 R1=0.867  (10s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1404/1560] XGB       repeat 3 fold 0  macro-F1=0.9216  P1=0.843 R1=0.843  (80s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1405/1560] XGB       repeat 3 fold 1  macro-F1=0.9227  P1=0.969 R1=0.750  (5s)  [ratio 0.0, orig^0.0, C=0, rho=0.00]

[1406/1560] XGB       repeat 3 fold 1  macro-F1=0.9275  P1=0.956 R1=0.774  (14s)  [ratio 0.0, orig^0.0, C=1, rho=0.00]

[1407/1560] XGB       repeat 3 fold 1  macro-F1=0.9237  P1=0.955 R1=0.762  (5s)  [ratio 0.0, orig^0.25, C=0, rho=0.01]

[1408/1560] XGB       repeat 3 fold 1  macro-F1=0.9068  P1=0.967 R1=0.702  (14s)  [ratio 0.0, orig^0.25, C=1, rho=0.01]

[1409/1560] XGB       repeat 3 fold 1  macro-F1=0.9313  P1=0.957 R1=0.786  (5s)  [ratio 0.0, orig^0.5, C=0, rho=0.04]

[1410/1560] XGB       repeat 3 fold 1  macro-F1=0.9148  P1=0.968 R1=0.726  (14s)  [ratio 0.0, orig^0.5, C=1, rho=0.04]

[1411/1560] XGB       repeat 3 fold 1  macro-F1=0.9209  P1=0.941 R1=0.762  (5s)  [ratio 0.0, orig^0.75, C=0, rho=0.20]

[1412/1560] XGB       repeat 3 fold 1  macro-F1=0.9209  P1=0.941 R1=0.762  (14s)  [ratio 0.0, orig^0.75, C=1, rho=0.20]

[1413/1560] XGB       repeat 3 fold 1  macro-F1=0.9266  P1=0.918 R1=0.798  (5s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1414/1560] XGB       repeat 3 fold 1  macro-F1=0.9350  P1=0.957 R1=0.798  (13s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1415/1560] XGB       repeat 3 fold 1  macro-F1=0.9222  P1=0.883 R1=0.810  (4s)  [ratio 0.0, orig^1.25, C=0, rho=4.95]

[1416/1560] XGB       repeat 3 fold 1  macro-F1=0.9350  P1=0.957 R1=0.798  (13s)  [ratio 0.0, orig^1.25, C=1, rho=4.95]

[1417/1560] XGB       repeat 3 fold 1  macro-F1=0.8998  P1=0.791 R1=0.810  (4s)  [ratio 0.0, orig^1.5, C=0, rho=24.52]

[1418/1560] XGB       repeat 3 fold 1  macro-F1=0.9294  P1=0.931 R1=0.798  (12s)  [ratio 0.0, orig^1.5, C=1, rho=24.52]

[1419/1560] XGB       repeat 3 fold 1  macro-F1=0.5562  P1=0.066 R1=0.810  (7s)  [ratio 0.0, orig^2.0, C=0, rho=601.41]

[1420/1560] XGB       repeat 3 fold 1  macro-F1=0.5767  P1=0.089 R1=0.810  (15s)  [ratio 0.0, orig^2.0, C=1, rho=601.41]

[1421/1560] XGB       repeat 3 fold 1  macro-F1=0.9124  P1=0.868 R1=0.786  (32s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1422/1560] XGB       repeat 3 fold 1  macro-F1=0.9199  P1=0.955 R1=0.750  (80s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1423/1560] XGB       repeat 3 fold 1  macro-F1=0.9145  P1=0.850 R1=0.810  (32s)  [ratio 0.5, orig^0.25, C=0, rho=2.48]

[1424/1560] XGB       repeat 3 fold 1  macro-F1=0.9220  P1=0.929 R1=0.774  (81s)  [ratio 0.5, orig^0.25, C=1, rho=2.48]

[1425/1560] XGB       repeat 3 fold 1  macro-F1=0.8818  P1=0.723 R1=0.810  (32s)  [ratio 0.5, orig^0.5, C=0, rho=12.26]

[1426/1560] XGB       repeat 3 fold 1  macro-F1=0.9186  P1=0.882 R1=0.798  (80s)  [ratio 0.5, orig^0.5, C=1, rho=12.26]

[1427/1560] XGB       repeat 3 fold 1  macro-F1=0.7799  P1=0.426 R1=0.821  (31s)  [ratio 0.5, orig^0.75, C=0, rho=60.72]

[1428/1560] XGB       repeat 3 fold 1  macro-F1=0.9070  P1=0.819 R1=0.810  (78s)  [ratio 0.5, orig^0.75, C=1, rho=60.72]

[1429/1560] XGB       repeat 3 fold 1  macro-F1=0.6008  P1=0.118 R1=0.857  (31s)  [ratio 0.5, orig^1.0, C=0, rho=300.70]

[1430/1560] XGB       repeat 3 fold 1  macro-F1=0.8346  P1=0.566 R1=0.821  (78s)  [ratio 0.5, orig^1.0, C=1, rho=300.70]

[1431/1560] XGB       repeat 3 fold 1  macro-F1=0.5017  P1=0.021 R1=0.893  (6s)  [ratio 0.5, orig^1.25, C=0, rho=1489.10]

[1432/1560] XGB       repeat 3 fold 1  macro-F1=0.6063  P1=0.125 R1=0.869  (51s)  [ratio 0.5, orig^1.25, C=1, rho=1489.10]

[1433/1560] XGB       repeat 3 fold 1  macro-F1=0.3431  P1=0.003 R1=0.964  (6s)  [ratio 0.5, orig^1.5, C=0, rho=7374.23]

[1434/1560] XGB       repeat 3 fold 1  macro-F1=0.4996  P1=0.000 R1=0.000  (50s)  [ratio 0.5, orig^1.5, C=1, rho=7374.23]

[1435/1560] XGB       repeat 3 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (5s)  [ratio 0.5, orig^2.0, C=0, rho=180843.15]

[1436/1560] XGB       repeat 3 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (54s)  [ratio 0.5, orig^2.0, C=1, rho=180843.15]

[1437/1560] XGB       repeat 3 fold 1  macro-F1=0.9176  P1=0.892 R1=0.786  (7s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1438/1560] XGB       repeat 3 fold 1  macro-F1=0.9199  P1=0.955 R1=0.750  (54s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1439/1560] XGB       repeat 3 fold 1  macro-F1=0.9113  P1=0.878 R1=0.774  (54s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1440/1560] XGB       repeat 3 fold 1  macro-F1=0.9171  P1=0.940 R1=0.750  (130s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1441/1560] XGB       repeat 3 fold 1  macro-F1=0.9059  P1=0.827 R1=0.798  (54s)  [ratio 1.0, orig^0.25, C=0, rho=4.95]

[1442/1560] XGB       repeat 3 fold 1  macro-F1=0.9209  P1=0.941 R1=0.762  (128s)  [ratio 1.0, orig^0.25, C=1, rho=4.95]

[1443/1560] XGB       repeat 3 fold 1  macro-F1=0.8614  P1=0.654 R1=0.810  (54s)  [ratio 1.0, orig^0.5, C=0, rho=24.52]

[1444/1560] XGB       repeat 3 fold 1  macro-F1=0.9257  P1=0.930 R1=0.786  (127s)  [ratio 1.0, orig^0.5, C=1, rho=24.52]

[1445/1560] XGB       repeat 3 fold 1  macro-F1=0.7203  P1=0.303 R1=0.821  (54s)  [ratio 1.0, orig^0.75, C=0, rho=121.44]

[1446/1560] XGB       repeat 3 fold 1  macro-F1=0.8975  P1=0.782 R1=0.810  (124s)  [ratio 1.0, orig^0.75, C=1, rho=121.44]

[1447/1560] XGB       repeat 3 fold 1  macro-F1=0.5605  P1=0.071 R1=0.881  (54s)  [ratio 1.0, orig^1.0, C=0, rho=601.41]

[1448/1560] XGB       repeat 3 fold 1  macro-F1=0.7770  P1=0.422 R1=0.810  (122s)  [ratio 1.0, orig^1.0, C=1, rho=601.41]

[1449/1560] XGB       repeat 3 fold 1  macro-F1=0.4835  P1=0.013 R1=0.905  (8s)  [ratio 1.0, orig^1.25, C=0, rho=2978.26]

[1450/1560] XGB       repeat 3 fold 1  macro-F1=0.5741  P1=0.086 R1=0.869  (81s)  [ratio 1.0, orig^1.25, C=1, rho=2978.26]

[1451/1560] XGB       repeat 3 fold 1  macro-F1=0.0267  P1=0.002 R1=1.000  (7s)  [ratio 1.0, orig^1.5, C=0, rho=14748.76]

[1452/1560] XGB       repeat 3 fold 1  macro-F1=0.0267  P1=0.002 R1=1.000  (82s)  [ratio 1.0, orig^1.5, C=1, rho=14748.76]

[1453/1560] XGB       repeat 3 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (7s)  [ratio 1.0, orig^2.0, C=0, rho=361693.55]

[1454/1560] XGB       repeat 3 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (79s)  [ratio 1.0, orig^2.0, C=1, rho=361693.55]

[1455/1560] XGB       repeat 3 fold 1  macro-F1=0.9113  P1=0.878 R1=0.774  (10s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1456/1560] XGB       repeat 3 fold 1  macro-F1=0.9171  P1=0.940 R1=0.750  (78s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1457/1560] XGB       repeat 4 fold 0  macro-F1=0.9257  P1=0.917 R1=0.795  (2s)  [ratio 0.0, orig^0.0, C=0, rho=0.00]

[1458/1560] XGB       repeat 4 fold 0  macro-F1=0.9293  P1=0.875 R1=0.843  (6s)  [ratio 0.0, orig^0.0, C=1, rho=0.00]

[1459/1560] XGB       repeat 4 fold 0  macro-F1=0.9203  P1=0.892 R1=0.795  (2s)  [ratio 0.0, orig^0.25, C=0, rho=0.01]

[1460/1560] XGB       repeat 4 fold 0  macro-F1=0.9203  P1=0.892 R1=0.795  (6s)  [ratio 0.0, orig^0.25, C=1, rho=0.01]

[1461/1560] XGB       repeat 4 fold 0  macro-F1=0.9267  P1=0.864 R1=0.843  (2s)  [ratio 0.0, orig^0.5, C=0, rho=0.04]

[1462/1560] XGB       repeat 4 fold 0  macro-F1=0.9190  P1=0.833 R1=0.843  (6s)  [ratio 0.0, orig^0.5, C=1, rho=0.04]

[1463/1560] XGB       repeat 4 fold 0  macro-F1=0.9320  P1=0.886 R1=0.843  (2s)  [ratio 0.0, orig^0.75, C=0, rho=0.20]

[1464/1560] XGB       repeat 4 fold 0  macro-F1=0.9320  P1=0.886 R1=0.843  (7s)  [ratio 0.0, orig^0.75, C=1, rho=0.20]

[1465/1560] XGB       repeat 4 fold 0  macro-F1=0.9267  P1=0.864 R1=0.843  (2s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1466/1560] XGB       repeat 4 fold 0  macro-F1=0.9257  P1=0.917 R1=0.795  (7s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1467/1560] XGB       repeat 4 fold 0  macro-F1=0.9130  P1=0.821 R1=0.831  (2s)  [ratio 0.0, orig^1.25, C=0, rho=4.94]

[1468/1560] XGB       repeat 4 fold 0  macro-F1=0.9186  P1=0.870 R1=0.807  (6s)  [ratio 0.0, orig^1.25, C=1, rho=4.94]

[1469/1560] XGB       repeat 4 fold 0  macro-F1=0.8899  P1=0.717 R1=0.855  (2s)  [ratio 0.0, orig^1.5, C=0, rho=24.38]

[1470/1560] XGB       repeat 4 fold 0  macro-F1=0.9293  P1=0.875 R1=0.843  (6s)  [ratio 0.0, orig^1.5, C=1, rho=24.38]

[1471/1560] XGB       repeat 4 fold 0  macro-F1=0.5727  P1=0.084 R1=0.892  (2s)  [ratio 0.0, orig^2.0, C=0, rho=594.24]

[1472/1560] XGB       repeat 4 fold 0  macro-F1=0.7557  P1=0.368 R1=0.843  (5s)  [ratio 0.0, orig^2.0, C=1, rho=594.24]

[1473/1560] XGB       repeat 4 fold 0  macro-F1=0.9241  P1=0.854 R1=0.843  (32s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1474/1560] XGB       repeat 4 fold 0  macro-F1=0.9276  P1=0.895 R1=0.819  (81s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1475/1560] XGB       repeat 4 fold 0  macro-F1=0.9068  P1=0.787 R1=0.843  (32s)  [ratio 0.5, orig^0.25, C=0, rho=2.47]

[1476/1560] XGB       repeat 4 fold 0  macro-F1=0.9165  P1=0.824 R1=0.843  (80s)  [ratio 0.5, orig^0.25, C=1, rho=2.47]

[1477/1560] XGB       repeat 4 fold 0  macro-F1=0.8638  P1=0.634 R1=0.855  (32s)  [ratio 0.5, orig^0.5, C=0, rho=12.19]

[1478/1560] XGB       repeat 4 fold 0  macro-F1=0.9170  P1=0.850 R1=0.819  (79s)  [ratio 0.5, orig^0.5, C=1, rho=12.19]

[1479/1560] XGB       repeat 4 fold 0  macro-F1=0.7149  P1=0.289 R1=0.855  (33s)  [ratio 0.5, orig^0.75, C=0, rho=60.18]

[1480/1560] XGB       repeat 4 fold 0  macro-F1=0.9010  P1=0.775 R1=0.831  (79s)  [ratio 0.5, orig^0.75, C=1, rho=60.18]

[1481/1560] XGB       repeat 4 fold 0  macro-F1=0.5610  P1=0.071 R1=0.904  (32s)  [ratio 0.5, orig^1.0, C=0, rho=297.12]

[1482/1560] XGB       repeat 4 fold 0  macro-F1=0.7875  P1=0.438 R1=0.843  (79s)  [ratio 0.5, orig^1.0, C=1, rho=297.12]

[1483/1560] XGB       repeat 4 fold 0  macro-F1=0.4816  P1=0.013 R1=0.928  (7s)  [ratio 0.5, orig^1.25, C=0, rho=1466.97]

[1484/1560] XGB       repeat 4 fold 0  macro-F1=0.5944  P1=0.750 R1=0.108  (53s)  [ratio 0.5, orig^1.25, C=1, rho=1466.97]

[1485/1560] XGB       repeat 4 fold 0  macro-F1=0.2399  P1=0.002 R1=0.976  (6s)  [ratio 0.5, orig^1.5, C=0, rho=7242.87]

[1486/1560] XGB       repeat 4 fold 0  macro-F1=0.2399  P1=0.002 R1=0.976  (56s)  [ratio 0.5, orig^1.5, C=1, rho=7242.87]

[1487/1560] XGB       repeat 4 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (6s)  [ratio 0.5, orig^2.0, C=0, rho=176559.46]

[1488/1560] XGB       repeat 4 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (56s)  [ratio 0.5, orig^2.0, C=1, rho=176559.46]

[1489/1560] XGB       repeat 4 fold 0  macro-F1=0.9165  P1=0.824 R1=0.843  (8s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1490/1560] XGB       repeat 4 fold 0  macro-F1=0.9285  P1=0.930 R1=0.795  (56s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1491/1560] XGB       repeat 4 fold 0  macro-F1=0.9190  P1=0.833 R1=0.843  (54s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1492/1560] XGB       repeat 4 fold 0  macro-F1=0.9257  P1=0.917 R1=0.795  (130s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1493/1560] XGB       repeat 4 fold 0  macro-F1=0.8987  P1=0.747 R1=0.855  (54s)  [ratio 1.0, orig^0.25, C=0, rho=4.94]

[1494/1560] XGB       repeat 4 fold 0  macro-F1=0.9232  P1=0.863 R1=0.831  (129s)  [ratio 1.0, orig^0.25, C=1, rho=4.94]

[1495/1560] XGB       repeat 4 fold 0  macro-F1=0.8283  P1=0.534 R1=0.855  (55s)  [ratio 1.0, orig^0.5, C=0, rho=24.38]

[1496/1560] XGB       repeat 4 fold 0  macro-F1=0.9241  P1=0.854 R1=0.843  (128s)  [ratio 1.0, orig^0.5, C=1, rho=24.38]

[1497/1560] XGB       repeat 4 fold 0  macro-F1=0.6675  P1=0.209 R1=0.880  (54s)  [ratio 1.0, orig^0.75, C=0, rho=120.36]

[1498/1560] XGB       repeat 4 fold 0  macro-F1=0.8919  P1=0.742 R1=0.831  (126s)  [ratio 1.0, orig^0.75, C=1, rho=120.36]

[1499/1560] XGB       repeat 4 fold 0  macro-F1=0.5332  P1=0.044 R1=0.916  (54s)  [ratio 1.0, orig^1.0, C=0, rho=594.24]

[1500/1560] XGB       repeat 4 fold 0  macro-F1=0.6898  P1=0.245 R1=0.867  (124s)  [ratio 1.0, orig^1.0, C=1, rho=594.24]

[1501/1560] XGB       repeat 4 fold 0  macro-F1=0.4611  P1=0.009 R1=0.940  (9s)  [ratio 1.0, orig^1.25, C=0, rho=2933.94]

[1502/1560] XGB       repeat 4 fold 0  macro-F1=0.5215  P1=0.034 R1=0.904  (83s)  [ratio 1.0, orig^1.25, C=1, rho=2933.94]

[1503/1560] XGB       repeat 4 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (7s)  [ratio 1.0, orig^1.5, C=0, rho=14485.74]

[1504/1560] XGB       repeat 4 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (82s)  [ratio 1.0, orig^1.5, C=1, rho=14485.74]

[1505/1560] XGB       repeat 4 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (8s)  [ratio 1.0, orig^2.0, C=0, rho=353118.91]

[1506/1560] XGB       repeat 4 fold 0  macro-F1=0.0017  P1=0.002 R1=1.000  (82s)  [ratio 1.0, orig^2.0, C=1, rho=353118.91]

[1507/1560] XGB       repeat 4 fold 0  macro-F1=0.9190  P1=0.833 R1=0.843  (10s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1508/1560] XGB       repeat 4 fold 0  macro-F1=0.9257  P1=0.917 R1=0.795  (79s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1509/1560] XGB       repeat 4 fold 1  macro-F1=0.9132  P1=0.939 R1=0.738  (3s)  [ratio 0.0, orig^0.0, C=0, rho=0.00]

[1510/1560] XGB       repeat 4 fold 1  macro-F1=0.9132  P1=0.939 R1=0.738  (10s)  [ratio 0.0, orig^0.0, C=1, rho=0.00]

[1511/1560] XGB       repeat 4 fold 1  macro-F1=0.9275  P1=0.956 R1=0.774  (4s)  [ratio 0.0, orig^0.25, C=0, rho=0.01]

[1512/1560] XGB       repeat 4 fold 1  macro-F1=0.9350  P1=0.957 R1=0.798  (10s)  [ratio 0.0, orig^0.25, C=1, rho=0.01]

[1513/1560] XGB       repeat 4 fold 1  macro-F1=0.9366  P1=0.932 R1=0.821  (4s)  [ratio 0.0, orig^0.5, C=0, rho=0.04]

[1514/1560] XGB       repeat 4 fold 1  macro-F1=0.9080  P1=0.952 R1=0.714  (10s)  [ratio 0.0, orig^0.5, C=1, rho=0.04]

[1515/1560] XGB       repeat 4 fold 1  macro-F1=0.9165  P1=0.903 R1=0.774  (4s)  [ratio 0.0, orig^0.75, C=0, rho=0.20]

[1516/1560] XGB       repeat 4 fold 1  macro-F1=0.9247  P1=0.942 R1=0.774  (11s)  [ratio 0.0, orig^0.75, C=1, rho=0.20]

[1517/1560] XGB       repeat 4 fold 1  macro-F1=0.9311  P1=0.908 R1=0.821  (4s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1518/1560] XGB       repeat 4 fold 1  macro-F1=0.9206  P1=0.863 R1=0.821  (11s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1519/1560] XGB       repeat 4 fold 1  macro-F1=0.9241  P1=0.864 R1=0.833  (3s)  [ratio 0.0, orig^1.25, C=0, rho=4.95]

[1520/1560] XGB       repeat 4 fold 1  macro-F1=0.9241  P1=0.864 R1=0.833  (10s)  [ratio 0.0, orig^1.25, C=1, rho=4.95]

[1521/1560] XGB       repeat 4 fold 1  macro-F1=0.9021  P1=0.758 R1=0.857  (3s)  [ratio 0.0, orig^1.5, C=0, rho=24.52]

[1522/1560] XGB       repeat 4 fold 1  macro-F1=0.9180  P1=0.852 R1=0.821  (10s)  [ratio 0.0, orig^1.5, C=1, rho=24.52]

[1523/1560] XGB       repeat 4 fold 1  macro-F1=0.5647  P1=0.075 R1=0.905  (3s)  [ratio 0.0, orig^2.0, C=0, rho=601.41]

[1524/1560] XGB       repeat 4 fold 1  macro-F1=0.7868  P1=0.424 R1=0.893  (8s)  [ratio 0.0, orig^2.0, C=1, rho=601.41]

[1525/1560] XGB       repeat 4 fold 1  macro-F1=0.9145  P1=0.850 R1=0.810  (33s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1526/1560] XGB       repeat 4 fold 1  macro-F1=0.8971  P1=0.935 R1=0.690  (80s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1527/1560] XGB       repeat 4 fold 1  macro-F1=0.8975  P1=0.782 R1=0.810  (32s)  [ratio 0.5, orig^0.25, C=0, rho=2.48]

[1528/1560] XGB       repeat 4 fold 1  macro-F1=0.9192  P1=0.915 R1=0.774  (81s)  [ratio 0.5, orig^0.25, C=1, rho=2.48]

[1529/1560] XGB       repeat 4 fold 1  macro-F1=0.8782  P1=0.693 R1=0.833  (32s)  [ratio 0.5, orig^0.5, C=0, rho=12.26]

[1530/1560] XGB       repeat 4 fold 1  macro-F1=0.9186  P1=0.882 R1=0.798  (80s)  [ratio 0.5, orig^0.5, C=1, rho=12.26]

[1531/1560] XGB       repeat 4 fold 1  macro-F1=0.7458  P1=0.346 R1=0.857  (32s)  [ratio 0.5, orig^0.75, C=0, rho=60.72]

[1532/1560] XGB       repeat 4 fold 1  macro-F1=0.9145  P1=0.850 R1=0.810  (79s)  [ratio 0.5, orig^0.75, C=1, rho=60.72]

[1533/1560] XGB       repeat 4 fold 1  macro-F1=0.5740  P1=0.085 R1=0.905  (32s)  [ratio 0.5, orig^1.0, C=0, rho=300.70]

[1534/1560] XGB       repeat 4 fold 1  macro-F1=0.8137  P1=0.500 R1=0.845  (79s)  [ratio 0.5, orig^1.0, C=1, rho=300.70]

[1535/1560] XGB       repeat 4 fold 1  macro-F1=0.4908  P1=0.016 R1=0.940  (7s)  [ratio 0.5, orig^1.25, C=0, rho=1489.10]

[1536/1560] XGB       repeat 4 fold 1  macro-F1=0.5574  P1=0.067 R1=0.893  (53s)  [ratio 0.5, orig^1.25, C=1, rho=1489.10]

[1537/1560] XGB       repeat 4 fold 1  macro-F1=0.3362  P1=0.003 R1=0.964  (6s)  [ratio 0.5, orig^1.5, C=0, rho=7374.23]

[1538/1560] XGB       repeat 4 fold 1  macro-F1=0.6027  P1=0.769 R1=0.119  (51s)  [ratio 0.5, orig^1.5, C=1, rho=7374.23]

[1539/1560] XGB       repeat 4 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (5s)  [ratio 0.5, orig^2.0, C=0, rho=180843.15]

[1540/1560] XGB       repeat 4 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (54s)  [ratio 0.5, orig^2.0, C=1, rho=180843.15]

[1541/1560] XGB       repeat 4 fold 1  macro-F1=0.9095  P1=0.829 R1=0.810  (8s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1542/1560] XGB       repeat 4 fold 1  macro-F1=0.9182  P1=0.928 R1=0.762  (56s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1543/1560] XGB       repeat 4 fold 1  macro-F1=0.9120  P1=0.840 R1=0.810  (54s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1544/1560] XGB       repeat 4 fold 1  macro-F1=0.9192  P1=0.915 R1=0.774  (130s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1545/1560] XGB       repeat 4 fold 1  macro-F1=0.8998  P1=0.791 R1=0.810  (55s)  [ratio 1.0, orig^0.25, C=0, rho=4.95]

[1546/1560] XGB       repeat 4 fold 1  macro-F1=0.9182  P1=0.928 R1=0.762  (129s)  [ratio 1.0, orig^0.25, C=1, rho=4.95]

[1547/1560] XGB       repeat 4 fold 1  macro-F1=0.8515  P1=0.609 R1=0.833  (54s)  [ratio 1.0, orig^0.5, C=0, rho=24.52]

[1548/1560] XGB       repeat 4 fold 1  macro-F1=0.9120  P1=0.840 R1=0.810  (128s)  [ratio 1.0, orig^0.5, C=1, rho=24.52]

[1549/1560] XGB       repeat 4 fold 1  macro-F1=0.6805  P1=0.228 R1=0.905  (53s)  [ratio 1.0, orig^0.75, C=0, rho=121.44]

[1550/1560] XGB       repeat 4 fold 1  macro-F1=0.8931  P1=0.745 R1=0.833  (127s)  [ratio 1.0, orig^0.75, C=1, rho=121.44]

[1551/1560] XGB       repeat 4 fold 1  macro-F1=0.5412  P1=0.051 R1=0.905  (54s)  [ratio 1.0, orig^1.0, C=0, rho=601.41]

[1552/1560] XGB       repeat 4 fold 1  macro-F1=0.7234  P1=0.304 R1=0.857  (123s)  [ratio 1.0, orig^1.0, C=1, rho=601.41]

[1553/1560] XGB       repeat 4 fold 1  macro-F1=0.4729  P1=0.011 R1=0.940  (9s)  [ratio 1.0, orig^1.25, C=0, rho=2978.26]

[1554/1560] XGB       repeat 4 fold 1  macro-F1=0.5821  P1=0.615 R1=0.095  (82s)  [ratio 1.0, orig^1.25, C=1, rho=2978.26]

[1555/1560] XGB       repeat 4 fold 1  macro-F1=0.0920  P1=0.002 R1=1.000  (8s)  [ratio 1.0, orig^1.5, C=0, rho=14748.76]

[1556/1560] XGB       repeat 4 fold 1  macro-F1=0.0920  P1=0.002 R1=1.000  (82s)  [ratio 1.0, orig^1.5, C=1, rho=14748.76]

[1557/1560] XGB       repeat 4 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (7s)  [ratio 1.0, orig^2.0, C=0, rho=361693.55]

[1558/1560] XGB       repeat 4 fold 1  macro-F1=0.0017  P1=0.002 R1=1.000  (80s)  [ratio 1.0, orig^2.0, C=1, rho=361693.55]

[1559/1560] XGB       repeat 4 fold 1  macro-F1=0.9120  P1=0.840 R1=0.810  (10s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1560/1560] XGB       repeat 4 fold 1  macro-F1=0.9192  P1=0.915 R1=0.774  (80s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

## Macro-F1 by resampling ratio, weight setting and threshold tuning

In [4]:
results.pivot_table(index=["sampling_ratio", "weight_mode", "weight_power"],
                    columns=["classifier", "C"], values="macro_f1").round(4)

classifier                                   LR              RF          \
C                                             0       1       0       1
sampling_ratio weight_mode weight_power
0.0            orig        0.00          0.8630  0.8847  0.9095  0.9201
                           0.25          0.8994  0.8951  0.9216  0.9214
                           0.50          0.8764  0.8976  0.9187  0.9234
                           0.75          0.7012  0.8928  0.9164  0.9204
                           1.00          0.5519  0.8225  0.9129  0.9178
                           1.25          0.5068  0.7734  0.9010  0.9134
                           1.50          0.4818  0.7483  0.7979  0.8955
                           2.00          0.3089  0.6537  0.5288  0.8238
0.5            orig        0.00          0.6393  0.8925  0.9174  0.9145
                           0.25          0.5275  0.7981  0.9055  0.9064
                           0.50          0.4752  0.7118  0.8398  0.8949
                           0.75          0.3366  0.6763  0.6400  0.8499
                           1.00          0.0085  0.6580  0.5270  0.8247
                           1.25          0.0017  0.8711  0.4148  0.8161
                           1.50          0.0017  0.9207  0.0997  0.8043
                           2.00          0.0017  0.0848  0.0017  0.5914
               recalc      1.00          0.5753  0.8682  0.9135  0.9118
1.0            orig        0.00          0.5696  0.8556  0.9131  0.9101
                           0.25          0.5042  0.7373  0.8925  0.9024
                           0.50          0.4479  0.6708  0.7802  0.8776
                           0.75          0.2145  0.6460  0.5920  0.8329
                           1.00          0.0020  0.6886  0.5040  0.8224
                           1.25          0.0017  0.9153  0.3514  0.8161
                           1.50          0.0017  0.9163  0.0547  0.8067
                           2.00          0.0017  0.0865  0.0017  0.5584
               recalc      1.00          0.5696  0.8556  0.9131  0.9101

classifier                                  XGB
C                                             0       1
sampling_ratio weight_mode weight_power
0.0            orig        0.00          0.9232  0.9235
                           0.25          0.9232  0.9214
                           0.50          0.9272  0.9219
                           0.75          0.9264  0.9250
                           1.00          0.9253  0.9231
                           1.25          0.9119  0.9197
                           1.50          0.8582  0.9193
                           2.00          0.5505  0.7180
0.5            orig        0.00          0.9155  0.9166
                           0.25          0.8996  0.9178
                           0.50          0.8673  0.9179
                           0.75          0.7563  0.9126
                           1.00          0.5912  0.8377
                           1.25          0.5011  0.6067
                           1.50          0.3489  0.4460
                           2.00          0.0017  0.0017
               recalc      1.00          0.9099  0.9197
1.0            orig        0.00          0.9093  0.9173
                           0.25          0.8954  0.9182
                           0.50          0.8450  0.9173
                           0.75          0.7035  0.8902
                           1.00          0.5568  0.7445
                           1.25          0.4816  0.5643
                           1.50          0.1923  0.2555
                           2.00          0.0017  0.0017
               recalc      1.00          0.9093  0.9173

In [5]:
results.groupby(["sampling_ratio", "weight_mode", "weight_power"])[["rho_eff", "precision_1", "recall_1", "ppr_ratio"]].mean().round(3)

                                            rho_eff  precision_1  recall_1  \
sampling_ratio weight_mode weight_power
0.0            orig        0.00               0.002        0.872     0.760
                           0.25               0.008        0.865     0.797
                           0.50               0.041        0.842     0.812
                           0.75               0.202        0.760     0.823
                           1.00               1.000        0.695     0.814
                           1.25               4.945        0.648     0.823
                           1.50              24.450        0.567     0.819
                           2.00             597.824        0.265     0.815
0.5            orig        0.00               0.500        0.733     0.818
                           0.25               2.472        0.642     0.826
                           0.50              12.225        0.539     0.840
                           0.75              60.450        0.392     0.846
                           1.00             298.909        0.274     0.856
                           1.25            1478.035        0.273     0.855
                           1.50            7308.552        0.281     0.802
                           2.00          178701.305        0.037     0.931
               recalc      1.00               1.000        0.698     0.822
1.0            orig        0.00               1.000        0.690     0.818
                           0.25               4.945        0.605     0.827
                           0.50              24.450        0.482     0.840
                           0.75             120.901        0.342     0.844
                           1.00             597.824        0.242     0.863
                           1.25            2956.099        0.328     0.797
                           1.50           14617.252        0.272     0.840
                           2.00          357406.234        0.028     0.947
               recalc      1.00               1.000        0.690     0.818

                                         ppr_ratio
sampling_ratio weight_mode weight_power
0.0            orig        0.00              0.876
                           0.25              0.928
                           0.50              0.980
                           0.75              1.368
                           1.00              3.342
                           1.25              7.628
                           1.50             13.572
                           2.00             64.657
0.5            orig        0.00              1.737
                           0.25              5.115
                           0.50             15.084
                           0.75             51.958
                           1.00            106.646
                           1.25            139.999
                           1.50            251.979
                           2.00            490.680
               recalc      1.00              2.686
1.0            orig        0.00              2.821
                           0.25              8.228
                           0.50             22.990
                           0.75             75.689
                           1.00            112.082
                           1.25            156.985
                           1.50            319.940
                           2.00            491.984
               recalc      1.00              2.821