# Oil Spill - E2 weight sensitivity
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/MuhammadDevX/ML-Research-Dataset-Imbalance/blob/main/oilspill/e2_weight_sensitivity/oilspill_e2_weight_sensitivity.ipynb)

Answers reviewer R3 (one weighting configuration only) and tests the over-correction mechanism.

* Classifiers: LR, RF, XGB.
* Resampling ratio: [0.0, 0.5, 1.0] (0 = none; otherwise SMOTETomek to that minority:majority ratio).
* Positive-class weight = IR ** power, power in [0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0]
  (0 = none, 0.5 = sqrt-inverse, 1 = inverse frequency), plus weights recomputed after resampling.
* Each setting with and without threshold tuning (C).
* Hyperparameters are reused from `c0_none` (no resampling) and `c1_A_smotetomek` (with resampling).
  **Run those two notebooks first**; missing folds are tuned here, which is slower.
* Each row records `rho_eff`, the positive:negative loss mass the classifier sees.

**How to run on Colab**
1. Click the badge, then *Runtime > Run all*. Allow Google Drive access when asked.
2. Results are appended to Google Drive after every classifier/fold:
   `MyDrive/ML-Research-Dataset-Imbalance/oilspill/e2_weight_sensitivity/results/oilspill__e2_weight_sensitivity.csv`.
3. If the runtime disconnects, just *Run all* again: finished folds are skipped.
4. When it is complete, copy the CSV into the same path in the repository and commit it.

In [1]:
# ---- Setup: identical in every notebook. Do not edit. ----
import os, sys, subprocess
REPO_URL = "https://github.com/MuhammadDevX/ML-Research-Dataset-Imbalance.git"
BRANCH = "main"
try:
    import google.colab  # noqa: F401
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    REPO_ROOT = "/content/ML-Research-Dataset-Imbalance"
    if not os.path.isdir(REPO_ROOT):
        subprocess.run(["git", "clone", "--branch", BRANCH, REPO_URL, REPO_ROOT], check=True)
    else:
        subprocess.run(["git", "-C", REPO_ROOT, "pull", "--ff-only"], check=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r",
                    f"{REPO_ROOT}/requirements.txt"], check=True)
    from google.colab import drive
    drive.mount("/content/drive")
    # Results go to Google Drive so they survive a disconnect.
    os.environ.setdefault("RESULTS_ROOT", "/content/drive/MyDrive/ML-Research-Dataset-Imbalance")
else:
    REPO_ROOT = os.path.abspath(os.getcwd())
    while not os.path.isdir(os.path.join(REPO_ROOT, "common")):
        parent = os.path.dirname(REPO_ROOT)
        if parent == REPO_ROOT:
            raise RuntimeError("Open this notebook from inside the repository.")
        REPO_ROOT = parent

sys.path.insert(0, REPO_ROOT)
os.chdir(REPO_ROOT)
from common.env import check_environment
check_environment()

Environment OK: scikit-learn 1.9.1, imbalanced-learn 0.14.2, xgboost 3.4.1, lightgbm 4.7.0

In [2]:
DATASET = "oilspill"
# Quick test run (2 folds, fewer classifiers and candidates): change the next line
# to  SMOKE = True . Its results go to a separate *__SMOKE.csv file and must never
# be used in the paper. Leave it as it is for the real run.
SMOKE = os.environ.get("SMOKE", "0") == "1"

In [3]:
from common.cv import run_e2
results = run_e2(DATASET, smoke=SMOKE)

Hyperparameters found: c0 70 folds, c1 70 folds. Missing ones are tuned here once with the same seed.
Writing to E:\Ablation_Study Research\ML-Research-Dataset-Imbalance\oilspill\e2_weight_sensitivity\results\oilspill__e2_weight_sensitivity.csv

[521/1560] RF        repeat 0 fold 0  macro-F1=0.6096  P1=0.750 R1=0.143  (2s)  [ratio 0.0, orig^0.0, C=0, rho=0.04]

[522/1560] RF        repeat 0 fold 0  macro-F1=0.7365  P1=0.444 R1=0.571  (8s)  [ratio 0.0, orig^0.0, C=1, rho=0.04]

[523/1560] RF        repeat 0 fold 0  macro-F1=0.6377  P1=0.667 R1=0.190  (2s)  [ratio 0.0, orig^0.25, C=0, rho=0.10]

[524/1560] RF        repeat 0 fold 0  macro-F1=0.7577  P1=0.550 R1=0.524  (7s)  [ratio 0.0, orig^0.25, C=1, rho=0.10]

[525/1560] RF        repeat 0 fold 0  macro-F1=0.6687  P1=0.714 R1=0.238  (1s)  [ratio 0.0, orig^0.5, C=0, rho=0.21]

[526/1560] RF        repeat 0 fold 0  macro-F1=0.6884  P1=0.500 R1=0.333  (8s)  [ratio 0.0, orig^0.5, C=1, rho=0.21]

[527/1560] RF        repeat 0 fold 0  macro-F1=0.6687  P1=0.714 R1=0.238  (1s)  [ratio 0.0, orig^0.75, C=0, rho=0.46]

[528/1560] RF        repeat 0 fold 0  macro-F1=0.7549  P1=0.500 R1=0.571  (7s)  [ratio 0.0, orig^0.75, C=1, rho=0.46]

[529/1560] RF        repeat 0 fold 0  macro-F1=0.6901  P1=0.667 R1=0.286  (2s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[530/1560] RF        repeat 0 fold 0  macro-F1=0.7685  P1=0.545 R1=0.571  (6s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[531/1560] RF        repeat 0 fold 0  macro-F1=0.6643  P1=0.462 R1=0.286  (1s)  [ratio 0.0, orig^1.25, C=0, rho=2.18]

[532/1560] RF        repeat 0 fold 0  macro-F1=0.6510  P1=0.333 R1=0.333  (5s)  [ratio 0.0, orig^1.25, C=1, rho=2.18]

[533/1560] RF        repeat 0 fold 0  macro-F1=0.6620  P1=0.310 R1=0.429  (1s)  [ratio 0.0, orig^1.5, C=0, rho=4.73]

[534/1560] RF        repeat 0 fold 0  macro-F1=0.6620  P1=0.310 R1=0.429  (4s)  [ratio 0.0, orig^1.5, C=1, rho=4.73]

[535/1560] RF        repeat 0 fold 0  macro-F1=0.5400  P1=0.125 R1=0.667  (1s)  [ratio 0.0, orig^2.0, C=0, rho=22.40]

[536/1560] RF        repeat 0 fold 0  macro-F1=0.6001  P1=0.190 R1=0.381  (3s)  [ratio 0.0, orig^2.0, C=1, rho=22.40]

[537/1560] RF        repeat 0 fold 0  macro-F1=0.6901  P1=0.667 R1=0.286  (1s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[538/1560] RF        repeat 0 fold 0  macro-F1=0.7854  P1=0.565 R1=0.619  (4s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[539/1560] RF        repeat 0 fold 0  macro-F1=0.6557  P1=0.556 R1=0.238  (1s)  [ratio 0.5, orig^0.25, C=0, rho=1.09]

[540/1560] RF        repeat 0 fold 0  macro-F1=0.7191  P1=0.500 R1=0.429  (4s)  [ratio 0.5, orig^0.25, C=1, rho=1.09]

[541/1560] RF        repeat 0 fold 0  macro-F1=0.7088  P1=0.636 R1=0.333  (1s)  [ratio 0.5, orig^0.5, C=0, rho=2.37]

[542/1560] RF        repeat 0 fold 0  macro-F1=0.7191  P1=0.500 R1=0.429  (4s)  [ratio 0.5, orig^0.5, C=1, rho=2.37]

[543/1560] RF        repeat 0 fold 0  macro-F1=0.7258  P1=0.476 R1=0.476  (1s)  [ratio 0.5, orig^0.75, C=0, rho=5.15]

[544/1560] RF        repeat 0 fold 0  macro-F1=0.7322  P1=0.500 R1=0.476  (5s)  [ratio 0.5, orig^0.75, C=1, rho=5.15]

[545/1560] RF        repeat 0 fold 0  macro-F1=0.6813  P1=0.324 R1=0.524  (1s)  [ratio 0.5, orig^1.0, C=0, rho=11.20]

[546/1560] RF        repeat 0 fold 0  macro-F1=0.6993  P1=0.367 R1=0.524  (5s)  [ratio 0.5, orig^1.0, C=1, rho=11.20]

[547/1560] RF        repeat 0 fold 0  macro-F1=0.5820  P1=0.160 R1=0.619  (1s)  [ratio 0.5, orig^1.25, C=0, rho=24.37]

[548/1560] RF        repeat 0 fold 0  macro-F1=0.7088  P1=0.636 R1=0.333  (5s)  [ratio 0.5, orig^1.25, C=1, rho=24.37]

[549/1560] RF        repeat 0 fold 0  macro-F1=0.4355  P1=0.081 R1=0.810  (1s)  [ratio 0.5, orig^1.5, C=0, rho=53.01]

[550/1560] RF        repeat 0 fold 0  macro-F1=0.6587  P1=0.429 R1=0.286  (4s)  [ratio 0.5, orig^1.5, C=1, rho=53.01]

[551/1560] RF        repeat 0 fold 0  macro-F1=0.0498  P1=0.045 R1=1.000  (1s)  [ratio 0.5, orig^2.0, C=0, rho=250.88]

[552/1560] RF        repeat 0 fold 0  macro-F1=0.6261  P1=0.286 R1=0.286  (4s)  [ratio 0.5, orig^2.0, C=1, rho=250.88]

[553/1560] RF        repeat 0 fold 0  macro-F1=0.6557  P1=0.556 R1=0.238  (1s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[554/1560] RF        repeat 0 fold 0  macro-F1=0.7128  P1=0.474 R1=0.429  (5s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[555/1560] RF        repeat 0 fold 0  macro-F1=0.6765  P1=0.545 R1=0.286  (1s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[556/1560] RF        repeat 0 fold 0  macro-F1=0.7257  P1=0.529 R1=0.429  (6s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[557/1560] RF        repeat 0 fold 0  macro-F1=0.6948  P1=0.538 R1=0.333  (1s)  [ratio 1.0, orig^0.25, C=0, rho=2.18]

[558/1560] RF        repeat 0 fold 0  macro-F1=0.7258  P1=0.476 R1=0.476  (10s)  [ratio 1.0, orig^0.25, C=1, rho=2.18]

[559/1560] RF        repeat 0 fold 0  macro-F1=0.7577  P1=0.550 R1=0.524  (1s)  [ratio 1.0, orig^0.5, C=0, rho=4.73]

[560/1560] RF        repeat 0 fold 0  macro-F1=0.7507  P1=0.524 R1=0.524  (13s)  [ratio 1.0, orig^0.5, C=1, rho=4.73]

[561/1560] RF        repeat 0 fold 0  macro-F1=0.7093  P1=0.393 R1=0.524  (3s)  [ratio 1.0, orig^0.75, C=0, rho=10.30]

[562/1560] RF        repeat 0 fold 0  macro-F1=0.7377  P1=0.478 R1=0.524  (20s)  [ratio 1.0, orig^0.75, C=1, rho=10.30]

[563/1560] RF        repeat 0 fold 0  macro-F1=0.6277  P1=0.218 R1=0.571  (4s)  [ratio 1.0, orig^1.0, C=0, rho=22.40]

[564/1560] RF        repeat 0 fold 0  macro-F1=0.6710  P1=0.364 R1=0.381  (19s)  [ratio 1.0, orig^1.0, C=1, rho=22.40]

[565/1560] RF        repeat 0 fold 0  macro-F1=0.5132  P1=0.107 R1=0.667  (4s)  [ratio 1.0, orig^1.25, C=0, rho=48.73]

[566/1560] RF        repeat 0 fold 0  macro-F1=0.6441  P1=0.455 R1=0.238  (21s)  [ratio 1.0, orig^1.25, C=1, rho=48.73]

[567/1560] RF        repeat 0 fold 0  macro-F1=0.3277  P1=0.066 R1=0.952  (5s)  [ratio 1.0, orig^1.5, C=0, rho=106.02]

[568/1560] RF        repeat 0 fold 0  macro-F1=0.6702  P1=0.500 R1=0.286  (21s)  [ratio 1.0, orig^1.5, C=1, rho=106.02]

[569/1560] RF        repeat 0 fold 0  macro-F1=0.0429  P1=0.045 R1=1.000  (3s)  [ratio 1.0, orig^2.0, C=0, rho=501.76]

[570/1560] RF        repeat 0 fold 0  macro-F1=0.6388  P1=0.417 R1=0.238  (16s)  [ratio 1.0, orig^2.0, C=1, rho=501.76]

[571/1560] RF        repeat 0 fold 0  macro-F1=0.6765  P1=0.545 R1=0.286  (4s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[572/1560] RF        repeat 0 fold 0  macro-F1=0.7257  P1=0.529 R1=0.429  (14s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[573/1560] RF        repeat 0 fold 1  macro-F1=0.6211  P1=1.000 R1=0.150  (1s)  [ratio 0.0, orig^0.0, C=0, rho=0.05]

[574/1560] RF        repeat 0 fold 1  macro-F1=0.7441  P1=0.478 R1=0.550  (7s)  [ratio 0.0, orig^0.0, C=1, rho=0.05]

[575/1560] RF        repeat 0 fold 1  macro-F1=0.6918  P1=1.000 R1=0.250  (1s)  [ratio 0.0, orig^0.25, C=0, rho=0.10]

[576/1560] RF        repeat 0 fold 1  macro-F1=0.8006  P1=0.591 R1=0.650  (7s)  [ratio 0.0, orig^0.25, C=1, rho=0.10]

[577/1560] RF        repeat 0 fold 1  macro-F1=0.6211  P1=1.000 R1=0.150  (1s)  [ratio 0.0, orig^0.5, C=0, rho=0.22]

[578/1560] RF        repeat 0 fold 1  macro-F1=0.8080  P1=0.667 R1=0.600  (8s)  [ratio 0.0, orig^0.5, C=1, rho=0.22]

[579/1560] RF        repeat 0 fold 1  macro-F1=0.6758  P1=0.714 R1=0.250  (2s)  [ratio 0.0, orig^0.75, C=0, rho=0.47]

[580/1560] RF        repeat 0 fold 1  macro-F1=0.7684  P1=0.522 R1=0.600  (7s)  [ratio 0.0, orig^0.75, C=1, rho=0.47]

[581/1560] RF        repeat 0 fold 1  macro-F1=0.7331  P1=0.778 R1=0.350  (2s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[582/1560] RF        repeat 0 fold 1  macro-F1=0.7458  P1=0.526 R1=0.500  (7s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[583/1560] RF        repeat 0 fold 1  macro-F1=0.7245  P1=0.700 R1=0.350  (1s)  [ratio 0.0, orig^1.25, C=0, rho=2.15]

[584/1560] RF        repeat 0 fold 1  macro-F1=0.7197  P1=0.435 R1=0.500  (7s)  [ratio 0.0, orig^1.25, C=1, rho=2.15]

[585/1560] RF        repeat 0 fold 1  macro-F1=0.7009  P1=0.409 R1=0.450  (1s)  [ratio 0.0, orig^1.5, C=0, rho=4.62]

[586/1560] RF        repeat 0 fold 1  macro-F1=0.7140  P1=0.857 R1=0.300  (8s)  [ratio 0.0, orig^1.5, C=1, rho=4.62]

[587/1560] RF        repeat 0 fold 1  macro-F1=0.5460  P1=0.126 R1=0.650  (2s)  [ratio 0.0, orig^2.0, C=0, rho=21.33]

[588/1560] RF        repeat 0 fold 1  macro-F1=0.6975  P1=0.667 R1=0.300  (8s)  [ratio 0.0, orig^2.0, C=1, rho=21.33]

[589/1560] RF        repeat 0 fold 1  macro-F1=0.7498  P1=0.727 R1=0.400  (3s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[590/1560] RF        repeat 0 fold 1  macro-F1=0.7308  P1=0.414 R1=0.600  (12s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[591/1560] RF        repeat 0 fold 1  macro-F1=0.7558  P1=0.643 R1=0.450  (3s)  [ratio 0.5, orig^0.25, C=0, rho=1.07]

[592/1560] RF        repeat 0 fold 1  macro-F1=0.7322  P1=0.476 R1=0.500  (17s)  [ratio 0.5, orig^0.25, C=1, rho=1.07]

[593/1560] RF        repeat 0 fold 1  macro-F1=0.7477  P1=0.600 R1=0.450  (4s)  [ratio 0.5, orig^0.5, C=0, rho=2.31]

[594/1560] RF        repeat 0 fold 1  macro-F1=0.6508  P1=0.263 R1=0.500  (18s)  [ratio 0.5, orig^0.5, C=1, rho=2.31]

[595/1560] RF        repeat 0 fold 1  macro-F1=0.6848  P1=0.360 R1=0.450  (6s)  [ratio 0.5, orig^0.75, C=0, rho=4.96]

[596/1560] RF        repeat 0 fold 1  macro-F1=0.7045  P1=0.471 R1=0.400  (19s)  [ratio 0.5, orig^0.75, C=1, rho=4.96]

[597/1560] RF        repeat 0 fold 1  macro-F1=0.6200  P1=0.214 R1=0.450  (4s)  [ratio 0.5, orig^1.0, C=0, rho=10.67]

[598/1560] RF        repeat 0 fold 1  macro-F1=0.6799  P1=0.346 R1=0.450  (20s)  [ratio 0.5, orig^1.0, C=1, rho=10.67]

[599/1560] RF        repeat 0 fold 1  macro-F1=0.5349  P1=0.110 R1=0.500  (5s)  [ratio 0.5, orig^1.25, C=0, rho=22.92]

[600/1560] RF        repeat 0 fold 1  macro-F1=0.6752  P1=0.333 R1=0.450  (20s)  [ratio 0.5, orig^1.25, C=1, rho=22.92]

[601/1560] RF        repeat 0 fold 1  macro-F1=0.4458  P1=0.087 R1=0.900  (5s)  [ratio 0.5, orig^1.5, C=0, rho=49.27]

[602/1560] RF        repeat 0 fold 1  macro-F1=0.6497  P1=0.455 R1=0.250  (20s)  [ratio 0.5, orig^1.5, C=1, rho=49.27]

[603/1560] RF        repeat 0 fold 1  macro-F1=0.0410  P1=0.043 R1=1.000  (5s)  [ratio 0.5, orig^2.0, C=0, rho=227.56]

[604/1560] RF        repeat 0 fold 1  macro-F1=0.6831  P1=0.545 R1=0.300  (26s)  [ratio 0.5, orig^2.0, C=1, rho=227.56]

[605/1560] RF        repeat 0 fold 1  macro-F1=0.7558  P1=0.643 R1=0.450  (7s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[606/1560] RF        repeat 0 fold 1  macro-F1=0.7388  P1=0.500 R1=0.500  (27s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[607/1560] RF        repeat 0 fold 1  macro-F1=0.7412  P1=0.667 R1=0.400  (7s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[608/1560] RF        repeat 0 fold 1  macro-F1=0.7322  P1=0.476 R1=0.500  (26s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[609/1560] RF        repeat 0 fold 1  macro-F1=0.7644  P1=0.692 R1=0.450  (8s)  [ratio 1.0, orig^0.25, C=0, rho=2.15]

[610/1560] RF        repeat 0 fold 1  macro-F1=0.6742  P1=0.312 R1=0.500  (24s)  [ratio 1.0, orig^0.25, C=1, rho=2.15]

[611/1560] RF        repeat 0 fold 1  macro-F1=0.7009  P1=0.409 R1=0.450  (7s)  [ratio 1.0, orig^0.5, C=0, rho=4.62]

[612/1560] RF        repeat 0 fold 1  macro-F1=0.6866  P1=0.400 R1=0.400  (25s)  [ratio 1.0, orig^0.5, C=1, rho=4.62]

[613/1560] RF        repeat 0 fold 1  macro-F1=0.6619  P1=0.300 R1=0.450  (9s)  [ratio 1.0, orig^0.75, C=0, rho=9.93]

[614/1560] RF        repeat 0 fold 1  macro-F1=0.6799  P1=0.346 R1=0.450  (23s)  [ratio 1.0, orig^0.75, C=1, rho=9.93]

[615/1560] RF        repeat 0 fold 1  macro-F1=0.5628  P1=0.134 R1=0.450  (6s)  [ratio 1.0, orig^1.0, C=0, rho=21.33]

[616/1560] RF        repeat 0 fold 1  macro-F1=0.6500  P1=0.273 R1=0.450  (19s)  [ratio 1.0, orig^1.0, C=1, rho=21.33]

[617/1560] RF        repeat 0 fold 1  macro-F1=0.5090  P1=0.104 R1=0.700  (5s)  [ratio 1.0, orig^1.25, C=0, rho=45.85]

[618/1560] RF        repeat 0 fold 1  macro-F1=0.6764  P1=0.500 R1=0.300  (16s)  [ratio 1.0, orig^1.25, C=1, rho=45.85]

[619/1560] RF        repeat 0 fold 1  macro-F1=0.3082  P1=0.060 R1=0.950  (4s)  [ratio 1.0, orig^1.5, C=0, rho=98.53]

[620/1560] RF        repeat 0 fold 1  macro-F1=0.6151  P1=0.750 R1=0.150  (14s)  [ratio 1.0, orig^1.5, C=1, rho=98.53]

[621/1560] RF        repeat 0 fold 1  macro-F1=0.0410  P1=0.043 R1=1.000  (3s)  [ratio 1.0, orig^2.0, C=0, rho=455.11]

[622/1560] RF        repeat 0 fold 1  macro-F1=0.7045  P1=0.471 R1=0.400  (12s)  [ratio 1.0, orig^2.0, C=1, rho=455.11]

[623/1560] RF        repeat 0 fold 1  macro-F1=0.7412  P1=0.667 R1=0.400  (5s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[624/1560] RF        repeat 0 fold 1  macro-F1=0.7322  P1=0.476 R1=0.500  (15s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[625/1560] RF        repeat 1 fold 0  macro-F1=0.6152  P1=1.000 R1=0.143  (5s)  [ratio 0.0, orig^0.0, C=0, rho=0.04]

[626/1560] RF        repeat 1 fold 0  macro-F1=0.6831  P1=0.600 R1=0.286  (29s)  [ratio 0.0, orig^0.0, C=1, rho=0.04]

[627/1560] RF        repeat 1 fold 0  macro-F1=0.6759  P1=0.833 R1=0.238  (8s)  [ratio 0.0, orig^0.25, C=0, rho=0.10]

[628/1560] RF        repeat 1 fold 0  macro-F1=0.7181  P1=0.571 R1=0.381  (28s)  [ratio 0.0, orig^0.25, C=1, rho=0.10]

[629/1560] RF        repeat 1 fold 0  macro-F1=0.6835  P1=1.000 R1=0.238  (8s)  [ratio 0.0, orig^0.5, C=0, rho=0.21]

[630/1560] RF        repeat 1 fold 0  macro-F1=0.7648  P1=0.500 R1=0.619  (26s)  [ratio 0.0, orig^0.5, C=1, rho=0.21]

[631/1560] RF        repeat 1 fold 0  macro-F1=0.6687  P1=0.714 R1=0.238  (7s)  [ratio 0.0, orig^0.75, C=0, rho=0.46]

[632/1560] RF        repeat 1 fold 0  macro-F1=0.7507  P1=0.524 R1=0.524  (23s)  [ratio 0.0, orig^0.75, C=1, rho=0.46]

[633/1560] RF        repeat 1 fold 0  macro-F1=0.7245  P1=0.778 R1=0.333  (6s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[634/1560] RF        repeat 1 fold 0  macro-F1=0.7532  P1=0.588 R1=0.476  (20s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[635/1560] RF        repeat 1 fold 0  macro-F1=0.7327  P1=0.562 R1=0.429  (6s)  [ratio 0.0, orig^1.25, C=0, rho=2.18]

[636/1560] RF        repeat 1 fold 0  macro-F1=0.7524  P1=0.464 R1=0.619  (19s)  [ratio 0.0, orig^1.25, C=1, rho=2.18]

[637/1560] RF        repeat 1 fold 0  macro-F1=0.7028  P1=0.400 R1=0.476  (3s)  [ratio 0.0, orig^1.5, C=0, rho=4.73]

[638/1560] RF        repeat 1 fold 0  macro-F1=0.6961  P1=0.343 R1=0.571  (14s)  [ratio 0.0, orig^1.5, C=1, rho=4.73]

[639/1560] RF        repeat 1 fold 0  macro-F1=0.5783  P1=0.162 R1=0.810  (4s)  [ratio 0.0, orig^2.0, C=0, rho=22.40]

[640/1560] RF        repeat 1 fold 0  macro-F1=0.6435  P1=0.353 R1=0.286  (9s)  [ratio 0.0, orig^2.0, C=1, rho=22.40]

[641/1560] RF        repeat 1 fold 0  macro-F1=0.7191  P1=0.500 R1=0.429  (2s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[642/1560] RF        repeat 1 fold 0  macro-F1=0.6993  P1=0.367 R1=0.524  (5s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[643/1560] RF        repeat 1 fold 0  macro-F1=0.7532  P1=0.588 R1=0.476  (1s)  [ratio 0.5, orig^0.25, C=0, rho=1.09]

[644/1560] RF        repeat 1 fold 0  macro-F1=0.7107  P1=0.350 R1=0.667  (5s)  [ratio 0.5, orig^0.25, C=1, rho=1.09]

[645/1560] RF        repeat 1 fold 0  macro-F1=0.6831  P1=0.345 R1=0.476  (1s)  [ratio 0.5, orig^0.5, C=0, rho=2.37]

[646/1560] RF        repeat 1 fold 0  macro-F1=0.7197  P1=0.455 R1=0.476  (5s)  [ratio 0.5, orig^0.5, C=1, rho=2.37]

[647/1560] RF        repeat 1 fold 0  macro-F1=0.6251  P1=0.214 R1=0.571  (1s)  [ratio 0.5, orig^0.75, C=0, rho=5.15]

[648/1560] RF        repeat 1 fold 0  macro-F1=0.6948  P1=0.538 R1=0.333  (5s)  [ratio 0.5, orig^0.75, C=1, rho=5.15]

[649/1560] RF        repeat 1 fold 0  macro-F1=0.5598  P1=0.147 R1=0.810  (1s)  [ratio 0.5, orig^1.0, C=0, rho=11.20]

[650/1560] RF        repeat 1 fold 0  macro-F1=0.7016  P1=0.583 R1=0.333  (5s)  [ratio 0.5, orig^1.0, C=1, rho=11.20]

[651/1560] RF        repeat 1 fold 0  macro-F1=0.3903  P1=0.078 R1=0.952  (1s)  [ratio 0.5, orig^1.25, C=0, rho=24.37]

[652/1560] RF        repeat 1 fold 0  macro-F1=0.6620  P1=0.310 R1=0.429  (5s)  [ratio 0.5, orig^1.25, C=1, rho=24.37]

[653/1560] RF        repeat 1 fold 0  macro-F1=0.0429  P1=0.045 R1=1.000  (1s)  [ratio 0.5, orig^1.5, C=0, rho=53.01]

[654/1560] RF        repeat 1 fold 0  macro-F1=0.6948  P1=0.538 R1=0.333  (4s)  [ratio 0.5, orig^1.5, C=1, rho=53.01]

[655/1560] RF        repeat 1 fold 0  macro-F1=0.0429  P1=0.045 R1=1.000  (1s)  [ratio 0.5, orig^2.0, C=0, rho=250.88]

[656/1560] RF        repeat 1 fold 0  macro-F1=0.6764  P1=0.438 R1=0.333  (4s)  [ratio 0.5, orig^2.0, C=1, rho=250.88]

[657/1560] RF        repeat 1 fold 0  macro-F1=0.7067  P1=0.450 R1=0.429  (1s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[658/1560] RF        repeat 1 fold 0  macro-F1=0.6900  P1=0.344 R1=0.524  (5s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[659/1560] RF        repeat 1 fold 0  macro-F1=0.7181  P1=0.571 R1=0.381  (1s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[660/1560] RF        repeat 1 fold 0  macro-F1=0.7249  P1=0.394 R1=0.619  (5s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[661/1560] RF        repeat 1 fold 0  macro-F1=0.7067  P1=0.450 R1=0.429  (1s)  [ratio 1.0, orig^0.25, C=0, rho=2.18]

[662/1560] RF        repeat 1 fold 0  macro-F1=0.7111  P1=0.533 R1=0.381  (5s)  [ratio 1.0, orig^0.25, C=1, rho=2.18]

[663/1560] RF        repeat 1 fold 0  macro-F1=0.6582  P1=0.286 R1=0.476  (1s)  [ratio 1.0, orig^0.5, C=0, rho=4.73]

[664/1560] RF        repeat 1 fold 0  macro-F1=0.6822  P1=0.467 R1=0.333  (5s)  [ratio 1.0, orig^0.5, C=1, rho=4.73]

[665/1560] RF        repeat 1 fold 0  macro-F1=0.6217  P1=0.205 R1=0.714  (1s)  [ratio 1.0, orig^0.75, C=0, rho=10.30]

[666/1560] RF        repeat 1 fold 0  macro-F1=0.6311  P1=0.233 R1=0.476  (5s)  [ratio 1.0, orig^0.75, C=1, rho=10.30]

[667/1560] RF        repeat 1 fold 0  macro-F1=0.4905  P1=0.109 R1=0.905  (1s)  [ratio 1.0, orig^1.0, C=0, rho=22.40]

[668/1560] RF        repeat 1 fold 0  macro-F1=0.6423  P1=0.304 R1=0.333  (6s)  [ratio 1.0, orig^1.0, C=1, rho=22.40]

[669/1560] RF        repeat 1 fold 0  macro-F1=0.2347  P1=0.057 R1=1.000  (1s)  [ratio 1.0, orig^1.25, C=0, rho=48.73]

[670/1560] RF        repeat 1 fold 0  macro-F1=0.6702  P1=0.500 R1=0.286  (6s)  [ratio 1.0, orig^1.25, C=1, rho=48.73]

[671/1560] RF        repeat 1 fold 0  macro-F1=0.0429  P1=0.045 R1=1.000  (1s)  [ratio 1.0, orig^1.5, C=0, rho=106.02]

[672/1560] RF        repeat 1 fold 0  macro-F1=0.6508  P1=0.270 R1=0.476  (8s)  [ratio 1.0, orig^1.5, C=1, rho=106.02]

[673/1560] RF        repeat 1 fold 0  macro-F1=0.0429  P1=0.045 R1=1.000  (1s)  [ratio 1.0, orig^2.0, C=0, rho=501.76]

[674/1560] RF        repeat 1 fold 0  macro-F1=0.6388  P1=0.333 R1=0.286  (9s)  [ratio 1.0, orig^2.0, C=1, rho=501.76]

[675/1560] RF        repeat 1 fold 0  macro-F1=0.7181  P1=0.571 R1=0.381  (3s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[676/1560] RF        repeat 1 fold 0  macro-F1=0.7249  P1=0.394 R1=0.619  (9s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[677/1560] RF        repeat 1 fold 1  macro-F1=0.6507  P1=0.800 R1=0.200  (2s)  [ratio 0.0, orig^0.0, C=0, rho=0.05]

[678/1560] RF        repeat 1 fold 1  macro-F1=0.7315  P1=0.440 R1=0.550  (8s)  [ratio 0.0, orig^0.0, C=1, rho=0.05]

[679/1560] RF        repeat 1 fold 1  macro-F1=0.7055  P1=0.750 R1=0.300  (2s)  [ratio 0.0, orig^0.25, C=0, rho=0.10]

[680/1560] RF        repeat 1 fold 1  macro-F1=0.7458  P1=0.526 R1=0.500  (8s)  [ratio 0.0, orig^0.25, C=1, rho=0.10]

[681/1560] RF        repeat 1 fold 1  macro-F1=0.7423  P1=0.875 R1=0.350  (2s)  [ratio 0.0, orig^0.5, C=0, rho=0.22]

[682/1560] RF        repeat 1 fold 1  macro-F1=0.7507  P1=0.500 R1=0.550  (8s)  [ratio 0.0, orig^0.5, C=1, rho=0.22]

[683/1560] RF        repeat 1 fold 1  macro-F1=0.6835  P1=0.833 R1=0.250  (2s)  [ratio 0.0, orig^0.75, C=0, rho=0.47]

[684/1560] RF        repeat 1 fold 1  macro-F1=0.8172  P1=0.650 R1=0.650  (8s)  [ratio 0.0, orig^0.75, C=1, rho=0.47]

[685/1560] RF        repeat 1 fold 1  macro-F1=0.6758  P1=0.714 R1=0.250  (2s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[686/1560] RF        repeat 1 fold 1  macro-F1=0.7864  P1=0.714 R1=0.500  (8s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[687/1560] RF        repeat 1 fold 1  macro-F1=0.7331  P1=0.778 R1=0.350  (1s)  [ratio 0.0, orig^1.25, C=0, rho=2.15]

[688/1560] RF        repeat 1 fold 1  macro-F1=0.7330  P1=0.615 R1=0.400  (8s)  [ratio 0.0, orig^1.25, C=1, rho=2.15]

[689/1560] RF        repeat 1 fold 1  macro-F1=0.7958  P1=0.769 R1=0.500  (1s)  [ratio 0.0, orig^1.5, C=0, rho=4.62]

[690/1560] RF        repeat 1 fold 1  macro-F1=0.7331  P1=0.778 R1=0.350  (8s)  [ratio 0.0, orig^1.5, C=1, rho=4.62]

[691/1560] RF        repeat 1 fold 1  macro-F1=0.5813  P1=0.159 R1=0.700  (1s)  [ratio 0.0, orig^2.0, C=0, rho=21.33]

[692/1560] RF        repeat 1 fold 1  macro-F1=0.6758  P1=0.714 R1=0.250  (9s)  [ratio 0.0, orig^2.0, C=1, rho=21.33]

[693/1560] RF        repeat 1 fold 1  macro-F1=0.7164  P1=0.636 R1=0.350  (3s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[694/1560] RF        repeat 1 fold 1  macro-F1=0.7164  P1=0.636 R1=0.350  (11s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[695/1560] RF        repeat 1 fold 1  macro-F1=0.7978  P1=0.688 R1=0.550  (3s)  [ratio 0.5, orig^0.25, C=0, rho=1.07]

[696/1560] RF        repeat 1 fold 1  macro-F1=0.7412  P1=0.667 R1=0.400  (10s)  [ratio 0.5, orig^0.25, C=1, rho=1.07]

[697/1560] RF        repeat 1 fold 1  macro-F1=0.8528  P1=0.737 R1=0.700  (2s)  [ratio 0.5, orig^0.5, C=0, rho=2.31]

[698/1560] RF        repeat 1 fold 1  macro-F1=0.8354  P1=0.722 R1=0.650  (10s)  [ratio 0.5, orig^0.5, C=1, rho=2.31]

[699/1560] RF        repeat 1 fold 1  macro-F1=0.7465  P1=0.433 R1=0.650  (2s)  [ratio 0.5, orig^0.75, C=0, rho=4.96]

[700/1560] RF        repeat 1 fold 1  macro-F1=0.7774  P1=0.667 R1=0.500  (10s)  [ratio 0.5, orig^0.75, C=1, rho=4.96]

[701/1560] RF        repeat 1 fold 1  macro-F1=0.5823  P1=0.161 R1=0.750  (2s)  [ratio 0.5, orig^1.0, C=0, rho=10.67]

[702/1560] RF        repeat 1 fold 1  macro-F1=0.7322  P1=0.476 R1=0.500  (10s)  [ratio 0.5, orig^1.0, C=1, rho=10.67]

[703/1560] RF        repeat 1 fold 1  macro-F1=0.3962  P1=0.076 R1=0.950  (2s)  [ratio 0.5, orig^1.25, C=0, rho=22.92]

[704/1560] RF        repeat 1 fold 1  macro-F1=0.7458  P1=0.526 R1=0.500  (9s)  [ratio 0.5, orig^1.25, C=1, rho=22.92]

[705/1560] RF        repeat 1 fold 1  macro-F1=0.0433  P1=0.043 R1=1.000  (2s)  [ratio 0.5, orig^1.5, C=0, rho=49.27]

[706/1560] RF        repeat 1 fold 1  macro-F1=0.7498  P1=0.727 R1=0.400  (9s)  [ratio 0.5, orig^1.5, C=1, rho=49.27]

[707/1560] RF        repeat 1 fold 1  macro-F1=0.0410  P1=0.043 R1=1.000  (2s)  [ratio 0.5, orig^2.0, C=0, rho=227.56]

[708/1560] RF        repeat 1 fold 1  macro-F1=0.6230  P1=0.220 R1=0.450  (9s)  [ratio 0.5, orig^2.0, C=1, rho=227.56]

[709/1560] RF        repeat 1 fold 1  macro-F1=0.7558  P1=0.643 R1=0.450  (2s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[710/1560] RF        repeat 1 fold 1  macro-F1=0.8006  P1=0.591 R1=0.650  (10s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[711/1560] RF        repeat 1 fold 1  macro-F1=0.7330  P1=0.615 R1=0.400  (3s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[712/1560] RF        repeat 1 fold 1  macro-F1=0.7164  P1=0.636 R1=0.350  (11s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[713/1560] RF        repeat 1 fold 1  macro-F1=0.7890  P1=0.647 R1=0.550  (3s)  [ratio 1.0, orig^0.25, C=0, rho=2.15]

[714/1560] RF        repeat 1 fold 1  macro-F1=0.7558  P1=0.643 R1=0.450  (12s)  [ratio 1.0, orig^0.25, C=1, rho=2.15]

[715/1560] RF        repeat 1 fold 1  macro-F1=0.7507  P1=0.500 R1=0.550  (3s)  [ratio 1.0, orig^0.5, C=0, rho=4.62]

[716/1560] RF        repeat 1 fold 1  macro-F1=0.7650  P1=0.550 R1=0.550  (12s)  [ratio 1.0, orig^0.5, C=1, rho=4.62]

[717/1560] RF        repeat 1 fold 1  macro-F1=0.6718  P1=0.286 R1=0.600  (3s)  [ratio 1.0, orig^0.75, C=0, rho=9.93]

[718/1560] RF        repeat 1 fold 1  macro-F1=0.7377  P1=0.458 R1=0.550  (12s)  [ratio 1.0, orig^0.75, C=1, rho=9.93]

[719/1560] RF        repeat 1 fold 1  macro-F1=0.5140  P1=0.109 R1=0.750  (3s)  [ratio 1.0, orig^1.0, C=0, rho=21.33]

[720/1560] RF        repeat 1 fold 1  macro-F1=0.7258  P1=0.455 R1=0.500  (11s)  [ratio 1.0, orig^1.0, C=1, rho=21.33]

[721/1560] RF        repeat 1 fold 1  macro-F1=0.1953  P1=0.051 R1=1.000  (3s)  [ratio 1.0, orig^1.25, C=0, rho=45.85]

[722/1560] RF        repeat 1 fold 1  macro-F1=0.7200  P1=0.407 R1=0.550  (10s)  [ratio 1.0, orig^1.25, C=1, rho=45.85]

[723/1560] RF        repeat 1 fold 1  macro-F1=0.0410  P1=0.043 R1=1.000  (3s)  [ratio 1.0, orig^1.5, C=0, rho=98.53]

[724/1560] RF        repeat 1 fold 1  macro-F1=0.7331  P1=0.778 R1=0.350  (8s)  [ratio 1.0, orig^1.5, C=1, rho=98.53]

[725/1560] RF        repeat 1 fold 1  macro-F1=0.0410  P1=0.043 R1=1.000  (2s)  [ratio 1.0, orig^2.0, C=0, rho=455.11]

[726/1560] RF        repeat 1 fold 1  macro-F1=0.6556  P1=0.333 R1=0.350  (6s)  [ratio 1.0, orig^2.0, C=1, rho=455.11]

[727/1560] RF        repeat 1 fold 1  macro-F1=0.7330  P1=0.615 R1=0.400  (2s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[728/1560] RF        repeat 1 fold 1  macro-F1=0.7164  P1=0.636 R1=0.350  (6s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[729/1560] RF        repeat 2 fold 0  macro-F1=0.6759  P1=0.833 R1=0.238  (1s)  [ratio 0.0, orig^0.0, C=0, rho=0.04]

[730/1560] RF        repeat 2 fold 0  macro-F1=0.6709  P1=0.412 R1=0.333  (5s)  [ratio 0.0, orig^0.0, C=1, rho=0.04]

[731/1560] RF        repeat 2 fold 0  macro-F1=0.6901  P1=0.667 R1=0.286  (1s)  [ratio 0.0, orig^0.25, C=0, rho=0.10]

[732/1560] RF        repeat 2 fold 0  macro-F1=0.7197  P1=0.455 R1=0.476  (5s)  [ratio 0.0, orig^0.25, C=1, rho=0.10]

[733/1560] RF        repeat 2 fold 0  macro-F1=0.7245  P1=0.778 R1=0.333  (1s)  [ratio 0.0, orig^0.5, C=0, rho=0.21]

[734/1560] RF        repeat 2 fold 0  macro-F1=0.7254  P1=0.414 R1=0.571  (5s)  [ratio 0.0, orig^0.5, C=1, rho=0.21]

[735/1560] RF        repeat 2 fold 0  macro-F1=0.6975  P1=0.750 R1=0.286  (1s)  [ratio 0.0, orig^0.75, C=0, rho=0.46]

[736/1560] RF        repeat 2 fold 0  macro-F1=0.7441  P1=0.500 R1=0.524  (10s)  [ratio 0.0, orig^0.75, C=1, rho=0.46]

[737/1560] RF        repeat 2 fold 0  macro-F1=0.7164  P1=0.700 R1=0.333  (1s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[738/1560] RF        repeat 2 fold 0  macro-F1=0.8261  P1=0.722 R1=0.619  (10s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[739/1560] RF        repeat 2 fold 0  macro-F1=0.7400  P1=0.600 R1=0.429  (1s)  [ratio 0.0, orig^1.25, C=0, rho=2.18]

[740/1560] RF        repeat 2 fold 0  macro-F1=0.8400  P1=0.640 R1=0.762  (12s)  [ratio 0.0, orig^1.25, C=1, rho=2.18]

[741/1560] RF        repeat 2 fold 0  macro-F1=0.8483  P1=0.667 R1=0.762  (2s)  [ratio 0.0, orig^1.5, C=0, rho=4.73]

[742/1560] RF        repeat 2 fold 0  macro-F1=0.8483  P1=0.667 R1=0.762  (12s)  [ratio 0.0, orig^1.5, C=1, rho=4.73]

[743/1560] RF        repeat 2 fold 0  macro-F1=0.5930  P1=0.176 R1=0.857  (2s)  [ratio 0.0, orig^2.0, C=0, rho=22.40]

[744/1560] RF        repeat 2 fold 0  macro-F1=0.8006  P1=0.619 R1=0.619  (12s)  [ratio 0.0, orig^2.0, C=1, rho=22.40]

[745/1560] RF        repeat 2 fold 0  macro-F1=0.7111  P1=0.533 R1=0.381  (5s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[746/1560] RF        repeat 2 fold 0  macro-F1=0.7441  P1=0.500 R1=0.524  (13s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[747/1560] RF        repeat 2 fold 0  macro-F1=0.7258  P1=0.476 R1=0.476  (3s)  [ratio 0.5, orig^0.25, C=0, rho=1.09]

[748/1560] RF        repeat 2 fold 0  macro-F1=0.7774  P1=0.714 R1=0.476  (12s)  [ratio 0.5, orig^0.25, C=1, rho=1.09]

[749/1560] RF        repeat 2 fold 0  macro-F1=0.7615  P1=0.467 R1=0.667  (3s)  [ratio 0.5, orig^0.5, C=0, rho=2.37]

[750/1560] RF        repeat 2 fold 0  macro-F1=0.7864  P1=0.769 R1=0.476  (12s)  [ratio 0.5, orig^0.5, C=1, rho=2.37]

[751/1560] RF        repeat 2 fold 0  macro-F1=0.6896  P1=0.288 R1=0.905  (3s)  [ratio 0.5, orig^0.75, C=0, rho=5.15]

[752/1560] RF        repeat 2 fold 0  macro-F1=0.7559  P1=0.692 R1=0.429  (11s)  [ratio 0.5, orig^0.75, C=1, rho=5.15]

[753/1560] RF        repeat 2 fold 0  macro-F1=0.5572  P1=0.148 R1=0.905  (2s)  [ratio 0.5, orig^1.0, C=0, rho=11.20]

[754/1560] RF        repeat 2 fold 0  macro-F1=0.7305  P1=0.362 R1=0.810  (11s)  [ratio 0.5, orig^1.0, C=1, rho=11.20]

[755/1560] RF        repeat 2 fold 0  macro-F1=0.3758  P1=0.077 R1=1.000  (2s)  [ratio 0.5, orig^1.25, C=0, rho=24.37]

[756/1560] RF        repeat 2 fold 0  macro-F1=0.7400  P1=0.600 R1=0.429  (10s)  [ratio 0.5, orig^1.25, C=1, rho=24.37]

[757/1560] RF        repeat 2 fold 0  macro-F1=0.0429  P1=0.045 R1=1.000  (3s)  [ratio 0.5, orig^1.5, C=0, rho=53.01]

[758/1560] RF        repeat 2 fold 0  macro-F1=0.7424  P1=0.462 R1=0.571  (9s)  [ratio 0.5, orig^1.5, C=1, rho=53.01]

[759/1560] RF        repeat 2 fold 0  macro-F1=0.0429  P1=0.045 R1=1.000  (2s)  [ratio 0.5, orig^2.0, C=0, rho=250.88]

[760/1560] RF        repeat 2 fold 0  macro-F1=0.6731  P1=0.270 R1=0.810  (8s)  [ratio 0.5, orig^2.0, C=1, rho=250.88]

[761/1560] RF        repeat 2 fold 0  macro-F1=0.7389  P1=0.526 R1=0.476  (2s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[762/1560] RF        repeat 2 fold 0  macro-F1=0.7330  P1=0.667 R1=0.381  (9s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[763/1560] RF        repeat 2 fold 0  macro-F1=0.7832  P1=0.600 R1=0.571  (2s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[764/1560] RF        repeat 2 fold 0  macro-F1=0.7832  P1=0.900 R1=0.429  (10s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[765/1560] RF        repeat 2 fold 0  macro-F1=0.8238  P1=0.567 R1=0.810  (3s)  [ratio 1.0, orig^0.25, C=0, rho=2.18]

[766/1560] RF        repeat 2 fold 0  macro-F1=0.7757  P1=0.571 R1=0.571  (11s)  [ratio 1.0, orig^0.25, C=1, rho=2.18]

[767/1560] RF        repeat 2 fold 0  macro-F1=0.7703  P1=0.429 R1=0.857  (3s)  [ratio 1.0, orig^0.5, C=0, rho=4.73]

[768/1560] RF        repeat 2 fold 0  macro-F1=0.7911  P1=0.632 R1=0.571  (11s)  [ratio 1.0, orig^0.5, C=1, rho=4.73]

[769/1560] RF        repeat 2 fold 0  macro-F1=0.6270  P1=0.211 R1=0.905  (3s)  [ratio 1.0, orig^0.75, C=0, rho=10.30]

[770/1560] RF        repeat 2 fold 0  macro-F1=0.7864  P1=0.769 R1=0.476  (11s)  [ratio 1.0, orig^0.75, C=1, rho=10.30]

[771/1560] RF        repeat 2 fold 0  macro-F1=0.4643  P1=0.100 R1=0.952  (3s)  [ratio 1.0, orig^1.0, C=0, rho=22.40]

[772/1560] RF        repeat 2 fold 0  macro-F1=0.7806  P1=0.647 R1=0.524  (11s)  [ratio 1.0, orig^1.0, C=1, rho=22.40]

[773/1560] RF        repeat 2 fold 0  macro-F1=0.1043  P1=0.048 R1=1.000  (3s)  [ratio 1.0, orig^1.25, C=0, rho=48.73]

[774/1560] RF        repeat 2 fold 0  macro-F1=0.7400  P1=0.600 R1=0.429  (10s)  [ratio 1.0, orig^1.25, C=1, rho=48.73]

[775/1560] RF        repeat 2 fold 0  macro-F1=0.0429  P1=0.045 R1=1.000  (2s)  [ratio 1.0, orig^1.5, C=0, rho=106.02]

[776/1560] RF        repeat 2 fold 0  macro-F1=0.7111  P1=0.533 R1=0.381  (10s)  [ratio 1.0, orig^1.5, C=1, rho=106.02]

[777/1560] RF        repeat 2 fold 0  macro-F1=0.0429  P1=0.045 R1=1.000  (2s)  [ratio 1.0, orig^2.0, C=0, rho=501.76]

[778/1560] RF        repeat 2 fold 0  macro-F1=0.7608  P1=0.625 R1=0.476  (8s)  [ratio 1.0, orig^2.0, C=1, rho=501.76]

[779/1560] RF        repeat 2 fold 0  macro-F1=0.7832  P1=0.600 R1=0.571  (3s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[780/1560] RF        repeat 2 fold 0  macro-F1=0.7832  P1=0.900 R1=0.429  (9s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[781/1560] RF        repeat 2 fold 1  macro-F1=0.7140  P1=0.857 R1=0.300  (2s)  [ratio 0.0, orig^0.0, C=0, rho=0.05]

[782/1560] RF        repeat 2 fold 1  macro-F1=0.7531  P1=0.556 R1=0.500  (9s)  [ratio 0.0, orig^0.0, C=1, rho=0.05]

[783/1560] RF        repeat 2 fold 1  macro-F1=0.7423  P1=0.875 R1=0.350  (2s)  [ratio 0.0, orig^0.25, C=0, rho=0.10]

[784/1560] RF        repeat 2 fold 1  macro-F1=0.8096  P1=0.556 R1=0.750  (10s)  [ratio 0.0, orig^0.25, C=1, rho=0.10]

[785/1560] RF        repeat 2 fold 1  macro-F1=0.7331  P1=0.778 R1=0.350  (2s)  [ratio 0.0, orig^0.5, C=0, rho=0.22]

[786/1560] RF        repeat 2 fold 1  macro-F1=0.7549  P1=0.480 R1=0.600  (10s)  [ratio 0.0, orig^0.5, C=1, rho=0.22]

[787/1560] RF        repeat 2 fold 1  macro-F1=0.7331  P1=0.778 R1=0.350  (2s)  [ratio 0.0, orig^0.75, C=0, rho=0.47]

[788/1560] RF        repeat 2 fold 1  macro-F1=0.7648  P1=0.481 R1=0.650  (8s)  [ratio 0.0, orig^0.75, C=1, rho=0.47]

[789/1560] RF        repeat 2 fold 1  macro-F1=0.6901  P1=0.600 R1=0.300  (2s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[790/1560] RF        repeat 2 fold 1  macro-F1=0.7523  P1=0.448 R1=0.650  (8s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[791/1560] RF        repeat 2 fold 1  macro-F1=0.6388  P1=0.385 R1=0.250  (2s)  [ratio 0.0, orig^1.25, C=0, rho=2.15]

[792/1560] RF        repeat 2 fold 1  macro-F1=0.6605  P1=0.350 R1=0.350  (9s)  [ratio 0.0, orig^1.25, C=1, rho=2.15]

[793/1560] RF        repeat 2 fold 1  macro-F1=0.6382  P1=0.280 R1=0.350  (2s)  [ratio 0.0, orig^1.5, C=0, rho=4.62]

[794/1560] RF        repeat 2 fold 1  macro-F1=0.6131  P1=0.219 R1=0.350  (9s)  [ratio 0.0, orig^1.5, C=1, rho=4.62]

[795/1560] RF        repeat 2 fold 1  macro-F1=0.5145  P1=0.088 R1=0.400  (2s)  [ratio 0.0, orig^2.0, C=0, rho=21.33]

[796/1560] RF        repeat 2 fold 1  macro-F1=0.5978  P1=0.217 R1=0.250  (8s)  [ratio 0.0, orig^2.0, C=1, rho=21.33]

[797/1560] RF        repeat 2 fold 1  macro-F1=0.7558  P1=0.643 R1=0.450  (3s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[798/1560] RF        repeat 2 fold 1  macro-F1=0.7424  P1=0.444 R1=0.600  (10s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[799/1560] RF        repeat 2 fold 1  macro-F1=0.7016  P1=0.538 R1=0.350  (3s)  [ratio 0.5, orig^0.25, C=0, rho=1.07]

[800/1560] RF        repeat 2 fold 1  macro-F1=0.7300  P1=0.394 R1=0.650  (8s)  [ratio 0.5, orig^0.25, C=1, rho=1.07]

[801/1560] RF        repeat 2 fold 1  macro-F1=0.6587  P1=0.400 R1=0.300  (2s)  [ratio 0.5, orig^0.5, C=0, rho=2.31]

[802/1560] RF        repeat 2 fold 1  macro-F1=0.6900  P1=0.375 R1=0.450  (7s)  [ratio 0.5, orig^0.5, C=1, rho=2.31]

[803/1560] RF        repeat 2 fold 1  macro-F1=0.5986  P1=0.200 R1=0.300  (2s)  [ratio 0.5, orig^0.75, C=0, rho=4.96]

[804/1560] RF        repeat 2 fold 1  macro-F1=0.5986  P1=0.200 R1=0.300  (7s)  [ratio 0.5, orig^0.75, C=1, rho=4.96]

[805/1560] RF        repeat 2 fold 1  macro-F1=0.5904  P1=0.175 R1=0.350  (2s)  [ratio 0.5, orig^1.0, C=0, rho=10.67]

[806/1560] RF        repeat 2 fold 1  macro-F1=0.5930  P1=0.179 R1=0.350  (8s)  [ratio 0.5, orig^1.0, C=1, rho=10.67]

[807/1560] RF        repeat 2 fold 1  macro-F1=0.5490  P1=0.120 R1=0.450  (2s)  [ratio 0.5, orig^1.25, C=0, rho=22.92]

[808/1560] RF        repeat 2 fold 1  macro-F1=0.6011  P1=0.194 R1=0.350  (7s)  [ratio 0.5, orig^1.25, C=1, rho=22.92]

[809/1560] RF        repeat 2 fold 1  macro-F1=0.4623  P1=0.075 R1=0.600  (2s)  [ratio 0.5, orig^1.5, C=0, rho=49.27]

[810/1560] RF        repeat 2 fold 1  macro-F1=0.5904  P1=0.175 R1=0.350  (6s)  [ratio 0.5, orig^1.5, C=1, rho=49.27]

[811/1560] RF        repeat 2 fold 1  macro-F1=0.1266  P1=0.047 R1=1.000  (1s)  [ratio 0.5, orig^2.0, C=0, rho=227.56]

[812/1560] RF        repeat 2 fold 1  macro-F1=0.5821  P1=0.167 R1=0.300  (6s)  [ratio 0.5, orig^2.0, C=1, rho=227.56]

[813/1560] RF        repeat 2 fold 1  macro-F1=0.7558  P1=0.643 R1=0.450  (1s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[814/1560] RF        repeat 2 fold 1  macro-F1=0.7424  P1=0.444 R1=0.600  (9s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[815/1560] RF        repeat 2 fold 1  macro-F1=0.7412  P1=0.667 R1=0.400  (2s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[816/1560] RF        repeat 2 fold 1  macro-F1=0.7249  P1=0.382 R1=0.650  (12s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[817/1560] RF        repeat 2 fold 1  macro-F1=0.6388  P1=0.385 R1=0.250  (2s)  [ratio 1.0, orig^0.25, C=0, rho=2.15]

[818/1560] RF        repeat 2 fold 1  macro-F1=0.6865  P1=0.298 R1=0.700  (12s)  [ratio 1.0, orig^0.25, C=1, rho=2.15]

[819/1560] RF        repeat 2 fold 1  macro-F1=0.6533  P1=0.375 R1=0.300  (3s)  [ratio 1.0, orig^0.5, C=0, rho=4.62]

[820/1560] RF        repeat 2 fold 1  macro-F1=0.6231  P1=0.241 R1=0.350  (11s)  [ratio 1.0, orig^0.5, C=1, rho=4.62]

[821/1560] RF        repeat 2 fold 1  macro-F1=0.6040  P1=0.200 R1=0.350  (4s)  [ratio 1.0, orig^0.75, C=0, rho=9.93]

[822/1560] RF        repeat 2 fold 1  macro-F1=0.5784  P1=0.156 R1=0.350  (8s)  [ratio 1.0, orig^0.75, C=1, rho=9.93]

[823/1560] RF        repeat 2 fold 1  macro-F1=0.5472  P1=0.115 R1=0.350  (2s)  [ratio 1.0, orig^1.0, C=0, rho=21.33]

[824/1560] RF        repeat 2 fold 1  macro-F1=0.5830  P1=0.163 R1=0.350  (7s)  [ratio 1.0, orig^1.0, C=1, rho=21.33]

[825/1560] RF        repeat 2 fold 1  macro-F1=0.5010  P1=0.083 R1=0.450  (2s)  [ratio 1.0, orig^1.25, C=0, rho=45.85]

[826/1560] RF        repeat 2 fold 1  macro-F1=0.5830  P1=0.163 R1=0.350  (6s)  [ratio 1.0, orig^1.25, C=1, rho=45.85]

[827/1560] RF        repeat 2 fold 1  macro-F1=0.3827  P1=0.061 R1=0.750  (1s)  [ratio 1.0, orig^1.5, C=0, rho=98.53]

[828/1560] RF        repeat 2 fold 1  macro-F1=0.5677  P1=0.140 R1=0.350  (5s)  [ratio 1.0, orig^1.5, C=1, rho=98.53]

[829/1560] RF        repeat 2 fold 1  macro-F1=0.0410  P1=0.043 R1=1.000  (1s)  [ratio 1.0, orig^2.0, C=0, rho=455.11]

[830/1560] RF        repeat 2 fold 1  macro-F1=0.5726  P1=0.150 R1=0.300  (4s)  [ratio 1.0, orig^2.0, C=1, rho=455.11]

[831/1560] RF        repeat 2 fold 1  macro-F1=0.7412  P1=0.667 R1=0.400  (1s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[832/1560] RF        repeat 2 fold 1  macro-F1=0.7249  P1=0.382 R1=0.650  (4s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[833/1560] RF        repeat 3 fold 0  macro-F1=0.5296  P1=0.333 R1=0.048  (2s)  [ratio 0.0, orig^0.0, C=0, rho=0.04]

[834/1560] RF        repeat 3 fold 0  macro-F1=0.5685  P1=0.500 R1=0.095  (7s)  [ratio 0.0, orig^0.0, C=1, rho=0.04]

[835/1560] RF        repeat 3 fold 0  macro-F1=0.5685  P1=0.500 R1=0.095  (2s)  [ratio 0.0, orig^0.25, C=0, rho=0.10]

[836/1560] RF        repeat 3 fold 0  macro-F1=0.5685  P1=0.500 R1=0.095  (8s)  [ratio 0.0, orig^0.25, C=1, rho=0.10]

[837/1560] RF        repeat 3 fold 0  macro-F1=0.6096  P1=0.750 R1=0.143  (2s)  [ratio 0.0, orig^0.5, C=0, rho=0.21]

[838/1560] RF        repeat 3 fold 0  macro-F1=0.6901  P1=0.667 R1=0.286  (9s)  [ratio 0.0, orig^0.5, C=1, rho=0.21]

[839/1560] RF        repeat 3 fold 0  macro-F1=0.6044  P1=0.600 R1=0.143  (2s)  [ratio 0.0, orig^0.75, C=0, rho=0.46]

[840/1560] RF        repeat 3 fold 0  macro-F1=0.7322  P1=0.500 R1=0.476  (13s)  [ratio 0.0, orig^0.75, C=1, rho=0.46]

[841/1560] RF        repeat 3 fold 0  macro-F1=0.6044  P1=0.600 R1=0.143  (3s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[842/1560] RF        repeat 3 fold 0  macro-F1=0.6812  P1=0.400 R1=0.381  (12s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[843/1560] RF        repeat 3 fold 0  macro-F1=0.6160  P1=0.294 R1=0.238  (3s)  [ratio 0.0, orig^1.25, C=0, rho=2.18]

[844/1560] RF        repeat 3 fold 0  macro-F1=0.6089  P1=0.196 R1=0.476  (12s)  [ratio 0.0, orig^1.25, C=1, rho=2.18]

[845/1560] RF        repeat 3 fold 0  macro-F1=0.5580  P1=0.130 R1=0.286  (3s)  [ratio 0.0, orig^1.5, C=0, rho=4.73]

[846/1560] RF        repeat 3 fold 0  macro-F1=0.5561  P1=0.128 R1=0.286  (11s)  [ratio 0.0, orig^1.5, C=1, rho=4.73]

[847/1560] RF        repeat 3 fold 0  macro-F1=0.5617  P1=0.138 R1=0.524  (3s)  [ratio 0.0, orig^2.0, C=0, rho=22.40]

[848/1560] RF        repeat 3 fold 0  macro-F1=0.5402  P1=0.106 R1=0.238  (10s)  [ratio 0.0, orig^2.0, C=1, rho=22.40]

[849/1560] RF        repeat 3 fold 0  macro-F1=0.6687  P1=0.714 R1=0.238  (2s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[850/1560] RF        repeat 3 fold 0  macro-F1=0.7458  P1=0.556 R1=0.476  (10s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[851/1560] RF        repeat 3 fold 0  macro-F1=0.6687  P1=0.714 R1=0.238  (2s)  [ratio 0.5, orig^0.25, C=0, rho=1.09]

[852/1560] RF        repeat 3 fold 0  macro-F1=0.6812  P1=0.400 R1=0.381  (9s)  [ratio 0.5, orig^0.25, C=1, rho=1.09]

[853/1560] RF        repeat 3 fold 0  macro-F1=0.6702  P1=0.500 R1=0.286  (2s)  [ratio 0.5, orig^0.5, C=0, rho=2.37]

[854/1560] RF        repeat 3 fold 0  macro-F1=0.6615  P1=0.333 R1=0.381  (9s)  [ratio 0.5, orig^0.5, C=1, rho=2.37]

[855/1560] RF        repeat 3 fold 0  macro-F1=0.6070  P1=0.212 R1=0.333  (2s)  [ratio 0.5, orig^0.75, C=0, rho=5.15]

[856/1560] RF        repeat 3 fold 0  macro-F1=0.6324  P1=0.243 R1=0.429  (9s)  [ratio 0.5, orig^0.75, C=1, rho=5.15]

[857/1560] RF        repeat 3 fold 0  macro-F1=0.5898  P1=0.169 R1=0.619  (2s)  [ratio 0.5, orig^1.0, C=0, rho=11.20]

[858/1560] RF        repeat 3 fold 0  macro-F1=0.5795  P1=0.156 R1=0.476  (10s)  [ratio 0.5, orig^1.0, C=1, rho=11.20]

[859/1560] RF        repeat 3 fold 0  macro-F1=0.4957  P1=0.111 R1=0.905  (2s)  [ratio 0.5, orig^1.25, C=0, rho=24.37]

[860/1560] RF        repeat 3 fold 0  macro-F1=0.5947  P1=0.175 R1=0.524  (10s)  [ratio 0.5, orig^1.25, C=1, rho=24.37]

[861/1560] RF        repeat 3 fold 0  macro-F1=0.0521  P1=0.045 R1=1.000  (3s)  [ratio 0.5, orig^1.5, C=0, rho=53.01]

[862/1560] RF        repeat 3 fold 0  macro-F1=0.6039  P1=0.189 R1=0.476  (10s)  [ratio 0.5, orig^1.5, C=1, rho=53.01]

[863/1560] RF        repeat 3 fold 0  macro-F1=0.0429  P1=0.045 R1=1.000  (2s)  [ratio 0.5, orig^2.0, C=0, rho=250.88]

[864/1560] RF        repeat 3 fold 0  macro-F1=0.6149  P1=0.250 R1=0.286  (8s)  [ratio 0.5, orig^2.0, C=1, rho=250.88]

[865/1560] RF        repeat 3 fold 0  macro-F1=0.6620  P1=0.625 R1=0.238  (2s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[866/1560] RF        repeat 3 fold 0  macro-F1=0.6884  P1=0.500 R1=0.333  (9s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[867/1560] RF        repeat 3 fold 0  macro-F1=0.6687  P1=0.714 R1=0.238  (2s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[868/1560] RF        repeat 3 fold 0  macro-F1=0.6656  P1=0.389 R1=0.333  (10s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[869/1560] RF        repeat 3 fold 0  macro-F1=0.6557  P1=0.556 R1=0.238  (3s)  [ratio 1.0, orig^0.25, C=0, rho=2.18]

[870/1560] RF        repeat 3 fold 0  macro-F1=0.6812  P1=0.400 R1=0.381  (10s)  [ratio 1.0, orig^0.25, C=1, rho=2.18]

[871/1560] RF        repeat 3 fold 0  macro-F1=0.6245  P1=0.333 R1=0.238  (3s)  [ratio 1.0, orig^0.5, C=0, rho=4.73]

[872/1560] RF        repeat 3 fold 0  macro-F1=0.6267  P1=0.259 R1=0.333  (10s)  [ratio 1.0, orig^0.5, C=1, rho=4.73]

[873/1560] RF        repeat 3 fold 0  macro-F1=0.5986  P1=0.184 R1=0.429  (3s)  [ratio 1.0, orig^0.75, C=0, rho=10.30]

[874/1560] RF        repeat 3 fold 0  macro-F1=0.5986  P1=0.184 R1=0.429  (10s)  [ratio 1.0, orig^0.75, C=1, rho=10.30]

[875/1560] RF        repeat 3 fold 0  macro-F1=0.5632  P1=0.146 R1=0.714  (3s)  [ratio 1.0, orig^1.0, C=0, rho=22.40]

[876/1560] RF        repeat 3 fold 0  macro-F1=0.5665  P1=0.140 R1=0.381  (10s)  [ratio 1.0, orig^1.0, C=1, rho=22.40]

[877/1560] RF        repeat 3 fold 0  macro-F1=0.4123  P1=0.086 R1=1.000  (2s)  [ratio 1.0, orig^1.25, C=0, rho=48.73]

[878/1560] RF        repeat 3 fold 0  macro-F1=0.6324  P1=0.243 R1=0.429  (9s)  [ratio 1.0, orig^1.25, C=1, rho=48.73]

[879/1560] RF        repeat 3 fold 0  macro-F1=0.0429  P1=0.045 R1=1.000  (2s)  [ratio 1.0, orig^1.5, C=0, rho=106.02]

[880/1560] RF        repeat 3 fold 0  macro-F1=0.6202  P1=0.229 R1=0.381  (9s)  [ratio 1.0, orig^1.5, C=1, rho=106.02]

[881/1560] RF        repeat 3 fold 0  macro-F1=0.0429  P1=0.045 R1=1.000  (2s)  [ratio 1.0, orig^2.0, C=0, rho=501.76]

[882/1560] RF        repeat 3 fold 0  macro-F1=0.5900  P1=0.188 R1=0.286  (7s)  [ratio 1.0, orig^2.0, C=1, rho=501.76]

[883/1560] RF        repeat 3 fold 0  macro-F1=0.6687  P1=0.714 R1=0.238  (2s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[884/1560] RF        repeat 3 fold 0  macro-F1=0.6656  P1=0.389 R1=0.333  (8s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[885/1560] RF        repeat 3 fold 1  macro-F1=0.5372  P1=1.000 R1=0.050  (4s)  [ratio 0.0, orig^0.0, C=0, rho=0.05]

[886/1560] RF        repeat 3 fold 1  macro-F1=0.5993  P1=0.267 R1=0.200  (16s)  [ratio 0.0, orig^0.0, C=1, rho=0.05]

[887/1560] RF        repeat 3 fold 1  macro-F1=0.5724  P1=0.500 R1=0.100  (4s)  [ratio 0.0, orig^0.25, C=0, rho=0.10]

[888/1560] RF        repeat 3 fold 1  macro-F1=0.6497  P1=0.455 R1=0.250  (18s)  [ratio 0.0, orig^0.25, C=1, rho=0.10]

[889/1560] RF        repeat 3 fold 1  macro-F1=0.5766  P1=0.667 R1=0.100  (4s)  [ratio 0.0, orig^0.5, C=0, rho=0.22]

[890/1560] RF        repeat 3 fold 1  macro-F1=0.6822  P1=0.438 R1=0.350  (18s)  [ratio 0.0, orig^0.5, C=1, rho=0.22]

[891/1560] RF        repeat 3 fold 1  macro-F1=0.5766  P1=0.667 R1=0.100  (5s)  [ratio 0.0, orig^0.75, C=0, rho=0.47]

[892/1560] RF        repeat 3 fold 1  macro-F1=0.7441  P1=0.478 R1=0.550  (15s)  [ratio 0.0, orig^0.75, C=1, rho=0.47]

[893/1560] RF        repeat 3 fold 1  macro-F1=0.6096  P1=0.600 R1=0.150  (4s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[894/1560] RF        repeat 3 fold 1  macro-F1=0.7164  P1=0.636 R1=0.350  (12s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[895/1560] RF        repeat 3 fold 1  macro-F1=0.6975  P1=0.667 R1=0.300  (3s)  [ratio 0.0, orig^1.25, C=0, rho=2.15]

[896/1560] RF        repeat 3 fold 1  macro-F1=0.6975  P1=0.667 R1=0.300  (11s)  [ratio 0.0, orig^1.25, C=1, rho=2.15]

[897/1560] RF        repeat 3 fold 1  macro-F1=0.7531  P1=0.556 R1=0.500  (2s)  [ratio 0.0, orig^1.5, C=0, rho=4.62]

[898/1560] RF        repeat 3 fold 1  macro-F1=0.6975  P1=0.667 R1=0.300  (13s)  [ratio 0.0, orig^1.5, C=1, rho=4.62]

[899/1560] RF        repeat 3 fold 1  macro-F1=0.5758  P1=0.154 R1=0.700  (2s)  [ratio 0.0, orig^2.0, C=0, rho=21.33]

[900/1560] RF        repeat 3 fold 1  macro-F1=0.6948  P1=0.500 R1=0.350  (14s)  [ratio 0.0, orig^2.0, C=1, rho=21.33]

[901/1560] RF        repeat 3 fold 1  macro-F1=0.6556  P1=0.500 R1=0.250  (4s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[902/1560] RF        repeat 3 fold 1  macro-F1=0.6556  P1=0.500 R1=0.250  (16s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[903/1560] RF        repeat 3 fold 1  macro-F1=0.6883  P1=0.467 R1=0.350  (4s)  [ratio 0.5, orig^0.25, C=0, rho=1.07]

[904/1560] RF        repeat 3 fold 1  macro-F1=0.6883  P1=0.467 R1=0.350  (16s)  [ratio 0.5, orig^0.25, C=1, rho=1.07]

[905/1560] RF        repeat 3 fold 1  macro-F1=0.7145  P1=0.393 R1=0.550  (6s)  [ratio 0.5, orig^0.5, C=0, rho=2.31]

[906/1560] RF        repeat 3 fold 1  macro-F1=0.7253  P1=0.571 R1=0.400  (13s)  [ratio 0.5, orig^0.5, C=1, rho=2.31]

[907/1560] RF        repeat 3 fold 1  macro-F1=0.6670  P1=0.271 R1=0.650  (5s)  [ratio 0.5, orig^0.75, C=0, rho=4.96]

[908/1560] RF        repeat 3 fold 1  macro-F1=0.7164  P1=0.636 R1=0.350  (10s)  [ratio 0.5, orig^0.75, C=1, rho=4.96]

[909/1560] RF        repeat 3 fold 1  macro-F1=0.5817  P1=0.163 R1=0.850  (2s)  [ratio 0.5, orig^1.0, C=0, rho=10.67]

[910/1560] RF        repeat 3 fold 1  macro-F1=0.6983  P1=0.444 R1=0.400  (11s)  [ratio 0.5, orig^1.0, C=1, rho=10.67]

[911/1560] RF        repeat 3 fold 1  macro-F1=0.3529  P1=0.070 R1=1.000  (2s)  [ratio 0.5, orig^1.25, C=0, rho=22.92]

[912/1560] RF        repeat 3 fold 1  macro-F1=0.6440  P1=0.667 R1=0.200  (10s)  [ratio 0.5, orig^1.25, C=1, rho=22.92]

[913/1560] RF        repeat 3 fold 1  macro-F1=0.0410  P1=0.043 R1=1.000  (2s)  [ratio 0.5, orig^1.5, C=0, rho=49.27]

[914/1560] RF        repeat 3 fold 1  macro-F1=0.6687  P1=0.625 R1=0.250  (9s)  [ratio 0.5, orig^1.5, C=1, rho=49.27]

[915/1560] RF        repeat 3 fold 1  macro-F1=0.0410  P1=0.043 R1=1.000  (2s)  [ratio 0.5, orig^2.0, C=0, rho=227.56]

[916/1560] RF        repeat 3 fold 1  macro-F1=0.6764  P1=0.500 R1=0.300  (7s)  [ratio 0.5, orig^2.0, C=1, rho=227.56]

[917/1560] RF        repeat 3 fold 1  macro-F1=0.6948  P1=0.500 R1=0.350  (2s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[918/1560] RF        repeat 3 fold 1  macro-F1=0.6948  P1=0.500 R1=0.350  (10s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[919/1560] RF        repeat 3 fold 1  macro-F1=0.7180  P1=0.533 R1=0.400  (2s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[920/1560] RF        repeat 3 fold 1  macro-F1=0.7180  P1=0.533 R1=0.400  (10s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[921/1560] RF        repeat 3 fold 1  macro-F1=0.7458  P1=0.526 R1=0.500  (3s)  [ratio 1.0, orig^0.25, C=0, rho=2.15]

[922/1560] RF        repeat 3 fold 1  macro-F1=0.7412  P1=0.667 R1=0.400  (12s)  [ratio 1.0, orig^0.25, C=1, rho=2.15]

[923/1560] RF        repeat 3 fold 1  macro-F1=0.7093  P1=0.379 R1=0.550  (2s)  [ratio 1.0, orig^0.5, C=0, rho=4.62]

[924/1560] RF        repeat 3 fold 1  macro-F1=0.7458  P1=0.526 R1=0.500  (17s)  [ratio 1.0, orig^0.5, C=1, rho=4.62]

[925/1560] RF        repeat 3 fold 1  macro-F1=0.6658  P1=0.258 R1=0.800  (3s)  [ratio 1.0, orig^0.75, C=0, rho=9.93]

[926/1560] RF        repeat 3 fold 1  macro-F1=0.7322  P1=0.476 R1=0.500  (19s)  [ratio 1.0, orig^0.75, C=1, rho=9.93]

[927/1560] RF        repeat 3 fold 1  macro-F1=0.4759  P1=0.102 R1=0.950  (4s)  [ratio 1.0, orig^1.0, C=0, rho=21.33]

[928/1560] RF        repeat 3 fold 1  macro-F1=0.7191  P1=0.474 R1=0.450  (17s)  [ratio 1.0, orig^1.0, C=1, rho=21.33]

[929/1560] RF        repeat 3 fold 1  macro-F1=0.1758  P1=0.050 R1=1.000  (4s)  [ratio 1.0, orig^1.25, C=0, rho=45.85]

[930/1560] RF        repeat 3 fold 1  macro-F1=0.6866  P1=0.400 R1=0.400  (18s)  [ratio 1.0, orig^1.25, C=1, rho=45.85]

[931/1560] RF        repeat 3 fold 1  macro-F1=0.0410  P1=0.043 R1=1.000  (4s)  [ratio 1.0, orig^1.5, C=0, rho=98.53]

[932/1560] RF        repeat 3 fold 1  macro-F1=0.6533  P1=0.375 R1=0.300  (16s)  [ratio 1.0, orig^1.5, C=1, rho=98.53]

[933/1560] RF        repeat 3 fold 1  macro-F1=0.0410  P1=0.043 R1=1.000  (3s)  [ratio 1.0, orig^2.0, C=0, rho=455.11]

[934/1560] RF        repeat 3 fold 1  macro-F1=0.6799  P1=0.346 R1=0.450  (15s)  [ratio 1.0, orig^2.0, C=1, rho=455.11]

[935/1560] RF        repeat 3 fold 1  macro-F1=0.7180  P1=0.533 R1=0.400  (4s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[936/1560] RF        repeat 3 fold 1  macro-F1=0.7180  P1=0.533 R1=0.400  (15s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[937/1560] RF        repeat 4 fold 0  macro-F1=0.6687  P1=0.714 R1=0.238  (2s)  [ratio 0.0, orig^0.0, C=0, rho=0.04]

[938/1560] RF        repeat 4 fold 0  macro-F1=0.7549  P1=0.500 R1=0.571  (9s)  [ratio 0.0, orig^0.0, C=1, rho=0.04]

[939/1560] RF        repeat 4 fold 0  macro-F1=0.7644  P1=0.750 R1=0.429  (2s)  [ratio 0.0, orig^0.25, C=0, rho=0.10]

[940/1560] RF        repeat 4 fold 0  macro-F1=0.7854  P1=0.565 R1=0.619  (9s)  [ratio 0.0, orig^0.25, C=1, rho=0.10]

[941/1560] RF        repeat 4 fold 0  macro-F1=0.7644  P1=0.750 R1=0.429  (2s)  [ratio 0.0, orig^0.5, C=0, rho=0.21]

[942/1560] RF        repeat 4 fold 0  macro-F1=0.7783  P1=0.542 R1=0.619  (10s)  [ratio 0.0, orig^0.5, C=1, rho=0.21]

[943/1560] RF        repeat 4 fold 0  macro-F1=0.7253  P1=0.615 R1=0.381  (2s)  [ratio 0.0, orig^0.75, C=0, rho=0.46]

[944/1560] RF        repeat 4 fold 0  macro-F1=0.7317  P1=0.372 R1=0.762  (11s)  [ratio 0.0, orig^0.75, C=1, rho=0.46]

[945/1560] RF        repeat 4 fold 0  macro-F1=0.7532  P1=0.588 R1=0.476  (2s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[946/1560] RF        repeat 4 fold 0  macro-F1=0.7739  P1=0.500 R1=0.667  (10s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[947/1560] RF        repeat 4 fold 0  macro-F1=0.7911  P1=0.632 R1=0.571  (2s)  [ratio 0.0, orig^1.25, C=0, rho=2.18]

[948/1560] RF        repeat 4 fold 0  macro-F1=0.7585  P1=0.481 R1=0.619  (9s)  [ratio 0.0, orig^1.25, C=1, rho=2.18]

[949/1560] RF        repeat 4 fold 0  macro-F1=0.7393  P1=0.412 R1=0.667  (2s)  [ratio 0.0, orig^1.5, C=0, rho=4.73]

[950/1560] RF        repeat 4 fold 0  macro-F1=0.7107  P1=0.350 R1=0.667  (7s)  [ratio 0.0, orig^1.5, C=1, rho=4.73]

[951/1560] RF        repeat 4 fold 0  macro-F1=0.4879  P1=0.105 R1=0.857  (2s)  [ratio 0.0, orig^2.0, C=0, rho=22.40]

[952/1560] RF        repeat 4 fold 0  macro-F1=0.6449  P1=0.245 R1=0.571  (7s)  [ratio 0.0, orig^2.0, C=1, rho=22.40]

[953/1560] RF        repeat 4 fold 0  macro-F1=0.7650  P1=0.579 R1=0.524  (3s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[954/1560] RF        repeat 4 fold 0  macro-F1=0.7911  P1=0.486 R1=0.810  (9s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[955/1560] RF        repeat 4 fold 0  macro-F1=0.8006  P1=0.619 R1=0.619  (2s)  [ratio 0.5, orig^0.25, C=0, rho=1.09]

[956/1560] RF        repeat 4 fold 0  macro-F1=0.7305  P1=0.362 R1=0.810  (9s)  [ratio 0.5, orig^0.25, C=1, rho=1.09]

[957/1560] RF        repeat 4 fold 0  macro-F1=0.7804  P1=0.519 R1=0.667  (2s)  [ratio 0.5, orig^0.5, C=0, rho=2.37]

[958/1560] RF        repeat 4 fold 0  macro-F1=0.7392  P1=0.378 R1=0.810  (9s)  [ratio 0.5, orig^0.5, C=1, rho=2.37]

[959/1560] RF        repeat 4 fold 0  macro-F1=0.7329  P1=0.385 R1=0.714  (2s)  [ratio 0.5, orig^0.75, C=0, rho=5.15]

[960/1560] RF        repeat 4 fold 0  macro-F1=0.6890  P1=0.293 R1=0.810  (9s)  [ratio 0.5, orig^0.75, C=1, rho=5.15]

[961/1560] RF        repeat 4 fold 0  macro-F1=0.6306  P1=0.215 R1=0.810  (2s)  [ratio 0.5, orig^1.0, C=0, rho=11.20]

[962/1560] RF        repeat 4 fold 0  macro-F1=0.7292  P1=0.389 R1=0.667  (9s)  [ratio 0.5, orig^1.0, C=1, rho=11.20]

[963/1560] RF        repeat 4 fold 0  macro-F1=0.5285  P1=0.127 R1=0.857  (2s)  [ratio 0.5, orig^1.25, C=0, rho=24.37]

[964/1560] RF        repeat 4 fold 0  macro-F1=0.6571  P1=0.260 R1=0.619  (9s)  [ratio 0.5, orig^1.25, C=1, rho=24.37]

[965/1560] RF        repeat 4 fold 0  macro-F1=0.3669  P1=0.072 R1=0.952  (2s)  [ratio 0.5, orig^1.5, C=0, rho=53.01]

[966/1560] RF        repeat 4 fold 0  macro-F1=0.6544  P1=0.261 R1=0.571  (9s)  [ratio 0.5, orig^1.5, C=1, rho=53.01]

[967/1560] RF        repeat 4 fold 0  macro-F1=0.0429  P1=0.045 R1=1.000  (2s)  [ratio 0.5, orig^2.0, C=0, rho=250.88]

[968/1560] RF        repeat 4 fold 0  macro-F1=0.6831  P1=0.345 R1=0.476  (8s)  [ratio 0.5, orig^2.0, C=1, rho=250.88]

[969/1560] RF        repeat 4 fold 0  macro-F1=0.8006  P1=0.619 R1=0.619  (2s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[970/1560] RF        repeat 4 fold 0  macro-F1=0.7839  P1=0.485 R1=0.762  (8s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[971/1560] RF        repeat 4 fold 0  macro-F1=0.8006  P1=0.619 R1=0.619  (3s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[972/1560] RF        repeat 4 fold 0  macro-F1=0.7509  P1=0.391 R1=0.857  (7s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[973/1560] RF        repeat 4 fold 0  macro-F1=0.7739  P1=0.500 R1=0.667  (2s)  [ratio 1.0, orig^0.25, C=0, rho=2.18]

[974/1560] RF        repeat 4 fold 0  macro-F1=0.7509  P1=0.391 R1=0.857  (7s)  [ratio 1.0, orig^0.25, C=1, rho=2.18]

[975/1560] RF        repeat 4 fold 0  macro-F1=0.7458  P1=0.400 R1=0.762  (2s)  [ratio 1.0, orig^0.5, C=0, rho=4.73]

[976/1560] RF        repeat 4 fold 0  macro-F1=0.6586  P1=0.250 R1=0.810  (7s)  [ratio 1.0, orig^0.5, C=1, rho=4.73]

[977/1560] RF        repeat 4 fold 0  macro-F1=0.6311  P1=0.216 R1=0.762  (2s)  [ratio 1.0, orig^0.75, C=0, rho=10.30]

[978/1560] RF        repeat 4 fold 0  macro-F1=0.6263  P1=0.211 R1=0.762  (9s)  [ratio 1.0, orig^0.75, C=1, rho=10.30]

[979/1560] RF        repeat 4 fold 0  macro-F1=0.5507  P1=0.142 R1=0.857  (1s)  [ratio 1.0, orig^1.0, C=0, rho=22.40]

[980/1560] RF        repeat 4 fold 0  macro-F1=0.6121  P1=0.194 R1=0.667  (10s)  [ratio 1.0, orig^1.0, C=1, rho=22.40]

[981/1560] RF        repeat 4 fold 0  macro-F1=0.4462  P1=0.088 R1=0.857  (2s)  [ratio 1.0, orig^1.25, C=0, rho=48.73]

[982/1560] RF        repeat 4 fold 0  macro-F1=0.5898  P1=0.169 R1=0.619  (8s)  [ratio 1.0, orig^1.25, C=1, rho=48.73]

[983/1560] RF        repeat 4 fold 0  macro-F1=0.2412  P1=0.057 R1=1.000  (3s)  [ratio 1.0, orig^1.5, C=0, rho=106.02]

[984/1560] RF        repeat 4 fold 0  macro-F1=0.6682  P1=0.286 R1=0.571  (10s)  [ratio 1.0, orig^1.5, C=1, rho=106.02]

[985/1560] RF        repeat 4 fold 0  macro-F1=0.0429  P1=0.045 R1=1.000  (2s)  [ratio 1.0, orig^2.0, C=0, rho=501.76]

[986/1560] RF        repeat 4 fold 0  macro-F1=0.6134  P1=0.200 R1=0.524  (9s)  [ratio 1.0, orig^2.0, C=1, rho=501.76]

[987/1560] RF        repeat 4 fold 0  macro-F1=0.8006  P1=0.619 R1=0.619  (5s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[988/1560] RF        repeat 4 fold 0  macro-F1=0.7509  P1=0.391 R1=0.857  (5s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[989/1560] RF        repeat 4 fold 1  macro-F1=0.6507  P1=0.800 R1=0.200  (1s)  [ratio 0.0, orig^0.0, C=0, rho=0.05]

[990/1560] RF        repeat 4 fold 1  macro-F1=0.7507  P1=0.500 R1=0.550  (4s)  [ratio 0.0, orig^0.0, C=1, rho=0.05]

[991/1560] RF        repeat 4 fold 1  macro-F1=0.7055  P1=0.750 R1=0.300  (1s)  [ratio 0.0, orig^0.25, C=0, rho=0.10]

[992/1560] RF        repeat 4 fold 1  macro-F1=0.7782  P1=0.520 R1=0.650  (4s)  [ratio 0.0, orig^0.25, C=1, rho=0.10]

[993/1560] RF        repeat 4 fold 1  macro-F1=0.6687  P1=0.625 R1=0.250  (1s)  [ratio 0.0, orig^0.5, C=0, rho=0.22]

[994/1560] RF        repeat 4 fold 1  macro-F1=0.7151  P1=0.361 R1=0.650  (4s)  [ratio 0.0, orig^0.5, C=1, rho=0.22]

[995/1560] RF        repeat 4 fold 1  macro-F1=0.6687  P1=0.625 R1=0.250  (1s)  [ratio 0.0, orig^0.75, C=0, rho=0.47]

[996/1560] RF        repeat 4 fold 1  macro-F1=0.7192  P1=0.349 R1=0.750  (4s)  [ratio 0.0, orig^0.75, C=1, rho=0.47]

[997/1560] RF        repeat 4 fold 1  macro-F1=0.6758  P1=0.714 R1=0.250  (1s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[998/1560] RF        repeat 4 fold 1  macro-F1=0.7872  P1=0.519 R1=0.700  (4s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[999/1560] RF        repeat 4 fold 1  macro-F1=0.7412  P1=0.667 R1=0.400  (1s)  [ratio 0.0, orig^1.25, C=0, rho=2.15]

[1000/1560] RF        repeat 4 fold 1  macro-F1=0.7082  P1=0.400 R1=0.500  (4s)  [ratio 0.0, orig^1.25, C=1, rho=2.15]

[1001/1560] RF        repeat 4 fold 1  macro-F1=0.6709  P1=0.348 R1=0.400  (1s)  [ratio 0.0, orig^1.5, C=0, rho=4.62]

[1002/1560] RF        repeat 4 fold 1  macro-F1=0.6539  P1=0.250 R1=0.650  (4s)  [ratio 0.0, orig^1.5, C=1, rho=4.62]

[1003/1560] RF        repeat 4 fold 1  macro-F1=0.5886  P1=0.168 R1=0.800  (1s)  [ratio 0.0, orig^2.0, C=0, rho=21.33]

[1004/1560] RF        repeat 4 fold 1  macro-F1=0.6441  P1=0.417 R1=0.250  (4s)  [ratio 0.0, orig^2.0, C=1, rho=21.33]

[1005/1560] RF        repeat 4 fold 1  macro-F1=0.7774  P1=0.667 R1=0.500  (1s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1006/1560] RF        repeat 4 fold 1  macro-F1=0.7282  P1=0.366 R1=0.750  (5s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1007/1560] RF        repeat 4 fold 1  macro-F1=0.7806  P1=0.611 R1=0.550  (1s)  [ratio 0.5, orig^0.25, C=0, rho=1.07]

[1008/1560] RF        repeat 4 fold 1  macro-F1=0.6772  P1=0.278 R1=0.750  (6s)  [ratio 0.5, orig^0.25, C=1, rho=1.07]

[1009/1560] RF        repeat 4 fold 1  macro-F1=0.7256  P1=0.423 R1=0.550  (1s)  [ratio 0.5, orig^0.5, C=0, rho=2.31]

[1010/1560] RF        repeat 4 fold 1  macro-F1=0.6583  P1=0.250 R1=0.750  (8s)  [ratio 0.5, orig^0.5, C=1, rho=2.31]

[1011/1560] RF        repeat 4 fold 1  macro-F1=0.6657  P1=0.264 R1=0.700  (1s)  [ratio 0.5, orig^0.75, C=0, rho=4.96]

[1012/1560] RF        repeat 4 fold 1  macro-F1=0.6445  P1=0.244 R1=0.550  (9s)  [ratio 0.5, orig^0.75, C=1, rho=4.96]

[1013/1560] RF        repeat 4 fold 1  macro-F1=0.6023  P1=0.182 R1=0.800  (2s)  [ratio 0.5, orig^1.0, C=0, rho=10.67]

[1014/1560] RF        repeat 4 fold 1  macro-F1=0.6184  P1=0.250 R1=0.300  (10s)  [ratio 0.5, orig^1.0, C=1, rho=10.67]

[1015/1560] RF        repeat 4 fold 1  macro-F1=0.4902  P1=0.108 R1=0.950  (2s)  [ratio 0.5, orig^1.25, C=0, rho=22.92]

[1016/1560] RF        repeat 4 fold 1  macro-F1=0.6483  P1=0.353 R1=0.300  (10s)  [ratio 0.5, orig^1.25, C=1, rho=22.92]

[1017/1560] RF        repeat 4 fold 1  macro-F1=0.1703  P1=0.049 R1=1.000  (2s)  [ratio 0.5, orig^1.5, C=0, rho=49.27]

[1018/1560] RF        repeat 4 fold 1  macro-F1=0.6440  P1=0.667 R1=0.200  (10s)  [ratio 0.5, orig^1.5, C=1, rho=49.27]

[1019/1560] RF        repeat 4 fold 1  macro-F1=0.0410  P1=0.043 R1=1.000  (2s)  [ratio 0.5, orig^2.0, C=0, rho=227.56]

[1020/1560] RF        repeat 4 fold 1  macro-F1=0.5727  P1=0.214 R1=0.150  (11s)  [ratio 0.5, orig^2.0, C=1, rho=227.56]

[1021/1560] RF        repeat 4 fold 1  macro-F1=0.7774  P1=0.667 R1=0.500  (4s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1022/1560] RF        repeat 4 fold 1  macro-F1=0.7026  P1=0.319 R1=0.750  (11s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1023/1560] RF        repeat 4 fold 1  macro-F1=0.7608  P1=0.588 R1=0.500  (3s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1024/1560] RF        repeat 4 fold 1  macro-F1=0.7107  P1=0.333 R1=0.750  (13s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1025/1560] RF        repeat 4 fold 1  macro-F1=0.7365  P1=0.429 R1=0.600  (3s)  [ratio 1.0, orig^0.25, C=0, rho=2.15]

[1026/1560] RF        repeat 4 fold 1  macro-F1=0.6865  P1=0.298 R1=0.700  (12s)  [ratio 1.0, orig^0.25, C=1, rho=2.15]

[1027/1560] RF        repeat 4 fold 1  macro-F1=0.6418  P1=0.235 R1=0.600  (3s)  [ratio 1.0, orig^0.5, C=0, rho=4.62]

[1028/1560] RF        repeat 4 fold 1  macro-F1=0.6323  P1=0.224 R1=0.550  (12s)  [ratio 1.0, orig^0.5, C=1, rho=4.62]

[1029/1560] RF        repeat 4 fold 1  macro-F1=0.6363  P1=0.221 R1=0.750  (3s)  [ratio 1.0, orig^0.75, C=0, rho=9.93]

[1030/1560] RF        repeat 4 fold 1  macro-F1=0.6382  P1=0.280 R1=0.350  (11s)  [ratio 1.0, orig^0.75, C=1, rho=9.93]

[1031/1560] RF        repeat 4 fold 1  macro-F1=0.5449  P1=0.132 R1=0.800  (3s)  [ratio 1.0, orig^1.0, C=0, rho=21.33]

[1032/1560] RF        repeat 4 fold 1  macro-F1=0.6342  P1=0.269 R1=0.350  (10s)  [ratio 1.0, orig^1.0, C=1, rho=21.33]

[1033/1560] RF        repeat 4 fold 1  macro-F1=0.4025  P1=0.078 R1=0.950  (2s)  [ratio 1.0, orig^1.25, C=0, rho=45.85]

[1034/1560] RF        repeat 4 fold 1  macro-F1=0.6201  P1=0.294 R1=0.250  (9s)  [ratio 1.0, orig^1.25, C=1, rho=45.85]

[1035/1560] RF        repeat 4 fold 1  macro-F1=0.0410  P1=0.043 R1=1.000  (2s)  [ratio 1.0, orig^1.5, C=0, rho=98.53]

[1036/1560] RF        repeat 4 fold 1  macro-F1=0.5996  P1=0.429 R1=0.150  (9s)  [ratio 1.0, orig^1.5, C=1, rho=98.53]

[1037/1560] RF        repeat 4 fold 1  macro-F1=0.0410  P1=0.043 R1=1.000  (2s)  [ratio 1.0, orig^2.0, C=0, rho=455.11]

[1038/1560] RF        repeat 4 fold 1  macro-F1=0.5523  P1=0.200 R1=0.100  (8s)  [ratio 1.0, orig^2.0, C=1, rho=455.11]

[1039/1560] RF        repeat 4 fold 1  macro-F1=0.7608  P1=0.588 R1=0.500  (2s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1040/1560] RF        repeat 4 fold 1  macro-F1=0.7107  P1=0.333 R1=0.750  (8s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

## Macro-F1 by resampling ratio, weight setting and threshold tuning

In [4]:
results.pivot_table(index=["sampling_ratio", "weight_mode", "weight_power"],
                    columns=["classifier", "C"], values="macro_f1").round(4)

classifier                                   LR              RF          \
C                                             0       1       0       1
sampling_ratio weight_mode weight_power
0.0            orig        0.00          0.7307  0.7272  0.6273  0.6993
                           0.25          0.7397  0.7349  0.6754  0.7333
                           0.50          0.7337  0.7248  0.6793  0.7358
                           0.75          0.7203  0.7123  0.6702  0.7527
                           1.00          0.7001  0.7205  0.6873  0.7591
                           1.25          0.6789  0.7258  0.7079  0.7130
                           1.50          0.6588  0.7220  0.7069  0.6885
                           2.00          0.6003  0.7322  0.5567  0.6539
0.5            orig        0.00          0.7278  0.7281  0.7209  0.7339
                           0.25          0.7027  0.7322  0.7328  0.7188
                           0.50          0.6694  0.7382  0.7304  0.7186
                           0.75          0.5940  0.7346  0.6743  0.6946
                           1.00          0.5707  0.7219  0.5995  0.6762
                           1.25          0.5393  0.7211  0.4696  0.6677
                           1.50          0.5014  0.7065  0.2103  0.6657
                           2.00          0.3735  0.6838  0.0512  0.6411
               recalc      1.00          0.7068  0.7330  0.7303  0.7287
1.0            orig        0.00          0.7061  0.7274  0.7341  0.7252
                           0.25          0.6807  0.7225  0.7329  0.7189
                           0.50          0.6140  0.7221  0.7012  0.6962
                           0.75          0.5743  0.7254  0.6428  0.6746
                           1.00          0.5489  0.7210  0.5341  0.6585
                           1.25          0.5137  0.7191  0.3494  0.6563
                           1.50          0.4649  0.6973  0.1511  0.6489
                           2.00          0.3341  0.6516  0.0419  0.6407
               recalc      1.00          0.7061  0.7274  0.7341  0.7252

classifier                                  XGB
C                                             0       1
sampling_ratio weight_mode weight_power
0.0            orig        0.00          0.6580  0.7397
                           0.25          0.6987  0.7404
                           0.50          0.7140  0.7472
                           0.75          0.7177  0.7529
                           1.00          0.7404  0.7413
                           1.25          0.7554  0.7488
                           1.50          0.7470  0.7289
                           2.00          0.6626  0.6871
0.5            orig        0.00          0.7510  0.7489
                           0.25          0.7559  0.7429
                           0.50          0.7420  0.7298
                           0.75          0.7017  0.7187
                           1.00          0.6438  0.6917
                           1.25          0.5667  0.6779
                           1.50          0.3775  0.4758
                           2.00          0.0735  0.0735
               recalc      1.00          0.7551  0.7495
1.0            orig        0.00          0.7707  0.7598
                           0.25          0.7527  0.7684
                           0.50          0.7167  0.7398
                           0.75          0.6606  0.7212
                           1.00          0.6090  0.6969
                           1.25          0.5034  0.5802
                           1.50          0.2496  0.2952
                           2.00          0.0419  0.0419
               recalc      1.00          0.7707  0.7598

In [5]:
results.groupby(["sampling_ratio", "weight_mode", "weight_power"])[["rho_eff", "precision_1", "recall_1", "ppr_ratio"]].mean().round(3)

                                         rho_eff  precision_1  recall_1  \
sampling_ratio weight_mode weight_power
0.0            orig        0.00            0.046        0.588     0.372
                           0.25            0.099        0.576     0.429
                           0.50            0.214        0.565     0.455
                           0.75            0.462        0.526     0.481
                           1.00            1.000        0.521     0.500
                           1.25            2.162        0.478     0.526
                           1.50            4.676        0.436     0.543
                           2.00           21.867        0.314     0.612
0.5            orig        0.00            0.500        0.509     0.519
                           0.25            1.081        0.484     0.543
                           0.50            2.338        0.450     0.570
                           0.75            5.056        0.386     0.580
                           1.00           10.933        0.309     0.624
                           1.25           23.645        0.272     0.663
                           1.50           51.138        0.233     0.722
                           2.00          239.218        0.148     0.816
               recalc      1.00            1.000        0.487     0.547
1.0            orig        0.00            1.000        0.501     0.551
                           0.25            2.162        0.457     0.591
                           0.50            4.676        0.392     0.588
                           0.75           10.111        0.331     0.616
                           1.00           21.867        0.277     0.657
                           1.25           47.290        0.238     0.708
                           1.50          102.275        0.197     0.767
                           2.00          478.436        0.132     0.827
               recalc      1.00            1.000        0.501     0.551

                                         ppr_ratio
sampling_ratio weight_mode weight_power
0.0            orig        0.00              0.691
                           0.25              0.781
                           0.50              0.882
                           0.75              1.002
                           1.00              1.077
                           1.25              1.254
                           1.50              1.490
                           2.00              2.759
0.5            orig        0.00              1.090
                           0.25              1.233
                           0.50              1.499
                           0.75              2.074
                           1.00              2.855
                           1.25              4.269
                           1.50              8.068
                           2.00             13.696
               recalc      1.00              1.223
1.0            orig        0.00              1.209
                           0.25              1.472
                           0.50              1.934
                           0.75              2.558
                           1.00              3.595
                           1.25              6.170
                           1.50             10.457
                           2.00             14.380
               recalc      1.00              1.209