# CIC-IDS2017 - E2 weight sensitivity
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/MuhammadDevX/ML-Research-Dataset-Imbalance/blob/main/cicids2017/e2_weight_sensitivity/cicids2017_e2_weight_sensitivity.ipynb)

Answers reviewer R3 (one weighting configuration only) and tests the over-correction mechanism.

* Classifiers: LR, RF, XGB.
* Resampling ratio: [0.0, 0.5, 1.0] (0 = none; otherwise SMOTETomek to that minority:majority ratio).
* Positive-class weight = IR ** power, power in [0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0]
  (0 = none, 0.5 = sqrt-inverse, 1 = inverse frequency), plus weights recomputed after resampling.
* Each setting with and without threshold tuning (C).
* Hyperparameters are reused from `c0_none` (no resampling) and `c1_A_smotetomek` (with resampling).
  **Run those two notebooks first**; missing folds are tuned here, which is slower.
* Each row records `rho_eff`, the positive:negative loss mass the classifier sees.

**How to run on Colab**
1. Click the badge, then *Runtime > Run all*. Allow Google Drive access when asked.
2. Results are appended to Google Drive after every classifier/fold:
   `MyDrive/ML-Research-Dataset-Imbalance/cicids2017/e2_weight_sensitivity/results/cicids2017__e2_weight_sensitivity.csv`.
3. If the runtime disconnects, just *Run all* again: finished folds are skipped.
4. When it is complete, copy the CSV into the same path in the repository and commit it.

In [1]:
# ---- Setup: identical in every notebook. Do not edit. ----
import os, sys, subprocess
REPO_URL = "https://github.com/MuhammadDevX/ML-Research-Dataset-Imbalance.git"
BRANCH = "main"
try:
    import google.colab  # noqa: F401
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    REPO_ROOT = "/content/ML-Research-Dataset-Imbalance"
    if not os.path.isdir(REPO_ROOT):
        subprocess.run(["git", "clone", "--branch", BRANCH, REPO_URL, REPO_ROOT], check=True)
    else:
        subprocess.run(["git", "-C", REPO_ROOT, "pull", "--ff-only"], check=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r",
                    f"{REPO_ROOT}/requirements.txt"], check=True)
    from google.colab import drive
    drive.mount("/content/drive")
    # Results go to Google Drive so they survive a disconnect.
    os.environ.setdefault("RESULTS_ROOT", "/content/drive/MyDrive/ML-Research-Dataset-Imbalance")
else:
    REPO_ROOT = os.path.abspath(os.getcwd())
    while not os.path.isdir(os.path.join(REPO_ROOT, "common")):
        parent = os.path.dirname(REPO_ROOT)
        if parent == REPO_ROOT:
            raise RuntimeError("Open this notebook from inside the repository.")
        REPO_ROOT = parent

sys.path.insert(0, REPO_ROOT)
os.chdir(REPO_ROOT)
from common.env import check_environment
check_environment()

Environment OK: scikit-learn 1.9.1, imbalanced-learn 0.14.2, xgboost 3.4.1, lightgbm 4.7.0

In [2]:
DATASET = "cicids2017"
# Quick test run (2 folds, fewer classifiers and candidates): change the next line
# to  SMOKE = True . Its results go to a separate *__SMOKE.csv file and must never
# be used in the paper. Leave it as it is for the real run.
SMOKE = os.environ.get("SMOKE", "0") == "1"

In [3]:
from common.cv import run_e2
results = run_e2(DATASET, smoke=SMOKE)

Hyperparameters found: c0 70 folds, c1 70 folds. Missing ones are tuned here once with the same seed.
Writing to C:\Users\LENOVO\Desktop\Semester 6\Machine Learning\research\cicids2017\e2_weight_sensitivity\results\cicids2017__e2_weight_sensitivity.csv

[1301/1560] XGB       repeat 2 fold 1  macro-F1=0.9918  P1=0.992 R1=0.976  (55s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1302/1560] XGB       repeat 2 fold 1  macro-F1=0.9898  P1=0.978 R1=0.982  (167s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1303/1560] XGB       repeat 2 fold 1  macro-F1=0.9923  P1=0.988 R1=0.982  (57s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1304/1560] XGB       repeat 2 fold 1  macro-F1=0.9903  P1=0.980 R1=0.982  (168s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1305/1560] XGB       repeat 2 fold 1  macro-F1=0.9913  P1=0.984 R1=0.982  (57s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1306/1560] XGB       repeat 2 fold 1  macro-F1=0.9903  P1=0.980 R1=0.982  (168s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1307/1560] XGB       repeat 2 fold 1  macro-F1=0.9913  P1=0.984 R1=0.982  (56s)  [ratio 0.0, orig^0.75, C=0, rho=0.38]

[1308/1560] XGB       repeat 2 fold 1  macro-F1=0.9908  P1=0.982 R1=0.982  (165s)  [ratio 0.0, orig^0.75, C=1, rho=0.38]

[1309/1560] XGB       repeat 2 fold 1  macro-F1=0.9903  P1=0.980 R1=0.982  (56s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1310/1560] XGB       repeat 2 fold 1  macro-F1=0.9903  P1=0.980 R1=0.982  (155s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1311/1560] XGB       repeat 2 fold 1  macro-F1=0.9903  P1=0.980 R1=0.982  (42s)  [ratio 0.0, orig^1.25, C=0, rho=2.65]

[1312/1560] XGB       repeat 2 fold 1  macro-F1=0.9918  P1=0.986 R1=0.982  (145s)  [ratio 0.0, orig^1.25, C=1, rho=2.65]

[1313/1560] XGB       repeat 2 fold 1  macro-F1=0.9888  P1=0.974 R1=0.982  (39s)  [ratio 0.0, orig^1.5, C=0, rho=7.00]

[1314/1560] XGB       repeat 2 fold 1  macro-F1=0.9888  P1=0.974 R1=0.982  (136s)  [ratio 0.0, orig^1.5, C=1, rho=7.00]

[1315/1560] XGB       repeat 2 fold 1  macro-F1=0.9777  P1=0.930 R1=0.984  (40s)  [ratio 0.0, orig^2.0, C=0, rho=49.00]

[1316/1560] XGB       repeat 2 fold 1  macro-F1=0.9923  P1=0.988 R1=0.982  (129s)  [ratio 0.0, orig^2.0, C=1, rho=49.00]

[1317/1560] XGB       repeat 2 fold 1  macro-F1=0.9918  P1=0.988 R1=0.980  (174s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1318/1560] XGB       repeat 2 fold 1  macro-F1=0.9888  P1=0.974 R1=0.982  (448s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1319/1560] XGB       repeat 2 fold 1  macro-F1=0.9918  P1=0.986 R1=0.982  (175s)  [ratio 0.5, orig^0.25, C=0, rho=1.32]

[1320/1560] XGB       repeat 2 fold 1  macro-F1=0.9913  P1=0.986 R1=0.980  (446s)  [ratio 0.5, orig^0.25, C=1, rho=1.32]

[1321/1560] XGB       repeat 2 fold 1  macro-F1=0.9918  P1=0.986 R1=0.982  (174s)  [ratio 0.5, orig^0.5, C=0, rho=3.49]

[1322/1560] XGB       repeat 2 fold 1  macro-F1=0.9918  P1=0.986 R1=0.982  (435s)  [ratio 0.5, orig^0.5, C=1, rho=3.49]

[1323/1560] XGB       repeat 2 fold 1  macro-F1=0.9903  P1=0.980 R1=0.982  (173s)  [ratio 0.5, orig^0.75, C=0, rho=9.24]

[1324/1560] XGB       repeat 2 fold 1  macro-F1=0.9918  P1=0.988 R1=0.980  (430s)  [ratio 0.5, orig^0.75, C=1, rho=9.24]

[1325/1560] XGB       repeat 2 fold 1  macro-F1=0.9854  P1=0.959 R1=0.984  (166s)  [ratio 0.5, orig^1.0, C=0, rho=24.46]

[1326/1560] XGB       repeat 2 fold 1  macro-F1=0.9903  P1=0.980 R1=0.982  (324s)  [ratio 0.5, orig^1.0, C=1, rho=24.46]

[1327/1560] XGB       repeat 2 fold 1  macro-F1=0.9758  P1=0.921 R1=0.986  (68s)  [ratio 0.5, orig^1.25, C=0, rho=64.71]

[1328/1560] XGB       repeat 2 fold 1  macro-F1=0.9903  P1=0.982 R1=0.980  (327s)  [ratio 0.5, orig^1.25, C=1, rho=64.71]

[1329/1560] XGB       repeat 2 fold 1  macro-F1=0.9440  P1=0.808 R1=0.992  (61s)  [ratio 0.5, orig^1.5, C=0, rho=171.22]

[1330/1560] XGB       repeat 2 fold 1  macro-F1=0.9908  P1=0.984 R1=0.980  (308s)  [ratio 0.5, orig^1.5, C=1, rho=171.22]

[1331/1560] XGB       repeat 2 fold 1  macro-F1=0.7005  P1=0.273 R1=0.996  (59s)  [ratio 0.5, orig^2.0, C=0, rho=1198.54]

[1332/1560] XGB       repeat 2 fold 1  macro-F1=0.9556  P1=0.856 R1=0.978  (298s)  [ratio 0.5, orig^2.0, C=1, rho=1198.54]

[1333/1560] XGB       repeat 2 fold 1  macro-F1=0.9918  P1=0.986 R1=0.982  (65s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1334/1560] XGB       repeat 2 fold 1  macro-F1=0.9908  P1=0.982 R1=0.982  (379s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1335/1560] XGB       repeat 2 fold 1  macro-F1=0.9918  P1=0.986 R1=0.982  (294s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1336/1560] XGB       repeat 2 fold 1  macro-F1=0.9908  P1=0.982 R1=0.982  (910s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1337/1560] XGB       repeat 2 fold 1  macro-F1=0.9918  P1=0.986 R1=0.982  (304s)  [ratio 1.0, orig^0.25, C=0, rho=2.65]

[1338/1560] XGB       repeat 2 fold 1  macro-F1=0.9909  P1=0.976 R1=0.988  (925s)  [ratio 1.0, orig^0.25, C=1, rho=2.65]

[1339/1560] XGB       repeat 2 fold 1  macro-F1=0.9913  P1=0.984 R1=0.982  (303s)  [ratio 1.0, orig^0.5, C=0, rho=7.00]

[1340/1560] XGB       repeat 2 fold 1  macro-F1=0.9918  P1=0.988 R1=0.980  (918s)  [ratio 1.0, orig^0.5, C=1, rho=7.00]

[1341/1560] XGB       repeat 2 fold 1  macro-F1=0.9883  P1=0.972 R1=0.982  (335s)  [ratio 1.0, orig^0.75, C=0, rho=18.52]

[1342/1560] XGB       repeat 2 fold 1  macro-F1=0.9903  P1=0.982 R1=0.980  (946s)  [ratio 1.0, orig^0.75, C=1, rho=18.52]

[1343/1560] XGB       repeat 2 fold 1  macro-F1=0.9824  P1=0.950 R1=0.982  (127s)  [ratio 1.0, orig^1.0, C=0, rho=49.00]

[1344/1560] XGB       repeat 2 fold 1  macro-F1=0.9913  P1=0.988 R1=0.978  (868s)  [ratio 1.0, orig^1.0, C=1, rho=49.00]

[1345/1560] XGB       repeat 2 fold 1  macro-F1=0.9686  P1=0.890 R1=0.992  (118s)  [ratio 1.0, orig^1.25, C=0, rho=129.64]

[1346/1560] XGB       repeat 2 fold 1  macro-F1=0.9893  P1=0.978 R1=0.980  (697s)  [ratio 1.0, orig^1.25, C=1, rho=129.64]

[1347/1560] XGB       repeat 2 fold 1  macro-F1=0.9203  P1=0.735 R1=0.992  (132s)  [ratio 1.0, orig^1.5, C=0, rho=343.00]

[1348/1560] XGB       repeat 2 fold 1  macro-F1=0.9903  P1=0.982 R1=0.980  (665s)  [ratio 1.0, orig^1.5, C=1, rho=343.00]

[1349/1560] XGB       repeat 2 fold 1  macro-F1=0.6233  P1=0.175 R1=0.998  (114s)  [ratio 1.0, orig^2.0, C=0, rho=2401.00]

[1350/1560] XGB       repeat 2 fold 1  macro-F1=0.8600  P1=0.579 R1=0.980  (602s)  [ratio 1.0, orig^2.0, C=1, rho=2401.00]

[1351/1560] XGB       repeat 2 fold 1  macro-F1=0.9918  P1=0.986 R1=0.982  (116s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1352/1560] XGB       repeat 2 fold 1  macro-F1=0.9908  P1=0.982 R1=0.982  (607s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1353/1560] XGB       repeat 3 fold 0  macro-F1=0.9855  P1=0.984 R1=0.960  (74s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1354/1560] XGB       repeat 3 fold 0  macro-F1=0.9861  P1=0.982 R1=0.964  (241s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1355/1560] XGB       repeat 3 fold 0  macro-F1=0.9867  P1=0.980 R1=0.968  (76s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1356/1560] XGB       repeat 3 fold 0  macro-F1=0.9866  P1=0.982 R1=0.966  (251s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1357/1560] XGB       repeat 3 fold 0  macro-F1=0.9878  P1=0.976 R1=0.976  (74s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1358/1560] XGB       repeat 3 fold 0  macro-F1=0.9877  P1=0.978 R1=0.974  (246s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1359/1560] XGB       repeat 3 fold 0  macro-F1=0.9908  P1=0.980 R1=0.984  (79s)  [ratio 0.0, orig^0.75, C=0, rho=0.38]

[1360/1560] XGB       repeat 3 fold 0  macro-F1=0.9908  P1=0.980 R1=0.984  (252s)  [ratio 0.0, orig^0.75, C=1, rho=0.38]

[1361/1560] XGB       repeat 3 fold 0  macro-F1=0.9898  P1=0.976 R1=0.984  (75s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1362/1560] XGB       repeat 3 fold 0  macro-F1=0.9903  P1=0.982 R1=0.980  (238s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1363/1560] XGB       repeat 3 fold 0  macro-F1=0.9894  P1=0.971 R1=0.988  (75s)  [ratio 0.0, orig^1.25, C=0, rho=2.65]

[1364/1560] XGB       repeat 3 fold 0  macro-F1=0.9887  P1=0.984 R1=0.972  (225s)  [ratio 0.0, orig^1.25, C=1, rho=2.65]

[1365/1560] XGB       repeat 3 fold 0  macro-F1=0.9845  P1=0.948 R1=0.992  (71s)  [ratio 0.0, orig^1.5, C=0, rho=7.00]

[1366/1560] XGB       repeat 3 fold 0  macro-F1=0.9894  P1=0.972 R1=0.986  (209s)  [ratio 0.0, orig^1.5, C=1, rho=7.00]

[1367/1560] XGB       repeat 3 fold 0  macro-F1=0.9156  P1=0.720 R1=0.994  (66s)  [ratio 0.0, orig^2.0, C=0, rho=49.00]

[1368/1560] XGB       repeat 3 fold 0  macro-F1=0.9842  P1=0.970 R1=0.968  (216s)  [ratio 0.0, orig^2.0, C=1, rho=49.00]

[1369/1560] XGB       repeat 3 fold 0  macro-F1=0.9893  P1=0.982 R1=0.976  (321s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1370/1560] XGB       repeat 3 fold 0  macro-F1=0.9893  P1=0.982 R1=0.976  (843s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1371/1560] XGB       repeat 3 fold 0  macro-F1=0.9908  P1=0.982 R1=0.982  (316s)  [ratio 0.5, orig^0.25, C=0, rho=1.32]

[1372/1560] XGB       repeat 3 fold 0  macro-F1=0.9908  P1=0.980 R1=0.984  (845s)  [ratio 0.5, orig^0.25, C=1, rho=1.32]

[1373/1560] XGB       repeat 3 fold 0  macro-F1=0.9903  P1=0.978 R1=0.984  (312s)  [ratio 0.5, orig^0.5, C=0, rho=3.50]

[1374/1560] XGB       repeat 3 fold 0  macro-F1=0.9887  P1=0.984 R1=0.972  (826s)  [ratio 0.5, orig^0.5, C=1, rho=3.50]

[1375/1560] XGB       repeat 3 fold 0  macro-F1=0.9894  P1=0.972 R1=0.986  (317s)  [ratio 0.5, orig^0.75, C=0, rho=9.26]

[1376/1560] XGB       repeat 3 fold 0  macro-F1=0.9898  P1=0.984 R1=0.976  (815s)  [ratio 0.5, orig^0.75, C=1, rho=9.26]

[1377/1560] XGB       repeat 3 fold 0  macro-F1=0.9860  P1=0.954 R1=0.992  (310s)  [ratio 0.5, orig^1.0, C=0, rho=24.50]

[1378/1560] XGB       repeat 3 fold 0  macro-F1=0.9893  P1=0.976 R1=0.982  (605s)  [ratio 0.5, orig^1.0, C=1, rho=24.50]

[1379/1560] XGB       repeat 3 fold 0  macro-F1=0.9686  P1=0.890 R1=0.992  (126s)  [ratio 0.5, orig^1.25, C=0, rho=64.82]

[1380/1560] XGB       repeat 3 fold 0  macro-F1=0.9893  P1=0.980 R1=0.978  (597s)  [ratio 0.5, orig^1.25, C=1, rho=64.82]

[1381/1560] XGB       repeat 3 fold 0  macro-F1=0.9282  P1=0.758 R1=0.992  (136s)  [ratio 0.5, orig^1.5, C=0, rho=171.49]

[1382/1560] XGB       repeat 3 fold 0  macro-F1=0.9836  P1=0.970 R1=0.966  (569s)  [ratio 0.5, orig^1.5, C=1, rho=171.49]

[1383/1560] XGB       repeat 3 fold 0  macro-F1=0.6968  P1=0.268 R1=0.996  (118s)  [ratio 0.5, orig^2.0, C=0, rho=1200.40]

[1384/1560] XGB       repeat 3 fold 0  macro-F1=0.9344  P1=0.786 R1=0.978  (535s)  [ratio 0.5, orig^2.0, C=1, rho=1200.40]

[1385/1560] XGB       repeat 3 fold 0  macro-F1=0.9898  P1=0.984 R1=0.976  (133s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1386/1560] XGB       repeat 3 fold 0  macro-F1=0.9898  P1=0.984 R1=0.976  (541s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1387/1560] XGB       repeat 3 fold 0  macro-F1=0.9898  P1=0.982 R1=0.978  (393s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1388/1560] XGB       repeat 3 fold 0  macro-F1=0.9903  P1=0.980 R1=0.982  (710s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1389/1560] XGB       repeat 3 fold 0  macro-F1=0.9908  P1=0.982 R1=0.982  (403s)  [ratio 1.0, orig^0.25, C=0, rho=2.65]

[1390/1560] XGB       repeat 3 fold 0  macro-F1=0.9903  P1=0.982 R1=0.980  (687s)  [ratio 1.0, orig^0.25, C=1, rho=2.65]

[1391/1560] XGB       repeat 3 fold 0  macro-F1=0.9893  P1=0.974 R1=0.984  (402s)  [ratio 1.0, orig^0.5, C=0, rho=7.00]

[1392/1560] XGB       repeat 3 fold 0  macro-F1=0.9903  P1=0.984 R1=0.978  (661s)  [ratio 1.0, orig^0.5, C=1, rho=7.00]

[1393/1560] XGB       repeat 3 fold 0  macro-F1=0.9879  P1=0.967 R1=0.986  (322s)  [ratio 1.0, orig^0.75, C=0, rho=18.52]

[1394/1560] XGB       repeat 3 fold 0  macro-F1=0.9898  P1=0.976 R1=0.984  (590s)  [ratio 1.0, orig^0.75, C=1, rho=18.52]

[1395/1560] XGB       repeat 3 fold 0  macro-F1=0.9768  P1=0.923 R1=0.988  (83s)  [ratio 1.0, orig^1.0, C=0, rho=49.00]

[1396/1560] XGB       repeat 3 fold 0  macro-F1=0.9893  P1=0.976 R1=0.982  (451s)  [ratio 1.0, orig^1.0, C=1, rho=49.00]

[1397/1560] XGB       repeat 3 fold 0  macro-F1=0.9444  P1=0.809 R1=0.992  (48s)  [ratio 1.0, orig^1.25, C=0, rho=129.64]

[1398/1560] XGB       repeat 3 fold 0  macro-F1=0.9853  P1=0.964 R1=0.978  (322s)  [ratio 1.0, orig^1.25, C=1, rho=129.64]

[1399/1560] XGB       repeat 3 fold 0  macro-F1=0.8983  P1=0.672 R1=0.994  (38s)  [ratio 1.0, orig^1.5, C=0, rho=343.00]

[1400/1560] XGB       repeat 3 fold 0  macro-F1=0.9857  P1=0.976 R1=0.968  (332s)  [ratio 1.0, orig^1.5, C=1, rho=343.00]

[1401/1560] XGB       repeat 3 fold 0  macro-F1=0.6224  P1=0.174 R1=0.996  (43s)  [ratio 1.0, orig^2.0, C=0, rho=2401.00]

[1402/1560] XGB       repeat 3 fold 0  macro-F1=0.8896  P1=0.651 R1=0.988  (322s)  [ratio 1.0, orig^2.0, C=1, rho=2401.00]

[1403/1560] XGB       repeat 3 fold 0  macro-F1=0.9898  P1=0.982 R1=0.978  (64s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1404/1560] XGB       repeat 3 fold 0  macro-F1=0.9903  P1=0.980 R1=0.982  (305s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1405/1560] XGB       repeat 3 fold 1  macro-F1=0.9855  P1=0.986 R1=0.958  (25s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1406/1560] XGB       repeat 3 fold 1  macro-F1=0.9867  P1=0.980 R1=0.968  (65s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1407/1560] XGB       repeat 3 fold 1  macro-F1=0.9829  P1=0.983 R1=0.950  (28s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1408/1560] XGB       repeat 3 fold 1  macro-F1=0.9846  P1=0.978 R1=0.962  (66s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1409/1560] XGB       repeat 3 fold 1  macro-F1=0.9860  P1=0.986 R1=0.960  (28s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1410/1560] XGB       repeat 3 fold 1  macro-F1=0.9856  P1=0.978 R1=0.966  (68s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1411/1560] XGB       repeat 3 fold 1  macro-F1=0.9866  P1=0.984 R1=0.964  (26s)  [ratio 0.0, orig^0.75, C=0, rho=0.38]

[1412/1560] XGB       repeat 3 fold 1  macro-F1=0.9861  P1=0.982 R1=0.964  (66s)  [ratio 0.0, orig^0.75, C=1, rho=0.38]

[1413/1560] XGB       repeat 3 fold 1  macro-F1=0.9887  P1=0.982 R1=0.974  (26s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1414/1560] XGB       repeat 3 fold 1  macro-F1=0.9887  P1=0.982 R1=0.974  (51s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1415/1560] XGB       repeat 3 fold 1  macro-F1=0.9882  P1=0.980 R1=0.974  (20s)  [ratio 0.0, orig^1.25, C=0, rho=2.65]

[1416/1560] XGB       repeat 3 fold 1  macro-F1=0.9887  P1=0.984 R1=0.972  (49s)  [ratio 0.0, orig^1.25, C=1, rho=2.65]

[1417/1560] XGB       repeat 3 fold 1  macro-F1=0.9872  P1=0.976 R1=0.974  (18s)  [ratio 0.0, orig^1.5, C=0, rho=7.00]

[1418/1560] XGB       repeat 3 fold 1  macro-F1=0.9887  P1=0.982 R1=0.974  (46s)  [ratio 0.0, orig^1.5, C=1, rho=7.00]

[1419/1560] XGB       repeat 3 fold 1  macro-F1=0.9653  P1=0.894 R1=0.974  (14s)  [ratio 0.0, orig^2.0, C=0, rho=49.00]

[1420/1560] XGB       repeat 3 fold 1  macro-F1=0.9867  P1=0.980 R1=0.968  (35s)  [ratio 0.0, orig^2.0, C=1, rho=49.00]

[1421/1560] XGB       repeat 3 fold 1  macro-F1=0.9850  P1=0.982 R1=0.960  (106s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1422/1560] XGB       repeat 3 fold 1  macro-F1=0.9845  P1=0.980 R1=0.960  (292s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1423/1560] XGB       repeat 3 fold 1  macro-F1=0.9855  P1=0.984 R1=0.960  (107s)  [ratio 0.5, orig^0.25, C=0, rho=1.32]

[1424/1560] XGB       repeat 3 fold 1  macro-F1=0.9855  P1=0.984 R1=0.960  (306s)  [ratio 0.5, orig^0.25, C=1, rho=1.32]

[1425/1560] XGB       repeat 3 fold 1  macro-F1=0.9887  P1=0.984 R1=0.972  (106s)  [ratio 0.5, orig^0.5, C=0, rho=3.49]

[1426/1560] XGB       repeat 3 fold 1  macro-F1=0.9876  P1=0.990 R1=0.962  (297s)  [ratio 0.5, orig^0.5, C=1, rho=3.49]

[1427/1560] XGB       repeat 3 fold 1  macro-F1=0.9862  P1=0.974 R1=0.972  (108s)  [ratio 0.5, orig^0.75, C=0, rho=9.24]

[1428/1560] XGB       repeat 3 fold 1  macro-F1=0.9862  P1=0.974 R1=0.972  (289s)  [ratio 0.5, orig^0.75, C=1, rho=9.24]

[1429/1560] XGB       repeat 3 fold 1  macro-F1=0.9863  P1=0.965 R1=0.982  (108s)  [ratio 0.5, orig^1.0, C=0, rho=24.45]

[1430/1560] XGB       repeat 3 fold 1  macro-F1=0.9862  P1=0.974 R1=0.972  (220s)  [ratio 0.5, orig^1.0, C=1, rho=24.45]

[1431/1560] XGB       repeat 3 fold 1  macro-F1=0.9771  P1=0.933 R1=0.978  (24s)  [ratio 0.5, orig^1.25, C=0, rho=64.69]

[1432/1560] XGB       repeat 3 fold 1  macro-F1=0.9851  P1=0.978 R1=0.964  (226s)  [ratio 0.5, orig^1.25, C=1, rho=64.69]

[1433/1560] XGB       repeat 3 fold 1  macro-F1=0.9263  P1=0.760 R1=0.980  (22s)  [ratio 0.5, orig^1.5, C=0, rho=171.15]

[1434/1560] XGB       repeat 3 fold 1  macro-F1=0.9810  P1=0.970 R1=0.956  (223s)  [ratio 0.5, orig^1.5, C=1, rho=171.15]

[1435/1560] XGB       repeat 3 fold 1  macro-F1=0.7033  P1=0.278 R1=0.990  (41s)  [ratio 0.5, orig^2.0, C=0, rho=1198.04]

[1436/1560] XGB       repeat 3 fold 1  macro-F1=0.9087  P1=0.706 R1=0.982  (228s)  [ratio 0.5, orig^2.0, C=1, rho=1198.04]

[1437/1560] XGB       repeat 3 fold 1  macro-F1=0.9856  P1=0.982 R1=0.962  (52s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1438/1560] XGB       repeat 3 fold 1  macro-F1=0.9850  P1=0.982 R1=0.960  (244s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1439/1560] XGB       repeat 3 fold 1  macro-F1=0.9866  P1=0.984 R1=0.964  (193s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1440/1560] XGB       repeat 3 fold 1  macro-F1=0.9866  P1=0.984 R1=0.964  (521s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1441/1560] XGB       repeat 3 fold 1  macro-F1=0.9882  P1=0.984 R1=0.970  (194s)  [ratio 1.0, orig^0.25, C=0, rho=2.65]

[1442/1560] XGB       repeat 3 fold 1  macro-F1=0.9872  P1=0.978 R1=0.972  (513s)  [ratio 1.0, orig^0.25, C=1, rho=2.65]

[1443/1560] XGB       repeat 3 fold 1  macro-F1=0.9857  P1=0.974 R1=0.970  (186s)  [ratio 1.0, orig^0.5, C=0, rho=7.00]

[1444/1560] XGB       repeat 3 fold 1  macro-F1=0.9866  P1=0.982 R1=0.966  (499s)  [ratio 1.0, orig^0.5, C=1, rho=7.00]

[1445/1560] XGB       repeat 3 fold 1  macro-F1=0.9828  P1=0.960 R1=0.972  (187s)  [ratio 1.0, orig^0.75, C=0, rho=18.52]

[1446/1560] XGB       repeat 3 fold 1  macro-F1=0.9862  P1=0.974 R1=0.972  (488s)  [ratio 1.0, orig^0.75, C=1, rho=18.52]

[1447/1560] XGB       repeat 3 fold 1  macro-F1=0.9736  P1=0.926 R1=0.972  (198s)  [ratio 1.0, orig^1.0, C=0, rho=49.00]

[1448/1560] XGB       repeat 3 fold 1  macro-F1=0.9817  P1=0.962 R1=0.966  (368s)  [ratio 1.0, orig^1.0, C=1, rho=49.00]

[1449/1560] XGB       repeat 3 fold 1  macro-F1=0.9503  P1=0.841 R1=0.974  (58s)  [ratio 1.0, orig^1.25, C=0, rho=129.64]

[1450/1560] XGB       repeat 3 fold 1  macro-F1=0.9842  P1=0.968 R1=0.970  (354s)  [ratio 1.0, orig^1.25, C=1, rho=129.64]

[1451/1560] XGB       repeat 3 fold 1  macro-F1=0.9031  P1=0.691 R1=0.982  (58s)  [ratio 1.0, orig^1.5, C=0, rho=343.00]

[1452/1560] XGB       repeat 3 fold 1  macro-F1=0.9871  P1=0.986 R1=0.964  (338s)  [ratio 1.0, orig^1.5, C=1, rho=343.00]

[1453/1560] XGB       repeat 3 fold 1  macro-F1=0.6296  P1=0.182 R1=0.994  (58s)  [ratio 1.0, orig^2.0, C=0, rho=2401.00]

[1454/1560] XGB       repeat 3 fold 1  macro-F1=0.8425  P1=0.537 R1=0.982  (298s)  [ratio 1.0, orig^2.0, C=1, rho=2401.00]

[1455/1560] XGB       repeat 3 fold 1  macro-F1=0.9866  P1=0.984 R1=0.964  (76s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1456/1560] XGB       repeat 3 fold 1  macro-F1=0.9866  P1=0.984 R1=0.964  (284s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1457/1560] XGB       repeat 4 fold 0  macro-F1=0.9860  P1=0.988 R1=0.958  (33s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1458/1560] XGB       repeat 4 fold 0  macro-F1=0.9855  P1=0.986 R1=0.958  (69s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1459/1560] XGB       repeat 4 fold 0  macro-F1=0.9876  P1=0.986 R1=0.966  (35s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1460/1560] XGB       repeat 4 fold 0  macro-F1=0.9892  P1=0.984 R1=0.974  (70s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1461/1560] XGB       repeat 4 fold 0  macro-F1=0.9887  P1=0.986 R1=0.970  (33s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1462/1560] XGB       repeat 4 fold 0  macro-F1=0.9898  P1=0.984 R1=0.976  (71s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1463/1560] XGB       repeat 4 fold 0  macro-F1=0.9887  P1=0.982 R1=0.974  (33s)  [ratio 0.0, orig^0.75, C=0, rho=0.38]

[1464/1560] XGB       repeat 4 fold 0  macro-F1=0.9883  P1=0.976 R1=0.978  (69s)  [ratio 0.0, orig^0.75, C=1, rho=0.38]

[1465/1560] XGB       repeat 4 fold 0  macro-F1=0.9888  P1=0.980 R1=0.976  (32s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1466/1560] XGB       repeat 4 fold 0  macro-F1=0.9888  P1=0.976 R1=0.980  (50s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1467/1560] XGB       repeat 4 fold 0  macro-F1=0.9878  P1=0.970 R1=0.982  (17s)  [ratio 0.0, orig^1.25, C=0, rho=2.65]

[1468/1560] XGB       repeat 4 fold 0  macro-F1=0.9878  P1=0.970 R1=0.982  (45s)  [ratio 0.0, orig^1.25, C=1, rho=2.65]

[1469/1560] XGB       repeat 4 fold 0  macro-F1=0.9854  P1=0.961 R1=0.982  (15s)  [ratio 0.0, orig^1.5, C=0, rho=7.00]

[1470/1560] XGB       repeat 4 fold 0  macro-F1=0.9883  P1=0.976 R1=0.978  (44s)  [ratio 0.0, orig^1.5, C=1, rho=7.00]

[1471/1560] XGB       repeat 4 fold 0  macro-F1=0.9196  P1=0.735 R1=0.988  (13s)  [ratio 0.0, orig^2.0, C=0, rho=49.00]

[1472/1560] XGB       repeat 4 fold 0  macro-F1=0.9897  P1=0.988 R1=0.972  (38s)  [ratio 0.0, orig^2.0, C=1, rho=49.00]

[1473/1560] XGB       repeat 4 fold 0  macro-F1=0.9862  P1=0.978 R1=0.968  (64s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1474/1560] XGB       repeat 4 fold 0  macro-F1=0.9868  P1=0.970 R1=0.978  (273s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1475/1560] XGB       repeat 4 fold 0  macro-F1=0.9877  P1=0.978 R1=0.974  (78s)  [ratio 0.5, orig^0.25, C=0, rho=1.32]

[1476/1560] XGB       repeat 4 fold 0  macro-F1=0.9883  P1=0.974 R1=0.980  (276s)  [ratio 0.5, orig^0.25, C=1, rho=1.32]

[1477/1560] XGB       repeat 4 fold 0  macro-F1=0.9893  P1=0.974 R1=0.984  (81s)  [ratio 0.5, orig^0.5, C=0, rho=3.49]

[1478/1560] XGB       repeat 4 fold 0  macro-F1=0.9874  P1=0.967 R1=0.984  (281s)  [ratio 0.5, orig^0.5, C=1, rho=3.49]

[1479/1560] XGB       repeat 4 fold 0  macro-F1=0.9854  P1=0.959 R1=0.984  (88s)  [ratio 0.5, orig^0.75, C=0, rho=9.25]

[1480/1560] XGB       repeat 4 fold 0  macro-F1=0.9878  P1=0.974 R1=0.978  (290s)  [ratio 0.5, orig^0.75, C=1, rho=9.25]

[1481/1560] XGB       repeat 4 fold 0  macro-F1=0.9809  P1=0.946 R1=0.980  (97s)  [ratio 0.5, orig^1.0, C=0, rho=24.46]

[1482/1560] XGB       repeat 4 fold 0  macro-F1=0.9863  P1=0.970 R1=0.976  (246s)  [ratio 0.5, orig^1.0, C=1, rho=24.46]

[1483/1560] XGB       repeat 4 fold 0  macro-F1=0.9776  P1=0.933 R1=0.980  (42s)  [ratio 0.5, orig^1.25, C=0, rho=64.73]

[1484/1560] XGB       repeat 4 fold 0  macro-F1=0.9842  P1=0.968 R1=0.970  (239s)  [ratio 0.5, orig^1.25, C=1, rho=64.73]

[1485/1560] XGB       repeat 4 fold 0  macro-F1=0.9135  P1=0.719 R1=0.984  (39s)  [ratio 0.5, orig^1.5, C=0, rho=171.25]

[1486/1560] XGB       repeat 4 fold 0  macro-F1=0.9703  P1=0.915 R1=0.970  (235s)  [ratio 0.5, orig^1.5, C=1, rho=171.25]

[1487/1560] XGB       repeat 4 fold 0  macro-F1=0.6992  P1=0.271 R1=0.994  (42s)  [ratio 0.5, orig^2.0, C=0, rho=1198.73]

[1488/1560] XGB       repeat 4 fold 0  macro-F1=0.9151  P1=0.723 R1=0.986  (238s)  [ratio 0.5, orig^2.0, C=1, rho=1198.73]

[1489/1560] XGB       repeat 4 fold 0  macro-F1=0.9862  P1=0.976 R1=0.970  (51s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1490/1560] XGB       repeat 4 fold 0  macro-F1=0.9850  P1=0.982 R1=0.960  (247s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1491/1560] XGB       repeat 4 fold 0  macro-F1=0.9866  P1=0.982 R1=0.966  (199s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1492/1560] XGB       repeat 4 fold 0  macro-F1=0.9851  P1=0.976 R1=0.966  (509s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1493/1560] XGB       repeat 4 fold 0  macro-F1=0.9857  P1=0.974 R1=0.970  (198s)  [ratio 1.0, orig^0.25, C=0, rho=2.65]

[1494/1560] XGB       repeat 4 fold 0  macro-F1=0.9853  P1=0.966 R1=0.976  (504s)  [ratio 1.0, orig^0.25, C=1, rho=2.65]

[1495/1560] XGB       repeat 4 fold 0  macro-F1=0.9863  P1=0.970 R1=0.976  (195s)  [ratio 1.0, orig^0.5, C=0, rho=7.00]

[1496/1560] XGB       repeat 4 fold 0  macro-F1=0.9877  P1=0.978 R1=0.974  (505s)  [ratio 1.0, orig^0.5, C=1, rho=7.00]

[1497/1560] XGB       repeat 4 fold 0  macro-F1=0.9863  P1=0.968 R1=0.978  (192s)  [ratio 1.0, orig^0.75, C=0, rho=18.52]

[1498/1560] XGB       repeat 4 fold 0  macro-F1=0.9873  P1=0.974 R1=0.976  (487s)  [ratio 1.0, orig^0.75, C=1, rho=18.52]

[1499/1560] XGB       repeat 4 fold 0  macro-F1=0.9795  P1=0.940 R1=0.980  (192s)  [ratio 1.0, orig^1.0, C=0, rho=49.00]

[1500/1560] XGB       repeat 4 fold 0  macro-F1=0.9846  P1=0.978 R1=0.962  (357s)  [ratio 1.0, orig^1.0, C=1, rho=49.00]

[1501/1560] XGB       repeat 4 fold 0  macro-F1=0.9688  P1=0.898 R1=0.984  (55s)  [ratio 1.0, orig^1.25, C=0, rho=129.64]

[1502/1560] XGB       repeat 4 fold 0  macro-F1=0.9835  P1=0.976 R1=0.960  (353s)  [ratio 1.0, orig^1.25, C=1, rho=129.64]

[1503/1560] XGB       repeat 4 fold 0  macro-F1=0.9081  P1=0.702 R1=0.988  (55s)  [ratio 1.0, orig^1.5, C=0, rho=343.00]

[1504/1560] XGB       repeat 4 fold 0  macro-F1=0.9883  P1=0.974 R1=0.980  (345s)  [ratio 1.0, orig^1.5, C=1, rho=343.00]

[1505/1560] XGB       repeat 4 fold 0  macro-F1=0.6321  P1=0.184 R1=0.994  (57s)  [ratio 1.0, orig^2.0, C=0, rho=2401.00]

[1506/1560] XGB       repeat 4 fold 0  macro-F1=0.8511  P1=0.555 R1=0.986  (305s)  [ratio 1.0, orig^2.0, C=1, rho=2401.00]

[1507/1560] XGB       repeat 4 fold 0  macro-F1=0.9866  P1=0.982 R1=0.966  (66s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1508/1560] XGB       repeat 4 fold 0  macro-F1=0.9851  P1=0.976 R1=0.966  (279s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1509/1560] XGB       repeat 4 fold 1  macro-F1=0.9886  P1=0.990 R1=0.966  (24s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1510/1560] XGB       repeat 4 fold 1  macro-F1=0.9887  P1=0.986 R1=0.970  (79s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1511/1560] XGB       repeat 4 fold 1  macro-F1=0.9892  P1=0.986 R1=0.972  (25s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1512/1560] XGB       repeat 4 fold 1  macro-F1=0.9903  P1=0.984 R1=0.978  (81s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1513/1560] XGB       repeat 4 fold 1  macro-F1=0.9898  P1=0.984 R1=0.976  (25s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1514/1560] XGB       repeat 4 fold 1  macro-F1=0.9903  P1=0.984 R1=0.978  (83s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1515/1560] XGB       repeat 4 fold 1  macro-F1=0.9888  P1=0.976 R1=0.980  (25s)  [ratio 0.0, orig^0.75, C=0, rho=0.38]

[1516/1560] XGB       repeat 4 fold 1  macro-F1=0.9887  P1=0.982 R1=0.974  (82s)  [ratio 0.0, orig^0.75, C=1, rho=0.38]

[1517/1560] XGB       repeat 4 fold 1  macro-F1=0.9878  P1=0.972 R1=0.980  (26s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1518/1560] XGB       repeat 4 fold 1  macro-F1=0.9908  P1=0.984 R1=0.980  (81s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1519/1560] XGB       repeat 4 fold 1  macro-F1=0.9873  P1=0.970 R1=0.980  (26s)  [ratio 0.0, orig^1.25, C=0, rho=2.65]

[1520/1560] XGB       repeat 4 fold 1  macro-F1=0.9893  P1=0.978 R1=0.980  (77s)  [ratio 0.0, orig^1.25, C=1, rho=2.65]

[1521/1560] XGB       repeat 4 fold 1  macro-F1=0.9854  P1=0.961 R1=0.982  (24s)  [ratio 0.0, orig^1.5, C=0, rho=7.00]

[1522/1560] XGB       repeat 4 fold 1  macro-F1=0.9883  P1=0.974 R1=0.980  (71s)  [ratio 0.0, orig^1.5, C=1, rho=7.00]

[1523/1560] XGB       repeat 4 fold 1  macro-F1=0.9485  P1=0.823 R1=0.992  (22s)  [ratio 0.0, orig^2.0, C=0, rho=49.00]

[1524/1560] XGB       repeat 4 fold 1  macro-F1=0.9882  P1=0.982 R1=0.972  (61s)  [ratio 0.0, orig^2.0, C=1, rho=49.00]

[1525/1560] XGB       repeat 4 fold 1  macro-F1=0.9908  P1=0.982 R1=0.982  (107s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1526/1560] XGB       repeat 4 fold 1  macro-F1=0.9908  P1=0.982 R1=0.982  (266s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1527/1560] XGB       repeat 4 fold 1  macro-F1=0.9903  P1=0.980 R1=0.982  (107s)  [ratio 0.5, orig^0.25, C=0, rho=1.32]

[1528/1560] XGB       repeat 4 fold 1  macro-F1=0.9888  P1=0.974 R1=0.982  (265s)  [ratio 0.5, orig^0.25, C=1, rho=1.32]

[1529/1560] XGB       repeat 4 fold 1  macro-F1=0.9908  P1=0.982 R1=0.982  (107s)  [ratio 0.5, orig^0.5, C=0, rho=3.49]

[1530/1560] XGB       repeat 4 fold 1  macro-F1=0.9903  P1=0.982 R1=0.980  (267s)  [ratio 0.5, orig^0.5, C=1, rho=3.49]

[1531/1560] XGB       repeat 4 fold 1  macro-F1=0.9839  P1=0.955 R1=0.982  (103s)  [ratio 0.5, orig^0.75, C=0, rho=9.24]

[1532/1560] XGB       repeat 4 fold 1  macro-F1=0.9898  P1=0.978 R1=0.982  (267s)  [ratio 0.5, orig^0.75, C=1, rho=9.24]

[1533/1560] XGB       repeat 4 fold 1  macro-F1=0.9772  P1=0.927 R1=0.986  (109s)  [ratio 0.5, orig^1.0, C=0, rho=24.44]

[1534/1560] XGB       repeat 4 fold 1  macro-F1=0.9903  P1=0.980 R1=0.982  (184s)  [ratio 0.5, orig^1.0, C=1, rho=24.44]

[1535/1560] XGB       repeat 4 fold 1  macro-F1=0.9425  P1=0.807 R1=0.986  (26s)  [ratio 0.5, orig^1.25, C=0, rho=64.66]

[1536/1560] XGB       repeat 4 fold 1  macro-F1=0.9908  P1=0.982 R1=0.982  (184s)  [ratio 0.5, orig^1.25, C=1, rho=64.66]

[1537/1560] XGB       repeat 4 fold 1  macro-F1=0.8871  P1=0.641 R1=0.996  (34s)  [ratio 0.5, orig^1.5, C=0, rho=171.07]

[1538/1560] XGB       repeat 4 fold 1  macro-F1=0.9873  P1=0.970 R1=0.980  (180s)  [ratio 0.5, orig^1.5, C=1, rho=171.07]

[1539/1560] XGB       repeat 4 fold 1  macro-F1=0.6008  P1=0.151 R1=0.998  (30s)  [ratio 0.5, orig^2.0, C=0, rho=1197.50]

[1540/1560] XGB       repeat 4 fold 1  macro-F1=0.8700  P1=0.602 R1=0.982  (168s)  [ratio 0.5, orig^2.0, C=1, rho=1197.50]

[1541/1560] XGB       repeat 4 fold 1  macro-F1=0.9898  P1=0.978 R1=0.982  (38s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1542/1560] XGB       repeat 4 fold 1  macro-F1=0.9898  P1=0.978 R1=0.982  (173s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1543/1560] XGB       repeat 4 fold 1  macro-F1=0.9903  P1=0.980 R1=0.982  (149s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1544/1560] XGB       repeat 4 fold 1  macro-F1=0.9903  P1=0.980 R1=0.982  (377s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1545/1560] XGB       repeat 4 fold 1  macro-F1=0.9893  P1=0.976 R1=0.982  (152s)  [ratio 1.0, orig^0.25, C=0, rho=2.65]

[1546/1560] XGB       repeat 4 fold 1  macro-F1=0.9913  P1=0.984 R1=0.982  (379s)  [ratio 1.0, orig^0.25, C=1, rho=2.65]

[1547/1560] XGB       repeat 4 fold 1  macro-F1=0.9868  P1=0.967 R1=0.982  (148s)  [ratio 1.0, orig^0.5, C=0, rho=7.00]

[1548/1560] XGB       repeat 4 fold 1  macro-F1=0.9888  P1=0.976 R1=0.980  (374s)  [ratio 1.0, orig^0.5, C=1, rho=7.00]

[1549/1560] XGB       repeat 4 fold 1  macro-F1=0.9815  P1=0.944 R1=0.984  (149s)  [ratio 1.0, orig^0.75, C=0, rho=18.52]

[1550/1560] XGB       repeat 4 fold 1  macro-F1=0.9873  P1=0.968 R1=0.982  (358s)  [ratio 1.0, orig^0.75, C=1, rho=18.52]

[1551/1560] XGB       repeat 4 fold 1  macro-F1=0.9671  P1=0.888 R1=0.988  (147s)  [ratio 1.0, orig^1.0, C=0, rho=49.00]

[1552/1560] XGB       repeat 4 fold 1  macro-F1=0.9883  P1=0.972 R1=0.982  (256s)  [ratio 1.0, orig^1.0, C=1, rho=49.00]

[1553/1560] XGB       repeat 4 fold 1  macro-F1=0.9215  P1=0.741 R1=0.988  (33s)  [ratio 1.0, orig^1.25, C=0, rho=129.64]

[1554/1560] XGB       repeat 4 fold 1  macro-F1=0.9873  P1=0.972 R1=0.978  (240s)  [ratio 1.0, orig^1.25, C=1, rho=129.64]

[1555/1560] XGB       repeat 4 fold 1  macro-F1=0.8344  P1=0.515 R1=0.994  (25s)  [ratio 1.0, orig^1.5, C=0, rho=343.00]

[1556/1560] XGB       repeat 4 fold 1  macro-F1=0.9824  P1=0.953 R1=0.978  (229s)  [ratio 1.0, orig^1.5, C=1, rho=343.00]

[1557/1560] XGB       repeat 4 fold 1  macro-F1=0.5483  P1=0.106 R1=1.000  (32s)  [ratio 1.0, orig^2.0, C=0, rho=2401.00]

[1558/1560] XGB       repeat 4 fold 1  macro-F1=0.7560  P1=0.362 R1=0.992  (210s)  [ratio 1.0, orig^2.0, C=1, rho=2401.00]

[1559/1560] XGB       repeat 4 fold 1  macro-F1=0.9903  P1=0.980 R1=0.982  (31s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1560/1560] XGB       repeat 4 fold 1  macro-F1=0.9903  P1=0.980 R1=0.982  (203s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

## Macro-F1 by resampling ratio, weight setting and threshold tuning

In [4]:
results.pivot_table(index=["sampling_ratio", "weight_mode", "weight_power"],
                    columns=["classifier", "C"], values="macro_f1").round(4)

classifier                                   LR              RF          \
C                                             0       1       0       1
sampling_ratio weight_mode weight_power
0.0            orig        0.00          0.8560  0.8673  0.9815  0.9823
                           0.25          0.8639  0.8647  0.9842  0.9837
                           0.50          0.7918  0.8623  0.9847  0.9841
                           0.75          0.7345  0.8589  0.9850  0.9845
                           1.00          0.6782  0.8509  0.9858  0.9847
                           1.25          0.6271  0.8405  0.9858  0.9848
                           1.50          0.5868  0.7982  0.9807  0.9828
                           2.00          0.5030  0.7138  0.8365  0.9779
0.5            orig        0.00          0.7397  0.8596  0.9854  0.9853
                           0.25          0.6790  0.8569  0.9863  0.9864
                           0.50          0.6433  0.8504  0.9858  0.9863
                           0.75          0.6085  0.7873  0.9751  0.9853
                           1.00          0.5717  0.7402  0.9122  0.9812
                           1.25          0.5340  0.7108  0.7478  0.9782
                           1.50          0.5012  0.6701  0.6443  0.9773
                           2.00          0.4432  0.5707  0.4378  0.9744
               recalc      1.00          0.6935  0.8594  0.9862  0.9862
1.0            orig        0.00          0.6952  0.8571  0.9864  0.9867
                           0.25          0.6538  0.8553  0.9867  0.9864
                           0.50          0.6180  0.8032  0.9824  0.9854
                           0.75          0.5872  0.7490  0.9449  0.9831
                           1.00          0.5457  0.7212  0.7855  0.9799
                           1.25          0.5126  0.6747  0.6854  0.9764
                           1.50          0.4817  0.6353  0.6049  0.9733
                           2.00          0.2941  0.5015  0.3952  0.9712
               recalc      1.00          0.6952  0.8571  0.9864  0.9867

classifier                                  XGB
C                                             0       1
sampling_ratio weight_mode weight_power
0.0            orig        0.00          0.9875  0.9876
                           0.25          0.9884  0.9880
                           0.50          0.9889  0.9887
                           0.75          0.9893  0.9892
                           1.00          0.9893  0.9897
                           1.25          0.9883  0.9896
                           1.50          0.9842  0.9891
                           2.00          0.9377  0.9871
0.5            orig        0.00          0.9887  0.9883
                           0.25          0.9887  0.9886
                           0.50          0.9885  0.9891
                           0.75          0.9857  0.9885
                           1.00          0.9780  0.9877
                           1.25          0.9539  0.9862
                           1.50          0.8771  0.9792
                           2.00          0.6363  0.8629
               recalc      1.00          0.9886  0.9882
1.0            orig        0.00          0.9885  0.9884
                           0.25          0.9886  0.9887
                           0.50          0.9871  0.9882
                           0.75          0.9818  0.9879
                           1.00          0.9686  0.9867
                           1.25          0.9275  0.9846
                           1.50          0.8275  0.9577
                           2.00          0.5655  0.7658
               recalc      1.00          0.9885  0.9884

In [5]:
results.groupby(["sampling_ratio", "weight_mode", "weight_power"])[["rho_eff", "precision_1", "recall_1", "ppr_ratio"]].mean().round(3)

                                          rho_eff  precision_1  recall_1  \
sampling_ratio weight_mode weight_power
0.0            orig        0.00             0.020        0.962     0.841
                           0.25             0.054        0.948     0.853
                           0.50             0.143        0.880     0.881
                           0.75             0.378        0.853     0.900
                           1.00             1.000        0.835     0.908
                           1.25             2.646        0.813     0.912
                           1.50             7.000        0.762     0.926
                           2.00            49.000        0.615     0.962
0.5            orig        0.00             0.499        0.842     0.913
                           0.25             1.321        0.830     0.915
                           0.50             3.495        0.811     0.921
                           0.75             9.247        0.751     0.940
                           1.00            24.464        0.683     0.953
                           1.25            64.727        0.597     0.963
                           1.50           171.250        0.581     0.897
                           2.00          1198.752        0.451     0.846
               recalc      1.00             1.000        0.832     0.916
1.0            orig        0.00             1.000        0.829     0.918
                           0.25             2.646        0.821     0.917
                           0.50             7.000        0.769     0.935
                           0.75            18.520        0.708     0.952
                           1.00            49.000        0.624     0.961
                           1.25           129.642        0.611     0.909
                           1.50           343.000        0.582     0.841
                           2.00          2401.000        0.313     0.802
               recalc      1.00             1.000        0.829     0.918

                                         ppr_ratio
sampling_ratio weight_mode weight_power
0.0            orig        0.00              0.871
                           0.25              0.894
                           0.50              1.059
                           0.75              1.229
                           1.00              1.445
                           1.25              1.710
                           1.50              2.093
                           2.00              3.569
0.5            orig        0.00              1.255
                           0.25              1.450
                           0.50              1.630
                           0.75              1.989
                           1.00              2.474
                           1.25              3.354
                           1.50              4.022
                           2.00              7.936
               recalc      1.00              1.400
1.0            orig        0.00              1.403
                           0.25              1.563
                           0.50              1.882
                           0.75              2.279
                           1.00              3.069
                           1.25              3.734
                           1.50              4.336
                           2.00             11.335
               recalc      1.00              1.403