# APS Failure (Scania Trucks) - E2 weight sensitivity
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/MuhammadDevX/ML-Research-Dataset-Imbalance/blob/main/aps/e2_weight_sensitivity/aps_e2_weight_sensitivity.ipynb)

Answers reviewer R3 (one weighting configuration only) and tests the over-correction mechanism.

* Classifiers: LR, RF, XGB.
* Resampling ratio: [0.0, 0.5, 1.0] (0 = none; otherwise SMOTETomek to that minority:majority ratio).
* Positive-class weight = IR ** power, power in [0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0]
  (0 = none, 0.5 = sqrt-inverse, 1 = inverse frequency), plus weights recomputed after resampling.
* Each setting with and without threshold tuning (C).
* Hyperparameters are reused from `c0_none` (no resampling) and `c1_A_smotetomek` (with resampling).
  **Run those two notebooks first**; missing folds are tuned here, which is slower.
* Each row records `rho_eff`, the positive:negative loss mass the classifier sees.

**How to run on Colab**
1. Click the badge, then *Runtime > Run all*. Allow Google Drive access when asked.
2. Results are appended to Google Drive after every classifier/fold:
   `MyDrive/ML-Research-Dataset-Imbalance/aps/e2_weight_sensitivity/results/aps__e2_weight_sensitivity.csv`.
3. If the runtime disconnects, just *Run all* again: finished folds are skipped.
4. When it is complete, copy the CSV into the same path in the repository and commit it.

In [1]:
# ---- Setup: identical in every notebook. Do not edit. ----
import os, sys, subprocess
REPO_URL = "https://github.com/MuhammadDevX/ML-Research-Dataset-Imbalance.git"
BRANCH = "main"
try:
    import google.colab  # noqa: F401
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    REPO_ROOT = "/content/ML-Research-Dataset-Imbalance"
    if not os.path.isdir(REPO_ROOT):
        subprocess.run(["git", "clone", "--branch", BRANCH, REPO_URL, REPO_ROOT], check=True)
    else:
        subprocess.run(["git", "-C", REPO_ROOT, "pull", "--ff-only"], check=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r",
                    f"{REPO_ROOT}/requirements.txt"], check=True)
    from google.colab import drive
    drive.mount("/content/drive")
    # Results go to Google Drive so they survive a disconnect.
    os.environ.setdefault("RESULTS_ROOT", "/content/drive/MyDrive/ML-Research-Dataset-Imbalance")
else:
    REPO_ROOT = os.path.abspath(os.getcwd())
    while not os.path.isdir(os.path.join(REPO_ROOT, "common")):
        parent = os.path.dirname(REPO_ROOT)
        if parent == REPO_ROOT:
            raise RuntimeError("Open this notebook from inside the repository.")
        REPO_ROOT = parent

sys.path.insert(0, REPO_ROOT)
os.chdir(REPO_ROOT)
from common.env import check_environment
check_environment()

Environment OK: scikit-learn 1.9.1, imbalanced-learn 0.14.2, xgboost 3.4.1, lightgbm 4.7.0

In [2]:
DATASET = "aps"
# Quick test run (2 folds, fewer classifiers and candidates): change the next line
# to  SMOKE = True . Its results go to a separate *__SMOKE.csv file and must never
# be used in the paper. Leave it as it is for the real run.
SMOKE = os.environ.get("SMOKE", "0") == "1"

In [3]:
from common.cv import run_e2
results = run_e2(DATASET, smoke=SMOKE)

Hyperparameters found: c0 70 folds, c1 70 folds. Missing ones are tuned here once with the same seed.
Writing to C:\Users\LENOVO\Desktop\Semester 6\Machine Learning\research\aps\e2_weight_sensitivity\results\aps__e2_weight_sensitivity.csv

[  1/1560] LR        repeat 0 fold 0  macro-F1=0.8334  P1=0.714 R1=0.635  (1s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[  2/1560] LR        repeat 0 fold 0  macro-F1=0.8364  P1=0.603 R1=0.779  (3s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[  3/1560] LR        repeat 0 fold 0  macro-F1=0.8390  P1=0.649 R1=0.724  (1s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[  4/1560] LR        repeat 0 fold 0  macro-F1=0.8328  P1=0.577 R1=0.807  (3s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[  5/1560] LR        repeat 0 fold 0  macro-F1=0.8297  P1=0.583 R1=0.779  (1s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[  6/1560] LR        repeat 0 fold 0  macro-F1=0.8338  P1=0.653 R1=0.696  (3s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[  7/1560] LR        repeat 0 fold 0  macro-F1=0.8024  P1=0.490 R1=0.823  (1s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[  8/1560] LR        repeat 0 fold 0  macro-F1=0.8256  P1=0.642 R1=0.674  (3s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[  9/1560] LR        repeat 0 fold 0  macro-F1=0.7770  P1=0.424 R1=0.851  (1s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[ 10/1560] LR        repeat 0 fold 0  macro-F1=0.8256  P1=0.633 R1=0.685  (3s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[ 11/1560] LR        repeat 0 fold 0  macro-F1=0.7407  P1=0.351 R1=0.856  (1s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[ 12/1560] LR        repeat 0 fold 0  macro-F1=0.8115  P1=0.566 R1=0.713  (3s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[ 13/1560] LR        repeat 0 fold 0  macro-F1=0.6917  P1=0.266 R1=0.867  (1s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[ 14/1560] LR        repeat 0 fold 0  macro-F1=0.8077  P1=0.551 R1=0.718  (3s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[ 15/1560] LR        repeat 0 fold 0  macro-F1=0.5092  P1=0.076 R1=0.967  (1s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[ 16/1560] LR        repeat 0 fold 0  macro-F1=0.7716  P1=0.415 R1=0.840  (2s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[ 17/1560] LR        repeat 0 fold 0  macro-F1=0.7912  P1=0.467 R1=0.812  (4s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[ 18/1560] LR        repeat 0 fold 0  macro-F1=0.8317  P1=0.620 R1=0.729  (10s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[ 19/1560] LR        repeat 0 fold 0  macro-F1=0.7630  P1=0.398 R1=0.834  (4s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[ 20/1560] LR        repeat 0 fold 0  macro-F1=0.8191  P1=0.576 R1=0.735  (9s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[ 21/1560] LR        repeat 0 fold 0  macro-F1=0.7312  P1=0.336 R1=0.840  (4s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[ 22/1560] LR        repeat 0 fold 0  macro-F1=0.8153  P1=0.589 R1=0.696  (10s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[ 23/1560] LR        repeat 0 fold 0  macro-F1=0.6821  P1=0.252 R1=0.856  (1s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[ 24/1560] LR        repeat 0 fold 0  macro-F1=0.8033  P1=0.535 R1=0.724  (7s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[ 25/1560] LR        repeat 0 fold 0  macro-F1=0.6285  P1=0.178 R1=0.901  (1s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[ 26/1560] LR        repeat 0 fold 0  macro-F1=0.7819  P1=0.459 R1=0.768  (6s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[ 27/1560] LR        repeat 0 fold 0  macro-F1=0.5020  P1=0.072 R1=0.967  (1s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[ 28/1560] LR        repeat 0 fold 0  macro-F1=0.7597  P1=0.389 R1=0.845  (6s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[ 29/1560] LR        repeat 0 fold 0  macro-F1=0.1788  P1=0.022 R1=1.000  (1s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[ 30/1560] LR        repeat 0 fold 0  macro-F1=0.7241  P1=0.317 R1=0.884  (2s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[ 31/1560] LR        repeat 0 fold 0  macro-F1=0.0185  P1=0.018 R1=1.000  (1s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[ 32/1560] LR        repeat 0 fold 0  macro-F1=0.5827  P1=0.130 R1=0.972  (2s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[ 33/1560] LR        repeat 0 fold 0  macro-F1=0.7702  P1=0.416 R1=0.823  (1s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[ 34/1560] LR        repeat 0 fold 0  macro-F1=0.8232  P1=0.588 R1=0.735  (3s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[ 35/1560] LR        repeat 0 fold 0  macro-F1=0.7777  P1=0.431 R1=0.829  (6s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[ 36/1560] LR        repeat 0 fold 0  macro-F1=0.8175  P1=0.568 R1=0.740  (15s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[ 37/1560] LR        repeat 0 fold 0  macro-F1=0.7440  P1=0.360 R1=0.834  (6s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[ 38/1560] LR        repeat 0 fold 0  macro-F1=0.8063  P1=0.514 R1=0.785  (15s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[ 39/1560] LR        repeat 0 fold 0  macro-F1=0.7060  P1=0.291 R1=0.845  (6s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[ 40/1560] LR        repeat 0 fold 0  macro-F1=0.8077  P1=0.551 R1=0.718  (15s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[ 41/1560] LR        repeat 0 fold 0  macro-F1=0.6525  P1=0.209 R1=0.884  (1s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[ 42/1560] LR        repeat 0 fold 0  macro-F1=0.7917  P1=0.488 R1=0.757  (9s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[ 43/1560] LR        repeat 0 fold 0  macro-F1=0.5436  P1=0.096 R1=0.923  (1s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[ 44/1560] LR        repeat 0 fold 0  macro-F1=0.7685  P1=0.418 R1=0.801  (9s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[ 45/1560] LR        repeat 0 fold 0  macro-F1=0.3067  P1=0.029 R1=0.978  (1s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[ 46/1560] LR        repeat 0 fold 0  macro-F1=0.7357  P1=0.339 R1=0.873  (9s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[ 47/1560] LR        repeat 0 fold 0  macro-F1=0.0485  P1=0.019 R1=1.000  (1s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[ 48/1560] LR        repeat 0 fold 0  macro-F1=0.7017  P1=0.277 R1=0.928  (3s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[ 49/1560] LR        repeat 0 fold 0  macro-F1=0.0183  P1=0.018 R1=1.000  (1s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[ 50/1560] LR        repeat 0 fold 0  macro-F1=0.5170  P1=0.800 R1=0.022  (3s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[ 51/1560] LR        repeat 0 fold 0  macro-F1=0.7777  P1=0.431 R1=0.829  (1s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[ 52/1560] LR        repeat 0 fold 0  macro-F1=0.8175  P1=0.568 R1=0.740  (3s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[ 53/1560] LR        repeat 0 fold 1  macro-F1=0.8123  P1=0.684 R1=0.586  (1s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[ 54/1560] LR        repeat 0 fold 1  macro-F1=0.8205  P1=0.692 R1=0.608  (4s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[ 55/1560] LR        repeat 0 fold 1  macro-F1=0.8151  P1=0.644 R1=0.630  (1s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[ 56/1560] LR        repeat 0 fold 1  macro-F1=0.8152  P1=0.639 R1=0.635  (4s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[ 57/1560] LR        repeat 0 fold 1  macro-F1=0.8177  P1=0.609 R1=0.680  (2s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[ 58/1560] LR        repeat 0 fold 1  macro-F1=0.8171  P1=0.646 R1=0.635  (4s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[ 59/1560] LR        repeat 0 fold 1  macro-F1=0.8023  P1=0.537 R1=0.713  (1s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[ 60/1560] LR        repeat 0 fold 1  macro-F1=0.8153  P1=0.634 R1=0.641  (4s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[ 61/1560] LR        repeat 0 fold 1  macro-F1=0.7734  P1=0.449 R1=0.735  (1s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[ 62/1560] LR        repeat 0 fold 1  macro-F1=0.8065  P1=0.601 R1=0.641  (4s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[ 63/1560] LR        repeat 0 fold 1  macro-F1=0.7400  P1=0.365 R1=0.768  (1s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[ 64/1560] LR        repeat 0 fold 1  macro-F1=0.8103  P1=0.605 R1=0.652  (3s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[ 65/1560] LR        repeat 0 fold 1  macro-F1=0.7020  P1=0.287 R1=0.818  (1s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[ 66/1560] LR        repeat 0 fold 1  macro-F1=0.7893  P1=0.524 R1=0.669  (3s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[ 67/1560] LR        repeat 0 fold 1  macro-F1=0.6048  P1=0.151 R1=0.884  (1s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[ 68/1560] LR        repeat 0 fold 1  macro-F1=0.7624  P1=0.414 R1=0.762  (3s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[ 69/1560] LR        repeat 0 fold 1  macro-F1=0.7904  P1=0.498 R1=0.724  (5s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[ 70/1560] LR        repeat 0 fold 1  macro-F1=0.8128  P1=0.659 R1=0.608  (12s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[ 71/1560] LR        repeat 0 fold 1  macro-F1=0.7548  P1=0.402 R1=0.746  (5s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[ 72/1560] LR        repeat 0 fold 1  macro-F1=0.8091  P1=0.611 R1=0.641  (12s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[ 73/1560] LR        repeat 0 fold 1  macro-F1=0.7287  P1=0.336 R1=0.807  (5s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[ 74/1560] LR        repeat 0 fold 1  macro-F1=0.7961  P1=0.545 R1=0.669  (12s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[ 75/1560] LR        repeat 0 fold 1  macro-F1=0.6849  P1=0.257 R1=0.851  (1s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[ 76/1560] LR        repeat 0 fold 1  macro-F1=0.7938  P1=0.528 R1=0.685  (8s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[ 77/1560] LR        repeat 0 fold 1  macro-F1=0.6313  P1=0.182 R1=0.873  (1s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[ 78/1560] LR        repeat 0 fold 1  macro-F1=0.7828  P1=0.469 R1=0.746  (8s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[ 79/1560] LR        repeat 0 fold 1  macro-F1=0.5611  P1=0.110 R1=0.923  (1s)  [ratio 0.5, orig^1.25, C=0, rho=73.60]

[ 80/1560] LR        repeat 0 fold 1  macro-F1=0.7546  P1=0.389 R1=0.796  (7s)  [ratio 0.5, orig^1.25, C=1, rho=73.60]

[ 81/1560] LR        repeat 0 fold 1  macro-F1=0.4281  P1=0.045 R1=0.967  (1s)  [ratio 0.5, orig^1.5, C=0, rho=199.74]

[ 82/1560] LR        repeat 0 fold 1  macro-F1=0.7274  P1=0.324 R1=0.878  (3s)  [ratio 0.5, orig^1.5, C=1, rho=199.74]

[ 83/1560] LR        repeat 0 fold 1  macro-F1=0.0190  P1=0.018 R1=1.000  (1s)  [ratio 0.5, orig^2.0, C=0, rho=1471.16]

[ 84/1560] LR        repeat 0 fold 1  macro-F1=0.6313  P1=0.181 R1=0.967  (3s)  [ratio 0.5, orig^2.0, C=1, rho=1471.16]

[ 85/1560] LR        repeat 0 fold 1  macro-F1=0.7678  P1=0.434 R1=0.740  (1s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[ 86/1560] LR        repeat 0 fold 1  macro-F1=0.8133  P1=0.637 R1=0.630  (4s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[ 87/1560] LR        repeat 0 fold 1  macro-F1=0.7627  P1=0.427 R1=0.724  (8s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[ 88/1560] LR        repeat 0 fold 1  macro-F1=0.8094  P1=0.602 R1=0.652  (22s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[ 89/1560] LR        repeat 0 fold 1  macro-F1=0.7376  P1=0.356 R1=0.790  (8s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[ 90/1560] LR        repeat 0 fold 1  macro-F1=0.8078  P1=0.592 R1=0.657  (21s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[ 91/1560] LR        repeat 0 fold 1  macro-F1=0.7001  P1=0.283 R1=0.823  (7s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[ 92/1560] LR        repeat 0 fold 1  macro-F1=0.7891  P1=0.517 R1=0.680  (21s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[ 93/1560] LR        repeat 0 fold 1  macro-F1=0.6545  P1=0.212 R1=0.862  (1s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[ 94/1560] LR        repeat 0 fold 1  macro-F1=0.7858  P1=0.490 R1=0.713  (14s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[ 95/1560] LR        repeat 0 fold 1  macro-F1=0.5956  P1=0.142 R1=0.895  (1s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[ 96/1560] LR        repeat 0 fold 1  macro-F1=0.7658  P1=0.419 R1=0.773  (13s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[ 97/1560] LR        repeat 0 fold 1  macro-F1=0.5015  P1=0.071 R1=0.956  (1s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[ 98/1560] LR        repeat 0 fold 1  macro-F1=0.7365  P1=0.343 R1=0.856  (14s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[ 99/1560] LR        repeat 0 fold 1  macro-F1=0.2337  P1=0.024 R1=0.983  (1s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[100/1560] LR        repeat 0 fold 1  macro-F1=0.6981  P1=0.273 R1=0.912  (3s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[101/1560] LR        repeat 0 fold 1  macro-F1=0.0183  P1=0.018 R1=1.000  (1s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[102/1560] LR        repeat 0 fold 1  macro-F1=0.5353  P1=0.092 R1=0.983  (3s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[103/1560] LR        repeat 0 fold 1  macro-F1=0.7627  P1=0.427 R1=0.724  (2s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[104/1560] LR        repeat 0 fold 1  macro-F1=0.8094  P1=0.602 R1=0.652  (4s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[105/1560] LR        repeat 1 fold 0  macro-F1=0.8294  P1=0.704 R1=0.630  (1s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[106/1560] LR        repeat 1 fold 0  macro-F1=0.8265  P1=0.685 R1=0.635  (4s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[107/1560] LR        repeat 1 fold 0  macro-F1=0.8274  P1=0.649 R1=0.674  (1s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[108/1560] LR        repeat 1 fold 0  macro-F1=0.8293  P1=0.661 R1=0.669  (3s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[109/1560] LR        repeat 1 fold 0  macro-F1=0.8058  P1=0.555 R1=0.702  (1s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[110/1560] LR        repeat 1 fold 0  macro-F1=0.8125  P1=0.591 R1=0.680  (4s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[111/1560] LR        repeat 1 fold 0  macro-F1=0.7840  P1=0.462 R1=0.773  (1s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[112/1560] LR        repeat 1 fold 0  macro-F1=0.8027  P1=0.545 R1=0.702  (4s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[113/1560] LR        repeat 1 fold 0  macro-F1=0.7477  P1=0.375 R1=0.796  (1s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[114/1560] LR        repeat 1 fold 0  macro-F1=0.8020  P1=0.528 R1=0.729  (4s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[115/1560] LR        repeat 1 fold 0  macro-F1=0.7285  P1=0.327 R1=0.867  (1s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[116/1560] LR        repeat 1 fold 0  macro-F1=0.8026  P1=0.533 R1=0.724  (4s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[117/1560] LR        repeat 1 fold 0  macro-F1=0.6969  P1=0.272 R1=0.901  (1s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[118/1560] LR        repeat 1 fold 0  macro-F1=0.8058  P1=0.523 R1=0.762  (3s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[119/1560] LR        repeat 1 fold 0  macro-F1=0.5868  P1=0.134 R1=0.956  (1s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[120/1560] LR        repeat 1 fold 0  macro-F1=0.7732  P1=0.416 R1=0.851  (3s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[121/1560] LR        repeat 1 fold 0  macro-F1=0.7613  P1=0.408 R1=0.779  (5s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[122/1560] LR        repeat 1 fold 0  macro-F1=0.7989  P1=0.522 R1=0.724  (15s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[123/1560] LR        repeat 1 fold 0  macro-F1=0.7384  P1=0.353 R1=0.812  (6s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[124/1560] LR        repeat 1 fold 0  macro-F1=0.8034  P1=0.565 R1=0.674  (16s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[125/1560] LR        repeat 1 fold 0  macro-F1=0.7176  P1=0.309 R1=0.856  (5s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[126/1560] LR        repeat 1 fold 0  macro-F1=0.8004  P1=0.538 R1=0.702  (14s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[127/1560] LR        repeat 1 fold 0  macro-F1=0.6832  P1=0.251 R1=0.906  (1s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[128/1560] LR        repeat 1 fold 0  macro-F1=0.7989  P1=0.502 R1=0.768  (10s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[129/1560] LR        repeat 1 fold 0  macro-F1=0.6341  P1=0.185 R1=0.939  (1s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[130/1560] LR        repeat 1 fold 0  macro-F1=0.7897  P1=0.460 R1=0.823  (10s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[131/1560] LR        repeat 1 fold 0  macro-F1=0.5693  P1=0.118 R1=0.956  (1s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[132/1560] LR        repeat 1 fold 0  macro-F1=0.7656  P1=0.396 R1=0.873  (9s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[133/1560] LR        repeat 1 fold 0  macro-F1=0.4231  P1=0.044 R1=0.961  (1s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[134/1560] LR        repeat 1 fold 0  macro-F1=0.7258  P1=0.317 R1=0.917  (3s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[135/1560] LR        repeat 1 fold 0  macro-F1=0.0214  P1=0.018 R1=1.000  (1s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[136/1560] LR        repeat 1 fold 0  macro-F1=0.6420  P1=0.194 R1=0.978  (3s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[137/1560] LR        repeat 1 fold 0  macro-F1=0.7426  P1=0.365 R1=0.796  (1s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[138/1560] LR        repeat 1 fold 0  macro-F1=0.8000  P1=0.531 R1=0.713  (4s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[139/1560] LR        repeat 1 fold 0  macro-F1=0.7426  P1=0.366 R1=0.790  (9s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[140/1560] LR        repeat 1 fold 0  macro-F1=0.8008  P1=0.533 R1=0.713  (24s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[141/1560] LR        repeat 1 fold 0  macro-F1=0.7222  P1=0.319 R1=0.840  (9s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[142/1560] LR        repeat 1 fold 0  macro-F1=0.7913  P1=0.498 R1=0.729  (23s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[143/1560] LR        repeat 1 fold 0  macro-F1=0.6999  P1=0.277 R1=0.890  (8s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[144/1560] LR        repeat 1 fold 0  macro-F1=0.7998  P1=0.511 R1=0.751  (23s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[145/1560] LR        repeat 1 fold 0  macro-F1=0.6528  P1=0.208 R1=0.923  (1s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[146/1560] LR        repeat 1 fold 0  macro-F1=0.7908  P1=0.469 R1=0.801  (17s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[147/1560] LR        repeat 1 fold 0  macro-F1=0.6027  P1=0.149 R1=0.945  (1s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[148/1560] LR        repeat 1 fold 0  macro-F1=0.7724  P1=0.416 R1=0.845  (13s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[149/1560] LR        repeat 1 fold 0  macro-F1=0.5153  P1=0.079 R1=0.956  (1s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[150/1560] LR        repeat 1 fold 0  macro-F1=0.7419  P1=0.346 R1=0.906  (15s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[151/1560] LR        repeat 1 fold 0  macro-F1=0.2927  P1=0.028 R1=0.989  (1s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[152/1560] LR        repeat 1 fold 0  macro-F1=0.6989  P1=0.273 R1=0.934  (5s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[153/1560] LR        repeat 1 fold 0  macro-F1=0.0207  P1=0.018 R1=1.000  (1s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[154/1560] LR        repeat 1 fold 0  macro-F1=0.5737  P1=0.667 R1=0.088  (4s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[155/1560] LR        repeat 1 fold 0  macro-F1=0.7426  P1=0.366 R1=0.790  (2s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[156/1560] LR        repeat 1 fold 0  macro-F1=0.8008  P1=0.533 R1=0.713  (5s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[157/1560] LR        repeat 1 fold 1  macro-F1=0.8275  P1=0.695 R1=0.630  (2s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[158/1560] LR        repeat 1 fold 1  macro-F1=0.8264  P1=0.719 R1=0.608  (5s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[159/1560] LR        repeat 1 fold 1  macro-F1=0.8219  P1=0.643 R1=0.657  (2s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[160/1560] LR        repeat 1 fold 1  macro-F1=0.8219  P1=0.643 R1=0.657  (6s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[161/1560] LR        repeat 1 fold 1  macro-F1=0.8197  P1=0.595 R1=0.707  (2s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[162/1560] LR        repeat 1 fold 1  macro-F1=0.8248  P1=0.612 R1=0.707  (6s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[163/1560] LR        repeat 1 fold 1  macro-F1=0.8009  P1=0.531 R1=0.718  (2s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[164/1560] LR        repeat 1 fold 1  macro-F1=0.8284  P1=0.680 R1=0.646  (6s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[165/1560] LR        repeat 1 fold 1  macro-F1=0.7886  P1=0.491 R1=0.729  (2s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[166/1560] LR        repeat 1 fold 1  macro-F1=0.8236  P1=0.667 R1=0.641  (6s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[167/1560] LR        repeat 1 fold 1  macro-F1=0.7692  P1=0.424 R1=0.785  (2s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[168/1560] LR        repeat 1 fold 1  macro-F1=0.8182  P1=0.634 R1=0.652  (5s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[169/1560] LR        repeat 1 fold 1  macro-F1=0.7307  P1=0.339 R1=0.812  (1s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[170/1560] LR        repeat 1 fold 1  macro-F1=0.7993  P1=0.541 R1=0.691  (5s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[171/1560] LR        repeat 1 fold 1  macro-F1=0.5685  P1=0.115 R1=0.873  (1s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[172/1560] LR        repeat 1 fold 1  macro-F1=0.7827  P1=0.455 R1=0.785  (5s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[173/1560] LR        repeat 1 fold 1  macro-F1=0.8007  P1=0.522 R1=0.735  (7s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[174/1560] LR        repeat 1 fold 1  macro-F1=0.8186  P1=0.604 R1=0.691  (19s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[175/1560] LR        repeat 1 fold 1  macro-F1=0.7851  P1=0.477 R1=0.740  (8s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[176/1560] LR        repeat 1 fold 1  macro-F1=0.8294  P1=0.678 R1=0.652  (19s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[177/1560] LR        repeat 1 fold 1  macro-F1=0.7646  P1=0.419 R1=0.762  (8s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[178/1560] LR        repeat 1 fold 1  macro-F1=0.8202  P1=0.627 R1=0.669  (18s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[179/1560] LR        repeat 1 fold 1  macro-F1=0.7324  P1=0.344 R1=0.801  (2s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[180/1560] LR        repeat 1 fold 1  macro-F1=0.8095  P1=0.573 R1=0.691  (13s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[181/1560] LR        repeat 1 fold 1  macro-F1=0.7011  P1=0.283 R1=0.845  (2s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[182/1560] LR        repeat 1 fold 1  macro-F1=0.7933  P1=0.496 R1=0.746  (12s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[183/1560] LR        repeat 1 fold 1  macro-F1=0.6036  P1=0.150 R1=0.873  (1s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[184/1560] LR        repeat 1 fold 1  macro-F1=0.7841  P1=0.457 R1=0.790  (12s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[185/1560] LR        repeat 1 fold 1  macro-F1=0.5311  P1=0.087 R1=0.917  (1s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[186/1560] LR        repeat 1 fold 1  macro-F1=0.7471  P1=0.367 R1=0.834  (4s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[187/1560] LR        repeat 1 fold 1  macro-F1=0.1373  P1=0.021 R1=0.989  (1s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[188/1560] LR        repeat 1 fold 1  macro-F1=0.6817  P1=0.247 R1=0.928  (4s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[189/1560] LR        repeat 1 fold 1  macro-F1=0.7895  P1=0.491 R1=0.735  (2s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[190/1560] LR        repeat 1 fold 1  macro-F1=0.8237  P1=0.645 R1=0.663  (6s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[191/1560] LR        repeat 1 fold 1  macro-F1=0.7890  P1=0.487 R1=0.740  (12s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[192/1560] LR        repeat 1 fold 1  macro-F1=0.8187  P1=0.671 R1=0.619  (29s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[193/1560] LR        repeat 1 fold 1  macro-F1=0.7591  P1=0.416 R1=0.729  (12s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[194/1560] LR        repeat 1 fold 1  macro-F1=0.8174  P1=0.626 R1=0.657  (29s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[195/1560] LR        repeat 1 fold 1  macro-F1=0.7409  P1=0.364 R1=0.779  (11s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[196/1560] LR        repeat 1 fold 1  macro-F1=0.8065  P1=0.579 R1=0.669  (28s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[197/1560] LR        repeat 1 fold 1  macro-F1=0.7044  P1=0.290 R1=0.823  (2s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[198/1560] LR        repeat 1 fold 1  macro-F1=0.7939  P1=0.516 R1=0.707  (18s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[199/1560] LR        repeat 1 fold 1  macro-F1=0.6064  P1=0.153 R1=0.856  (1s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[200/1560] LR        repeat 1 fold 1  macro-F1=0.7880  P1=0.470 R1=0.779  (18s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[201/1560] LR        repeat 1 fold 1  macro-F1=0.5462  P1=0.097 R1=0.890  (1s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[202/1560] LR        repeat 1 fold 1  macro-F1=0.7425  P1=0.362 R1=0.807  (17s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[203/1560] LR        repeat 1 fold 1  macro-F1=0.4856  P1=0.064 R1=0.972  (1s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[204/1560] LR        repeat 1 fold 1  macro-F1=0.7234  P1=0.316 R1=0.890  (4s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[205/1560] LR        repeat 1 fold 1  macro-F1=0.1324  P1=0.020 R1=0.989  (1s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[206/1560] LR        repeat 1 fold 1  macro-F1=0.6492  P1=0.203 R1=0.945  (4s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[207/1560] LR        repeat 1 fold 1  macro-F1=0.7890  P1=0.487 R1=0.740  (2s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[208/1560] LR        repeat 1 fold 1  macro-F1=0.8187  P1=0.671 R1=0.619  (5s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[209/1560] LR        repeat 2 fold 0  macro-F1=0.8264  P1=0.735 R1=0.597  (1s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[210/1560] LR        repeat 2 fold 0  macro-F1=0.8294  P1=0.704 R1=0.630  (5s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[211/1560] LR        repeat 2 fold 0  macro-F1=0.8372  P1=0.704 R1=0.657  (1s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[212/1560] LR        repeat 2 fold 0  macro-F1=0.8372  P1=0.704 R1=0.657  (5s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[213/1560] LR        repeat 2 fold 0  macro-F1=0.8482  P1=0.651 R1=0.762  (2s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[214/1560] LR        repeat 2 fold 0  macro-F1=0.8335  P1=0.729 R1=0.624  (5s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[215/1560] LR        repeat 2 fold 0  macro-F1=0.8196  P1=0.545 R1=0.796  (1s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[216/1560] LR        repeat 2 fold 0  macro-F1=0.8355  P1=0.650 R1=0.707  (5s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[217/1560] LR        repeat 2 fold 0  macro-F1=0.8013  P1=0.485 R1=0.829  (1s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[218/1560] LR        repeat 2 fold 0  macro-F1=0.8301  P1=0.631 R1=0.707  (5s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[219/1560] LR        repeat 2 fold 0  macro-F1=0.7637  P1=0.401 R1=0.829  (1s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[220/1560] LR        repeat 2 fold 0  macro-F1=0.8193  P1=0.624 R1=0.669  (5s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[221/1560] LR        repeat 2 fold 0  macro-F1=0.7159  P1=0.304 R1=0.878  (1s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[222/1560] LR        repeat 2 fold 0  macro-F1=0.8171  P1=0.591 R1=0.702  (5s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[223/1560] LR        repeat 2 fold 0  macro-F1=0.5737  P1=0.121 R1=0.950  (1s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[224/1560] LR        repeat 2 fold 0  macro-F1=0.7979  P1=0.472 R1=0.845  (4s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[225/1560] LR        repeat 2 fold 0  macro-F1=0.8182  P1=0.537 R1=0.807  (7s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[226/1560] LR        repeat 2 fold 0  macro-F1=0.8275  P1=0.716 R1=0.613  (18s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[227/1560] LR        repeat 2 fold 0  macro-F1=0.7987  P1=0.479 R1=0.829  (5s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[228/1560] LR        repeat 2 fold 0  macro-F1=0.8237  P1=0.645 R1=0.663  (16s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[229/1560] LR        repeat 2 fold 0  macro-F1=0.7552  P1=0.384 R1=0.829  (5s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[230/1560] LR        repeat 2 fold 0  macro-F1=0.8205  P1=0.598 R1=0.707  (16s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[231/1560] LR        repeat 2 fold 0  macro-F1=0.7128  P1=0.299 R1=0.878  (1s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[232/1560] LR        repeat 2 fold 0  macro-F1=0.8148  P1=0.576 R1=0.713  (11s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[233/1560] LR        repeat 2 fold 0  macro-F1=0.6561  P1=0.212 R1=0.928  (1s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[234/1560] LR        repeat 2 fold 0  macro-F1=0.8069  P1=0.518 R1=0.779  (12s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[235/1560] LR        repeat 2 fold 0  macro-F1=0.5734  P1=0.121 R1=0.945  (1s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[236/1560] LR        repeat 2 fold 0  macro-F1=0.7891  P1=0.449 R1=0.856  (12s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[237/1560] LR        repeat 2 fold 0  macro-F1=0.4237  P1=0.045 R1=0.978  (1s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[238/1560] LR        repeat 2 fold 0  macro-F1=0.7437  P1=0.351 R1=0.895  (4s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[239/1560] LR        repeat 2 fold 0  macro-F1=0.0186  P1=0.018 R1=1.000  (1s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[240/1560] LR        repeat 2 fold 0  macro-F1=0.6424  P1=0.194 R1=0.978  (4s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[241/1560] LR        repeat 2 fold 0  macro-F1=0.8051  P1=0.497 R1=0.823  (2s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[242/1560] LR        repeat 2 fold 0  macro-F1=0.8265  P1=0.704 R1=0.619  (6s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[243/1560] LR        repeat 2 fold 0  macro-F1=0.8037  P1=0.493 R1=0.823  (12s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[244/1560] LR        repeat 2 fold 0  macro-F1=0.8304  P1=0.688 R1=0.646  (28s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[245/1560] LR        repeat 2 fold 0  macro-F1=0.7752  P1=0.424 R1=0.834  (12s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[246/1560] LR        repeat 2 fold 0  macro-F1=0.8293  P1=0.646 R1=0.685  (27s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[247/1560] LR        repeat 2 fold 0  macro-F1=0.7273  P1=0.326 R1=0.856  (12s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[248/1560] LR        repeat 2 fold 0  macro-F1=0.8195  P1=0.611 R1=0.685  (25s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[249/1560] LR        repeat 2 fold 0  macro-F1=0.6734  P1=0.237 R1=0.890  (2s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[250/1560] LR        repeat 2 fold 0  macro-F1=0.8177  P1=0.559 R1=0.757  (17s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[251/1560] LR        repeat 2 fold 0  macro-F1=0.6034  P1=0.150 R1=0.934  (1s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[252/1560] LR        repeat 2 fold 0  macro-F1=0.7927  P1=0.474 R1=0.801  (15s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[253/1560] LR        repeat 2 fold 0  macro-F1=0.5063  P1=0.074 R1=0.967  (1s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[254/1560] LR        repeat 2 fold 0  macro-F1=0.7606  P1=0.385 R1=0.878  (15s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[255/1560] LR        repeat 2 fold 0  macro-F1=0.2206  P1=0.024 R1=0.994  (1s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[256/1560] LR        repeat 2 fold 0  macro-F1=0.7215  P1=0.310 R1=0.912  (3s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[257/1560] LR        repeat 2 fold 0  macro-F1=0.0185  P1=0.018 R1=1.000  (1s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[258/1560] LR        repeat 2 fold 0  macro-F1=0.5375  P1=0.094 R1=0.983  (3s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[259/1560] LR        repeat 2 fold 0  macro-F1=0.8037  P1=0.493 R1=0.823  (1s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[260/1560] LR        repeat 2 fold 0  macro-F1=0.8304  P1=0.688 R1=0.646  (4s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[261/1560] LR        repeat 2 fold 1  macro-F1=0.8335  P1=0.729 R1=0.624  (1s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[262/1560] LR        repeat 2 fold 1  macro-F1=0.8325  P1=0.724 R1=0.624  (4s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[263/1560] LR        repeat 2 fold 1  macro-F1=0.8430  P1=0.677 R1=0.707  (1s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[264/1560] LR        repeat 2 fold 1  macro-F1=0.8381  P1=0.708 R1=0.657  (4s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[265/1560] LR        repeat 2 fold 1  macro-F1=0.8290  P1=0.590 R1=0.762  (1s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[266/1560] LR        repeat 2 fold 1  macro-F1=0.8439  P1=0.675 R1=0.713  (4s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[267/1560] LR        repeat 2 fold 1  macro-F1=0.8119  P1=0.514 R1=0.823  (1s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[268/1560] LR        repeat 2 fold 1  macro-F1=0.8420  P1=0.668 R1=0.713  (3s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[269/1560] LR        repeat 2 fold 1  macro-F1=0.7929  P1=0.456 R1=0.862  (1s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[270/1560] LR        repeat 2 fold 1  macro-F1=0.8198  P1=0.657 R1=0.635  (3s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[271/1560] LR        repeat 2 fold 1  macro-F1=0.7553  P1=0.374 R1=0.884  (1s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[272/1560] LR        repeat 2 fold 1  macro-F1=0.8224  P1=0.583 R1=0.740  (3s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[273/1560] LR        repeat 2 fold 1  macro-F1=0.7028  P1=0.281 R1=0.895  (1s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[274/1560] LR        repeat 2 fold 1  macro-F1=0.8114  P1=0.547 R1=0.746  (3s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[275/1560] LR        repeat 2 fold 1  macro-F1=0.5226  P1=0.083 R1=0.950  (1s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[276/1560] LR        repeat 2 fold 1  macro-F1=0.7716  P1=0.418 R1=0.829  (3s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[277/1560] LR        repeat 2 fold 1  macro-F1=0.8022  P1=0.493 R1=0.812  (4s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[278/1560] LR        repeat 2 fold 1  macro-F1=0.8187  P1=0.671 R1=0.619  (13s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[279/1560] LR        repeat 2 fold 1  macro-F1=0.7746  P1=0.423 R1=0.834  (5s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[280/1560] LR        repeat 2 fold 1  macro-F1=0.8199  P1=0.652 R1=0.641  (12s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[281/1560] LR        repeat 2 fold 1  macro-F1=0.7329  P1=0.336 R1=0.856  (5s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[282/1560] LR        repeat 2 fold 1  macro-F1=0.8053  P1=0.547 R1=0.713  (13s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[283/1560] LR        repeat 2 fold 1  macro-F1=0.6788  P1=0.246 R1=0.867  (1s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[284/1560] LR        repeat 2 fold 1  macro-F1=0.7960  P1=0.514 R1=0.724  (8s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[285/1560] LR        repeat 2 fold 1  macro-F1=0.6127  P1=0.160 R1=0.901  (1s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[286/1560] LR        repeat 2 fold 1  macro-F1=0.7834  P1=0.461 R1=0.773  (8s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[287/1560] LR        repeat 2 fold 1  macro-F1=0.5151  P1=0.078 R1=0.939  (1s)  [ratio 0.5, orig^1.25, C=0, rho=73.60]

[288/1560] LR        repeat 2 fold 1  macro-F1=0.7506  P1=0.375 R1=0.823  (8s)  [ratio 0.5, orig^1.25, C=1, rho=73.60]

[289/1560] LR        repeat 2 fold 1  macro-F1=0.3098  P1=0.029 R1=0.967  (1s)  [ratio 0.5, orig^1.5, C=0, rho=199.74]

[290/1560] LR        repeat 2 fold 1  macro-F1=0.7032  P1=0.285 R1=0.862  (3s)  [ratio 0.5, orig^1.5, C=1, rho=199.74]

[291/1560] LR        repeat 2 fold 1  macro-F1=0.0181  P1=0.018 R1=1.000  (1s)  [ratio 0.5, orig^2.0, C=0, rho=1471.16]

[292/1560] LR        repeat 2 fold 1  macro-F1=0.6103  P1=0.158 R1=0.967  (3s)  [ratio 0.5, orig^2.0, C=1, rho=1471.16]

[293/1560] LR        repeat 2 fold 1  macro-F1=0.7817  P1=0.440 R1=0.829  (2s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[294/1560] LR        repeat 2 fold 1  macro-F1=0.8140  P1=0.651 R1=0.619  (4s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[295/1560] LR        repeat 2 fold 1  macro-F1=0.7857  P1=0.449 R1=0.829  (7s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[296/1560] LR        repeat 2 fold 1  macro-F1=0.8112  P1=0.640 R1=0.619  (19s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[297/1560] LR        repeat 2 fold 1  macro-F1=0.7555  P1=0.379 R1=0.856  (7s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[298/1560] LR        repeat 2 fold 1  macro-F1=0.8184  P1=0.567 R1=0.746  (19s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[299/1560] LR        repeat 2 fold 1  macro-F1=0.7040  P1=0.287 R1=0.856  (7s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[300/1560] LR        repeat 2 fold 1  macro-F1=0.8024  P1=0.535 R1=0.718  (21s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[301/1560] LR        repeat 2 fold 1  macro-F1=0.6499  P1=0.205 R1=0.890  (1s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[302/1560] LR        repeat 2 fold 1  macro-F1=0.7906  P1=0.483 R1=0.762  (12s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[303/1560] LR        repeat 2 fold 1  macro-F1=0.5567  P1=0.107 R1=0.923  (1s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[304/1560] LR        repeat 2 fold 1  macro-F1=0.7702  P1=0.419 R1=0.812  (13s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[305/1560] LR        repeat 2 fold 1  macro-F1=0.4693  P1=0.057 R1=0.945  (1s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[306/1560] LR        repeat 2 fold 1  macro-F1=0.7215  P1=0.318 R1=0.840  (13s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[307/1560] LR        repeat 2 fold 1  macro-F1=0.2091  P1=0.023 R1=0.983  (1s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[308/1560] LR        repeat 2 fold 1  macro-F1=0.6861  P1=0.255 R1=0.906  (5s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[309/1560] LR        repeat 2 fold 1  macro-F1=0.0179  P1=0.018 R1=1.000  (1s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[310/1560] LR        repeat 2 fold 1  macro-F1=0.5267  P1=0.086 R1=0.978  (4s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[311/1560] LR        repeat 2 fold 1  macro-F1=0.7857  P1=0.449 R1=0.829  (3s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[312/1560] LR        repeat 2 fold 1  macro-F1=0.8112  P1=0.640 R1=0.619  (6s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[313/1560] LR        repeat 3 fold 0  macro-F1=0.8120  P1=0.764 R1=0.536  (1s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[314/1560] LR        repeat 3 fold 0  macro-F1=0.7980  P1=0.763 R1=0.497  (4s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[315/1560] LR        repeat 3 fold 0  macro-F1=0.8355  P1=0.731 R1=0.630  (1s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[316/1560] LR        repeat 3 fold 0  macro-F1=0.8398  P1=0.613 R1=0.779  (4s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[317/1560] LR        repeat 3 fold 0  macro-F1=0.8462  P1=0.665 R1=0.735  (1s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[318/1560] LR        repeat 3 fold 0  macro-F1=0.8523  P1=0.697 R1=0.724  (4s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[319/1560] LR        repeat 3 fold 0  macro-F1=0.8320  P1=0.578 R1=0.801  (1s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[320/1560] LR        repeat 3 fold 0  macro-F1=0.8375  P1=0.661 R1=0.702  (4s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[321/1560] LR        repeat 3 fold 0  macro-F1=0.7938  P1=0.466 R1=0.834  (1s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[322/1560] LR        repeat 3 fold 0  macro-F1=0.8229  P1=0.632 R1=0.674  (4s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[323/1560] LR        repeat 3 fold 0  macro-F1=0.7599  P1=0.383 R1=0.884  (1s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[324/1560] LR        repeat 3 fold 0  macro-F1=0.8209  P1=0.568 R1=0.757  (4s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[325/1560] LR        repeat 3 fold 0  macro-F1=0.7036  P1=0.282 R1=0.906  (1s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[326/1560] LR        repeat 3 fold 0  macro-F1=0.8137  P1=0.583 R1=0.696  (4s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[327/1560] LR        repeat 3 fold 0  macro-F1=0.4156  P1=0.043 R1=0.978  (1s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[328/1560] LR        repeat 3 fold 0  macro-F1=0.7681  P1=0.412 R1=0.823  (4s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[329/1560] LR        repeat 3 fold 0  macro-F1=0.8045  P1=0.530 R1=0.740  (7s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[330/1560] LR        repeat 3 fold 0  macro-F1=0.8174  P1=0.577 R1=0.724  (18s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[331/1560] LR        repeat 3 fold 0  macro-F1=0.7843  P1=0.471 R1=0.751  (7s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[332/1560] LR        repeat 3 fold 0  macro-F1=0.7993  P1=0.529 R1=0.713  (18s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[333/1560] LR        repeat 3 fold 0  macro-F1=0.7656  P1=0.417 R1=0.779  (7s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[334/1560] LR        repeat 3 fold 0  macro-F1=0.8038  P1=0.542 R1=0.713  (18s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[335/1560] LR        repeat 3 fold 0  macro-F1=0.7315  P1=0.343 R1=0.796  (2s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[336/1560] LR        repeat 3 fold 0  macro-F1=0.8103  P1=0.552 R1=0.729  (12s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[337/1560] LR        repeat 3 fold 0  macro-F1=0.6444  P1=0.199 R1=0.856  (1s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[338/1560] LR        repeat 3 fold 0  macro-F1=0.8072  P1=0.543 R1=0.729  (12s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[339/1560] LR        repeat 3 fold 0  macro-F1=0.5881  P1=0.134 R1=0.901  (1s)  [ratio 0.5, orig^1.25, C=0, rho=73.60]

[340/1560] LR        repeat 3 fold 0  macro-F1=0.7919  P1=0.480 R1=0.779  (11s)  [ratio 0.5, orig^1.25, C=1, rho=73.60]

[341/1560] LR        repeat 3 fold 0  macro-F1=0.5232  P1=0.082 R1=0.917  (1s)  [ratio 0.5, orig^1.5, C=0, rho=199.74]

[342/1560] LR        repeat 3 fold 0  macro-F1=0.7727  P1=0.426 R1=0.807  (4s)  [ratio 0.5, orig^1.5, C=1, rho=199.74]

[343/1560] LR        repeat 3 fold 0  macro-F1=0.1662  P1=0.021 R1=0.989  (1s)  [ratio 0.5, orig^2.0, C=0, rho=1471.16]

[344/1560] LR        repeat 3 fold 0  macro-F1=0.6959  P1=0.268 R1=0.928  (4s)  [ratio 0.5, orig^2.0, C=1, rho=1471.16]

[345/1560] LR        repeat 3 fold 0  macro-F1=0.7895  P1=0.484 R1=0.751  (2s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[346/1560] LR        repeat 3 fold 0  macro-F1=0.8047  P1=0.542 R1=0.718  (6s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[347/1560] LR        repeat 3 fold 0  macro-F1=0.7890  P1=0.487 R1=0.740  (8s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[348/1560] LR        repeat 3 fold 0  macro-F1=0.8047  P1=0.542 R1=0.718  (30s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[349/1560] LR        repeat 3 fold 0  macro-F1=0.7723  P1=0.439 R1=0.757  (9s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[350/1560] LR        repeat 3 fold 0  macro-F1=0.7994  P1=0.526 R1=0.718  (28s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[351/1560] LR        repeat 3 fold 0  macro-F1=0.7515  P1=0.386 R1=0.779  (11s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[352/1560] LR        repeat 3 fold 0  macro-F1=0.7978  P1=0.514 R1=0.735  (28s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[353/1560] LR        repeat 3 fold 0  macro-F1=0.6823  P1=0.254 R1=0.829  (2s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[354/1560] LR        repeat 3 fold 0  macro-F1=0.8157  P1=0.572 R1=0.724  (20s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[355/1560] LR        repeat 3 fold 0  macro-F1=0.6161  P1=0.164 R1=0.867  (1s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[356/1560] LR        repeat 3 fold 0  macro-F1=0.7992  P1=0.507 R1=0.757  (17s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[357/1560] LR        repeat 3 fold 0  macro-F1=0.5623  P1=0.111 R1=0.912  (1s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[358/1560] LR        repeat 3 fold 0  macro-F1=0.7885  P1=0.462 R1=0.807  (19s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[359/1560] LR        repeat 3 fold 0  macro-F1=0.4012  P1=0.039 R1=0.950  (1s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[360/1560] LR        repeat 3 fold 0  macro-F1=0.7458  P1=0.364 R1=0.834  (5s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[361/1560] LR        repeat 3 fold 0  macro-F1=0.1704  P1=0.022 R1=0.989  (1s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[362/1560] LR        repeat 3 fold 0  macro-F1=0.6731  P1=0.235 R1=0.928  (4s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[363/1560] LR        repeat 3 fold 0  macro-F1=0.7890  P1=0.487 R1=0.740  (3s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[364/1560] LR        repeat 3 fold 0  macro-F1=0.8047  P1=0.542 R1=0.718  (6s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[365/1560] LR        repeat 3 fold 1  macro-F1=0.8096  P1=0.628 R1=0.624  (1s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[366/1560] LR        repeat 3 fold 1  macro-F1=0.8093  P1=0.638 R1=0.613  (5s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[367/1560] LR        repeat 3 fold 1  macro-F1=0.8065  P1=0.579 R1=0.669  (2s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[368/1560] LR        repeat 3 fold 1  macro-F1=0.7959  P1=0.632 R1=0.569  (5s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[369/1560] LR        repeat 3 fold 1  macro-F1=0.7890  P1=0.502 R1=0.707  (2s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[370/1560] LR        repeat 3 fold 1  macro-F1=0.7973  P1=0.586 R1=0.619  (5s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[371/1560] LR        repeat 3 fold 1  macro-F1=0.7792  P1=0.454 R1=0.762  (2s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[372/1560] LR        repeat 3 fold 1  macro-F1=0.7918  P1=0.576 R1=0.608  (6s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[373/1560] LR        repeat 3 fold 1  macro-F1=0.7538  P1=0.390 R1=0.785  (2s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[374/1560] LR        repeat 3 fold 1  macro-F1=0.7929  P1=0.575 R1=0.613  (5s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[375/1560] LR        repeat 3 fold 1  macro-F1=0.7176  P1=0.312 R1=0.829  (2s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[376/1560] LR        repeat 3 fold 1  macro-F1=0.7954  P1=0.543 R1=0.669  (5s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[377/1560] LR        repeat 3 fold 1  macro-F1=0.6760  P1=0.243 R1=0.851  (2s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[378/1560] LR        repeat 3 fold 1  macro-F1=0.7801  P1=0.478 R1=0.707  (5s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[379/1560] LR        repeat 3 fold 1  macro-F1=0.5791  P1=0.125 R1=0.878  (1s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[380/1560] LR        repeat 3 fold 1  macro-F1=0.7474  P1=0.370 R1=0.818  (4s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[381/1560] LR        repeat 3 fold 1  macro-F1=0.7741  P1=0.427 R1=0.812  (7s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[382/1560] LR        repeat 3 fold 1  macro-F1=0.8080  P1=0.545 R1=0.729  (17s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[383/1560] LR        repeat 3 fold 1  macro-F1=0.7422  P1=0.356 R1=0.840  (7s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[384/1560] LR        repeat 3 fold 1  macro-F1=0.8032  P1=0.523 R1=0.746  (17s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[385/1560] LR        repeat 3 fold 1  macro-F1=0.6915  P1=0.266 R1=0.867  (6s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[386/1560] LR        repeat 3 fold 1  macro-F1=0.7995  P1=0.538 R1=0.696  (17s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[387/1560] LR        repeat 3 fold 1  macro-F1=0.6383  P1=0.190 R1=0.895  (1s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[388/1560] LR        repeat 3 fold 1  macro-F1=0.7958  P1=0.498 R1=0.757  (11s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[389/1560] LR        repeat 3 fold 1  macro-F1=0.5701  P1=0.118 R1=0.950  (1s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[390/1560] LR        repeat 3 fold 1  macro-F1=0.7714  P1=0.416 R1=0.834  (11s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[391/1560] LR        repeat 3 fold 1  macro-F1=0.4063  P1=0.041 R1=0.978  (1s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[392/1560] LR        repeat 3 fold 1  macro-F1=0.7368  P1=0.340 R1=0.884  (11s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[393/1560] LR        repeat 3 fold 1  macro-F1=0.0716  P1=0.019 R1=0.994  (1s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[394/1560] LR        repeat 3 fold 1  macro-F1=0.7064  P1=0.285 R1=0.917  (4s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[395/1560] LR        repeat 3 fold 1  macro-F1=0.0178  P1=0.018 R1=1.000  (1s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[396/1560] LR        repeat 3 fold 1  macro-F1=0.6986  P1=0.272 R1=0.934  (4s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[397/1560] LR        repeat 3 fold 1  macro-F1=0.7527  P1=0.378 R1=0.834  (1s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[398/1560] LR        repeat 3 fold 1  macro-F1=0.8066  P1=0.538 R1=0.735  (5s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[399/1560] LR        repeat 3 fold 1  macro-F1=0.7522  P1=0.377 R1=0.834  (11s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[400/1560] LR        repeat 3 fold 1  macro-F1=0.8089  P1=0.545 R1=0.735  (25s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[401/1560] LR        repeat 3 fold 1  macro-F1=0.7124  P1=0.300 R1=0.856  (11s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[402/1560] LR        repeat 3 fold 1  macro-F1=0.7993  P1=0.518 R1=0.735  (26s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[403/1560] LR        repeat 3 fold 1  macro-F1=0.6586  P1=0.217 R1=0.878  (11s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[404/1560] LR        repeat 3 fold 1  macro-F1=0.7947  P1=0.485 R1=0.785  (23s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[405/1560] LR        repeat 3 fold 1  macro-F1=0.5990  P1=0.145 R1=0.912  (1s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[406/1560] LR        repeat 3 fold 1  macro-F1=0.7793  P1=0.442 R1=0.801  (15s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[407/1560] LR        repeat 3 fold 1  macro-F1=0.4982  P1=0.070 R1=0.961  (1s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[408/1560] LR        repeat 3 fold 1  macro-F1=0.7445  P1=0.357 R1=0.862  (15s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[409/1560] LR        repeat 3 fold 1  macro-F1=0.2463  P1=0.025 R1=0.994  (1s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[410/1560] LR        repeat 3 fold 1  macro-F1=0.7145  P1=0.300 R1=0.901  (14s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[411/1560] LR        repeat 3 fold 1  macro-F1=0.0180  P1=0.018 R1=1.000  (1s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[412/1560] LR        repeat 3 fold 1  macro-F1=0.6810  P1=0.246 R1=0.939  (3s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[413/1560] LR        repeat 3 fold 1  macro-F1=0.0178  P1=0.018 R1=1.000  (1s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[414/1560] LR        repeat 3 fold 1  macro-F1=0.7601  P1=0.387 R1=0.862  (3s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[415/1560] LR        repeat 3 fold 1  macro-F1=0.7522  P1=0.377 R1=0.834  (1s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[416/1560] LR        repeat 3 fold 1  macro-F1=0.8089  P1=0.545 R1=0.735  (3s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[417/1560] LR        repeat 4 fold 0  macro-F1=0.8511  P1=0.744 R1=0.674  (1s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[418/1560] LR        repeat 4 fold 0  macro-F1=0.8529  P1=0.715 R1=0.707  (3s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[419/1560] LR        repeat 4 fold 0  macro-F1=0.8441  P1=0.686 R1=0.702  (1s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[420/1560] LR        repeat 4 fold 0  macro-F1=0.8393  P1=0.668 R1=0.702  (4s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[421/1560] LR        repeat 4 fold 0  macro-F1=0.8224  P1=0.583 R1=0.740  (1s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[422/1560] LR        repeat 4 fold 0  macro-F1=0.8365  P1=0.658 R1=0.702  (4s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[423/1560] LR        repeat 4 fold 0  macro-F1=0.8106  P1=0.526 R1=0.785  (1s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[424/1560] LR        repeat 4 fold 0  macro-F1=0.8208  P1=0.574 R1=0.746  (4s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[425/1560] LR        repeat 4 fold 0  macro-F1=0.7925  P1=0.475 R1=0.796  (1s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[426/1560] LR        repeat 4 fold 0  macro-F1=0.8299  P1=0.603 R1=0.746  (4s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[427/1560] LR        repeat 4 fold 0  macro-F1=0.7691  P1=0.416 R1=0.812  (1s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[428/1560] LR        repeat 4 fold 0  macro-F1=0.8308  P1=0.617 R1=0.729  (4s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[429/1560] LR        repeat 4 fold 0  macro-F1=0.7361  P1=0.343 R1=0.851  (1s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[430/1560] LR        repeat 4 fold 0  macro-F1=0.8173  P1=0.542 R1=0.790  (3s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[431/1560] LR        repeat 4 fold 0  macro-F1=0.6448  P1=0.198 R1=0.906  (1s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[432/1560] LR        repeat 4 fold 0  macro-F1=0.7979  P1=0.487 R1=0.801  (3s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[433/1560] LR        repeat 4 fold 0  macro-F1=0.8083  P1=0.509 R1=0.812  (6s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[434/1560] LR        repeat 4 fold 0  macro-F1=0.8428  P1=0.637 R1=0.757  (11s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[435/1560] LR        repeat 4 fold 0  macro-F1=0.7827  P1=0.439 R1=0.840  (5s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[436/1560] LR        repeat 4 fold 0  macro-F1=0.8324  P1=0.607 R1=0.751  (12s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[437/1560] LR        repeat 4 fold 0  macro-F1=0.7497  P1=0.366 R1=0.867  (4s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[438/1560] LR        repeat 4 fold 0  macro-F1=0.8226  P1=0.562 R1=0.779  (12s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[439/1560] LR        repeat 4 fold 0  macro-F1=0.7028  P1=0.281 R1=0.895  (1s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[440/1560] LR        repeat 4 fold 0  macro-F1=0.8249  P1=0.581 R1=0.757  (8s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[441/1560] LR        repeat 4 fold 0  macro-F1=0.6505  P1=0.205 R1=0.928  (1s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[442/1560] LR        repeat 4 fold 0  macro-F1=0.7999  P1=0.500 R1=0.779  (8s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[443/1560] LR        repeat 4 fold 0  macro-F1=0.5943  P1=0.141 R1=0.956  (1s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[444/1560] LR        repeat 4 fold 0  macro-F1=0.7647  P1=0.403 R1=0.829  (8s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[445/1560] LR        repeat 4 fold 0  macro-F1=0.4972  P1=0.070 R1=0.978  (1s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[446/1560] LR        repeat 4 fold 0  macro-F1=0.7379  P1=0.340 R1=0.901  (3s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[447/1560] LR        repeat 4 fold 0  macro-F1=0.0180  P1=0.018 R1=1.000  (1s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[448/1560] LR        repeat 4 fold 0  macro-F1=0.6352  P1=0.186 R1=0.961  (3s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[449/1560] LR        repeat 4 fold 0  macro-F1=0.7902  P1=0.463 R1=0.818  (1s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[450/1560] LR        repeat 4 fold 0  macro-F1=0.8367  P1=0.621 R1=0.751  (4s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[451/1560] LR        repeat 4 fold 0  macro-F1=0.7933  P1=0.470 R1=0.818  (7s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[452/1560] LR        repeat 4 fold 0  macro-F1=0.8333  P1=0.610 R1=0.751  (23s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[453/1560] LR        repeat 4 fold 0  macro-F1=0.7632  P1=0.394 R1=0.856  (9s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[454/1560] LR        repeat 4 fold 0  macro-F1=0.8428  P1=0.637 R1=0.757  (27s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[455/1560] LR        repeat 4 fold 0  macro-F1=0.7253  P1=0.319 R1=0.890  (8s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[456/1560] LR        repeat 4 fold 0  macro-F1=0.8113  P1=0.528 R1=0.785  (26s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[457/1560] LR        repeat 4 fold 0  macro-F1=0.6734  P1=0.236 R1=0.912  (1s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[458/1560] LR        repeat 4 fold 0  macro-F1=0.8089  P1=0.526 R1=0.773  (18s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[459/1560] LR        repeat 4 fold 0  macro-F1=0.6184  P1=0.166 R1=0.939  (1s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[460/1560] LR        repeat 4 fold 0  macro-F1=0.7816  P1=0.448 R1=0.801  (18s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[461/1560] LR        repeat 4 fold 0  macro-F1=0.5509  P1=0.103 R1=0.967  (1s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[462/1560] LR        repeat 4 fold 0  macro-F1=0.7500  P1=0.365 R1=0.878  (17s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[463/1560] LR        repeat 4 fold 0  macro-F1=0.4027  P1=0.040 R1=0.978  (1s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[464/1560] LR        repeat 4 fold 0  macro-F1=0.7092  P1=0.290 R1=0.917  (5s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[465/1560] LR        repeat 4 fold 0  macro-F1=0.0179  P1=0.018 R1=1.000  (1s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[466/1560] LR        repeat 4 fold 0  macro-F1=0.5752  P1=0.123 R1=0.978  (4s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[467/1560] LR        repeat 4 fold 0  macro-F1=0.7933  P1=0.470 R1=0.818  (2s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[468/1560] LR        repeat 4 fold 0  macro-F1=0.8333  P1=0.610 R1=0.751  (5s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[469/1560] LR        repeat 4 fold 1  macro-F1=0.8211  P1=0.743 R1=0.575  (1s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[470/1560] LR        repeat 4 fold 1  macro-F1=0.8213  P1=0.711 R1=0.597  (5s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[471/1560] LR        repeat 4 fold 1  macro-F1=0.8256  P1=0.652 R1=0.663  (2s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[472/1560] LR        repeat 4 fold 1  macro-F1=0.8243  P1=0.750 R1=0.580  (5s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[473/1560] LR        repeat 4 fold 1  macro-F1=0.8163  P1=0.584 R1=0.707  (2s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[474/1560] LR        repeat 4 fold 1  macro-F1=0.8226  P1=0.681 R1=0.624  (5s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[475/1560] LR        repeat 4 fold 1  macro-F1=0.7977  P1=0.506 R1=0.751  (2s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[476/1560] LR        repeat 4 fold 1  macro-F1=0.8067  P1=0.697 R1=0.558  (5s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[477/1560] LR        repeat 4 fold 1  macro-F1=0.7817  P1=0.440 R1=0.829  (2s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[478/1560] LR        repeat 4 fold 1  macro-F1=0.8199  P1=0.652 R1=0.641  (5s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[479/1560] LR        repeat 4 fold 1  macro-F1=0.7456  P1=0.357 R1=0.878  (1s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[480/1560] LR        repeat 4 fold 1  macro-F1=0.8083  P1=0.607 R1=0.641  (5s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[481/1560] LR        repeat 4 fold 1  macro-F1=0.6940  P1=0.267 R1=0.901  (1s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[482/1560] LR        repeat 4 fold 1  macro-F1=0.7968  P1=0.537 R1=0.685  (5s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[483/1560] LR        repeat 4 fold 1  macro-F1=0.5034  P1=0.073 R1=0.967  (1s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[484/1560] LR        repeat 4 fold 1  macro-F1=0.7738  P1=0.428 R1=0.807  (4s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[485/1560] LR        repeat 4 fold 1  macro-F1=0.7966  P1=0.483 R1=0.801  (7s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[486/1560] LR        repeat 4 fold 1  macro-F1=0.8213  P1=0.718 R1=0.591  (16s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[487/1560] LR        repeat 4 fold 1  macro-F1=0.7672  P1=0.397 R1=0.884  (6s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[488/1560] LR        repeat 4 fold 1  macro-F1=0.8186  P1=0.677 R1=0.613  (18s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[489/1560] LR        repeat 4 fold 1  macro-F1=0.7152  P1=0.300 R1=0.906  (7s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[490/1560] LR        repeat 4 fold 1  macro-F1=0.8110  P1=0.557 R1=0.724  (17s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[491/1560] LR        repeat 4 fold 1  macro-F1=0.6601  P1=0.218 R1=0.934  (1s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[492/1560] LR        repeat 4 fold 1  macro-F1=0.7964  P1=0.510 R1=0.735  (11s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[493/1560] LR        repeat 4 fold 1  macro-F1=0.5776  P1=0.125 R1=0.972  (1s)  [ratio 0.5, orig^1.0, C=0, rho=27.11]

[494/1560] LR        repeat 4 fold 1  macro-F1=0.7850  P1=0.457 R1=0.796  (11s)  [ratio 0.5, orig^1.0, C=1, rho=27.11]

[495/1560] LR        repeat 4 fold 1  macro-F1=0.2212  P1=0.024 R1=0.994  (1s)  [ratio 0.5, orig^1.25, C=0, rho=73.58]

[496/1560] LR        repeat 4 fold 1  macro-F1=0.7627  P1=0.390 R1=0.873  (11s)  [ratio 0.5, orig^1.25, C=1, rho=73.58]

[497/1560] LR        repeat 4 fold 1  macro-F1=0.0351  P1=0.018 R1=1.000  (1s)  [ratio 0.5, orig^1.5, C=0, rho=199.70]

[498/1560] LR        repeat 4 fold 1  macro-F1=0.7275  P1=0.321 R1=0.901  (4s)  [ratio 0.5, orig^1.5, C=1, rho=199.70]

[499/1560] LR        repeat 4 fold 1  macro-F1=0.0179  P1=0.018 R1=1.000  (1s)  [ratio 0.5, orig^2.0, C=0, rho=1470.86]

[500/1560] LR        repeat 4 fold 1  macro-F1=0.7130  P1=0.296 R1=0.912  (4s)  [ratio 0.5, orig^2.0, C=1, rho=1470.86]

[501/1560] LR        repeat 4 fold 1  macro-F1=0.7805  P1=0.428 R1=0.867  (1s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[502/1560] LR        repeat 4 fold 1  macro-F1=0.8224  P1=0.708 R1=0.602  (5s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[503/1560] LR        repeat 4 fold 1  macro-F1=0.7780  P1=0.421 R1=0.873  (11s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[504/1560] LR        repeat 4 fold 1  macro-F1=0.8265  P1=0.712 R1=0.613  (26s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[505/1560] LR        repeat 4 fold 1  macro-F1=0.7340  P1=0.333 R1=0.901  (11s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[506/1560] LR        repeat 4 fold 1  macro-F1=0.8093  P1=0.556 R1=0.718  (26s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[507/1560] LR        repeat 4 fold 1  macro-F1=0.6797  P1=0.245 R1=0.917  (11s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[508/1560] LR        repeat 4 fold 1  macro-F1=0.8002  P1=0.528 R1=0.718  (26s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[509/1560] LR        repeat 4 fold 1  macro-F1=0.6141  P1=0.162 R1=0.950  (1s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[510/1560] LR        repeat 4 fold 1  macro-F1=0.7893  P1=0.473 R1=0.779  (17s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[511/1560] LR        repeat 4 fold 1  macro-F1=0.3750  P1=0.036 R1=0.983  (1s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[512/1560] LR        repeat 4 fold 1  macro-F1=0.7696  P1=0.408 R1=0.851  (15s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[513/1560] LR        repeat 4 fold 1  macro-F1=0.0941  P1=0.020 R1=1.000  (1s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[514/1560] LR        repeat 4 fold 1  macro-F1=0.7360  P1=0.338 R1=0.890  (16s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[515/1560] LR        repeat 4 fold 1  macro-F1=0.0189  P1=0.018 R1=1.000  (1s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[516/1560] LR        repeat 4 fold 1  macro-F1=0.6973  P1=0.271 R1=0.928  (4s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[517/1560] LR        repeat 4 fold 1  macro-F1=0.0178  P1=0.018 R1=1.000  (1s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[518/1560] LR        repeat 4 fold 1  macro-F1=0.7515  P1=0.373 R1=0.845  (4s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[519/1560] LR        repeat 4 fold 1  macro-F1=0.7780  P1=0.421 R1=0.873  (2s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[520/1560] LR        repeat 4 fold 1  macro-F1=0.8265  P1=0.712 R1=0.613  (4s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[521/1560] RF        repeat 0 fold 0  macro-F1=0.8551  P1=0.826 R1=0.630  (24s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[522/1560] RF        repeat 0 fold 0  macro-F1=0.8662  P1=0.709 R1=0.768  (58s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[523/1560] RF        repeat 0 fold 0  macro-F1=0.8648  P1=0.751 R1=0.718  (24s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[524/1560] RF        repeat 0 fold 0  macro-F1=0.8702  P1=0.739 R1=0.751  (59s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[525/1560] RF        repeat 0 fold 0  macro-F1=0.8368  P1=0.680 R1=0.680  (21s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[526/1560] RF        repeat 0 fold 0  macro-F1=0.8394  P1=0.599 R1=0.801  (53s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[527/1560] RF        repeat 0 fold 0  macro-F1=0.8076  P1=0.536 R1=0.746  (16s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[528/1560] RF        repeat 0 fold 0  macro-F1=0.8075  P1=0.522 R1=0.773  (44s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[529/1560] RF        repeat 0 fold 0  macro-F1=0.7660  P1=0.414 R1=0.796  (13s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[530/1560] RF        repeat 0 fold 0  macro-F1=0.7635  P1=0.417 R1=0.762  (33s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[531/1560] RF        repeat 0 fold 0  macro-F1=0.7493  P1=0.365 R1=0.867  (7s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[532/1560] RF        repeat 0 fold 0  macro-F1=0.7562  P1=0.422 R1=0.691  (23s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[533/1560] RF        repeat 0 fold 0  macro-F1=0.7246  P1=0.317 R1=0.901  (5s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[534/1560] RF        repeat 0 fold 0  macro-F1=0.7457  P1=0.386 R1=0.729  (26s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[535/1560] RF        repeat 0 fold 0  macro-F1=0.6662  P1=0.225 R1=0.945  (4s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[536/1560] RF        repeat 0 fold 0  macro-F1=0.7296  P1=0.333 R1=0.834  (17s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[537/1560] RF        repeat 0 fold 0  macro-F1=0.8273  P1=0.564 R1=0.801  (36s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[538/1560] RF        repeat 0 fold 0  macro-F1=0.8273  P1=0.567 R1=0.796  (89s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[539/1560] RF        repeat 0 fold 0  macro-F1=0.8075  P1=0.495 R1=0.845  (34s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[540/1560] RF        repeat 0 fold 0  macro-F1=0.8162  P1=0.555 R1=0.757  (104s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[541/1560] RF        repeat 0 fold 0  macro-F1=0.7583  P1=0.376 R1=0.906  (35s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[542/1560] RF        repeat 0 fold 0  macro-F1=0.7963  P1=0.520 R1=0.713  (86s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[543/1560] RF        repeat 0 fold 0  macro-F1=0.7034  P1=0.279 R1=0.934  (21s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[544/1560] RF        repeat 0 fold 0  macro-F1=0.7954  P1=0.543 R1=0.669  (75s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[545/1560] RF        repeat 0 fold 0  macro-F1=0.6641  P1=0.222 R1=0.961  (19s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[546/1560] RF        repeat 0 fold 0  macro-F1=0.7709  P1=0.493 R1=0.624  (59s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[547/1560] RF        repeat 0 fold 0  macro-F1=0.6101  P1=0.157 R1=0.989  (15s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[548/1560] RF        repeat 0 fold 0  macro-F1=0.7354  P1=0.370 R1=0.702  (44s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[549/1560] RF        repeat 0 fold 0  macro-F1=0.5468  P1=0.101 R1=0.989  (13s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[550/1560] RF        repeat 0 fold 0  macro-F1=0.7251  P1=0.356 R1=0.669  (35s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[551/1560] RF        repeat 0 fold 0  macro-F1=0.1639  P1=0.022 R1=1.000  (9s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[552/1560] RF        repeat 0 fold 0  macro-F1=0.6878  P1=0.272 R1=0.729  (21s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[553/1560] RF        repeat 0 fold 0  macro-F1=0.8082  P1=0.510 R1=0.807  (30s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[554/1560] RF        repeat 0 fold 0  macro-F1=0.8154  P1=0.552 R1=0.757  (72s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[555/1560] RF        repeat 0 fold 0  macro-F1=0.8173  P1=0.542 R1=0.790  (47s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[556/1560] RF        repeat 0 fold 0  macro-F1=0.8300  P1=0.614 R1=0.729  (125s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[557/1560] RF        repeat 0 fold 0  macro-F1=0.7842  P1=0.444 R1=0.834  (53s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[558/1560] RF        repeat 0 fold 0  macro-F1=0.7970  P1=0.559 R1=0.652  (138s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[559/1560] RF        repeat 0 fold 0  macro-F1=0.7374  P1=0.336 R1=0.923  (49s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[560/1560] RF        repeat 0 fold 0  macro-F1=0.7929  P1=0.549 R1=0.646  (119s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[561/1560] RF        repeat 0 fold 0  macro-F1=0.6866  P1=0.254 R1=0.945  (33s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[562/1560] RF        repeat 0 fold 0  macro-F1=0.7829  P1=0.511 R1=0.657  (104s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[563/1560] RF        repeat 0 fold 0  macro-F1=0.6388  P1=0.190 R1=0.978  (25s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[564/1560] RF        repeat 0 fold 0  macro-F1=0.7538  P1=0.443 R1=0.624  (78s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[565/1560] RF        repeat 0 fold 0  macro-F1=0.5825  P1=0.130 R1=0.989  (19s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[566/1560] RF        repeat 0 fold 0  macro-F1=0.7172  P1=0.324 R1=0.740  (65s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[567/1560] RF        repeat 0 fold 0  macro-F1=0.5187  P1=0.082 R1=0.989  (15s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[568/1560] RF        repeat 0 fold 0  macro-F1=0.7318  P1=0.396 R1=0.597  (44s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[569/1560] RF        repeat 0 fold 0  macro-F1=0.1368  P1=0.021 R1=1.000  (8s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[570/1560] RF        repeat 0 fold 0  macro-F1=0.6818  P1=0.263 R1=0.724  (25s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[571/1560] RF        repeat 0 fold 0  macro-F1=0.8173  P1=0.542 R1=0.790  (37s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[572/1560] RF        repeat 0 fold 0  macro-F1=0.8300  P1=0.614 R1=0.729  (110s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[573/1560] RF        repeat 0 fold 1  macro-F1=0.8489  P1=0.822 R1=0.613  (31s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[574/1560] RF        repeat 0 fold 1  macro-F1=0.8476  P1=0.717 R1=0.685  (72s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[575/1560] RF        repeat 0 fold 1  macro-F1=0.8508  P1=0.771 R1=0.652  (28s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[576/1560] RF        repeat 0 fold 1  macro-F1=0.8551  P1=0.755 R1=0.680  (74s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[577/1560] RF        repeat 0 fold 1  macro-F1=0.8547  P1=0.774 R1=0.663  (23s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[578/1560] RF        repeat 0 fold 1  macro-F1=0.8403  P1=0.605 R1=0.796  (60s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[579/1560] RF        repeat 0 fold 1  macro-F1=0.8292  P1=0.641 R1=0.691  (20s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[580/1560] RF        repeat 0 fold 1  macro-F1=0.8257  P1=0.555 R1=0.812  (47s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[581/1560] RF        repeat 0 fold 1  macro-F1=0.7987  P1=0.504 R1=0.762  (14s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[582/1560] RF        repeat 0 fold 1  macro-F1=0.7996  P1=0.504 R1=0.768  (31s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[583/1560] RF        repeat 0 fold 1  macro-F1=0.7776  P1=0.425 R1=0.851  (8s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[584/1560] RF        repeat 0 fold 1  macro-F1=0.7799  P1=0.447 R1=0.790  (23s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[585/1560] RF        repeat 0 fold 1  macro-F1=0.7505  P1=0.367 R1=0.873  (5s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[586/1560] RF        repeat 0 fold 1  macro-F1=0.7838  P1=0.454 R1=0.796  (15s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[587/1560] RF        repeat 0 fold 1  macro-F1=0.6849  P1=0.251 R1=0.939  (3s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[588/1560] RF        repeat 0 fold 1  macro-F1=0.7650  P1=0.416 R1=0.779  (10s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[589/1560] RF        repeat 0 fold 1  macro-F1=0.8444  P1=0.663 R1=0.729  (24s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[590/1560] RF        repeat 0 fold 1  macro-F1=0.8456  P1=0.677 R1=0.718  (66s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[591/1560] RF        repeat 0 fold 1  macro-F1=0.8265  P1=0.576 R1=0.773  (26s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[592/1560] RF        repeat 0 fold 1  macro-F1=0.8257  P1=0.620 R1=0.702  (76s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[593/1560] RF        repeat 0 fold 1  macro-F1=0.7879  P1=0.461 R1=0.807  (24s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[594/1560] RF        repeat 0 fold 1  macro-F1=0.8150  P1=0.604 R1=0.674  (74s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[595/1560] RF        repeat 0 fold 1  macro-F1=0.7488  P1=0.360 R1=0.895  (18s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[596/1560] RF        repeat 0 fold 1  macro-F1=0.7977  P1=0.550 R1=0.669  (66s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[597/1560] RF        repeat 0 fold 1  macro-F1=0.6918  P1=0.263 R1=0.923  (15s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[598/1560] RF        repeat 0 fold 1  macro-F1=0.7704  P1=0.461 R1=0.685  (57s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[599/1560] RF        repeat 0 fold 1  macro-F1=0.6280  P1=0.177 R1=0.956  (14s)  [ratio 0.5, orig^1.25, C=0, rho=73.60]

[600/1560] RF        repeat 0 fold 1  macro-F1=0.7571  P1=0.444 R1=0.641  (56s)  [ratio 0.5, orig^1.25, C=1, rho=73.60]

[601/1560] RF        repeat 0 fold 1  macro-F1=0.5702  P1=0.119 R1=0.967  (14s)  [ratio 0.5, orig^1.5, C=0, rho=199.74]

[602/1560] RF        repeat 0 fold 1  macro-F1=0.7632  P1=0.459 R1=0.646  (41s)  [ratio 0.5, orig^1.5, C=1, rho=199.74]

[603/1560] RF        repeat 0 fold 1  macro-F1=0.3595  P1=0.034 R1=0.983  (11s)  [ratio 0.5, orig^2.0, C=0, rho=1471.16]

[604/1560] RF        repeat 0 fold 1  macro-F1=0.7369  P1=0.378 R1=0.685  (28s)  [ratio 0.5, orig^2.0, C=1, rho=1471.16]

[605/1560] RF        repeat 0 fold 1  macro-F1=0.8257  P1=0.593 R1=0.740  (29s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[606/1560] RF        repeat 0 fold 1  macro-F1=0.8300  P1=0.622 R1=0.718  (72s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[607/1560] RF        repeat 0 fold 1  macro-F1=0.8353  P1=0.636 R1=0.724  (47s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[608/1560] RF        repeat 0 fold 1  macro-F1=0.8386  P1=0.676 R1=0.691  (128s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[609/1560] RF        repeat 0 fold 1  macro-F1=0.8032  P1=0.523 R1=0.746  (65s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[610/1560] RF        repeat 0 fold 1  macro-F1=0.8189  P1=0.589 R1=0.713  (149s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[611/1560] RF        repeat 0 fold 1  macro-F1=0.7770  P1=0.424 R1=0.851  (66s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[612/1560] RF        repeat 0 fold 1  macro-F1=0.7942  P1=0.523 R1=0.696  (134s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[613/1560] RF        repeat 0 fold 1  macro-F1=0.7203  P1=0.309 R1=0.901  (47s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[614/1560] RF        repeat 0 fold 1  macro-F1=0.7838  P1=0.520 R1=0.646  (105s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[615/1560] RF        repeat 0 fold 1  macro-F1=0.6606  P1=0.218 R1=0.934  (30s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[616/1560] RF        repeat 0 fold 1  macro-F1=0.7614  P1=0.484 R1=0.591  (87s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[617/1560] RF        repeat 0 fold 1  macro-F1=0.6017  P1=0.149 R1=0.967  (22s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[618/1560] RF        repeat 0 fold 1  macro-F1=0.7426  P1=0.422 R1=0.602  (70s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[619/1560] RF        repeat 0 fold 1  macro-F1=0.5438  P1=0.098 R1=0.967  (18s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[620/1560] RF        repeat 0 fold 1  macro-F1=0.7495  P1=0.431 R1=0.624  (49s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[621/1560] RF        repeat 0 fold 1  macro-F1=0.2845  P1=0.027 R1=0.994  (10s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[622/1560] RF        repeat 0 fold 1  macro-F1=0.7090  P1=0.470 R1=0.392  (28s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[623/1560] RF        repeat 0 fold 1  macro-F1=0.8353  P1=0.636 R1=0.724  (38s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[624/1560] RF        repeat 0 fold 1  macro-F1=0.8386  P1=0.676 R1=0.691  (96s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[625/1560] RF        repeat 1 fold 0  macro-F1=0.8219  P1=0.798 R1=0.547  (24s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[626/1560] RF        repeat 1 fold 0  macro-F1=0.8394  P1=0.674 R1=0.696  (58s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[627/1560] RF        repeat 1 fold 0  macro-F1=0.8285  P1=0.713 R1=0.619  (23s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[628/1560] RF        repeat 1 fold 0  macro-F1=0.8436  P1=0.665 R1=0.724  (56s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[629/1560] RF        repeat 1 fold 0  macro-F1=0.8095  P1=0.671 R1=0.586  (19s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[630/1560] RF        repeat 1 fold 0  macro-F1=0.8291  P1=0.611 R1=0.729  (48s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[631/1560] RF        repeat 1 fold 0  macro-F1=0.8057  P1=0.654 R1=0.586  (14s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[632/1560] RF        repeat 1 fold 0  macro-F1=0.8017  P1=0.598 R1=0.624  (35s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[633/1560] RF        repeat 1 fold 0  macro-F1=0.7943  P1=0.571 R1=0.624  (10s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[634/1560] RF        repeat 1 fold 0  macro-F1=0.7951  P1=0.535 R1=0.680  (25s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[635/1560] RF        repeat 1 fold 0  macro-F1=0.7871  P1=0.502 R1=0.696  (6s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[636/1560] RF        repeat 1 fold 0  macro-F1=0.7892  P1=0.500 R1=0.713  (17s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[637/1560] RF        repeat 1 fold 0  macro-F1=0.7714  P1=0.416 R1=0.834  (4s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[638/1560] RF        repeat 1 fold 0  macro-F1=0.7749  P1=0.478 R1=0.674  (12s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[639/1560] RF        repeat 1 fold 0  macro-F1=0.6661  P1=0.224 R1=0.972  (2s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[640/1560] RF        repeat 1 fold 0  macro-F1=0.7670  P1=0.450 R1=0.691  (8s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[641/1560] RF        repeat 1 fold 0  macro-F1=0.8360  P1=0.626 R1=0.740  (23s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[642/1560] RF        repeat 1 fold 0  macro-F1=0.8199  P1=0.652 R1=0.641  (65s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[643/1560] RF        repeat 1 fold 0  macro-F1=0.8155  P1=0.550 R1=0.762  (25s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[644/1560] RF        repeat 1 fold 0  macro-F1=0.8122  P1=0.644 R1=0.619  (72s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[645/1560] RF        repeat 1 fold 0  macro-F1=0.7953  P1=0.462 R1=0.862  (24s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[646/1560] RF        repeat 1 fold 0  macro-F1=0.7922  P1=0.498 R1=0.735  (70s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[647/1560] RF        repeat 1 fold 0  macro-F1=0.7425  P1=0.344 R1=0.928  (18s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[648/1560] RF        repeat 1 fold 0  macro-F1=0.7913  P1=0.491 R1=0.746  (58s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[649/1560] RF        repeat 1 fold 0  macro-F1=0.6763  P1=0.239 R1=0.950  (15s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[650/1560] RF        repeat 1 fold 0  macro-F1=0.7743  P1=0.462 R1=0.707  (50s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[651/1560] RF        repeat 1 fold 0  macro-F1=0.6241  P1=0.173 R1=0.972  (14s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[652/1560] RF        repeat 1 fold 0  macro-F1=0.7552  P1=0.401 R1=0.751  (43s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[653/1560] RF        repeat 1 fold 0  macro-F1=0.5687  P1=0.118 R1=0.989  (11s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[654/1560] RF        repeat 1 fold 0  macro-F1=0.7385  P1=0.394 R1=0.646  (32s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[655/1560] RF        repeat 1 fold 0  macro-F1=0.3005  P1=0.029 R1=0.994  (7s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[656/1560] RF        repeat 1 fold 0  macro-F1=0.7151  P1=0.327 R1=0.702  (20s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[657/1560] RF        repeat 1 fold 0  macro-F1=0.8257  P1=0.580 R1=0.762  (25s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[658/1560] RF        repeat 1 fold 0  macro-F1=0.8257  P1=0.580 R1=0.762  (69s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[659/1560] RF        repeat 1 fold 0  macro-F1=0.8240  P1=0.598 R1=0.724  (49s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[660/1560] RF        repeat 1 fold 0  macro-F1=0.8234  P1=0.553 R1=0.801  (123s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[661/1560] RF        repeat 1 fold 0  macro-F1=0.8071  P1=0.514 R1=0.790  (53s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[662/1560] RF        repeat 1 fold 0  macro-F1=0.8055  P1=0.502 R1=0.812  (134s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[663/1560] RF        repeat 1 fold 0  macro-F1=0.7766  P1=0.415 R1=0.890  (48s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[664/1560] RF        repeat 1 fold 0  macro-F1=0.7917  P1=0.488 R1=0.757  (117s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[665/1560] RF        repeat 1 fold 0  macro-F1=0.7090  P1=0.288 R1=0.939  (44s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[666/1560] RF        repeat 1 fold 0  macro-F1=0.7805  P1=0.461 R1=0.751  (97s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[667/1560] RF        repeat 1 fold 0  macro-F1=0.6528  P1=0.207 R1=0.956  (29s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[668/1560] RF        repeat 1 fold 0  macro-F1=0.7731  P1=0.455 R1=0.718  (78s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[669/1560] RF        repeat 1 fold 0  macro-F1=0.5999  P1=0.147 R1=0.983  (21s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[670/1560] RF        repeat 1 fold 0  macro-F1=0.7605  P1=0.478 R1=0.597  (61s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[671/1560] RF        repeat 1 fold 0  macro-F1=0.5393  P1=0.095 R1=0.989  (16s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[672/1560] RF        repeat 1 fold 0  macro-F1=0.7265  P1=0.438 R1=0.492  (43s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[673/1560] RF        repeat 1 fold 0  macro-F1=0.2458  P1=0.025 R1=0.994  (9s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[674/1560] RF        repeat 1 fold 0  macro-F1=0.7153  P1=0.312 R1=0.801  (23s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[675/1560] RF        repeat 1 fold 0  macro-F1=0.8240  P1=0.598 R1=0.724  (33s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[676/1560] RF        repeat 1 fold 0  macro-F1=0.8234  P1=0.553 R1=0.801  (94s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[677/1560] RF        repeat 1 fold 1  macro-F1=0.8460  P1=0.837 R1=0.597  (11s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[678/1560] RF        repeat 1 fold 1  macro-F1=0.8614  P1=0.732 R1=0.724  (31s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[679/1560] RF        repeat 1 fold 1  macro-F1=0.8729  P1=0.837 R1=0.680  (11s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[680/1560] RF        repeat 1 fold 1  macro-F1=0.8532  P1=0.656 R1=0.779  (30s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[681/1560] RF        repeat 1 fold 1  macro-F1=0.8613  P1=0.805 R1=0.663  (9s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[682/1560] RF        repeat 1 fold 1  macro-F1=0.8529  P1=0.634 R1=0.812  (26s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[683/1560] RF        repeat 1 fold 1  macro-F1=0.8401  P1=0.662 R1=0.713  (7s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[684/1560] RF        repeat 1 fold 1  macro-F1=0.8358  P1=0.614 R1=0.757  (21s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[685/1560] RF        repeat 1 fold 1  macro-F1=0.7906  P1=0.471 R1=0.796  (5s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[686/1560] RF        repeat 1 fold 1  macro-F1=0.7963  P1=0.502 R1=0.751  (16s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[687/1560] RF        repeat 1 fold 1  macro-F1=0.7670  P1=0.401 R1=0.862  (4s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[688/1560] RF        repeat 1 fold 1  macro-F1=0.7781  P1=0.443 R1=0.790  (11s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[689/1560] RF        repeat 1 fold 1  macro-F1=0.7365  P1=0.342 R1=0.862  (3s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[690/1560] RF        repeat 1 fold 1  macro-F1=0.7800  P1=0.439 R1=0.818  (8s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[691/1560] RF        repeat 1 fold 1  macro-F1=0.6858  P1=0.253 R1=0.928  (2s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[692/1560] RF        repeat 1 fold 1  macro-F1=0.7584  P1=0.498 R1=0.558  (6s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[693/1560] RF        repeat 1 fold 1  macro-F1=0.8364  P1=0.648 R1=0.713  (27s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[694/1560] RF        repeat 1 fold 1  macro-F1=0.8414  P1=0.681 R1=0.696  (69s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[695/1560] RF        repeat 1 fold 1  macro-F1=0.8152  P1=0.561 R1=0.740  (29s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[696/1560] RF        repeat 1 fold 1  macro-F1=0.8226  P1=0.669 R1=0.635  (74s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[697/1560] RF        repeat 1 fold 1  macro-F1=0.7757  P1=0.428 R1=0.823  (28s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[698/1560] RF        repeat 1 fold 1  macro-F1=0.8043  P1=0.635 R1=0.597  (70s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[699/1560] RF        repeat 1 fold 1  macro-F1=0.7356  P1=0.336 R1=0.895  (18s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[700/1560] RF        repeat 1 fold 1  macro-F1=0.7834  P1=0.500 R1=0.680  (54s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[701/1560] RF        repeat 1 fold 1  macro-F1=0.6847  P1=0.251 R1=0.934  (14s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[702/1560] RF        repeat 1 fold 1  macro-F1=0.7707  P1=0.441 R1=0.740  (43s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[703/1560] RF        repeat 1 fold 1  macro-F1=0.6319  P1=0.182 R1=0.967  (12s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[704/1560] RF        repeat 1 fold 1  macro-F1=0.7490  P1=0.416 R1=0.657  (36s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[705/1560] RF        repeat 1 fold 1  macro-F1=0.5730  P1=0.121 R1=0.967  (8s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[706/1560] RF        repeat 1 fold 1  macro-F1=0.7401  P1=0.398 R1=0.646  (27s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[707/1560] RF        repeat 1 fold 1  macro-F1=0.3130  P1=0.030 R1=1.000  (5s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[708/1560] RF        repeat 1 fold 1  macro-F1=0.7141  P1=0.333 R1=0.663  (16s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[709/1560] RF        repeat 1 fold 1  macro-F1=0.8274  P1=0.598 R1=0.740  (24s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[710/1560] RF        repeat 1 fold 1  macro-F1=0.8191  P1=0.638 R1=0.652  (72s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[711/1560] RF        repeat 1 fold 1  macro-F1=0.8186  P1=0.604 R1=0.691  (45s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[712/1560] RF        repeat 1 fold 1  macro-F1=0.8205  P1=0.594 R1=0.713  (133s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[713/1560] RF        repeat 1 fold 1  macro-F1=0.8023  P1=0.523 R1=0.740  (51s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[714/1560] RF        repeat 1 fold 1  macro-F1=0.8057  P1=0.654 R1=0.586  (148s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[715/1560] RF        repeat 1 fold 1  macro-F1=0.7632  P1=0.394 R1=0.856  (50s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[716/1560] RF        repeat 1 fold 1  macro-F1=0.7974  P1=0.602 R1=0.602  (130s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[717/1560] RF        repeat 1 fold 1  macro-F1=0.7123  P1=0.295 R1=0.912  (35s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[718/1560] RF        repeat 1 fold 1  macro-F1=0.7733  P1=0.462 R1=0.702  (105s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[719/1560] RF        repeat 1 fold 1  macro-F1=0.6619  P1=0.220 R1=0.945  (33s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[720/1560] RF        repeat 1 fold 1  macro-F1=0.7577  P1=0.417 R1=0.718  (84s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[721/1560] RF        repeat 1 fold 1  macro-F1=0.6011  P1=0.148 R1=0.967  (23s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[722/1560] RF        repeat 1 fold 1  macro-F1=0.7464  P1=0.473 R1=0.536  (64s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[723/1560] RF        repeat 1 fold 1  macro-F1=0.5472  P1=0.100 R1=0.972  (17s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[724/1560] RF        repeat 1 fold 1  macro-F1=0.7294  P1=0.381 R1=0.619  (42s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[725/1560] RF        repeat 1 fold 1  macro-F1=0.1758  P1=0.022 R1=1.000  (9s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[726/1560] RF        repeat 1 fold 1  macro-F1=0.7109  P1=0.406 R1=0.464  (22s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[727/1560] RF        repeat 1 fold 1  macro-F1=0.8186  P1=0.604 R1=0.691  (32s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[728/1560] RF        repeat 1 fold 1  macro-F1=0.8205  P1=0.594 R1=0.713  (92s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[729/1560] RF        repeat 2 fold 0  macro-F1=0.8579  P1=0.908 R1=0.597  (12s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[730/1560] RF        repeat 2 fold 0  macro-F1=0.8815  P1=0.823 R1=0.718  (32s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[731/1560] RF        repeat 2 fold 0  macro-F1=0.8810  P1=0.851 R1=0.696  (13s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[732/1560] RF        repeat 2 fold 0  macro-F1=0.8723  P1=0.732 R1=0.768  (32s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[733/1560] RF        repeat 2 fold 0  macro-F1=0.8594  P1=0.774 R1=0.680  (10s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[734/1560] RF        repeat 2 fold 0  macro-F1=0.8665  P1=0.715 R1=0.762  (26s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[735/1560] RF        repeat 2 fold 0  macro-F1=0.8468  P1=0.659 R1=0.746  (7s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[736/1560] RF        repeat 2 fold 0  macro-F1=0.8471  P1=0.668 R1=0.735  (20s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[737/1560] RF        repeat 2 fold 0  macro-F1=0.7855  P1=0.455 R1=0.807  (5s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[738/1560] RF        repeat 2 fold 0  macro-F1=0.7846  P1=0.455 R1=0.801  (15s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[739/1560] RF        repeat 2 fold 0  macro-F1=0.7559  P1=0.383 R1=0.840  (4s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[740/1560] RF        repeat 2 fold 0  macro-F1=0.7684  P1=0.423 R1=0.779  (11s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[741/1560] RF        repeat 2 fold 0  macro-F1=0.7329  P1=0.335 R1=0.867  (3s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[742/1560] RF        repeat 2 fold 0  macro-F1=0.7706  P1=0.429 R1=0.779  (8s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[743/1560] RF        repeat 2 fold 0  macro-F1=0.6828  P1=0.248 R1=0.961  (2s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[744/1560] RF        repeat 2 fold 0  macro-F1=0.7611  P1=0.406 R1=0.785  (6s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[745/1560] RF        repeat 2 fold 0  macro-F1=0.8524  P1=0.639 R1=0.801  (28s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[746/1560] RF        repeat 2 fold 0  macro-F1=0.8597  P1=0.678 R1=0.779  (69s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[747/1560] RF        repeat 2 fold 0  macro-F1=0.8220  P1=0.538 R1=0.829  (29s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[748/1560] RF        repeat 2 fold 0  macro-F1=0.8456  P1=0.677 R1=0.718  (74s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[749/1560] RF        repeat 2 fold 0  macro-F1=0.7758  P1=0.415 R1=0.884  (27s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[750/1560] RF        repeat 2 fold 0  macro-F1=0.8341  P1=0.680 R1=0.669  (69s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[751/1560] RF        repeat 2 fold 0  macro-F1=0.7171  P1=0.300 R1=0.950  (19s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[752/1560] RF        repeat 2 fold 0  macro-F1=0.7987  P1=0.504 R1=0.762  (54s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[753/1560] RF        repeat 2 fold 0  macro-F1=0.6643  P1=0.222 R1=0.961  (15s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[754/1560] RF        repeat 2 fold 0  macro-F1=0.7871  P1=0.502 R1=0.696  (43s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[755/1560] RF        repeat 2 fold 0  macro-F1=0.6095  P1=0.157 R1=0.978  (12s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[756/1560] RF        repeat 2 fold 0  macro-F1=0.7701  P1=0.580 R1=0.519  (34s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[757/1560] RF        repeat 2 fold 0  macro-F1=0.5589  P1=0.110 R1=0.983  (9s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[758/1560] RF        repeat 2 fold 0  macro-F1=0.7456  P1=0.410 R1=0.652  (24s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[759/1560] RF        repeat 2 fold 0  macro-F1=0.2731  P1=0.027 R1=0.994  (6s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[760/1560] RF        repeat 2 fold 0  macro-F1=0.7073  P1=0.308 R1=0.724  (16s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[761/1560] RF        repeat 2 fold 0  macro-F1=0.8357  P1=0.572 R1=0.834  (20s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[762/1560] RF        repeat 2 fold 0  macro-F1=0.8509  P1=0.737 R1=0.680  (62s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[763/1560] RF        repeat 2 fold 0  macro-F1=0.8387  P1=0.603 R1=0.790  (38s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[764/1560] RF        repeat 2 fold 0  macro-F1=0.8454  P1=0.667 R1=0.729  (116s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[765/1560] RF        repeat 2 fold 0  macro-F1=0.8028  P1=0.486 R1=0.840  (44s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[766/1560] RF        repeat 2 fold 0  macro-F1=0.8338  P1=0.658 R1=0.691  (130s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[767/1560] RF        repeat 2 fold 0  macro-F1=0.7545  P1=0.367 R1=0.917  (41s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[768/1560] RF        repeat 2 fold 0  macro-F1=0.8231  P1=0.607 R1=0.707  (123s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[769/1560] RF        repeat 2 fold 0  macro-F1=0.6910  P1=0.260 R1=0.950  (33s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[770/1560] RF        repeat 2 fold 0  macro-F1=0.8038  P1=0.596 R1=0.635  (102s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[771/1560] RF        repeat 2 fold 0  macro-F1=0.6401  P1=0.191 R1=0.967  (32s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[772/1560] RF        repeat 2 fold 0  macro-F1=0.7769  P1=0.583 R1=0.541  (83s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[773/1560] RF        repeat 2 fold 0  macro-F1=0.5866  P1=0.134 R1=0.978  (21s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[774/1560] RF        repeat 2 fold 0  macro-F1=0.7689  P1=0.505 R1=0.597  (70s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[775/1560] RF        repeat 2 fold 0  macro-F1=0.5333  P1=0.091 R1=0.989  (18s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[776/1560] RF        repeat 2 fold 0  macro-F1=0.7386  P1=0.416 R1=0.591  (46s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[777/1560] RF        repeat 2 fold 0  macro-F1=0.2011  P1=0.023 R1=0.994  (10s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[778/1560] RF        repeat 2 fold 0  macro-F1=0.7147  P1=0.317 R1=0.757  (27s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[779/1560] RF        repeat 2 fold 0  macro-F1=0.8387  P1=0.603 R1=0.790  (37s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[780/1560] RF        repeat 2 fold 0  macro-F1=0.8454  P1=0.667 R1=0.729  (83s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[781/1560] RF        repeat 2 fold 1  macro-F1=0.8190  P1=0.741 R1=0.569  (17s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[782/1560] RF        repeat 2 fold 1  macro-F1=0.8425  P1=0.691 R1=0.691  (52s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[783/1560] RF        repeat 2 fold 1  macro-F1=0.8404  P1=0.677 R1=0.696  (18s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[784/1560] RF        repeat 2 fold 1  macro-F1=0.8359  P1=0.622 R1=0.746  (52s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[785/1560] RF        repeat 2 fold 1  macro-F1=0.8139  P1=0.548 R1=0.757  (17s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[786/1560] RF        repeat 2 fold 1  macro-F1=0.8134  P1=0.562 R1=0.729  (49s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[787/1560] RF        repeat 2 fold 1  macro-F1=0.7773  P1=0.442 R1=0.785  (14s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[788/1560] RF        repeat 2 fold 1  macro-F1=0.7979  P1=0.547 R1=0.674  (39s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[789/1560] RF        repeat 2 fold 1  macro-F1=0.7608  P1=0.389 R1=0.856  (11s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[790/1560] RF        repeat 2 fold 1  macro-F1=0.7623  P1=0.428 R1=0.718  (28s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[791/1560] RF        repeat 2 fold 1  macro-F1=0.7228  P1=0.314 R1=0.895  (6s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[792/1560] RF        repeat 2 fold 1  macro-F1=0.7599  P1=0.434 R1=0.685  (19s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[793/1560] RF        repeat 2 fold 1  macro-F1=0.6913  P1=0.262 R1=0.923  (4s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[794/1560] RF        repeat 2 fold 1  macro-F1=0.7447  P1=0.382 R1=0.735  (13s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[795/1560] RF        repeat 2 fold 1  macro-F1=0.6463  P1=0.199 R1=0.950  (3s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[796/1560] RF        repeat 2 fold 1  macro-F1=0.7474  P1=0.391 R1=0.724  (9s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[797/1560] RF        repeat 2 fold 1  macro-F1=0.8367  P1=0.583 R1=0.818  (16s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[798/1560] RF        repeat 2 fold 1  macro-F1=0.8411  P1=0.631 R1=0.757  (41s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[799/1560] RF        repeat 2 fold 1  macro-F1=0.8037  P1=0.493 R1=0.823  (16s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[800/1560] RF        repeat 2 fold 1  macro-F1=0.8225  P1=0.567 R1=0.768  (43s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[801/1560] RF        repeat 2 fold 1  macro-F1=0.7699  P1=0.406 R1=0.867  (16s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[802/1560] RF        repeat 2 fold 1  macro-F1=0.7999  P1=0.509 R1=0.757  (42s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[803/1560] RF        repeat 2 fold 1  macro-F1=0.7190  P1=0.307 R1=0.906  (12s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[804/1560] RF        repeat 2 fold 1  macro-F1=0.7797  P1=0.566 R1=0.569  (35s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[805/1560] RF        repeat 2 fold 1  macro-F1=0.6660  P1=0.225 R1=0.945  (9s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[806/1560] RF        repeat 2 fold 1  macro-F1=0.7687  P1=0.477 R1=0.641  (28s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[807/1560] RF        repeat 2 fold 1  macro-F1=0.6116  P1=0.159 R1=0.961  (7s)  [ratio 0.5, orig^1.25, C=0, rho=73.60]

[808/1560] RF        repeat 2 fold 1  macro-F1=0.7554  P1=0.433 R1=0.657  (25s)  [ratio 0.5, orig^1.25, C=1, rho=73.60]

[809/1560] RF        repeat 2 fold 1  macro-F1=0.5483  P1=0.102 R1=0.989  (7s)  [ratio 0.5, orig^1.5, C=0, rho=199.74]

[810/1560] RF        repeat 2 fold 1  macro-F1=0.7418  P1=0.466 R1=0.525  (17s)  [ratio 0.5, orig^1.5, C=1, rho=199.74]

[811/1560] RF        repeat 2 fold 1  macro-F1=0.1868  P1=0.022 R1=1.000  (4s)  [ratio 0.5, orig^2.0, C=0, rho=1471.16]

[812/1560] RF        repeat 2 fold 1  macro-F1=0.7171  P1=0.478 R1=0.414  (11s)  [ratio 0.5, orig^2.0, C=1, rho=1471.16]

[813/1560] RF        repeat 2 fold 1  macro-F1=0.8096  P1=0.514 R1=0.807  (12s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[814/1560] RF        repeat 2 fold 1  macro-F1=0.8239  P1=0.622 R1=0.691  (33s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[815/1560] RF        repeat 2 fold 1  macro-F1=0.8187  P1=0.548 R1=0.785  (24s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[816/1560] RF        repeat 2 fold 1  macro-F1=0.8226  P1=0.559 R1=0.785  (60s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[817/1560] RF        repeat 2 fold 1  macro-F1=0.7945  P1=0.461 R1=0.856  (25s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[818/1560] RF        repeat 2 fold 1  macro-F1=0.8101  P1=0.520 R1=0.796  (65s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[819/1560] RF        repeat 2 fold 1  macro-F1=0.7524  P1=0.368 R1=0.890  (24s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[820/1560] RF        repeat 2 fold 1  macro-F1=0.7962  P1=0.512 R1=0.729  (55s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[821/1560] RF        repeat 2 fold 1  macro-F1=0.6976  P1=0.271 R1=0.928  (19s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[822/1560] RF        repeat 2 fold 1  macro-F1=0.7841  P1=0.502 R1=0.680  (48s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[823/1560] RF        repeat 2 fold 1  macro-F1=0.6409  P1=0.192 R1=0.961  (12s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[824/1560] RF        repeat 2 fold 1  macro-F1=0.7559  P1=0.418 R1=0.702  (41s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[825/1560] RF        repeat 2 fold 1  macro-F1=0.5845  P1=0.132 R1=0.978  (9s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[826/1560] RF        repeat 2 fold 1  macro-F1=0.7445  P1=0.407 R1=0.652  (36s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[827/1560] RF        repeat 2 fold 1  macro-F1=0.5136  P1=0.079 R1=0.989  (8s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[828/1560] RF        repeat 2 fold 1  macro-F1=0.7416  P1=0.430 R1=0.580  (24s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[829/1560] RF        repeat 2 fold 1  macro-F1=0.1409  P1=0.021 R1=1.000  (5s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[830/1560] RF        repeat 2 fold 1  macro-F1=0.6797  P1=0.259 R1=0.724  (14s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[831/1560] RF        repeat 2 fold 1  macro-F1=0.8187  P1=0.548 R1=0.785  (18s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[832/1560] RF        repeat 2 fold 1  macro-F1=0.8226  P1=0.559 R1=0.785  (48s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[833/1560] RF        repeat 3 fold 0  macro-F1=0.8125  P1=0.816 R1=0.514  (23s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[834/1560] RF        repeat 3 fold 0  macro-F1=0.8402  P1=0.796 R1=0.602  (61s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[835/1560] RF        repeat 3 fold 0  macro-F1=0.8503  P1=0.793 R1=0.635  (25s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[836/1560] RF        repeat 3 fold 0  macro-F1=0.8525  P1=0.731 R1=0.691  (63s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[837/1560] RF        repeat 3 fold 0  macro-F1=0.8540  P1=0.750 R1=0.680  (21s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[838/1560] RF        repeat 3 fold 0  macro-F1=0.8380  P1=0.784 R1=0.602  (54s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[839/1560] RF        repeat 3 fold 0  macro-F1=0.8346  P1=0.646 R1=0.707  (15s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[840/1560] RF        repeat 3 fold 0  macro-F1=0.8354  P1=0.723 R1=0.635  (40s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[841/1560] RF        repeat 3 fold 0  macro-F1=0.8083  P1=0.522 R1=0.779  (11s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[842/1560] RF        repeat 3 fold 0  macro-F1=0.8153  P1=0.592 R1=0.691  (29s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[843/1560] RF        repeat 3 fold 0  macro-F1=0.7815  P1=0.444 R1=0.812  (7s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[844/1560] RF        repeat 3 fold 0  macro-F1=0.8078  P1=0.621 R1=0.624  (19s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[845/1560] RF        repeat 3 fold 0  macro-F1=0.7496  P1=0.365 R1=0.873  (4s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[846/1560] RF        repeat 3 fold 0  macro-F1=0.8013  P1=0.569 R1=0.657  (15s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[847/1560] RF        repeat 3 fold 0  macro-F1=0.6626  P1=0.220 R1=0.967  (3s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[848/1560] RF        repeat 3 fold 0  macro-F1=0.7532  P1=0.492 R1=0.541  (10s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[849/1560] RF        repeat 3 fold 0  macro-F1=0.8357  P1=0.660 R1=0.696  (16s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[850/1560] RF        repeat 3 fold 0  macro-F1=0.8441  P1=0.727 R1=0.663  (39s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[851/1560] RF        repeat 3 fold 0  macro-F1=0.8333  P1=0.614 R1=0.746  (17s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[852/1560] RF        repeat 3 fold 0  macro-F1=0.8213  P1=0.711 R1=0.597  (42s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[853/1560] RF        repeat 3 fold 0  macro-F1=0.7950  P1=0.476 R1=0.812  (16s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[854/1560] RF        repeat 3 fold 0  macro-F1=0.8199  P1=0.578 R1=0.735  (38s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[855/1560] RF        repeat 3 fold 0  macro-F1=0.7496  P1=0.361 R1=0.901  (9s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[856/1560] RF        repeat 3 fold 0  macro-F1=0.7918  P1=0.591 R1=0.591  (28s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[857/1560] RF        repeat 3 fold 0  macro-F1=0.6873  P1=0.255 R1=0.934  (7s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[858/1560] RF        repeat 3 fold 0  macro-F1=0.7750  P1=0.548 R1=0.569  (24s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[859/1560] RF        repeat 3 fold 0  macro-F1=0.6344  P1=0.185 R1=0.978  (6s)  [ratio 0.5, orig^1.25, C=0, rho=73.60]

[860/1560] RF        repeat 3 fold 0  macro-F1=0.7491  P1=0.421 R1=0.646  (20s)  [ratio 0.5, orig^1.25, C=1, rho=73.60]

[861/1560] RF        repeat 3 fold 0  macro-F1=0.5635  P1=0.113 R1=0.978  (5s)  [ratio 0.5, orig^1.5, C=0, rho=199.74]

[862/1560] RF        repeat 3 fold 0  macro-F1=0.7444  P1=0.427 R1=0.602  (14s)  [ratio 0.5, orig^1.5, C=1, rho=199.74]

[863/1560] RF        repeat 3 fold 0  macro-F1=0.2665  P1=0.026 R1=1.000  (3s)  [ratio 0.5, orig^2.0, C=0, rho=1471.16]

[864/1560] RF        repeat 3 fold 0  macro-F1=0.6832  P1=0.278 R1=0.624  (9s)  [ratio 0.5, orig^2.0, C=1, rho=1471.16]

[865/1560] RF        repeat 3 fold 0  macro-F1=0.8256  P1=0.633 R1=0.685  (11s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[866/1560] RF        repeat 3 fold 0  macro-F1=0.8284  P1=0.693 R1=0.635  (31s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[867/1560] RF        repeat 3 fold 0  macro-F1=0.8265  P1=0.656 R1=0.663  (22s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[868/1560] RF        repeat 3 fold 0  macro-F1=0.8245  P1=0.703 R1=0.613  (66s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[869/1560] RF        repeat 3 fold 0  macro-F1=0.8224  P1=0.579 R1=0.746  (24s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[870/1560] RF        repeat 3 fold 0  macro-F1=0.8197  P1=0.669 R1=0.624  (74s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[871/1560] RF        repeat 3 fold 0  macro-F1=0.7719  P1=0.415 R1=0.845  (23s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[872/1560] RF        repeat 3 fold 0  macro-F1=0.8059  P1=0.619 R1=0.619  (65s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[873/1560] RF        repeat 3 fold 0  macro-F1=0.7254  P1=0.316 R1=0.917  (23s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[874/1560] RF        repeat 3 fold 0  macro-F1=0.7951  P1=0.574 R1=0.624  (56s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[875/1560] RF        repeat 3 fold 0  macro-F1=0.6626  P1=0.220 R1=0.961  (13s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[876/1560] RF        repeat 3 fold 0  macro-F1=0.7502  P1=0.393 R1=0.740  (48s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[877/1560] RF        repeat 3 fold 0  macro-F1=0.6039  P1=0.151 R1=0.978  (12s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[878/1560] RF        repeat 3 fold 0  macro-F1=0.7448  P1=0.449 R1=0.564  (39s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[879/1560] RF        repeat 3 fold 0  macro-F1=0.5331  P1=0.091 R1=0.978  (9s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[880/1560] RF        repeat 3 fold 0  macro-F1=0.7415  P1=0.419 R1=0.602  (26s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[881/1560] RF        repeat 3 fold 0  macro-F1=0.1641  P1=0.022 R1=1.000  (5s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[882/1560] RF        repeat 3 fold 0  macro-F1=0.7063  P1=0.347 R1=0.552  (15s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[883/1560] RF        repeat 3 fold 0  macro-F1=0.8265  P1=0.656 R1=0.663  (20s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[884/1560] RF        repeat 3 fold 0  macro-F1=0.8245  P1=0.703 R1=0.613  (52s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[885/1560] RF        repeat 3 fold 1  macro-F1=0.8521  P1=0.830 R1=0.619  (22s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[886/1560] RF        repeat 3 fold 1  macro-F1=0.8523  P1=0.697 R1=0.724  (53s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[887/1560] RF        repeat 3 fold 1  macro-F1=0.8555  P1=0.771 R1=0.669  (20s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[888/1560] RF        repeat 3 fold 1  macro-F1=0.8611  P1=0.725 R1=0.729  (51s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[889/1560] RF        repeat 3 fold 1  macro-F1=0.8436  P1=0.753 R1=0.641  (17s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[890/1560] RF        repeat 3 fold 1  macro-F1=0.8496  P1=0.725 R1=0.685  (43s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[891/1560] RF        repeat 3 fold 1  macro-F1=0.8244  P1=0.710 R1=0.608  (12s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[892/1560] RF        repeat 3 fold 1  macro-F1=0.8206  P1=0.587 R1=0.724  (31s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[893/1560] RF        repeat 3 fold 1  macro-F1=0.8160  P1=0.653 R1=0.624  (9s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[894/1560] RF        repeat 3 fold 1  macro-F1=0.8199  P1=0.581 R1=0.729  (23s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[895/1560] RF        repeat 3 fold 1  macro-F1=0.8099  P1=0.542 R1=0.746  (6s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[896/1560] RF        repeat 3 fold 1  macro-F1=0.8077  P1=0.533 R1=0.751  (16s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[897/1560] RF        repeat 3 fold 1  macro-F1=0.7696  P1=0.406 R1=0.862  (4s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[898/1560] RF        repeat 3 fold 1  macro-F1=0.7967  P1=0.516 R1=0.724  (11s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[899/1560] RF        repeat 3 fold 1  macro-F1=0.6764  P1=0.240 R1=0.934  (2s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[900/1560] RF        repeat 3 fold 1  macro-F1=0.7713  P1=0.442 R1=0.740  (8s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[901/1560] RF        repeat 3 fold 1  macro-F1=0.8396  P1=0.606 R1=0.790  (21s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[902/1560] RF        repeat 3 fold 1  macro-F1=0.8385  P1=0.670 R1=0.696  (60s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[903/1560] RF        repeat 3 fold 1  macro-F1=0.8111  P1=0.514 R1=0.818  (23s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[904/1560] RF        repeat 3 fold 1  macro-F1=0.8348  P1=0.667 R1=0.685  (65s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[905/1560] RF        repeat 3 fold 1  macro-F1=0.7810  P1=0.421 R1=0.906  (22s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[906/1560] RF        repeat 3 fold 1  macro-F1=0.8202  P1=0.627 R1=0.669  (62s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[907/1560] RF        repeat 3 fold 1  macro-F1=0.7175  P1=0.302 R1=0.928  (17s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[908/1560] RF        repeat 3 fold 1  macro-F1=0.7952  P1=0.605 R1=0.591  (53s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[909/1560] RF        repeat 3 fold 1  macro-F1=0.6636  P1=0.222 R1=0.939  (13s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[910/1560] RF        repeat 3 fold 1  macro-F1=0.7937  P1=0.552 R1=0.646  (44s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[911/1560] RF        repeat 3 fold 1  macro-F1=0.6054  P1=0.152 R1=0.972  (11s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[912/1560] RF        repeat 3 fold 1  macro-F1=0.7646  P1=0.481 R1=0.613  (38s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[913/1560] RF        repeat 3 fold 1  macro-F1=0.5559  P1=0.107 R1=0.983  (9s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[914/1560] RF        repeat 3 fold 1  macro-F1=0.7553  P1=0.403 R1=0.746  (26s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[915/1560] RF        repeat 3 fold 1  macro-F1=0.2788  P1=0.027 R1=0.994  (6s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[916/1560] RF        repeat 3 fold 1  macro-F1=0.7153  P1=0.312 R1=0.801  (17s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[917/1560] RF        repeat 3 fold 1  macro-F1=0.8219  P1=0.552 R1=0.796  (21s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[918/1560] RF        repeat 3 fold 1  macro-F1=0.8352  P1=0.627 R1=0.735  (58s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[919/1560] RF        repeat 3 fold 1  macro-F1=0.8257  P1=0.577 R1=0.768  (38s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[920/1560] RF        repeat 3 fold 1  macro-F1=0.8324  P1=0.607 R1=0.751  (95s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[921/1560] RF        repeat 3 fold 1  macro-F1=0.8048  P1=0.490 R1=0.840  (42s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[922/1560] RF        repeat 3 fold 1  macro-F1=0.8239  P1=0.610 R1=0.707  (105s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[923/1560] RF        repeat 3 fold 1  macro-F1=0.7550  P1=0.369 R1=0.912  (40s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[924/1560] RF        repeat 3 fold 1  macro-F1=0.8075  P1=0.557 R1=0.707  (90s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[925/1560] RF        repeat 3 fold 1  macro-F1=0.6956  P1=0.267 R1=0.939  (28s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[926/1560] RF        repeat 3 fold 1  macro-F1=0.7876  P1=0.552 R1=0.619  (78s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[927/1560] RF        repeat 3 fold 1  macro-F1=0.6401  P1=0.192 R1=0.956  (23s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[928/1560] RF        repeat 3 fold 1  macro-F1=0.7696  P1=0.452 R1=0.702  (60s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[929/1560] RF        repeat 3 fold 1  macro-F1=0.5782  P1=0.126 R1=0.972  (15s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[930/1560] RF        repeat 3 fold 1  macro-F1=0.7567  P1=0.439 R1=0.652  (48s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[931/1560] RF        repeat 3 fold 1  macro-F1=0.5325  P1=0.090 R1=0.983  (12s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[932/1560] RF        repeat 3 fold 1  macro-F1=0.7475  P1=0.419 R1=0.641  (34s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[933/1560] RF        repeat 3 fold 1  macro-F1=0.2305  P1=0.024 R1=0.994  (6s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[934/1560] RF        repeat 3 fold 1  macro-F1=0.7080  P1=0.299 R1=0.801  (20s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[935/1560] RF        repeat 3 fold 1  macro-F1=0.8257  P1=0.577 R1=0.768  (29s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[936/1560] RF        repeat 3 fold 1  macro-F1=0.8324  P1=0.607 R1=0.751  (85s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[937/1560] RF        repeat 4 fold 0  macro-F1=0.8495  P1=0.857 R1=0.597  (11s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[938/1560] RF        repeat 4 fold 0  macro-F1=0.8725  P1=0.804 R1=0.702  (29s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[939/1560] RF        repeat 4 fold 0  macro-F1=0.8588  P1=0.786 R1=0.669  (10s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[940/1560] RF        repeat 4 fold 0  macro-F1=0.8541  P1=0.698 R1=0.729  (28s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[941/1560] RF        repeat 4 fold 0  macro-F1=0.8375  P1=0.732 R1=0.635  (9s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[942/1560] RF        repeat 4 fold 0  macro-F1=0.8462  P1=0.641 R1=0.768  (24s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[943/1560] RF        repeat 4 fold 0  macro-F1=0.8293  P1=0.651 R1=0.680  (7s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[944/1560] RF        repeat 4 fold 0  macro-F1=0.8211  P1=0.547 R1=0.801  (20s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[945/1560] RF        repeat 4 fold 0  macro-F1=0.7931  P1=0.477 R1=0.796  (5s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[946/1560] RF        repeat 4 fold 0  macro-F1=0.7869  P1=0.452 R1=0.829  (15s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[947/1560] RF        repeat 4 fold 0  macro-F1=0.7652  P1=0.398 R1=0.856  (3s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[948/1560] RF        repeat 4 fold 0  macro-F1=0.7747  P1=0.438 R1=0.779  (11s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[949/1560] RF        repeat 4 fold 0  macro-F1=0.7377  P1=0.344 R1=0.867  (2s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[950/1560] RF        repeat 4 fold 0  macro-F1=0.7797  P1=0.448 R1=0.785  (9s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[951/1560] RF        repeat 4 fold 0  macro-F1=0.6745  P1=0.237 R1=0.934  (2s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[952/1560] RF        repeat 4 fold 0  macro-F1=0.7579  P1=0.433 R1=0.674  (7s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[953/1560] RF        repeat 4 fold 0  macro-F1=0.8404  P1=0.609 R1=0.790  (26s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[954/1560] RF        repeat 4 fold 0  macro-F1=0.8397  P1=0.609 R1=0.785  (60s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[955/1560] RF        repeat 4 fold 0  macro-F1=0.8181  P1=0.539 R1=0.801  (25s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[956/1560] RF        repeat 4 fold 0  macro-F1=0.8257  P1=0.580 R1=0.762  (66s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[957/1560] RF        repeat 4 fold 0  macro-F1=0.7903  P1=0.452 R1=0.856  (25s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[958/1560] RF        repeat 4 fold 0  macro-F1=0.8072  P1=0.543 R1=0.729  (63s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[959/1560] RF        repeat 4 fold 0  macro-F1=0.7382  P1=0.338 R1=0.917  (16s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[960/1560] RF        repeat 4 fold 0  macro-F1=0.7904  P1=0.514 R1=0.691  (49s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[961/1560] RF        repeat 4 fold 0  macro-F1=0.6840  P1=0.250 R1=0.945  (13s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[962/1560] RF        repeat 4 fold 0  macro-F1=0.7697  P1=0.444 R1=0.724  (40s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[963/1560] RF        repeat 4 fold 0  macro-F1=0.6381  P1=0.189 R1=0.961  (10s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[964/1560] RF        repeat 4 fold 0  macro-F1=0.7546  P1=0.429 R1=0.663  (34s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[965/1560] RF        repeat 4 fold 0  macro-F1=0.5827  P1=0.130 R1=0.972  (8s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[966/1560] RF        repeat 4 fold 0  macro-F1=0.7561  P1=0.402 R1=0.757  (26s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[967/1560] RF        repeat 4 fold 0  macro-F1=0.3843  P1=0.038 R1=0.989  (5s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[968/1560] RF        repeat 4 fold 0  macro-F1=0.7140  P1=0.337 R1=0.646  (16s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[969/1560] RF        repeat 4 fold 0  macro-F1=0.8265  P1=0.567 R1=0.790  (22s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[970/1560] RF        repeat 4 fold 0  macro-F1=0.8195  P1=0.548 R1=0.790  (65s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[971/1560] RF        repeat 4 fold 0  macro-F1=0.8257  P1=0.580 R1=0.762  (41s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[972/1560] RF        repeat 4 fold 0  macro-F1=0.8257  P1=0.580 R1=0.762  (121s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[973/1560] RF        repeat 4 fold 0  macro-F1=0.8032  P1=0.500 R1=0.801  (46s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[974/1560] RF        repeat 4 fold 0  macro-F1=0.8112  P1=0.530 R1=0.779  (135s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[975/1560] RF        repeat 4 fold 0  macro-F1=0.7672  P1=0.397 R1=0.884  (47s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[976/1560] RF        repeat 4 fold 0  macro-F1=0.7959  P1=0.506 R1=0.740  (118s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[977/1560] RF        repeat 4 fold 0  macro-F1=0.7118  P1=0.294 R1=0.917  (32s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[978/1560] RF        repeat 4 fold 0  macro-F1=0.7801  P1=0.478 R1=0.707  (107s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[979/1560] RF        repeat 4 fold 0  macro-F1=0.6652  P1=0.224 R1=0.956  (26s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[980/1560] RF        repeat 4 fold 0  macro-F1=0.7660  P1=0.470 R1=0.641  (81s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[981/1560] RF        repeat 4 fold 0  macro-F1=0.6146  P1=0.162 R1=0.967  (24s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[982/1560] RF        repeat 4 fold 0  macro-F1=0.7566  P1=0.469 R1=0.591  (61s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[983/1560] RF        repeat 4 fold 0  macro-F1=0.5593  P1=0.110 R1=0.972  (17s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[984/1560] RF        repeat 4 fold 0  macro-F1=0.7455  P1=0.405 R1=0.663  (39s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[985/1560] RF        repeat 4 fold 0  macro-F1=0.2847  P1=0.027 R1=0.994  (8s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[986/1560] RF        repeat 4 fold 0  macro-F1=0.7092  P1=0.308 R1=0.751  (21s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[987/1560] RF        repeat 4 fold 0  macro-F1=0.8257  P1=0.580 R1=0.762  (29s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[988/1560] RF        repeat 4 fold 0  macro-F1=0.8257  P1=0.580 R1=0.762  (83s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[989/1560] RF        repeat 4 fold 1  macro-F1=0.8297  P1=0.846 R1=0.547  (14s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[990/1560] RF        repeat 4 fold 1  macro-F1=0.8316  P1=0.743 R1=0.608  (35s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[991/1560] RF        repeat 4 fold 1  macro-F1=0.8336  P1=0.745 R1=0.613  (13s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[992/1560] RF        repeat 4 fold 1  macro-F1=0.8294  P1=0.690 R1=0.641  (35s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[993/1560] RF        repeat 4 fold 1  macro-F1=0.8183  P1=0.704 R1=0.591  (11s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[994/1560] RF        repeat 4 fold 1  macro-F1=0.8428  P1=0.637 R1=0.757  (30s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[995/1560] RF        repeat 4 fold 1  macro-F1=0.8122  P1=0.691 R1=0.580  (9s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[996/1560] RF        repeat 4 fold 1  macro-F1=0.8301  P1=0.631 R1=0.707  (23s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[997/1560] RF        repeat 4 fold 1  macro-F1=0.8020  P1=0.615 R1=0.608  (7s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[998/1560] RF        repeat 4 fold 1  macro-F1=0.8031  P1=0.553 R1=0.691  (17s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[999/1560] RF        repeat 4 fold 1  macro-F1=0.7883  P1=0.524 R1=0.663  (4s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[1000/1560] RF        repeat 4 fold 1  macro-F1=0.7984  P1=0.568 R1=0.646  (12s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[1001/1560] RF        repeat 4 fold 1  macro-F1=0.7585  P1=0.393 R1=0.818  (3s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[1002/1560] RF        repeat 4 fold 1  macro-F1=0.7803  P1=0.494 R1=0.674  (8s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[1003/1560] RF        repeat 4 fold 1  macro-F1=0.6772  P1=0.241 R1=0.923  (2s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[1004/1560] RF        repeat 4 fold 1  macro-F1=0.7485  P1=0.485 R1=0.530  (6s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[1005/1560] RF        repeat 4 fold 1  macro-F1=0.8327  P1=0.631 R1=0.718  (15s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1006/1560] RF        repeat 4 fold 1  macro-F1=0.8337  P1=0.648 R1=0.702  (42s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1007/1560] RF        repeat 4 fold 1  macro-F1=0.8124  P1=0.541 R1=0.762  (16s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[1008/1560] RF        repeat 4 fold 1  macro-F1=0.8146  P1=0.583 R1=0.702  (44s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[1009/1560] RF        repeat 4 fold 1  macro-F1=0.7743  P1=0.421 R1=0.840  (15s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[1010/1560] RF        repeat 4 fold 1  macro-F1=0.8041  P1=0.553 R1=0.696  (41s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[1011/1560] RF        repeat 4 fold 1  macro-F1=0.7207  P1=0.310 R1=0.901  (10s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[1012/1560] RF        repeat 4 fold 1  macro-F1=0.7956  P1=0.637 R1=0.564  (33s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[1013/1560] RF        repeat 4 fold 1  macro-F1=0.6627  P1=0.221 R1=0.945  (8s)  [ratio 0.5, orig^1.0, C=0, rho=27.11]

[1014/1560] RF        repeat 4 fold 1  macro-F1=0.7691  P1=0.476 R1=0.646  (28s)  [ratio 0.5, orig^1.0, C=1, rho=27.11]

[1015/1560] RF        repeat 4 fold 1  macro-F1=0.5999  P1=0.147 R1=0.983  (7s)  [ratio 0.5, orig^1.25, C=0, rho=73.58]

[1016/1560] RF        repeat 4 fold 1  macro-F1=0.7508  P1=0.438 R1=0.619  (24s)  [ratio 0.5, orig^1.25, C=1, rho=73.58]

[1017/1560] RF        repeat 4 fold 1  macro-F1=0.5338  P1=0.092 R1=0.994  (6s)  [ratio 0.5, orig^1.5, C=0, rho=199.70]

[1018/1560] RF        repeat 4 fold 1  macro-F1=0.7150  P1=0.367 R1=0.558  (16s)  [ratio 0.5, orig^1.5, C=1, rho=199.70]

[1019/1560] RF        repeat 4 fold 1  macro-F1=0.1776  P1=0.022 R1=1.000  (4s)  [ratio 0.5, orig^2.0, C=0, rho=1470.86]

[1020/1560] RF        repeat 4 fold 1  macro-F1=0.7044  P1=0.311 R1=0.674  (10s)  [ratio 0.5, orig^2.0, C=1, rho=1470.86]

[1021/1560] RF        repeat 4 fold 1  macro-F1=0.8182  P1=0.576 R1=0.729  (12s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1022/1560] RF        repeat 4 fold 1  macro-F1=0.8182  P1=0.576 R1=0.729  (31s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1023/1560] RF        repeat 4 fold 1  macro-F1=0.8274  P1=0.609 R1=0.724  (23s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1024/1560] RF        repeat 4 fold 1  macro-F1=0.8326  P1=0.627 R1=0.724  (59s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1025/1560] RF        repeat 4 fold 1  macro-F1=0.7987  P1=0.504 R1=0.762  (24s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[1026/1560] RF        repeat 4 fold 1  macro-F1=0.8132  P1=0.602 R1=0.669  (64s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[1027/1560] RF        repeat 4 fold 1  macro-F1=0.7426  P1=0.357 R1=0.840  (23s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[1028/1560] RF        repeat 4 fold 1  macro-F1=0.8002  P1=0.658 R1=0.564  (55s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[1029/1560] RF        repeat 4 fold 1  macro-F1=0.6913  P1=0.262 R1=0.923  (20s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[1030/1560] RF        repeat 4 fold 1  macro-F1=0.7738  P1=0.490 R1=0.646  (48s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[1031/1560] RF        repeat 4 fold 1  macro-F1=0.6305  P1=0.180 R1=0.956  (12s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[1032/1560] RF        repeat 4 fold 1  macro-F1=0.7610  P1=0.458 R1=0.635  (40s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[1033/1560] RF        repeat 4 fold 1  macro-F1=0.5749  P1=0.123 R1=0.989  (10s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[1034/1560] RF        repeat 4 fold 1  macro-F1=0.7432  P1=0.484 R1=0.508  (34s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[1035/1560] RF        repeat 4 fold 1  macro-F1=0.4978  P1=0.071 R1=0.989  (8s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[1036/1560] RF        repeat 4 fold 1  macro-F1=0.7185  P1=0.334 R1=0.702  (23s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[1037/1560] RF        repeat 4 fold 1  macro-F1=0.0247  P1=0.018 R1=1.000  (4s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[1038/1560] RF        repeat 4 fold 1  macro-F1=0.6932  P1=0.284 R1=0.707  (13s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[1039/1560] RF        repeat 4 fold 1  macro-F1=0.8274  P1=0.609 R1=0.724  (18s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1040/1560] RF        repeat 4 fold 1  macro-F1=0.8326  P1=0.627 R1=0.724  (47s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1041/1560] XGB       repeat 0 fold 0  macro-F1=0.8597  P1=0.782 R1=0.674  (7s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1042/1560] XGB       repeat 0 fold 0  macro-F1=0.8479  P1=0.827 R1=0.608  (21s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1043/1560] XGB       repeat 0 fold 0  macro-F1=0.8639  P1=0.773 R1=0.696  (7s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1044/1560] XGB       repeat 0 fold 0  macro-F1=0.8636  P1=0.691 R1=0.779  (21s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1045/1560] XGB       repeat 0 fold 0  macro-F1=0.8674  P1=0.750 R1=0.729  (7s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1046/1560] XGB       repeat 0 fold 0  macro-F1=0.8713  P1=0.743 R1=0.751  (22s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1047/1560] XGB       repeat 0 fold 0  macro-F1=0.8591  P1=0.717 R1=0.729  (7s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[1048/1560] XGB       repeat 0 fold 0  macro-F1=0.8645  P1=0.667 R1=0.818  (22s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[1049/1560] XGB       repeat 0 fold 0  macro-F1=0.8607  P1=0.681 R1=0.779  (7s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1050/1560] XGB       repeat 0 fold 0  macro-F1=0.8668  P1=0.721 R1=0.757  (21s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1051/1560] XGB       repeat 0 fold 0  macro-F1=0.8578  P1=0.642 R1=0.823  (7s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[1052/1560] XGB       repeat 0 fold 0  macro-F1=0.8625  P1=0.671 R1=0.801  (23s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[1053/1560] XGB       repeat 0 fold 0  macro-F1=0.8422  P1=0.593 R1=0.829  (7s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[1054/1560] XGB       repeat 0 fold 0  macro-F1=0.8586  P1=0.687 R1=0.762  (21s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[1055/1560] XGB       repeat 0 fold 0  macro-F1=0.7539  P1=0.365 R1=0.923  (6s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[1056/1560] XGB       repeat 0 fold 0  macro-F1=0.8349  P1=0.608 R1=0.762  (18s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[1057/1560] XGB       repeat 0 fold 0  macro-F1=0.8549  P1=0.678 R1=0.757  (14s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1058/1560] XGB       repeat 0 fold 0  macro-F1=0.8529  P1=0.715 R1=0.707  (46s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1059/1560] XGB       repeat 0 fold 0  macro-F1=0.8437  P1=0.640 R1=0.757  (15s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[1060/1560] XGB       repeat 0 fold 0  macro-F1=0.8451  P1=0.657 R1=0.740  (40s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[1061/1560] XGB       repeat 0 fold 0  macro-F1=0.8547  P1=0.639 R1=0.812  (18s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[1062/1560] XGB       repeat 0 fold 0  macro-F1=0.8564  P1=0.675 R1=0.768  (41s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[1063/1560] XGB       repeat 0 fold 0  macro-F1=0.8367  P1=0.583 R1=0.818  (14s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[1064/1560] XGB       repeat 0 fold 0  macro-F1=0.8450  P1=0.684 R1=0.707  (39s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[1065/1560] XGB       repeat 0 fold 0  macro-F1=0.8214  P1=0.525 R1=0.856  (10s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[1066/1560] XGB       repeat 0 fold 0  macro-F1=0.8573  P1=0.716 R1=0.724  (38s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[1067/1560] XGB       repeat 0 fold 0  macro-F1=0.7823  P1=0.424 R1=0.901  (10s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[1068/1560] XGB       repeat 0 fold 0  macro-F1=0.8568  P1=0.704 R1=0.735  (29s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[1069/1560] XGB       repeat 0 fold 0  macro-F1=0.7120  P1=0.293 R1=0.934  (10s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[1070/1560] XGB       repeat 0 fold 0  macro-F1=0.8124  P1=0.521 R1=0.807  (26s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[1071/1560] XGB       repeat 0 fold 0  macro-F1=0.5680  P1=0.117 R1=0.983  (8s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[1072/1560] XGB       repeat 0 fold 0  macro-F1=0.6717  P1=0.233 R1=0.934  (24s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[1073/1560] XGB       repeat 0 fold 0  macro-F1=0.8487  P1=0.645 R1=0.773  (9s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1074/1560] XGB       repeat 0 fold 0  macro-F1=0.8511  P1=0.645 R1=0.785  (28s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1075/1560] XGB       repeat 0 fold 0  macro-F1=0.8571  P1=0.673 R1=0.773  (15s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1076/1560] XGB       repeat 0 fold 0  macro-F1=0.8538  P1=0.693 R1=0.735  (47s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1077/1560] XGB       repeat 0 fold 0  macro-F1=0.8504  P1=0.647 R1=0.779  (15s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[1078/1560] XGB       repeat 0 fold 0  macro-F1=0.8534  P1=0.660 R1=0.773  (47s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[1079/1560] XGB       repeat 0 fold 0  macro-F1=0.8508  P1=0.621 R1=0.823  (16s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[1080/1560] XGB       repeat 0 fold 0  macro-F1=0.8477  P1=0.690 R1=0.713  (42s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[1081/1560] XGB       repeat 0 fold 0  macro-F1=0.8288  P1=0.563 R1=0.812  (11s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[1082/1560] XGB       repeat 0 fold 0  macro-F1=0.8485  P1=0.660 R1=0.751  (49s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[1083/1560] XGB       repeat 0 fold 0  macro-F1=0.8041  P1=0.480 R1=0.867  (11s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[1084/1560] XGB       repeat 0 fold 0  macro-F1=0.8532  P1=0.791 R1=0.646  (44s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[1085/1560] XGB       repeat 0 fold 0  macro-F1=0.7533  P1=0.366 R1=0.912  (11s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[1086/1560] XGB       repeat 0 fold 0  macro-F1=0.8428  P1=0.667 R1=0.718  (35s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[1087/1560] XGB       repeat 0 fold 0  macro-F1=0.6811  P1=0.245 R1=0.961  (11s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[1088/1560] XGB       repeat 0 fold 0  macro-F1=0.7754  P1=0.418 R1=0.862  (33s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[1089/1560] XGB       repeat 0 fold 0  macro-F1=0.5106  P1=0.077 R1=0.989  (10s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[1090/1560] XGB       repeat 0 fold 0  macro-F1=0.6329  P1=0.183 R1=0.950  (32s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[1091/1560] XGB       repeat 0 fold 0  macro-F1=0.8571  P1=0.673 R1=0.773  (12s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1092/1560] XGB       repeat 0 fold 0  macro-F1=0.8538  P1=0.693 R1=0.735  (34s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1093/1560] XGB       repeat 0 fold 1  macro-F1=0.8512  P1=0.835 R1=0.613  (4s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1094/1560] XGB       repeat 0 fold 1  macro-F1=0.8572  P1=0.764 R1=0.680  (11s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1095/1560] XGB       repeat 0 fold 1  macro-F1=0.8610  P1=0.796 R1=0.669  (4s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1096/1560] XGB       repeat 0 fold 1  macro-F1=0.8616  P1=0.717 R1=0.740  (12s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1097/1560] XGB       repeat 0 fold 1  macro-F1=0.8687  P1=0.801 R1=0.691  (4s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1098/1560] XGB       repeat 0 fold 1  macro-F1=0.8710  P1=0.790 R1=0.707  (12s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1099/1560] XGB       repeat 0 fold 1  macro-F1=0.8673  P1=0.768 R1=0.713  (4s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[1100/1560] XGB       repeat 0 fold 1  macro-F1=0.8620  P1=0.746 R1=0.713  (12s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[1101/1560] XGB       repeat 0 fold 1  macro-F1=0.8578  P1=0.707 R1=0.735  (4s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1102/1560] XGB       repeat 0 fold 1  macro-F1=0.8677  P1=0.757 R1=0.724  (13s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1103/1560] XGB       repeat 0 fold 1  macro-F1=0.8511  P1=0.645 R1=0.785  (4s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[1104/1560] XGB       repeat 0 fold 1  macro-F1=0.8517  P1=0.659 R1=0.768  (12s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[1105/1560] XGB       repeat 0 fold 1  macro-F1=0.8389  P1=0.584 R1=0.829  (3s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[1106/1560] XGB       repeat 0 fold 1  macro-F1=0.8466  P1=0.654 R1=0.751  (11s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[1107/1560] XGB       repeat 0 fold 1  macro-F1=0.7197  P1=0.304 R1=0.945  (3s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[1108/1560] XGB       repeat 0 fold 1  macro-F1=0.8132  P1=0.519 R1=0.818  (9s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[1109/1560] XGB       repeat 0 fold 1  macro-F1=0.8695  P1=0.759 R1=0.729  (9s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1110/1560] XGB       repeat 0 fold 1  macro-F1=0.8670  P1=0.760 R1=0.718  (25s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1111/1560] XGB       repeat 0 fold 1  macro-F1=0.8566  P1=0.698 R1=0.740  (8s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[1112/1560] XGB       repeat 0 fold 1  macro-F1=0.8421  P1=0.638 R1=0.751  (20s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[1113/1560] XGB       repeat 0 fold 1  macro-F1=0.8406  P1=0.646 R1=0.735  (7s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[1114/1560] XGB       repeat 0 fold 1  macro-F1=0.8547  P1=0.717 R1=0.713  (19s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[1115/1560] XGB       repeat 0 fold 1  macro-F1=0.8414  P1=0.615 R1=0.785  (7s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[1116/1560] XGB       repeat 0 fold 1  macro-F1=0.8591  P1=0.697 R1=0.751  (18s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[1117/1560] XGB       repeat 0 fold 1  macro-F1=0.8235  P1=0.533 R1=0.851  (4s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[1118/1560] XGB       repeat 0 fold 1  macro-F1=0.8566  P1=0.698 R1=0.740  (16s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[1119/1560] XGB       repeat 0 fold 1  macro-F1=0.7745  P1=0.409 R1=0.901  (4s)  [ratio 0.5, orig^1.25, C=0, rho=73.60]

[1120/1560] XGB       repeat 0 fold 1  macro-F1=0.8313  P1=0.584 R1=0.785  (17s)  [ratio 0.5, orig^1.25, C=1, rho=73.60]

[1121/1560] XGB       repeat 0 fold 1  macro-F1=0.6957  P1=0.266 R1=0.961  (4s)  [ratio 0.5, orig^1.5, C=0, rho=199.74]

[1122/1560] XGB       repeat 0 fold 1  macro-F1=0.8038  P1=0.503 R1=0.796  (11s)  [ratio 0.5, orig^1.5, C=1, rho=199.74]

[1123/1560] XGB       repeat 0 fold 1  macro-F1=0.5467  P1=0.100 R1=0.989  (3s)  [ratio 0.5, orig^2.0, C=0, rho=1471.16]

[1124/1560] XGB       repeat 0 fold 1  macro-F1=0.6559  P1=0.211 R1=0.967  (8s)  [ratio 0.5, orig^2.0, C=1, rho=1471.16]

[1125/1560] XGB       repeat 0 fold 1  macro-F1=0.8517  P1=0.705 R1=0.713  (4s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1126/1560] XGB       repeat 0 fold 1  macro-F1=0.8593  P1=0.685 R1=0.768  (13s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1127/1560] XGB       repeat 0 fold 1  macro-F1=0.8593  P1=0.724 R1=0.724  (11s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1128/1560] XGB       repeat 0 fold 1  macro-F1=0.8617  P1=0.739 R1=0.718  (30s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1129/1560] XGB       repeat 0 fold 1  macro-F1=0.8496  P1=0.668 R1=0.746  (11s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[1130/1560] XGB       repeat 0 fold 1  macro-F1=0.8650  P1=0.778 R1=0.696  (30s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[1131/1560] XGB       repeat 0 fold 1  macro-F1=0.8506  P1=0.651 R1=0.773  (11s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[1132/1560] XGB       repeat 0 fold 1  macro-F1=0.8545  P1=0.710 R1=0.718  (24s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[1133/1560] XGB       repeat 0 fold 1  macro-F1=0.8296  P1=0.571 R1=0.801  (11s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[1134/1560] XGB       repeat 0 fold 1  macro-F1=0.8660  P1=0.804 R1=0.680  (23s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[1135/1560] XGB       repeat 0 fold 1  macro-F1=0.8042  P1=0.479 R1=0.873  (5s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[1136/1560] XGB       repeat 0 fold 1  macro-F1=0.8474  P1=0.679 R1=0.724  (22s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[1137/1560] XGB       repeat 0 fold 1  macro-F1=0.7441  P1=0.346 R1=0.934  (5s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[1138/1560] XGB       repeat 0 fold 1  macro-F1=0.8209  P1=0.563 R1=0.768  (19s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[1139/1560] XGB       repeat 0 fold 1  macro-F1=0.6641  P1=0.222 R1=0.967  (4s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[1140/1560] XGB       repeat 0 fold 1  macro-F1=0.7691  P1=0.403 R1=0.873  (11s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[1141/1560] XGB       repeat 0 fold 1  macro-F1=0.5096  P1=0.077 R1=0.994  (3s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[1142/1560] XGB       repeat 0 fold 1  macro-F1=0.6255  P1=0.174 R1=0.972  (9s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[1143/1560] XGB       repeat 0 fold 1  macro-F1=0.8593  P1=0.724 R1=0.724  (4s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1144/1560] XGB       repeat 0 fold 1  macro-F1=0.8617  P1=0.739 R1=0.718  (11s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1145/1560] XGB       repeat 1 fold 0  macro-F1=0.8390  P1=0.780 R1=0.608  (4s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1146/1560] XGB       repeat 1 fold 0  macro-F1=0.8630  P1=0.712 R1=0.751  (14s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1147/1560] XGB       repeat 1 fold 0  macro-F1=0.8583  P1=0.769 R1=0.680  (5s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1148/1560] XGB       repeat 1 fold 0  macro-F1=0.8636  P1=0.691 R1=0.779  (16s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1149/1560] XGB       repeat 1 fold 0  macro-F1=0.8629  P1=0.727 R1=0.735  (5s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1150/1560] XGB       repeat 1 fold 0  macro-F1=0.8446  P1=0.750 R1=0.646  (17s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1151/1560] XGB       repeat 1 fold 0  macro-F1=0.8494  P1=0.663 R1=0.751  (5s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[1152/1560] XGB       repeat 1 fold 0  macro-F1=0.8400  P1=0.703 R1=0.669  (17s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[1153/1560] XGB       repeat 1 fold 0  macro-F1=0.8405  P1=0.585 R1=0.834  (5s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1154/1560] XGB       repeat 1 fold 0  macro-F1=0.8402  P1=0.667 R1=0.707  (17s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1155/1560] XGB       repeat 1 fold 0  macro-F1=0.8139  P1=0.503 R1=0.867  (5s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[1156/1560] XGB       repeat 1 fold 0  macro-F1=0.8325  P1=0.619 R1=0.735  (15s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[1157/1560] XGB       repeat 1 fold 0  macro-F1=0.7926  P1=0.444 R1=0.912  (4s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[1158/1560] XGB       repeat 1 fold 0  macro-F1=0.8394  P1=0.674 R1=0.696  (14s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[1159/1560] XGB       repeat 1 fold 0  macro-F1=0.6919  P1=0.260 R1=0.961  (4s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[1160/1560] XGB       repeat 1 fold 0  macro-F1=0.7934  P1=0.469 R1=0.823  (11s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[1161/1560] XGB       repeat 1 fold 0  macro-F1=0.8462  P1=0.665 R1=0.735  (9s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1162/1560] XGB       repeat 1 fold 0  macro-F1=0.8538  P1=0.743 R1=0.685  (26s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1163/1560] XGB       repeat 1 fold 0  macro-F1=0.8407  P1=0.619 R1=0.773  (8s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[1164/1560] XGB       repeat 1 fold 0  macro-F1=0.8594  P1=0.747 R1=0.702  (28s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[1165/1560] XGB       repeat 1 fold 0  macro-F1=0.8482  P1=0.613 R1=0.823  (5s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[1166/1560] XGB       repeat 1 fold 0  macro-F1=0.8491  P1=0.706 R1=0.702  (27s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[1167/1560] XGB       repeat 1 fold 0  macro-F1=0.8335  P1=0.574 R1=0.818  (8s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[1168/1560] XGB       repeat 1 fold 0  macro-F1=0.8386  P1=0.631 R1=0.746  (23s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[1169/1560] XGB       repeat 1 fold 0  macro-F1=0.8050  P1=0.487 R1=0.851  (5s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[1170/1560] XGB       repeat 1 fold 0  macro-F1=0.8531  P1=0.695 R1=0.729  (22s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[1171/1560] XGB       repeat 1 fold 0  macro-F1=0.7530  P1=0.364 R1=0.923  (5s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[1172/1560] XGB       repeat 1 fold 0  macro-F1=0.8505  P1=0.672 R1=0.746  (20s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[1173/1560] XGB       repeat 1 fold 0  macro-F1=0.6880  P1=0.255 R1=0.956  (4s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[1174/1560] XGB       repeat 1 fold 0  macro-F1=0.7891  P1=0.463 R1=0.807  (13s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[1175/1560] XGB       repeat 1 fold 0  macro-F1=0.5522  P1=0.105 R1=0.989  (3s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[1176/1560] XGB       repeat 1 fold 0  macro-F1=0.6633  P1=0.221 R1=0.961  (10s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[1177/1560] XGB       repeat 1 fold 0  macro-F1=0.8357  P1=0.611 R1=0.762  (7s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1178/1560] XGB       repeat 1 fold 0  macro-F1=0.8497  P1=0.697 R1=0.713  (22s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1179/1560] XGB       repeat 1 fold 0  macro-F1=0.8405  P1=0.641 R1=0.740  (14s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1180/1560] XGB       repeat 1 fold 0  macro-F1=0.8498  P1=0.732 R1=0.680  (43s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1181/1560] XGB       repeat 1 fold 0  macro-F1=0.8381  P1=0.611 R1=0.773  (14s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[1182/1560] XGB       repeat 1 fold 0  macro-F1=0.8509  P1=0.707 R1=0.707  (42s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[1183/1560] XGB       repeat 1 fold 0  macro-F1=0.8328  P1=0.580 R1=0.801  (14s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[1184/1560] XGB       repeat 1 fold 0  macro-F1=0.8491  P1=0.742 R1=0.669  (33s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[1185/1560] XGB       repeat 1 fold 0  macro-F1=0.8167  P1=0.533 R1=0.807  (8s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[1186/1560] XGB       repeat 1 fold 0  macro-F1=0.8413  P1=0.640 R1=0.746  (30s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[1187/1560] XGB       repeat 1 fold 0  macro-F1=0.7827  P1=0.433 R1=0.867  (13s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[1188/1560] XGB       repeat 1 fold 0  macro-F1=0.8397  P1=0.643 R1=0.735  (30s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[1189/1560] XGB       repeat 1 fold 0  macro-F1=0.7336  P1=0.329 R1=0.923  (6s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[1190/1560] XGB       repeat 1 fold 0  macro-F1=0.8289  P1=0.583 R1=0.773  (25s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[1191/1560] XGB       repeat 1 fold 0  macro-F1=0.6611  P1=0.218 R1=0.961  (6s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[1192/1560] XGB       repeat 1 fold 0  macro-F1=0.7502  P1=0.370 R1=0.845  (14s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[1193/1560] XGB       repeat 1 fold 0  macro-F1=0.5088  P1=0.076 R1=0.989  (4s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[1194/1560] XGB       repeat 1 fold 0  macro-F1=0.6376  P1=0.188 R1=0.972  (11s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[1195/1560] XGB       repeat 1 fold 0  macro-F1=0.8405  P1=0.641 R1=0.740  (8s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1196/1560] XGB       repeat 1 fold 0  macro-F1=0.8498  P1=0.732 R1=0.680  (22s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1197/1560] XGB       repeat 1 fold 1  macro-F1=0.8638  P1=0.853 R1=0.641  (3s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1198/1560] XGB       repeat 1 fold 1  macro-F1=0.8633  P1=0.757 R1=0.707  (9s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1199/1560] XGB       repeat 1 fold 1  macro-F1=0.8666  P1=0.771 R1=0.707  (3s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1200/1560] XGB       repeat 1 fold 1  macro-F1=0.8563  P1=0.712 R1=0.724  (10s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1201/1560] XGB       repeat 1 fold 1  macro-F1=0.8527  P1=0.684 R1=0.740  (3s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1202/1560] XGB       repeat 1 fold 1  macro-F1=0.8565  P1=0.718 R1=0.718  (10s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1203/1560] XGB       repeat 1 fold 1  macro-F1=0.8391  P1=0.618 R1=0.768  (3s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[1204/1560] XGB       repeat 1 fold 1  macro-F1=0.8432  P1=0.650 R1=0.740  (10s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[1205/1560] XGB       repeat 1 fold 1  macro-F1=0.8257  P1=0.550 R1=0.823  (3s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1206/1560] XGB       repeat 1 fold 1  macro-F1=0.8408  P1=0.655 R1=0.724  (10s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1207/1560] XGB       repeat 1 fold 1  macro-F1=0.8033  P1=0.489 R1=0.834  (3s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[1208/1560] XGB       repeat 1 fold 1  macro-F1=0.8249  P1=0.560 R1=0.796  (10s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[1209/1560] XGB       repeat 1 fold 1  macro-F1=0.7942  P1=0.458 R1=0.867  (3s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[1210/1560] XGB       repeat 1 fold 1  macro-F1=0.8527  P1=0.709 R1=0.713  (10s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[1211/1560] XGB       repeat 1 fold 1  macro-F1=0.7269  P1=0.318 R1=0.928  (3s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[1212/1560] XGB       repeat 1 fold 1  macro-F1=0.8188  P1=0.546 R1=0.790  (9s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[1213/1560] XGB       repeat 1 fold 1  macro-F1=0.8519  P1=0.711 R1=0.707  (15s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1214/1560] XGB       repeat 1 fold 1  macro-F1=0.8521  P1=0.748 R1=0.674  (42s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1215/1560] XGB       repeat 1 fold 1  macro-F1=0.8591  P1=0.697 R1=0.751  (14s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[1216/1560] XGB       repeat 1 fold 1  macro-F1=0.8576  P1=0.702 R1=0.740  (41s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[1217/1560] XGB       repeat 1 fold 1  macro-F1=0.8477  P1=0.638 R1=0.779  (14s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[1218/1560] XGB       repeat 1 fold 1  macro-F1=0.8548  P1=0.696 R1=0.735  (40s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[1219/1560] XGB       repeat 1 fold 1  macro-F1=0.8394  P1=0.599 R1=0.801  (10s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[1220/1560] XGB       repeat 1 fold 1  macro-F1=0.8494  P1=0.718 R1=0.691  (36s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[1221/1560] XGB       repeat 1 fold 1  macro-F1=0.8221  P1=0.527 R1=0.856  (10s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[1222/1560] XGB       repeat 1 fold 1  macro-F1=0.8369  P1=0.685 R1=0.674  (34s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[1223/1560] XGB       repeat 1 fold 1  macro-F1=0.7688  P1=0.396 R1=0.906  (9s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[1224/1560] XGB       repeat 1 fold 1  macro-F1=0.8350  P1=0.615 R1=0.751  (32s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[1225/1560] XGB       repeat 1 fold 1  macro-F1=0.6941  P1=0.266 R1=0.923  (9s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[1226/1560] XGB       repeat 1 fold 1  macro-F1=0.7914  P1=0.465 R1=0.818  (26s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[1227/1560] XGB       repeat 1 fold 1  macro-F1=0.5583  P1=0.109 R1=0.989  (7s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[1228/1560] XGB       repeat 1 fold 1  macro-F1=0.6779  P1=0.242 R1=0.934  (22s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[1229/1560] XGB       repeat 1 fold 1  macro-F1=0.8573  P1=0.696 R1=0.746  (9s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1230/1560] XGB       repeat 1 fold 1  macro-F1=0.8560  P1=0.706 R1=0.729  (32s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1231/1560] XGB       repeat 1 fold 1  macro-F1=0.8655  P1=0.711 R1=0.762  (16s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1232/1560] XGB       repeat 1 fold 1  macro-F1=0.8625  P1=0.701 R1=0.762  (56s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1233/1560] XGB       repeat 1 fold 1  macro-F1=0.8602  P1=0.688 R1=0.768  (19s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[1234/1560] XGB       repeat 1 fold 1  macro-F1=0.8550  P1=0.702 R1=0.729  (58s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[1235/1560] XGB       repeat 1 fold 1  macro-F1=0.8533  P1=0.642 R1=0.801  (19s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[1236/1560] XGB       repeat 1 fold 1  macro-F1=0.8434  P1=0.694 R1=0.691  (50s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[1237/1560] XGB       repeat 1 fold 1  macro-F1=0.8342  P1=0.573 R1=0.823  (19s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[1238/1560] XGB       repeat 1 fold 1  macro-F1=0.8392  P1=0.663 R1=0.707  (51s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[1239/1560] XGB       repeat 1 fold 1  macro-F1=0.8081  P1=0.486 R1=0.878  (13s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[1240/1560] XGB       repeat 1 fold 1  macro-F1=0.8367  P1=0.621 R1=0.751  (50s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[1241/1560] XGB       repeat 1 fold 1  macro-F1=0.7351  P1=0.332 R1=0.923  (13s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[1242/1560] XGB       repeat 1 fold 1  macro-F1=0.8291  P1=0.611 R1=0.729  (43s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[1243/1560] XGB       repeat 1 fold 1  macro-F1=0.6660  P1=0.225 R1=0.956  (13s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[1244/1560] XGB       repeat 1 fold 1  macro-F1=0.7542  P1=0.374 R1=0.873  (36s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[1245/1560] XGB       repeat 1 fold 1  macro-F1=0.5134  P1=0.079 R1=0.994  (11s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[1246/1560] XGB       repeat 1 fold 1  macro-F1=0.6569  P1=0.213 R1=0.950  (37s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[1247/1560] XGB       repeat 1 fold 1  macro-F1=0.8655  P1=0.711 R1=0.762  (13s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1248/1560] XGB       repeat 1 fold 1  macro-F1=0.8625  P1=0.701 R1=0.762  (36s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1249/1560] XGB       repeat 2 fold 0  macro-F1=0.8747  P1=0.913 R1=0.641  (5s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1250/1560] XGB       repeat 2 fold 0  macro-F1=0.8876  P1=0.769 R1=0.790  (15s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1251/1560] XGB       repeat 2 fold 0  macro-F1=0.8843  P1=0.843 R1=0.713  (5s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1252/1560] XGB       repeat 2 fold 0  macro-F1=0.8816  P1=0.778 R1=0.757  (15s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1253/1560] XGB       repeat 2 fold 0  macro-F1=0.8832  P1=0.791 R1=0.751  (5s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1254/1560] XGB       repeat 2 fold 0  macro-F1=0.8842  P1=0.766 R1=0.779  (16s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1255/1560] XGB       repeat 2 fold 0  macro-F1=0.8824  P1=0.740 R1=0.801  (5s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[1256/1560] XGB       repeat 2 fold 0  macro-F1=0.8859  P1=0.768 R1=0.785  (16s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[1257/1560] XGB       repeat 2 fold 0  macro-F1=0.8763  P1=0.698 R1=0.829  (5s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1258/1560] XGB       repeat 2 fold 0  macro-F1=0.8857  P1=0.742 R1=0.812  (15s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1259/1560] XGB       repeat 2 fold 0  macro-F1=0.8434  P1=0.586 R1=0.851  (5s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[1260/1560] XGB       repeat 2 fold 0  macro-F1=0.8776  P1=0.694 R1=0.840  (13s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[1261/1560] XGB       repeat 2 fold 0  macro-F1=0.8175  P1=0.503 R1=0.895  (4s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[1262/1560] XGB       repeat 2 fold 0  macro-F1=0.8760  P1=0.726 R1=0.790  (12s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[1263/1560] XGB       repeat 2 fold 0  macro-F1=0.6904  P1=0.258 R1=0.967  (3s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[1264/1560] XGB       repeat 2 fold 0  macro-F1=0.7953  P1=0.456 R1=0.884  (9s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[1265/1560] XGB       repeat 2 fold 0  macro-F1=0.8753  P1=0.728 R1=0.785  (8s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1266/1560] XGB       repeat 2 fold 0  macro-F1=0.8740  P1=0.733 R1=0.773  (22s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1267/1560] XGB       repeat 2 fold 0  macro-F1=0.8779  P1=0.699 R1=0.834  (8s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[1268/1560] XGB       repeat 2 fold 0  macro-F1=0.8827  P1=0.755 R1=0.785  (19s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[1269/1560] XGB       repeat 2 fold 0  macro-F1=0.8466  P1=0.595 R1=0.851  (7s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[1270/1560] XGB       repeat 2 fold 0  macro-F1=0.8753  P1=0.728 R1=0.785  (21s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[1271/1560] XGB       repeat 2 fold 0  macro-F1=0.8116  P1=0.489 R1=0.895  (7s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[1272/1560] XGB       repeat 2 fold 0  macro-F1=0.8780  P1=0.733 R1=0.790  (17s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[1273/1560] XGB       repeat 2 fold 0  macro-F1=0.7561  P1=0.369 R1=0.923  (4s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[1274/1560] XGB       repeat 2 fold 0  macro-F1=0.8696  P1=0.712 R1=0.779  (17s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[1275/1560] XGB       repeat 2 fold 0  macro-F1=0.6820  P1=0.246 R1=0.967  (4s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[1276/1560] XGB       repeat 2 fold 0  macro-F1=0.8142  P1=0.514 R1=0.840  (12s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[1277/1560] XGB       repeat 2 fold 0  macro-F1=0.6223  P1=0.171 R1=0.978  (4s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[1278/1560] XGB       repeat 2 fold 0  macro-F1=0.7219  P1=0.310 R1=0.917  (10s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[1279/1560] XGB       repeat 2 fold 0  macro-F1=0.4010  P1=0.041 R1=0.994  (3s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[1280/1560] XGB       repeat 2 fold 0  macro-F1=0.4010  P1=0.041 R1=0.994  (10s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[1281/1560] XGB       repeat 2 fold 0  macro-F1=0.8771  P1=0.708 R1=0.818  (5s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1282/1560] XGB       repeat 2 fold 0  macro-F1=0.8769  P1=0.716 R1=0.807  (16s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1283/1560] XGB       repeat 2 fold 0  macro-F1=0.8659  P1=0.704 R1=0.773  (10s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1284/1560] XGB       repeat 2 fold 0  macro-F1=0.8652  P1=0.706 R1=0.768  (31s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1285/1560] XGB       repeat 2 fold 0  macro-F1=0.8554  P1=0.638 R1=0.818  (10s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[1286/1560] XGB       repeat 2 fold 0  macro-F1=0.8699  P1=0.718 R1=0.773  (32s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[1287/1560] XGB       repeat 2 fold 0  macro-F1=0.8359  P1=0.554 R1=0.878  (9s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[1288/1560] XGB       repeat 2 fold 0  macro-F1=0.8642  P1=0.662 R1=0.823  (27s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[1289/1560] XGB       repeat 2 fold 0  macro-F1=0.7994  P1=0.459 R1=0.906  (6s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[1290/1560] XGB       repeat 2 fold 0  macro-F1=0.8789  P1=0.723 R1=0.807  (34s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[1291/1560] XGB       repeat 2 fold 0  macro-F1=0.7328  P1=0.326 R1=0.945  (6s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[1292/1560] XGB       repeat 2 fold 0  macro-F1=0.8581  P1=0.694 R1=0.751  (28s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[1293/1560] XGB       repeat 2 fold 0  macro-F1=0.6546  P1=0.209 R1=0.972  (6s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[1294/1560] XGB       repeat 2 fold 0  macro-F1=0.7658  P1=0.392 R1=0.895  (26s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[1295/1560] XGB       repeat 2 fold 0  macro-F1=0.5944  P1=0.141 R1=0.983  (6s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[1296/1560] XGB       repeat 2 fold 0  macro-F1=0.6981  P1=0.271 R1=0.934  (16s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[1297/1560] XGB       repeat 2 fold 0  macro-F1=0.0178  P1=0.018 R1=1.000  (4s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[1298/1560] XGB       repeat 2 fold 0  macro-F1=0.0178  P1=0.018 R1=1.000  (16s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[1299/1560] XGB       repeat 2 fold 0  macro-F1=0.8659  P1=0.704 R1=0.773  (8s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1300/1560] XGB       repeat 2 fold 0  macro-F1=0.8652  P1=0.706 R1=0.768  (21s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1301/1560] XGB       repeat 2 fold 1  macro-F1=0.8610  P1=0.796 R1=0.669  (9s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1302/1560] XGB       repeat 2 fold 1  macro-F1=0.8588  P1=0.786 R1=0.669  (26s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1303/1560] XGB       repeat 2 fold 1  macro-F1=0.8596  P1=0.730 R1=0.718  (9s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1304/1560] XGB       repeat 2 fold 1  macro-F1=0.8546  P1=0.806 R1=0.641  (28s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1305/1560] XGB       repeat 2 fold 1  macro-F1=0.8620  P1=0.708 R1=0.751  (10s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1306/1560] XGB       repeat 2 fold 1  macro-F1=0.8553  P1=0.762 R1=0.674  (30s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1307/1560] XGB       repeat 2 fold 1  macro-F1=0.8619  P1=0.690 R1=0.773  (10s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[1308/1560] XGB       repeat 2 fold 1  macro-F1=0.8472  P1=0.786 R1=0.630  (32s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[1309/1560] XGB       repeat 2 fold 1  macro-F1=0.8597  P1=0.662 R1=0.801  (10s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1310/1560] XGB       repeat 2 fold 1  macro-F1=0.8567  P1=0.664 R1=0.785  (34s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1311/1560] XGB       repeat 2 fold 1  macro-F1=0.8480  P1=0.610 R1=0.829  (10s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[1312/1560] XGB       repeat 2 fold 1  macro-F1=0.8523  P1=0.673 R1=0.751  (32s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[1313/1560] XGB       repeat 2 fold 1  macro-F1=0.8235  P1=0.535 R1=0.845  (9s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[1314/1560] XGB       repeat 2 fold 1  macro-F1=0.8502  P1=0.747 R1=0.669  (30s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[1315/1560] XGB       repeat 2 fold 1  macro-F1=0.7302  P1=0.321 R1=0.950  (7s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[1316/1560] XGB       repeat 2 fold 1  macro-F1=0.7992  P1=0.498 R1=0.779  (21s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[1317/1560] XGB       repeat 2 fold 1  macro-F1=0.8629  P1=0.727 R1=0.735  (12s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1318/1560] XGB       repeat 2 fold 1  macro-F1=0.8595  P1=0.673 R1=0.785  (31s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1319/1560] XGB       repeat 2 fold 1  macro-F1=0.8590  P1=0.680 R1=0.773  (9s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[1320/1560] XGB       repeat 2 fold 1  macro-F1=0.8529  P1=0.745 R1=0.680  (28s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[1321/1560] XGB       repeat 2 fold 1  macro-F1=0.8520  P1=0.648 R1=0.785  (11s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[1322/1560] XGB       repeat 2 fold 1  macro-F1=0.8619  P1=0.690 R1=0.773  (27s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[1323/1560] XGB       repeat 2 fold 1  macro-F1=0.8488  P1=0.628 R1=0.801  (8s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[1324/1560] XGB       repeat 2 fold 1  macro-F1=0.8549  P1=0.723 R1=0.707  (26s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[1325/1560] XGB       repeat 2 fold 1  macro-F1=0.8344  P1=0.582 R1=0.807  (6s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[1326/1560] XGB       repeat 2 fold 1  macro-F1=0.8578  P1=0.729 R1=0.713  (22s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[1327/1560] XGB       repeat 2 fold 1  macro-F1=0.8026  P1=0.472 R1=0.884  (7s)  [ratio 0.5, orig^1.25, C=0, rho=73.60]

[1328/1560] XGB       repeat 2 fold 1  macro-F1=0.8322  P1=0.590 R1=0.779  (23s)  [ratio 0.5, orig^1.25, C=1, rho=73.60]

[1329/1560] XGB       repeat 2 fold 1  macro-F1=0.7460  P1=0.349 R1=0.939  (6s)  [ratio 0.5, orig^1.5, C=0, rho=199.74]

[1330/1560] XGB       repeat 2 fold 1  macro-F1=0.7953  P1=0.512 R1=0.724  (16s)  [ratio 0.5, orig^1.5, C=1, rho=199.74]

[1331/1560] XGB       repeat 2 fold 1  macro-F1=0.5355  P1=0.093 R1=0.994  (4s)  [ratio 0.5, orig^2.0, C=0, rho=1471.16]

[1332/1560] XGB       repeat 2 fold 1  macro-F1=0.6614  P1=0.218 R1=0.978  (13s)  [ratio 0.5, orig^2.0, C=1, rho=1471.16]

[1333/1560] XGB       repeat 2 fold 1  macro-F1=0.8645  P1=0.708 R1=0.762  (6s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1334/1560] XGB       repeat 2 fold 1  macro-F1=0.8642  P1=0.737 R1=0.729  (19s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1335/1560] XGB       repeat 2 fold 1  macro-F1=0.8509  P1=0.682 R1=0.735  (12s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1336/1560] XGB       repeat 2 fold 1  macro-F1=0.8515  P1=0.675 R1=0.746  (39s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1337/1560] XGB       repeat 2 fold 1  macro-F1=0.8632  P1=0.698 R1=0.768  (12s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[1338/1560] XGB       repeat 2 fold 1  macro-F1=0.8583  P1=0.743 R1=0.702  (41s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[1339/1560] XGB       repeat 2 fold 1  macro-F1=0.8537  P1=0.650 R1=0.790  (13s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[1340/1560] XGB       repeat 2 fold 1  macro-F1=0.8494  P1=0.797 R1=0.630  (38s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[1341/1560] XGB       repeat 2 fold 1  macro-F1=0.8445  P1=0.614 R1=0.801  (11s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[1342/1560] XGB       repeat 2 fold 1  macro-F1=0.8507  P1=0.729 R1=0.685  (45s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[1343/1560] XGB       repeat 2 fold 1  macro-F1=0.8265  P1=0.549 R1=0.829  (11s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[1344/1560] XGB       repeat 2 fold 1  macro-F1=0.8327  P1=0.766 R1=0.597  (41s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[1345/1560] XGB       repeat 2 fold 1  macro-F1=0.7799  P1=0.418 R1=0.906  (10s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[1346/1560] XGB       repeat 2 fold 1  macro-F1=0.8059  P1=0.552 R1=0.707  (31s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[1347/1560] XGB       repeat 2 fold 1  macro-F1=0.7041  P1=0.279 R1=0.956  (10s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[1348/1560] XGB       repeat 2 fold 1  macro-F1=0.7697  P1=0.431 R1=0.762  (26s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[1349/1560] XGB       repeat 2 fold 1  macro-F1=0.4813  P1=0.063 R1=0.994  (7s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[1350/1560] XGB       repeat 2 fold 1  macro-F1=0.6316  P1=0.181 R1=0.983  (27s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[1351/1560] XGB       repeat 2 fold 1  macro-F1=0.8509  P1=0.682 R1=0.735  (11s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1352/1560] XGB       repeat 2 fold 1  macro-F1=0.8515  P1=0.675 R1=0.746  (26s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1353/1560] XGB       repeat 3 fold 0  macro-F1=0.8229  P1=0.829 R1=0.536  (5s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1354/1560] XGB       repeat 3 fold 0  macro-F1=0.8252  P1=0.818 R1=0.547  (14s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1355/1560] XGB       repeat 3 fold 0  macro-F1=0.8340  P1=0.812 R1=0.575  (5s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1356/1560] XGB       repeat 3 fold 0  macro-F1=0.8444  P1=0.742 R1=0.652  (15s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1357/1560] XGB       repeat 3 fold 0  macro-F1=0.8444  P1=0.799 R1=0.613  (5s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1358/1560] XGB       repeat 3 fold 0  macro-F1=0.8319  P1=0.835 R1=0.558  (16s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1359/1560] XGB       repeat 3 fold 0  macro-F1=0.8563  P1=0.797 R1=0.652  (5s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[1360/1560] XGB       repeat 3 fold 0  macro-F1=0.8578  P1=0.753 R1=0.691  (17s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[1361/1560] XGB       repeat 3 fold 0  macro-F1=0.8523  P1=0.756 R1=0.669  (6s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1362/1560] XGB       repeat 3 fold 0  macro-F1=0.8389  P1=0.771 R1=0.613  (16s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1363/1560] XGB       repeat 3 fold 0  macro-F1=0.8521  P1=0.691 R1=0.729  (5s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[1364/1560] XGB       repeat 3 fold 0  macro-F1=0.8594  P1=0.747 R1=0.702  (15s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[1365/1560] XGB       repeat 3 fold 0  macro-F1=0.8428  P1=0.637 R1=0.757  (5s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[1366/1560] XGB       repeat 3 fold 0  macro-F1=0.8358  P1=0.764 R1=0.608  (14s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[1367/1560] XGB       repeat 3 fold 0  macro-F1=0.7442  P1=0.348 R1=0.923  (3s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[1368/1560] XGB       repeat 3 fold 0  macro-F1=0.8184  P1=0.567 R1=0.746  (10s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[1369/1560] XGB       repeat 3 fold 0  macro-F1=0.8362  P1=0.707 R1=0.652  (7s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1370/1560] XGB       repeat 3 fold 0  macro-F1=0.8390  P1=0.699 R1=0.669  (17s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1371/1560] XGB       repeat 3 fold 0  macro-F1=0.8446  P1=0.705 R1=0.685  (3s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[1372/1560] XGB       repeat 3 fold 0  macro-F1=0.8275  P1=0.740 R1=0.597  (16s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[1373/1560] XGB       repeat 3 fold 0  macro-F1=0.8382  P1=0.655 R1=0.713  (6s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[1374/1560] XGB       repeat 3 fold 0  macro-F1=0.8407  P1=0.755 R1=0.630  (14s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[1375/1560] XGB       repeat 3 fold 0  macro-F1=0.8179  P1=0.593 R1=0.702  (6s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[1376/1560] XGB       repeat 3 fold 0  macro-F1=0.8204  P1=0.855 R1=0.519  (17s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[1377/1560] XGB       repeat 3 fold 0  macro-F1=0.8139  P1=0.545 R1=0.762  (3s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[1378/1560] XGB       repeat 3 fold 0  macro-F1=0.8415  P1=0.744 R1=0.641  (13s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[1379/1560] XGB       repeat 3 fold 0  macro-F1=0.7569  P1=0.385 R1=0.840  (3s)  [ratio 0.5, orig^1.25, C=0, rho=73.60]

[1380/1560] XGB       repeat 3 fold 0  macro-F1=0.8074  P1=0.669 R1=0.580  (10s)  [ratio 0.5, orig^1.25, C=1, rho=73.60]

[1381/1560] XGB       repeat 3 fold 0  macro-F1=0.7024  P1=0.279 R1=0.917  (3s)  [ratio 0.5, orig^1.5, C=0, rho=199.74]

[1382/1560] XGB       repeat 3 fold 0  macro-F1=0.7918  P1=0.494 R1=0.740  (8s)  [ratio 0.5, orig^1.5, C=1, rho=199.74]

[1383/1560] XGB       repeat 3 fold 0  macro-F1=0.5251  P1=0.086 R1=0.989  (2s)  [ratio 0.5, orig^2.0, C=0, rho=1471.16]

[1384/1560] XGB       repeat 3 fold 0  macro-F1=0.6696  P1=0.229 R1=0.956  (11s)  [ratio 0.5, orig^2.0, C=1, rho=1471.16]

[1385/1560] XGB       repeat 3 fold 0  macro-F1=0.8389  P1=0.693 R1=0.674  (3s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1386/1560] XGB       repeat 3 fold 0  macro-F1=0.8307  P1=0.784 R1=0.580  (9s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1387/1560] XGB       repeat 3 fold 0  macro-F1=0.8362  P1=0.707 R1=0.652  (8s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1388/1560] XGB       repeat 3 fold 0  macro-F1=0.8335  P1=0.729 R1=0.624  (25s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1389/1560] XGB       repeat 3 fold 0  macro-F1=0.8320  P1=0.656 R1=0.685  (8s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[1390/1560] XGB       repeat 3 fold 0  macro-F1=0.8296  P1=0.759 R1=0.591  (24s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[1391/1560] XGB       repeat 3 fold 0  macro-F1=0.8274  P1=0.630 R1=0.696  (9s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[1392/1560] XGB       repeat 3 fold 0  macro-F1=0.8367  P1=0.752 R1=0.619  (25s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[1393/1560] XGB       repeat 3 fold 0  macro-F1=0.8151  P1=0.564 R1=0.735  (3s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[1394/1560] XGB       repeat 3 fold 0  macro-F1=0.8264  P1=0.743 R1=0.591  (20s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[1395/1560] XGB       repeat 3 fold 0  macro-F1=0.7893  P1=0.473 R1=0.779  (4s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[1396/1560] XGB       repeat 3 fold 0  macro-F1=0.8210  P1=0.640 R1=0.657  (20s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[1397/1560] XGB       repeat 3 fold 0  macro-F1=0.7396  P1=0.344 R1=0.890  (4s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[1398/1560] XGB       repeat 3 fold 0  macro-F1=0.8265  P1=0.661 R1=0.657  (18s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[1399/1560] XGB       repeat 3 fold 0  macro-F1=0.6694  P1=0.230 R1=0.934  (3s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[1400/1560] XGB       repeat 3 fold 0  macro-F1=0.7552  P1=0.392 R1=0.790  (10s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[1401/1560] XGB       repeat 3 fold 0  macro-F1=0.4582  P1=0.055 R1=0.994  (3s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[1402/1560] XGB       repeat 3 fold 0  macro-F1=0.6452  P1=0.198 R1=0.972  (9s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[1403/1560] XGB       repeat 3 fold 0  macro-F1=0.8362  P1=0.707 R1=0.652  (4s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1404/1560] XGB       repeat 3 fold 0  macro-F1=0.8335  P1=0.729 R1=0.624  (10s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1405/1560] XGB       repeat 3 fold 1  macro-F1=0.8519  P1=0.819 R1=0.624  (7s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1406/1560] XGB       repeat 3 fold 1  macro-F1=0.8606  P1=0.713 R1=0.740  (20s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1407/1560] XGB       repeat 3 fold 1  macro-F1=0.8547  P1=0.774 R1=0.663  (7s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1408/1560] XGB       repeat 3 fold 1  macro-F1=0.8569  P1=0.685 R1=0.757  (20s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1409/1560] XGB       repeat 3 fold 1  macro-F1=0.8536  P1=0.735 R1=0.691  (7s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1410/1560] XGB       repeat 3 fold 1  macro-F1=0.8525  P1=0.764 R1=0.663  (21s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1411/1560] XGB       repeat 3 fold 1  macro-F1=0.8591  P1=0.717 R1=0.729  (7s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[1412/1560] XGB       repeat 3 fold 1  macro-F1=0.8536  P1=0.769 R1=0.663  (22s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[1413/1560] XGB       repeat 3 fold 1  macro-F1=0.8568  P1=0.704 R1=0.735  (7s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1414/1560] XGB       repeat 3 fold 1  macro-F1=0.8588  P1=0.733 R1=0.713  (22s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1415/1560] XGB       repeat 3 fold 1  macro-F1=0.8386  P1=0.631 R1=0.746  (7s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[1416/1560] XGB       repeat 3 fold 1  macro-F1=0.8494  P1=0.718 R1=0.691  (22s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[1417/1560] XGB       repeat 3 fold 1  macro-F1=0.8305  P1=0.576 R1=0.796  (7s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[1418/1560] XGB       repeat 3 fold 1  macro-F1=0.8523  P1=0.673 R1=0.751  (20s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[1419/1560] XGB       repeat 3 fold 1  macro-F1=0.7431  P1=0.343 R1=0.950  (6s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[1420/1560] XGB       repeat 3 fold 1  macro-F1=0.8209  P1=0.563 R1=0.768  (15s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[1421/1560] XGB       repeat 3 fold 1  macro-F1=0.8540  P1=0.675 R1=0.757  (6s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1422/1560] XGB       repeat 3 fold 1  macro-F1=0.8567  P1=0.664 R1=0.785  (18s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1423/1560] XGB       repeat 3 fold 1  macro-F1=0.8366  P1=0.613 R1=0.762  (3s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[1424/1560] XGB       repeat 3 fold 1  macro-F1=0.8317  P1=0.624 R1=0.724  (17s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[1425/1560] XGB       repeat 3 fold 1  macro-F1=0.8353  P1=0.590 R1=0.796  (3s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[1426/1560] XGB       repeat 3 fold 1  macro-F1=0.8508  P1=0.656 R1=0.768  (14s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[1427/1560] XGB       repeat 3 fold 1  macro-F1=0.8142  P1=0.514 R1=0.840  (6s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[1428/1560] XGB       repeat 3 fold 1  macro-F1=0.8377  P1=0.594 R1=0.801  (16s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[1429/1560] XGB       repeat 3 fold 1  macro-F1=0.7771  P1=0.416 R1=0.890  (6s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[1430/1560] XGB       repeat 3 fold 1  macro-F1=0.8341  P1=0.609 R1=0.757  (9s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[1431/1560] XGB       repeat 3 fold 1  macro-F1=0.6925  P1=0.262 R1=0.956  (3s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[1432/1560] XGB       repeat 3 fold 1  macro-F1=0.8028  P1=0.505 R1=0.785  (12s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[1433/1560] XGB       repeat 3 fold 1  macro-F1=0.6277  P1=0.177 R1=0.978  (3s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[1434/1560] XGB       repeat 3 fold 1  macro-F1=0.7317  P1=0.327 R1=0.912  (8s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[1435/1560] XGB       repeat 3 fold 1  macro-F1=0.4198  P1=0.044 R1=0.994  (2s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[1436/1560] XGB       repeat 3 fold 1  macro-F1=0.4198  P1=0.044 R1=0.994  (8s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[1437/1560] XGB       repeat 3 fold 1  macro-F1=0.8333  P1=0.614 R1=0.746  (3s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1438/1560] XGB       repeat 3 fold 1  macro-F1=0.8407  P1=0.650 R1=0.729  (9s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1439/1560] XGB       repeat 3 fold 1  macro-F1=0.8504  P1=0.667 R1=0.751  (9s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1440/1560] XGB       repeat 3 fold 1  macro-F1=0.8432  P1=0.624 R1=0.779  (24s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1441/1560] XGB       repeat 3 fold 1  macro-F1=0.8249  P1=0.574 R1=0.768  (9s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[1442/1560] XGB       repeat 3 fold 1  macro-F1=0.8383  P1=0.619 R1=0.762  (24s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[1443/1560] XGB       repeat 3 fold 1  macro-F1=0.8203  P1=0.548 R1=0.796  (9s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[1444/1560] XGB       repeat 3 fold 1  macro-F1=0.8369  P1=0.629 R1=0.740  (24s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[1445/1560] XGB       repeat 3 fold 1  macro-F1=0.8084  P1=0.494 R1=0.856  (3s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[1446/1560] XGB       repeat 3 fold 1  macro-F1=0.8474  P1=0.652 R1=0.757  (19s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[1447/1560] XGB       repeat 3 fold 1  macro-F1=0.7459  P1=0.352 R1=0.917  (4s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[1448/1560] XGB       repeat 3 fold 1  macro-F1=0.8247  P1=0.625 R1=0.691  (19s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[1449/1560] XGB       repeat 3 fold 1  macro-F1=0.6643  P1=0.222 R1=0.967  (3s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[1450/1560] XGB       repeat 3 fold 1  macro-F1=0.7661  P1=0.405 R1=0.834  (18s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[1451/1560] XGB       repeat 3 fold 1  macro-F1=0.5886  P1=0.136 R1=0.978  (3s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[1452/1560] XGB       repeat 3 fold 1  macro-F1=0.6941  P1=0.265 R1=0.934  (9s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[1453/1560] XGB       repeat 3 fold 1  macro-F1=0.0178  P1=0.018 R1=1.000  (3s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[1454/1560] XGB       repeat 3 fold 1  macro-F1=0.0178  P1=0.018 R1=1.000  (9s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[1455/1560] XGB       repeat 3 fold 1  macro-F1=0.8504  P1=0.667 R1=0.751  (4s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1456/1560] XGB       repeat 3 fold 1  macro-F1=0.8432  P1=0.624 R1=0.779  (10s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1457/1560] XGB       repeat 4 fold 0  macro-F1=0.8580  P1=0.823 R1=0.641  (2s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1458/1560] XGB       repeat 4 fold 0  macro-F1=0.8636  P1=0.724 R1=0.740  (9s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1459/1560] XGB       repeat 4 fold 0  macro-F1=0.8608  P1=0.787 R1=0.674  (3s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1460/1560] XGB       repeat 4 fold 0  macro-F1=0.8608  P1=0.787 R1=0.674  (9s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1461/1560] XGB       repeat 4 fold 0  macro-F1=0.8748  P1=0.746 R1=0.762  (3s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1462/1560] XGB       repeat 4 fold 0  macro-F1=0.8762  P1=0.757 R1=0.757  (9s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1463/1560] XGB       repeat 4 fold 0  macro-F1=0.8506  P1=0.651 R1=0.773  (3s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[1464/1560] XGB       repeat 4 fold 0  macro-F1=0.8574  P1=0.678 R1=0.768  (9s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[1465/1560] XGB       repeat 4 fold 0  macro-F1=0.8371  P1=0.598 R1=0.790  (3s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1466/1560] XGB       repeat 4 fold 0  macro-F1=0.8561  P1=0.687 R1=0.751  (9s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1467/1560] XGB       repeat 4 fold 0  macro-F1=0.8235  P1=0.535 R1=0.845  (3s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[1468/1560] XGB       repeat 4 fold 0  macro-F1=0.8525  P1=0.678 R1=0.746  (9s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[1469/1560] XGB       repeat 4 fold 0  macro-F1=0.8106  P1=0.494 R1=0.873  (3s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[1470/1560] XGB       repeat 4 fold 0  macro-F1=0.8544  P1=0.733 R1=0.696  (8s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[1471/1560] XGB       repeat 4 fold 0  macro-F1=0.7328  P1=0.326 R1=0.945  (2s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[1472/1560] XGB       repeat 4 fold 0  macro-F1=0.8227  P1=0.546 R1=0.812  (7s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[1473/1560] XGB       repeat 4 fold 0  macro-F1=0.8450  P1=0.684 R1=0.707  (6s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1474/1560] XGB       repeat 4 fold 0  macro-F1=0.8410  P1=0.665 R1=0.713  (16s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1475/1560] XGB       repeat 4 fold 0  macro-F1=0.8379  P1=0.636 R1=0.735  (6s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[1476/1560] XGB       repeat 4 fold 0  macro-F1=0.8395  P1=0.634 R1=0.746  (16s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[1477/1560] XGB       repeat 4 fold 0  macro-F1=0.8405  P1=0.612 R1=0.785  (6s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[1478/1560] XGB       repeat 4 fold 0  macro-F1=0.8548  P1=0.696 R1=0.735  (13s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[1479/1560] XGB       repeat 4 fold 0  macro-F1=0.8140  P1=0.519 R1=0.823  (6s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[1480/1560] XGB       repeat 4 fold 0  macro-F1=0.8402  P1=0.667 R1=0.707  (13s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[1481/1560] XGB       repeat 4 fold 0  macro-F1=0.7804  P1=0.419 R1=0.906  (3s)  [ratio 0.5, orig^1.0, C=0, rho=27.12]

[1482/1560] XGB       repeat 4 fold 0  macro-F1=0.8265  P1=0.614 R1=0.713  (13s)  [ratio 0.5, orig^1.0, C=1, rho=27.12]

[1483/1560] XGB       repeat 4 fold 0  macro-F1=0.7018  P1=0.275 R1=0.956  (3s)  [ratio 0.5, orig^1.25, C=0, rho=73.61]

[1484/1560] XGB       repeat 4 fold 0  macro-F1=0.7895  P1=0.484 R1=0.751  (8s)  [ratio 0.5, orig^1.25, C=1, rho=73.61]

[1485/1560] XGB       repeat 4 fold 0  macro-F1=0.6402  P1=0.192 R1=0.972  (2s)  [ratio 0.5, orig^1.5, C=0, rho=199.76]

[1486/1560] XGB       repeat 4 fold 0  macro-F1=0.7232  P1=0.314 R1=0.906  (7s)  [ratio 0.5, orig^1.5, C=1, rho=199.76]

[1487/1560] XGB       repeat 4 fold 0  macro-F1=0.4022  P1=0.041 R1=0.994  (2s)  [ratio 0.5, orig^2.0, C=0, rho=1471.31]

[1488/1560] XGB       repeat 4 fold 0  macro-F1=0.4022  P1=0.041 R1=0.994  (8s)  [ratio 0.5, orig^2.0, C=1, rho=1471.31]

[1489/1560] XGB       repeat 4 fold 0  macro-F1=0.8399  P1=0.652 R1=0.724  (3s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1490/1560] XGB       repeat 4 fold 0  macro-F1=0.8414  P1=0.644 R1=0.740  (9s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1491/1560] XGB       repeat 4 fold 0  macro-F1=0.8373  P1=0.652 R1=0.713  (9s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1492/1560] XGB       repeat 4 fold 0  macro-F1=0.8408  P1=0.655 R1=0.724  (25s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1493/1560] XGB       repeat 4 fold 0  macro-F1=0.8454  P1=0.642 R1=0.762  (9s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[1494/1560] XGB       repeat 4 fold 0  macro-F1=0.8541  P1=0.698 R1=0.729  (25s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[1495/1560] XGB       repeat 4 fold 0  macro-F1=0.8226  P1=0.556 R1=0.790  (9s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[1496/1560] XGB       repeat 4 fold 0  macro-F1=0.8417  P1=0.658 R1=0.724  (26s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[1497/1560] XGB       repeat 4 fold 0  macro-F1=0.7986  P1=0.472 R1=0.851  (4s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[1498/1560] XGB       repeat 4 fold 0  macro-F1=0.8464  P1=0.706 R1=0.691  (20s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[1499/1560] XGB       repeat 4 fold 0  macro-F1=0.7485  P1=0.357 R1=0.912  (4s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[1500/1560] XGB       repeat 4 fold 0  macro-F1=0.8142  P1=0.597 R1=0.680  (20s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[1501/1560] XGB       repeat 4 fold 0  macro-F1=0.6718  P1=0.232 R1=0.961  (4s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[1502/1560] XGB       repeat 4 fold 0  macro-F1=0.7611  P1=0.389 R1=0.862  (18s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[1503/1560] XGB       repeat 4 fold 0  macro-F1=0.5988  P1=0.146 R1=0.978  (3s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[1504/1560] XGB       repeat 4 fold 0  macro-F1=0.6941  P1=0.266 R1=0.923  (9s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[1505/1560] XGB       repeat 4 fold 0  macro-F1=0.0178  P1=0.018 R1=1.000  (3s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[1506/1560] XGB       repeat 4 fold 0  macro-F1=0.0178  P1=0.018 R1=1.000  (9s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[1507/1560] XGB       repeat 4 fold 0  macro-F1=0.8373  P1=0.652 R1=0.713  (4s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1508/1560] XGB       repeat 4 fold 0  macro-F1=0.8408  P1=0.655 R1=0.724  (10s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1509/1560] XGB       repeat 4 fold 1  macro-F1=0.8441  P1=0.779 R1=0.624  (4s)  [ratio 0.0, orig^0.0, C=0, rho=0.02]

[1510/1560] XGB       repeat 4 fold 1  macro-F1=0.8441  P1=0.779 R1=0.624  (11s)  [ratio 0.0, orig^0.0, C=1, rho=0.02]

[1511/1560] XGB       repeat 4 fold 1  macro-F1=0.8326  P1=0.740 R1=0.613  (4s)  [ratio 0.0, orig^0.25, C=0, rho=0.05]

[1512/1560] XGB       repeat 4 fold 1  macro-F1=0.8490  P1=0.735 R1=0.674  (11s)  [ratio 0.0, orig^0.25, C=1, rho=0.05]

[1513/1560] XGB       repeat 4 fold 1  macro-F1=0.8643  P1=0.781 R1=0.691  (4s)  [ratio 0.0, orig^0.5, C=0, rho=0.14]

[1514/1560] XGB       repeat 4 fold 1  macro-F1=0.8580  P1=0.736 R1=0.707  (11s)  [ratio 0.0, orig^0.5, C=1, rho=0.14]

[1515/1560] XGB       repeat 4 fold 1  macro-F1=0.8493  P1=0.712 R1=0.696  (3s)  [ratio 0.0, orig^0.75, C=0, rho=0.37]

[1516/1560] XGB       repeat 4 fold 1  macro-F1=0.8464  P1=0.800 R1=0.619  (11s)  [ratio 0.0, orig^0.75, C=1, rho=0.37]

[1517/1560] XGB       repeat 4 fold 1  macro-F1=0.8556  P1=0.694 R1=0.740  (4s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1518/1560] XGB       repeat 4 fold 1  macro-F1=0.8541  P1=0.787 R1=0.652  (11s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1519/1560] XGB       repeat 4 fold 1  macro-F1=0.8342  P1=0.620 R1=0.740  (4s)  [ratio 0.0, orig^1.25, C=0, rho=2.71]

[1520/1560] XGB       repeat 4 fold 1  macro-F1=0.8381  P1=0.708 R1=0.657  (11s)  [ratio 0.0, orig^1.25, C=1, rho=2.71]

[1521/1560] XGB       repeat 4 fold 1  macro-F1=0.8351  P1=0.578 R1=0.818  (3s)  [ratio 0.0, orig^1.5, C=0, rho=7.37]

[1522/1560] XGB       repeat 4 fold 1  macro-F1=0.8315  P1=0.727 R1=0.619  (11s)  [ratio 0.0, orig^1.5, C=1, rho=7.37]

[1523/1560] XGB       repeat 4 fold 1  macro-F1=0.7515  P1=0.360 R1=0.934  (3s)  [ratio 0.0, orig^2.0, C=0, rho=54.25]

[1524/1560] XGB       repeat 4 fold 1  macro-F1=0.8125  P1=0.539 R1=0.768  (9s)  [ratio 0.0, orig^2.0, C=1, rho=54.25]

[1525/1560] XGB       repeat 4 fold 1  macro-F1=0.8393  P1=0.668 R1=0.702  (10s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1526/1560] XGB       repeat 4 fold 1  macro-F1=0.8391  P1=0.658 R1=0.713  (28s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1527/1560] XGB       repeat 4 fold 1  macro-F1=0.8381  P1=0.650 R1=0.718  (10s)  [ratio 0.5, orig^0.25, C=0, rho=1.36]

[1528/1560] XGB       repeat 4 fold 1  macro-F1=0.8418  P1=0.705 R1=0.674  (28s)  [ratio 0.5, orig^0.25, C=1, rho=1.36]

[1529/1560] XGB       repeat 4 fold 1  macro-F1=0.8298  P1=0.586 R1=0.773  (9s)  [ratio 0.5, orig^0.5, C=0, rho=3.68]

[1530/1560] XGB       repeat 4 fold 1  macro-F1=0.8331  P1=0.676 R1=0.669  (26s)  [ratio 0.5, orig^0.5, C=1, rho=3.68]

[1531/1560] XGB       repeat 4 fold 1  macro-F1=0.8165  P1=0.511 R1=0.862  (6s)  [ratio 0.5, orig^0.75, C=0, rho=9.99]

[1532/1560] XGB       repeat 4 fold 1  macro-F1=0.8372  P1=0.711 R1=0.652  (20s)  [ratio 0.5, orig^0.75, C=1, rho=9.99]

[1533/1560] XGB       repeat 4 fold 1  macro-F1=0.7543  P1=0.369 R1=0.906  (5s)  [ratio 0.5, orig^1.0, C=0, rho=27.11]

[1534/1560] XGB       repeat 4 fold 1  macro-F1=0.8166  P1=0.675 R1=0.608  (18s)  [ratio 0.5, orig^1.0, C=1, rho=27.11]

[1535/1560] XGB       repeat 4 fold 1  macro-F1=0.6747  P1=0.237 R1=0.950  (4s)  [ratio 0.5, orig^1.25, C=0, rho=73.58]

[1536/1560] XGB       repeat 4 fold 1  macro-F1=0.7902  P1=0.493 R1=0.735  (15s)  [ratio 0.5, orig^1.25, C=1, rho=73.58]

[1537/1560] XGB       repeat 4 fold 1  macro-F1=0.6058  P1=0.153 R1=0.972  (3s)  [ratio 0.5, orig^1.5, C=0, rho=199.70]

[1538/1560] XGB       repeat 4 fold 1  macro-F1=0.7329  P1=0.334 R1=0.873  (10s)  [ratio 0.5, orig^1.5, C=1, rho=199.70]

[1539/1560] XGB       repeat 4 fold 1  macro-F1=0.3887  P1=0.039 R1=0.994  (3s)  [ratio 0.5, orig^2.0, C=0, rho=1470.86]

[1540/1560] XGB       repeat 4 fold 1  macro-F1=0.3887  P1=0.039 R1=0.994  (9s)  [ratio 0.5, orig^2.0, C=1, rho=1470.86]

[1541/1560] XGB       repeat 4 fold 1  macro-F1=0.8364  P1=0.653 R1=0.707  (7s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1542/1560] XGB       repeat 4 fold 1  macro-F1=0.8339  P1=0.663 R1=0.685  (20s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1543/1560] XGB       repeat 4 fold 1  macro-F1=0.8283  P1=0.638 R1=0.691  (14s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1544/1560] XGB       repeat 4 fold 1  macro-F1=0.8283  P1=0.638 R1=0.691  (38s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1545/1560] XGB       repeat 4 fold 1  macro-F1=0.8300  P1=0.618 R1=0.724  (14s)  [ratio 1.0, orig^0.25, C=0, rho=2.71]

[1546/1560] XGB       repeat 4 fold 1  macro-F1=0.8315  P1=0.727 R1=0.619  (37s)  [ratio 1.0, orig^0.25, C=1, rho=2.71]

[1547/1560] XGB       repeat 4 fold 1  macro-F1=0.8164  P1=0.544 R1=0.779  (12s)  [ratio 1.0, orig^0.5, C=0, rho=7.37]

[1548/1560] XGB       repeat 4 fold 1  macro-F1=0.8245  P1=0.683 R1=0.630  (29s)  [ratio 1.0, orig^0.5, C=1, rho=7.37]

[1549/1560] XGB       repeat 4 fold 1  macro-F1=0.7942  P1=0.458 R1=0.867  (6s)  [ratio 1.0, orig^0.75, C=0, rho=19.99]

[1550/1560] XGB       repeat 4 fold 1  macro-F1=0.8284  P1=0.686 R1=0.641  (31s)  [ratio 1.0, orig^0.75, C=1, rho=19.99]

[1551/1560] XGB       repeat 4 fold 1  macro-F1=0.7269  P1=0.318 R1=0.928  (5s)  [ratio 1.0, orig^1.0, C=0, rho=54.25]

[1552/1560] XGB       repeat 4 fold 1  macro-F1=0.8148  P1=0.612 R1=0.663  (23s)  [ratio 1.0, orig^1.0, C=1, rho=54.25]

[1553/1560] XGB       repeat 4 fold 1  macro-F1=0.6484  P1=0.202 R1=0.967  (4s)  [ratio 1.0, orig^1.25, C=0, rho=147.23]

[1554/1560] XGB       repeat 4 fold 1  macro-F1=0.7629  P1=0.404 R1=0.807  (20s)  [ratio 1.0, orig^1.25, C=1, rho=147.23]

[1555/1560] XGB       repeat 4 fold 1  macro-F1=0.5729  P1=0.122 R1=0.989  (4s)  [ratio 1.0, orig^1.5, C=0, rho=399.56]

[1556/1560] XGB       repeat 4 fold 1  macro-F1=0.6960  P1=0.270 R1=0.912  (10s)  [ratio 1.0, orig^1.5, C=1, rho=399.56]

[1557/1560] XGB       repeat 4 fold 1  macro-F1=0.0178  P1=0.018 R1=1.000  (2s)  [ratio 1.0, orig^2.0, C=0, rho=2942.91]

[1558/1560] XGB       repeat 4 fold 1  macro-F1=0.0178  P1=0.018 R1=1.000  (9s)  [ratio 1.0, orig^2.0, C=1, rho=2942.91]

[1559/1560] XGB       repeat 4 fold 1  macro-F1=0.8283  P1=0.638 R1=0.691  (7s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1560/1560] XGB       repeat 4 fold 1  macro-F1=0.8283  P1=0.638 R1=0.691  (18s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

## Macro-F1 by resampling ratio, weight setting and threshold tuning

In [4]:
results.pivot_table(index=["sampling_ratio", "weight_mode", "weight_power"],
                    columns=["classifier", "C"], values="macro_f1").round(4)

classifier                                   LR              RF          \
C                                             0       1       0       1
sampling_ratio weight_mode weight_power
0.0            orig        0.00          0.8256  0.8253  0.8392  0.8535
                           0.25          0.8295  0.8274  0.8537  0.8527
                           0.50          0.8224  0.8274  0.8389  0.8418
                           0.75          0.8041  0.8206  0.8207  0.8223
                           1.00          0.7803  0.8173  0.7915  0.7926
                           1.25          0.7490  0.8140  0.7705  0.7820
                           1.50          0.7050  0.8039  0.7423  0.7758
                           2.00          0.5509  0.7747  0.6723  0.7559
0.5            orig        0.00          0.7947  0.8198  0.8381  0.8391
                           0.25          0.7691  0.8158  0.8165  0.8241
                           0.50          0.7352  0.8095  0.7804  0.8093
                           0.75          0.6907  0.8044  0.7292  0.7919
                           1.00          0.6306  0.7902  0.6745  0.7750
                           1.25          0.5134  0.7660  0.6193  0.7541
                           1.50          0.3422  0.7316  0.5602  0.7425
                           2.00          0.0453  0.6533  0.2704  0.7095
               recalc      1.00          0.7770  0.8171  0.8224  0.8266
1.0            orig        0.00          0.7774  0.8161  0.8258  0.8296
                           0.25          0.7475  0.8121  0.8023  0.8139
                           0.50          0.7093  0.8029  0.7598  0.8005
                           0.75          0.6556  0.7964  0.7041  0.7845
                           1.00          0.5616  0.7753  0.6493  0.7626
                           1.25          0.4299  0.7428  0.5928  0.7481
                           1.50          0.2331  0.7063  0.5319  0.7370
                           2.00          0.0450  0.6099  0.1889  0.7028
               recalc      1.00          0.7774  0.8161  0.8258  0.8296

classifier                                  XGB
C                                             0       1
sampling_ratio weight_mode weight_power
0.0            orig        0.00          0.8526  0.8571
                           0.25          0.8576  0.8592
                           0.50          0.8634  0.8602
                           0.75          0.8574  0.8558
                           1.00          0.8522  0.8566
                           1.25          0.8366  0.8501
                           1.50          0.8228  0.8497
                           2.00          0.7285  0.8129
0.5            orig        0.00          0.8535  0.8535
                           0.25          0.8494  0.8480
                           0.50          0.8434  0.8532
                           0.75          0.8274  0.8461
                           1.00          0.7988  0.8450
                           1.25          0.7389  0.8210
                           1.50          0.6734  0.7693
                           2.00          0.4897  0.5611
               recalc      1.00          0.8484  0.8504
1.0            orig        0.00          0.8491  0.8490
                           0.25          0.8449  0.8506
                           0.50          0.8364  0.8448
                           0.75          0.8170  0.8473
                           1.00          0.7769  0.8343
                           1.25          0.7125  0.8010
                           1.50          0.6401  0.7356
                           2.00          0.3053  0.3901
               recalc      1.00          0.8491  0.8490

In [5]:
results.groupby(["sampling_ratio", "weight_mode", "weight_power"])[["rho_eff", "precision_1", "recall_1", "ppr_ratio"]].mean().round(3)

                                          rho_eff  precision_1  recall_1  \
sampling_ratio weight_mode weight_power
0.0            orig        0.00             0.018        0.760     0.638
                           0.25             0.050        0.718     0.687
                           0.50             0.136        0.688     0.702
                           0.75             0.368        0.636     0.717
                           1.00             1.000        0.576     0.743
                           1.25             2.714        0.523     0.770
                           1.50             7.365        0.482     0.790
                           2.00            54.249        0.343     0.853
0.5            orig        0.00             0.500        0.633     0.732
                           0.25             1.357        0.592     0.741
                           0.50             3.682        0.540     0.768
                           0.75             9.993        0.490     0.781
                           1.00            27.120        0.425     0.811
                           1.25            73.601        0.341     0.844
                           1.50           199.748        0.261     0.876
                           2.00          1471.217        0.137     0.929
               recalc      1.00             1.000        0.601     0.739
1.0            orig        0.00             1.000        0.606     0.734
                           0.25             2.714        0.565     0.752
                           0.50             7.365        0.513     0.770
                           0.75            19.989        0.457     0.795
                           1.00            54.249        0.385     0.820
                           1.25           147.226        0.305     0.852
                           1.50           399.561        0.226     0.887
                           2.00          2942.913        0.141     0.900
               recalc      1.00             1.000        0.606     0.734

                                         ppr_ratio
sampling_ratio weight_mode weight_power
0.0            orig        0.00              0.848
                           0.25              0.966
                           0.50              1.038
                           0.75              1.159
                           1.00              1.358
                           1.25              1.577
                           1.50              1.849
                           2.00              3.687
0.5            orig        0.00              1.188
                           0.25              1.310
                           0.50              1.544
                           0.75              1.878
                           1.00              2.530
                           1.25              4.503
                           1.50              8.024
                           2.00             20.915
               recalc      1.00              1.277
1.0            orig        0.00              1.258
                           0.25              1.422
                           0.50              1.694
                           0.75              2.172
                           1.00              3.460
                           1.25              6.079
                           1.50             10.428
                           2.00             26.807
               recalc      1.00              1.258