# SMS Spam Collection - E2 weight sensitivity
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/MuhammadDevX/ML-Research-Dataset-Imbalance/blob/main/smsspam/e2_weight_sensitivity/smsspam_e2_weight_sensitivity.ipynb)

Answers reviewer R3 (one weighting configuration only) and tests the over-correction mechanism.

* Classifiers: LR, RF, XGB.
* Resampling ratio: [0.0, 0.5, 1.0] (0 = none; otherwise SMOTETomek to that minority:majority ratio).
* Positive-class weight = IR ** power, power in [0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0]
  (0 = none, 0.5 = sqrt-inverse, 1 = inverse frequency), plus weights recomputed after resampling.
* Each setting with and without threshold tuning (C).
* Hyperparameters are reused from `c0_none` (no resampling) and `c1_A_smotetomek` (with resampling).
  **Run those two notebooks first**; missing folds are tuned here, which is slower.
* Each row records `rho_eff`, the positive:negative loss mass the classifier sees.

**How to run on Colab**
1. Click the badge, then *Runtime > Run all*. Allow Google Drive access when asked.
2. Results are appended to Google Drive after every classifier/fold:
   `MyDrive/ML-Research-Dataset-Imbalance/smsspam/e2_weight_sensitivity/results/smsspam__e2_weight_sensitivity.csv`.
3. If the runtime disconnects, just *Run all* again: finished folds are skipped.
4. When it is complete, copy the CSV into the same path in the repository and commit it.

In [1]:
# ---- Setup: identical in every notebook. Do not edit. ----
import os, sys, subprocess
REPO_URL = "https://github.com/MuhammadDevX/ML-Research-Dataset-Imbalance.git"
BRANCH = "main"
try:
    import google.colab  # noqa: F401
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    REPO_ROOT = "/content/ML-Research-Dataset-Imbalance"
    if not os.path.isdir(REPO_ROOT):
        subprocess.run(["git", "clone", "--branch", BRANCH, REPO_URL, REPO_ROOT], check=True)
    else:
        subprocess.run(["git", "-C", REPO_ROOT, "pull", "--ff-only"], check=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r",
                    f"{REPO_ROOT}/requirements.txt"], check=True)
    from google.colab import drive
    drive.mount("/content/drive")
    # Results go to Google Drive so they survive a disconnect.
    os.environ.setdefault("RESULTS_ROOT", "/content/drive/MyDrive/ML-Research-Dataset-Imbalance")
else:
    REPO_ROOT = os.path.abspath(os.getcwd())
    while not os.path.isdir(os.path.join(REPO_ROOT, "common")):
        parent = os.path.dirname(REPO_ROOT)
        if parent == REPO_ROOT:
            raise RuntimeError("Open this notebook from inside the repository.")
        REPO_ROOT = parent

sys.path.insert(0, REPO_ROOT)
os.chdir(REPO_ROOT)
from common.env import check_environment
check_environment()

Environment OK: scikit-learn 1.9.1, imbalanced-learn 0.14.2, xgboost 3.4.1, lightgbm 4.7.0

In [2]:
DATASET = "smsspam"
# Quick test run (2 folds, fewer classifiers and candidates): change the next line
# to  SMOKE = True . Its results go to a separate *__SMOKE.csv file and must never
# be used in the paper. Leave it as it is for the real run.
SMOKE = os.environ.get("SMOKE", "0") == "1"

In [3]:
from common.cv import run_e2
results = run_e2(DATASET, smoke=SMOKE)

Hyperparameters found: c0 70 folds, c1 70 folds. Missing ones are tuned here once with the same seed.
Writing to E:\Ablation_Study Research\ML-Research-Dataset-Imbalance\smsspam\e2_weight_sensitivity\results\smsspam__e2_weight_sensitivity.csv

[  1/1560] LR        repeat 0 fold 0  macro-F1=0.9440  P1=0.937 R1=0.869  (6s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[  2/1560] LR        repeat 0 fold 0  macro-F1=0.9429  P1=0.904 R1=0.896  (17s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[  3/1560] LR        repeat 0 fold 0  macro-F1=0.9417  P1=0.925 R1=0.872  (6s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[  4/1560] LR        repeat 0 fold 0  macro-F1=0.9415  P1=0.912 R1=0.884  (18s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[  5/1560] LR        repeat 0 fold 0  macro-F1=0.9439  P1=0.920 R1=0.884  (6s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[  6/1560] LR        repeat 0 fold 0  macro-F1=0.9439  P1=0.920 R1=0.884  (18s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[  7/1560] LR        repeat 0 fold 0  macro-F1=0.9427  P1=0.907 R1=0.893  (6s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[  8/1560] LR        repeat 0 fold 0  macro-F1=0.9450  P1=0.918 R1=0.890  (18s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[  9/1560] LR        repeat 0 fold 0  macro-F1=0.9414  P1=0.896 R1=0.899  (6s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[ 10/1560] LR        repeat 0 fold 0  macro-F1=0.9447  P1=0.923 R1=0.884  (17s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[ 11/1560] LR        repeat 0 fold 0  macro-F1=0.9384  P1=0.883 R1=0.902  (6s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[ 12/1560] LR        repeat 0 fold 0  macro-F1=0.9436  P1=0.926 R1=0.878  (17s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[ 13/1560] LR        repeat 0 fold 0  macro-F1=0.9327  P1=0.856 R1=0.911  (5s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[ 14/1560] LR        repeat 0 fold 0  macro-F1=0.9436  P1=0.926 R1=0.878  (17s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[ 15/1560] LR        repeat 0 fold 0  macro-F1=0.9156  P1=0.795 R1=0.924  (5s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[ 16/1560] LR        repeat 0 fold 0  macro-F1=0.9429  P1=0.920 R1=0.881  (17s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[ 17/1560] LR        repeat 0 fold 0  macro-F1=0.9476  P1=0.944 R1=0.875  (6s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[ 18/1560] LR        repeat 0 fold 0  macro-F1=0.9480  P1=0.935 R1=0.884  (19s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[ 19/1560] LR        repeat 0 fold 0  macro-F1=0.9429  P1=0.904 R1=0.896  (7s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[ 20/1560] LR        repeat 0 fold 0  macro-F1=0.9465  P1=0.927 R1=0.887  (18s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[ 21/1560] LR        repeat 0 fold 0  macro-F1=0.9295  P1=0.849 R1=0.908  (6s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[ 22/1560] LR        repeat 0 fold 0  macro-F1=0.9447  P1=0.923 R1=0.884  (19s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[ 23/1560] LR        repeat 0 fold 0  macro-F1=0.9196  P1=0.802 R1=0.930  (6s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[ 24/1560] LR        repeat 0 fold 0  macro-F1=0.9466  P1=0.924 R1=0.890  (19s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[ 25/1560] LR        repeat 0 fold 0  macro-F1=0.8853  P1=0.701 R1=0.945  (6s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[ 26/1560] LR        repeat 0 fold 0  macro-F1=0.9415  P1=0.912 R1=0.884  (19s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[ 27/1560] LR        repeat 0 fold 0  macro-F1=0.8328  P1=0.578 R1=0.960  (6s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[ 28/1560] LR        repeat 0 fold 0  macro-F1=0.9423  P1=0.915 R1=0.884  (18s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[ 29/1560] LR        repeat 0 fold 0  macro-F1=0.7570  P1=0.446 R1=0.969  (6s)  [ratio 0.5, orig^1.5, C=0, rho=9.12]

[ 30/1560] LR        repeat 0 fold 0  macro-F1=0.9400  P1=0.903 R1=0.887  (19s)  [ratio 0.5, orig^1.5, C=1, rho=9.12]

[ 31/1560] LR        repeat 0 fold 0  macro-F1=0.4467  P1=0.193 R1=0.991  (6s)  [ratio 0.5, orig^2.0, C=0, rho=24.00]

[ 32/1560] LR        repeat 0 fold 0  macro-F1=0.9445  P1=0.946 R1=0.862  (18s)  [ratio 0.5, orig^2.0, C=1, rho=24.00]

[ 33/1560] LR        repeat 0 fold 0  macro-F1=0.9375  P1=0.883 R1=0.899  (6s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[ 34/1560] LR        repeat 0 fold 0  macro-F1=0.9457  P1=0.924 R1=0.887  (19s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[ 35/1560] LR        repeat 0 fold 0  macro-F1=0.9356  P1=0.868 R1=0.908  (7s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[ 36/1560] LR        repeat 0 fold 0  macro-F1=0.9447  P1=0.923 R1=0.884  (20s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[ 37/1560] LR        repeat 0 fold 0  macro-F1=0.9251  P1=0.823 R1=0.924  (7s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[ 38/1560] LR        repeat 0 fold 0  macro-F1=0.9415  P1=0.912 R1=0.884  (20s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[ 39/1560] LR        repeat 0 fold 0  macro-F1=0.8991  P1=0.741 R1=0.936  (7s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[ 40/1560] LR        repeat 0 fold 0  macro-F1=0.9402  P1=0.901 R1=0.890  (19s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[ 41/1560] LR        repeat 0 fold 0  macro-F1=0.8679  P1=0.659 R1=0.945  (7s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[ 42/1560] LR        repeat 0 fold 0  macro-F1=0.9405  P1=0.896 R1=0.896  (19s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[ 43/1560] LR        repeat 0 fold 0  macro-F1=0.8128  P1=0.539 R1=0.963  (6s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[ 44/1560] LR        repeat 0 fold 0  macro-F1=0.9386  P1=0.895 R1=0.890  (18s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[ 45/1560] LR        repeat 0 fold 0  macro-F1=0.7358  P1=0.417 R1=0.966  (7s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[ 46/1560] LR        repeat 0 fold 0  macro-F1=0.9381  P1=0.888 R1=0.896  (17s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[ 47/1560] LR        repeat 0 fold 0  macro-F1=0.6141  P1=0.287 R1=0.979  (7s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[ 48/1560] LR        repeat 0 fold 0  macro-F1=0.9367  P1=0.880 R1=0.899  (16s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[ 49/1560] LR        repeat 0 fold 0  macro-F1=0.2102  P1=0.138 R1=1.000  (6s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[ 50/1560] LR        repeat 0 fold 0  macro-F1=0.9390  P1=0.936 R1=0.853  (13s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[ 51/1560] LR        repeat 0 fold 0  macro-F1=0.9356  P1=0.868 R1=0.908  (6s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[ 52/1560] LR        repeat 0 fold 0  macro-F1=0.9447  P1=0.923 R1=0.884  (9s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[ 53/1560] LR        repeat 0 fold 1  macro-F1=0.9549  P1=0.928 R1=0.914  (6s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[ 54/1560] LR        repeat 0 fold 1  macro-F1=0.9476  P1=0.886 R1=0.933  (18s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[ 55/1560] LR        repeat 0 fold 1  macro-F1=0.9496  P1=0.901 R1=0.923  (6s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[ 56/1560] LR        repeat 0 fold 1  macro-F1=0.9468  P1=0.884 R1=0.933  (17s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[ 57/1560] LR        repeat 0 fold 1  macro-F1=0.9474  P1=0.891 R1=0.926  (6s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[ 58/1560] LR        repeat 0 fold 1  macro-F1=0.9459  P1=0.883 R1=0.929  (18s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[ 59/1560] LR        repeat 0 fold 1  macro-F1=0.9467  P1=0.886 R1=0.929  (6s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[ 60/1560] LR        repeat 0 fold 1  macro-F1=0.9459  P1=0.883 R1=0.929  (17s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[ 61/1560] LR        repeat 0 fold 1  macro-F1=0.9428  P1=0.873 R1=0.929  (6s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[ 62/1560] LR        repeat 0 fold 1  macro-F1=0.9443  P1=0.878 R1=0.929  (17s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[ 63/1560] LR        repeat 0 fold 1  macro-F1=0.9375  P1=0.854 R1=0.933  (6s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[ 64/1560] LR        repeat 0 fold 1  macro-F1=0.9403  P1=0.868 R1=0.926  (17s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[ 65/1560] LR        repeat 0 fold 1  macro-F1=0.9297  P1=0.823 R1=0.942  (5s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[ 66/1560] LR        repeat 0 fold 1  macro-F1=0.9403  P1=0.868 R1=0.926  (16s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[ 67/1560] LR        repeat 0 fold 1  macro-F1=0.9116  P1=0.765 R1=0.951  (5s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[ 68/1560] LR        repeat 0 fold 1  macro-F1=0.9525  P1=0.920 R1=0.914  (17s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[ 69/1560] LR        repeat 0 fold 1  macro-F1=0.9551  P1=0.926 R1=0.917  (6s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[ 70/1560] LR        repeat 0 fold 1  macro-F1=0.9514  P1=0.904 R1=0.926  (19s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[ 71/1560] LR        repeat 0 fold 1  macro-F1=0.9466  P1=0.888 R1=0.926  (7s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[ 72/1560] LR        repeat 0 fold 1  macro-F1=0.9474  P1=0.891 R1=0.926  (18s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[ 73/1560] LR        repeat 0 fold 1  macro-F1=0.9364  P1=0.843 R1=0.942  (6s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[ 74/1560] LR        repeat 0 fold 1  macro-F1=0.9458  P1=0.886 R1=0.926  (19s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[ 75/1560] LR        repeat 0 fold 1  macro-F1=0.9147  P1=0.778 R1=0.945  (6s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[ 76/1560] LR        repeat 0 fold 1  macro-F1=0.9436  P1=0.876 R1=0.929  (19s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[ 77/1560] LR        repeat 0 fold 1  macro-F1=0.8839  P1=0.693 R1=0.954  (6s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[ 78/1560] LR        repeat 0 fold 1  macro-F1=0.9541  P1=0.925 R1=0.914  (18s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[ 79/1560] LR        repeat 0 fold 1  macro-F1=0.8406  P1=0.594 R1=0.960  (6s)  [ratio 0.5, orig^1.25, C=0, rho=5.60]

[ 80/1560] LR        repeat 0 fold 1  macro-F1=0.9542  P1=0.923 R1=0.917  (18s)  [ratio 0.5, orig^1.25, C=1, rho=5.60]

[ 81/1560] LR        repeat 0 fold 1  macro-F1=0.7723  P1=0.470 R1=0.969  (6s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[ 82/1560] LR        repeat 0 fold 1  macro-F1=0.9518  P1=0.914 R1=0.917  (18s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[ 83/1560] LR        repeat 0 fold 1  macro-F1=0.5068  P1=0.218 R1=0.988  (6s)  [ratio 0.5, orig^2.0, C=0, rho=23.85]

[ 84/1560] LR        repeat 0 fold 1  macro-F1=0.9526  P1=0.917 R1=0.917  (18s)  [ratio 0.5, orig^2.0, C=1, rho=23.85]

[ 85/1560] LR        repeat 0 fold 1  macro-F1=0.9407  P1=0.862 R1=0.936  (6s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[ 86/1560] LR        repeat 0 fold 1  macro-F1=0.9551  P1=0.926 R1=0.917  (18s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[ 87/1560] LR        repeat 0 fold 1  macro-F1=0.9407  P1=0.862 R1=0.936  (7s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[ 88/1560] LR        repeat 0 fold 1  macro-F1=0.9478  P1=0.901 R1=0.917  (20s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[ 89/1560] LR        repeat 0 fold 1  macro-F1=0.9297  P1=0.823 R1=0.942  (6s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[ 90/1560] LR        repeat 0 fold 1  macro-F1=0.9439  P1=0.885 R1=0.920  (20s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[ 91/1560] LR        repeat 0 fold 1  macro-F1=0.9036  P1=0.748 R1=0.945  (6s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[ 92/1560] LR        repeat 0 fold 1  macro-F1=0.9415  P1=0.864 R1=0.936  (19s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[ 93/1560] LR        repeat 0 fold 1  macro-F1=0.8696  P1=0.659 R1=0.954  (7s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[ 94/1560] LR        repeat 0 fold 1  macro-F1=0.9486  P1=0.903 R1=0.917  (19s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[ 95/1560] LR        repeat 0 fold 1  macro-F1=0.8280  P1=0.568 R1=0.963  (6s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[ 96/1560] LR        repeat 0 fold 1  macro-F1=0.9478  P1=0.901 R1=0.917  (18s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[ 97/1560] LR        repeat 0 fold 1  macro-F1=0.7523  P1=0.439 R1=0.969  (7s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[ 98/1560] LR        repeat 0 fold 1  macro-F1=0.9479  P1=0.898 R1=0.920  (18s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[ 99/1560] LR        repeat 0 fold 1  macro-F1=0.6521  P1=0.320 R1=0.982  (7s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[100/1560] LR        repeat 0 fold 1  macro-F1=0.9471  P1=0.896 R1=0.920  (16s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[101/1560] LR        repeat 0 fold 1  macro-F1=0.2739  P1=0.148 R1=0.997  (6s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[102/1560] LR        repeat 0 fold 1  macro-F1=0.9512  P1=0.927 R1=0.902  (13s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[103/1560] LR        repeat 0 fold 1  macro-F1=0.9407  P1=0.862 R1=0.936  (6s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[104/1560] LR        repeat 0 fold 1  macro-F1=0.9478  P1=0.901 R1=0.917  (10s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[105/1560] LR        repeat 1 fold 0  macro-F1=0.9453  P1=0.972 R1=0.844  (6s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[106/1560] LR        repeat 1 fold 0  macro-F1=0.9535  P1=0.942 R1=0.896  (18s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[107/1560] LR        repeat 1 fold 0  macro-F1=0.9485  P1=0.966 R1=0.859  (6s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[108/1560] LR        repeat 1 fold 0  macro-F1=0.9536  P1=0.939 R1=0.899  (18s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[109/1560] LR        repeat 1 fold 0  macro-F1=0.9500  P1=0.956 R1=0.872  (6s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[110/1560] LR        repeat 1 fold 0  macro-F1=0.9503  P1=0.927 R1=0.899  (18s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[111/1560] LR        repeat 1 fold 0  macro-F1=0.9540  P1=0.954 R1=0.887  (6s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[112/1560] LR        repeat 1 fold 0  macro-F1=0.9503  P1=0.927 R1=0.899  (18s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[113/1560] LR        repeat 1 fold 0  macro-F1=0.9512  P1=0.930 R1=0.899  (6s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[114/1560] LR        repeat 1 fold 0  macro-F1=0.9487  P1=0.922 R1=0.899  (17s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[115/1560] LR        repeat 1 fold 0  macro-F1=0.9471  P1=0.916 R1=0.899  (6s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[116/1560] LR        repeat 1 fold 0  macro-F1=0.9512  P1=0.950 R1=0.881  (17s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[117/1560] LR        repeat 1 fold 0  macro-F1=0.9411  P1=0.887 R1=0.908  (5s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[118/1560] LR        repeat 1 fold 0  macro-F1=0.9493  P1=0.950 R1=0.875  (17s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[119/1560] LR        repeat 1 fold 0  macro-F1=0.9247  P1=0.808 R1=0.942  (5s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[120/1560] LR        repeat 1 fold 0  macro-F1=0.9531  P1=0.951 R1=0.887  (17s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[121/1560] LR        repeat 1 fold 0  macro-F1=0.9485  P1=0.966 R1=0.859  (7s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[122/1560] LR        repeat 1 fold 0  macro-F1=0.9606  P1=0.958 R1=0.905  (19s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[123/1560] LR        repeat 1 fold 0  macro-F1=0.9607  P1=0.955 R1=0.908  (7s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[124/1560] LR        repeat 1 fold 0  macro-F1=0.9606  P1=0.958 R1=0.905  (18s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[125/1560] LR        repeat 1 fold 0  macro-F1=0.9498  P1=0.901 R1=0.924  (6s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[126/1560] LR        repeat 1 fold 0  macro-F1=0.9597  P1=0.955 R1=0.905  (19s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[127/1560] LR        repeat 1 fold 0  macro-F1=0.9342  P1=0.839 R1=0.939  (7s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[128/1560] LR        repeat 1 fold 0  macro-F1=0.9590  P1=0.949 R1=0.908  (19s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[129/1560] LR        repeat 1 fold 0  macro-F1=0.8901  P1=0.707 R1=0.957  (6s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[130/1560] LR        repeat 1 fold 0  macro-F1=0.9573  P1=0.943 R1=0.908  (19s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[131/1560] LR        repeat 1 fold 0  macro-F1=0.8199  P1=0.553 R1=0.963  (6s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[132/1560] LR        repeat 1 fold 0  macro-F1=0.9566  P1=0.937 R1=0.911  (18s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[133/1560] LR        repeat 1 fold 0  macro-F1=0.6995  P1=0.371 R1=0.963  (6s)  [ratio 0.5, orig^1.5, C=0, rho=9.11]

[134/1560] LR        repeat 1 fold 0  macro-F1=0.9539  P1=0.934 R1=0.905  (19s)  [ratio 0.5, orig^1.5, C=1, rho=9.11]

[135/1560] LR        repeat 1 fold 0  macro-F1=0.2548  P1=0.145 R1=0.997  (6s)  [ratio 0.5, orig^2.0, C=0, rho=23.99]

[136/1560] LR        repeat 1 fold 0  macro-F1=0.9553  P1=0.945 R1=0.899  (19s)  [ratio 0.5, orig^2.0, C=1, rho=23.99]

[137/1560] LR        repeat 1 fold 0  macro-F1=0.9574  P1=0.940 R1=0.911  (6s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[138/1560] LR        repeat 1 fold 0  macro-F1=0.9597  P1=0.955 R1=0.905  (19s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[139/1560] LR        repeat 1 fold 0  macro-F1=0.9574  P1=0.940 R1=0.911  (7s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[140/1560] LR        repeat 1 fold 0  macro-F1=0.9569  P1=0.954 R1=0.896  (20s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[141/1560] LR        repeat 1 fold 0  macro-F1=0.9454  P1=0.879 R1=0.933  (7s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[142/1560] LR        repeat 1 fold 0  macro-F1=0.9561  P1=0.948 R1=0.899  (20s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[143/1560] LR        repeat 1 fold 0  macro-F1=0.9290  P1=0.823 R1=0.939  (7s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[144/1560] LR        repeat 1 fold 0  macro-F1=0.9540  P1=0.931 R1=0.908  (20s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[145/1560] LR        repeat 1 fold 0  macro-F1=0.8750  P1=0.670 R1=0.957  (7s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[146/1560] LR        repeat 1 fold 0  macro-F1=0.9532  P1=0.928 R1=0.908  (20s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[147/1560] LR        repeat 1 fold 0  macro-F1=0.8093  P1=0.533 R1=0.963  (7s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[148/1560] LR        repeat 1 fold 0  macro-F1=0.9524  P1=0.925 R1=0.908  (19s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[149/1560] LR        repeat 1 fold 0  macro-F1=0.6933  P1=0.364 R1=0.963  (7s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[150/1560] LR        repeat 1 fold 0  macro-F1=0.9532  P1=0.928 R1=0.908  (18s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[151/1560] LR        repeat 1 fold 0  macro-F1=0.5234  P1=0.226 R1=0.979  (7s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[152/1560] LR        repeat 1 fold 0  macro-F1=0.9557  P1=0.937 R1=0.908  (16s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[153/1560] LR        repeat 1 fold 0  macro-F1=0.1180  P1=0.127 R1=1.000  (6s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[154/1560] LR        repeat 1 fold 0  macro-F1=0.9488  P1=0.959 R1=0.865  (13s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[155/1560] LR        repeat 1 fold 0  macro-F1=0.9574  P1=0.940 R1=0.911  (6s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[156/1560] LR        repeat 1 fold 0  macro-F1=0.9569  P1=0.954 R1=0.896  (9s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[157/1560] LR        repeat 1 fold 1  macro-F1=0.9587  P1=0.955 R1=0.902  (6s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[158/1560] LR        repeat 1 fold 1  macro-F1=0.9589  P1=0.949 R1=0.908  (17s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[159/1560] LR        repeat 1 fold 1  macro-F1=0.9589  P1=0.949 R1=0.908  (6s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[160/1560] LR        repeat 1 fold 1  macro-F1=0.9580  P1=0.946 R1=0.908  (17s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[161/1560] LR        repeat 1 fold 1  macro-F1=0.9591  P1=0.943 R1=0.914  (6s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[162/1560] LR        repeat 1 fold 1  macro-F1=0.9579  P1=0.949 R1=0.905  (17s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[163/1560] LR        repeat 1 fold 1  macro-F1=0.9568  P1=0.929 R1=0.920  (6s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[164/1560] LR        repeat 1 fold 1  macro-F1=0.9577  P1=0.932 R1=0.920  (17s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[165/1560] LR        repeat 1 fold 1  macro-F1=0.9546  P1=0.915 R1=0.926  (6s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[166/1560] LR        repeat 1 fold 1  macro-F1=0.9563  P1=0.942 R1=0.905  (17s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[167/1560] LR        repeat 1 fold 1  macro-F1=0.9507  P1=0.899 R1=0.929  (6s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[168/1560] LR        repeat 1 fold 1  macro-F1=0.9552  P1=0.923 R1=0.920  (17s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[169/1560] LR        repeat 1 fold 1  macro-F1=0.9465  P1=0.875 R1=0.942  (5s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[170/1560] LR        repeat 1 fold 1  macro-F1=0.9538  P1=0.912 R1=0.926  (16s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[171/1560] LR        repeat 1 fold 1  macro-F1=0.9227  P1=0.798 R1=0.948  (5s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[172/1560] LR        repeat 1 fold 1  macro-F1=0.9546  P1=0.915 R1=0.926  (17s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[173/1560] LR        repeat 1 fold 1  macro-F1=0.9535  P1=0.963 R1=0.877  (6s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[174/1560] LR        repeat 1 fold 1  macro-F1=0.9543  P1=0.903 R1=0.939  (19s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[175/1560] LR        repeat 1 fold 1  macro-F1=0.9565  P1=0.937 R1=0.911  (6s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[176/1560] LR        repeat 1 fold 1  macro-F1=0.9565  P1=0.916 R1=0.933  (18s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[177/1560] LR        repeat 1 fold 1  macro-F1=0.9491  P1=0.878 R1=0.948  (6s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[178/1560] LR        repeat 1 fold 1  macro-F1=0.9558  P1=0.910 R1=0.936  (18s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[179/1560] LR        repeat 1 fold 1  macro-F1=0.8969  P1=0.720 R1=0.963  (6s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[180/1560] LR        repeat 1 fold 1  macro-F1=0.9543  P1=0.903 R1=0.939  (18s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[181/1560] LR        repeat 1 fold 1  macro-F1=0.7591  P1=0.449 R1=0.972  (6s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[182/1560] LR        repeat 1 fold 1  macro-F1=0.9552  P1=0.903 R1=0.942  (18s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[183/1560] LR        repeat 1 fold 1  macro-F1=0.4871  P1=0.210 R1=0.997  (6s)  [ratio 0.5, orig^1.25, C=0, rho=5.60]

[184/1560] LR        repeat 1 fold 1  macro-F1=0.9540  P1=0.907 R1=0.933  (18s)  [ratio 0.5, orig^1.25, C=1, rho=5.60]

[185/1560] LR        repeat 1 fold 1  macro-F1=0.1512  P1=0.130 R1=1.000  (6s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[186/1560] LR        repeat 1 fold 1  macro-F1=0.9534  P1=0.920 R1=0.917  (18s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[187/1560] LR        repeat 1 fold 1  macro-F1=0.1120  P1=0.126 R1=1.000  (6s)  [ratio 0.5, orig^2.0, C=0, rho=23.85]

[188/1560] LR        repeat 1 fold 1  macro-F1=0.9553  P1=0.942 R1=0.902  (18s)  [ratio 0.5, orig^2.0, C=1, rho=23.85]

[189/1560] LR        repeat 1 fold 1  macro-F1=0.9558  P1=0.910 R1=0.936  (6s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[190/1560] LR        repeat 1 fold 1  macro-F1=0.9569  P1=0.926 R1=0.923  (18s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[191/1560] LR        repeat 1 fold 1  macro-F1=0.9545  P1=0.918 R1=0.923  (7s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[192/1560] LR        repeat 1 fold 1  macro-F1=0.9567  P1=0.931 R1=0.917  (20s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[193/1560] LR        repeat 1 fold 1  macro-F1=0.9371  P1=0.836 R1=0.954  (6s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[194/1560] LR        repeat 1 fold 1  macro-F1=0.9558  P1=0.931 R1=0.914  (20s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[195/1560] LR        repeat 1 fold 1  macro-F1=0.8753  P1=0.668 R1=0.963  (7s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[196/1560] LR        repeat 1 fold 1  macro-F1=0.9577  P1=0.932 R1=0.920  (19s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[197/1560] LR        repeat 1 fold 1  macro-F1=0.7406  P1=0.422 R1=0.975  (7s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[198/1560] LR        repeat 1 fold 1  macro-F1=0.9569  P1=0.926 R1=0.923  (19s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[199/1560] LR        repeat 1 fold 1  macro-F1=0.4790  P1=0.206 R1=0.997  (6s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[200/1560] LR        repeat 1 fold 1  macro-F1=0.9548  P1=0.931 R1=0.911  (18s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[201/1560] LR        repeat 1 fold 1  macro-F1=0.1597  P1=0.131 R1=1.000  (6s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[202/1560] LR        repeat 1 fold 1  macro-F1=0.9547  P1=0.934 R1=0.908  (17s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[203/1560] LR        repeat 1 fold 1  macro-F1=0.1120  P1=0.126 R1=1.000  (6s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[204/1560] LR        repeat 1 fold 1  macro-F1=0.9543  P1=0.942 R1=0.899  (16s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[205/1560] LR        repeat 1 fold 1  macro-F1=0.1120  P1=0.126 R1=1.000  (6s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[206/1560] LR        repeat 1 fold 1  macro-F1=0.9555  P1=0.960 R1=0.887  (12s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[207/1560] LR        repeat 1 fold 1  macro-F1=0.9545  P1=0.918 R1=0.923  (6s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[208/1560] LR        repeat 1 fold 1  macro-F1=0.9567  P1=0.931 R1=0.917  (9s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[209/1560] LR        repeat 2 fold 0  macro-F1=0.9533  P1=0.948 R1=0.890  (6s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[210/1560] LR        repeat 2 fold 0  macro-F1=0.9502  P1=0.930 R1=0.896  (18s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[211/1560] LR        repeat 2 fold 0  macro-F1=0.9517  P1=0.939 R1=0.893  (6s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[212/1560] LR        repeat 2 fold 0  macro-F1=0.9512  P1=0.930 R1=0.899  (18s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[213/1560] LR        repeat 2 fold 0  macro-F1=0.9512  P1=0.930 R1=0.899  (6s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[214/1560] LR        repeat 2 fold 0  macro-F1=0.9443  P1=0.897 R1=0.908  (18s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[215/1560] LR        repeat 2 fold 0  macro-F1=0.9497  P1=0.922 R1=0.902  (6s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[216/1560] LR        repeat 2 fold 0  macro-F1=0.9548  P1=0.957 R1=0.887  (18s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[217/1560] LR        repeat 2 fold 0  macro-F1=0.9464  P1=0.910 R1=0.902  (6s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[218/1560] LR        repeat 2 fold 0  macro-F1=0.9534  P1=0.945 R1=0.893  (17s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[219/1560] LR        repeat 2 fold 0  macro-F1=0.9459  P1=0.903 R1=0.908  (6s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[220/1560] LR        repeat 2 fold 0  macro-F1=0.9456  P1=0.908 R1=0.902  (17s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[221/1560] LR        repeat 2 fold 0  macro-F1=0.9438  P1=0.890 R1=0.914  (5s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[222/1560] LR        repeat 2 fold 0  macro-F1=0.9526  P1=0.942 R1=0.893  (16s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[223/1560] LR        repeat 2 fold 0  macro-F1=0.9352  P1=0.849 R1=0.930  (6s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[224/1560] LR        repeat 2 fold 0  macro-F1=0.9529  P1=0.934 R1=0.902  (17s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[225/1560] LR        repeat 2 fold 0  macro-F1=0.9589  P1=0.976 R1=0.884  (6s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[226/1560] LR        repeat 2 fold 0  macro-F1=0.9574  P1=0.940 R1=0.911  (19s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[227/1560] LR        repeat 2 fold 0  macro-F1=0.9590  P1=0.949 R1=0.908  (7s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[228/1560] LR        repeat 2 fold 0  macro-F1=0.9566  P1=0.937 R1=0.911  (18s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[229/1560] LR        repeat 2 fold 0  macro-F1=0.9562  P1=0.924 R1=0.924  (6s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[230/1560] LR        repeat 2 fold 0  macro-F1=0.9583  P1=0.943 R1=0.911  (19s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[231/1560] LR        repeat 2 fold 0  macro-F1=0.9334  P1=0.837 R1=0.939  (7s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[232/1560] LR        repeat 2 fold 0  macro-F1=0.9574  P1=0.940 R1=0.911  (18s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[233/1560] LR        repeat 2 fold 0  macro-F1=0.8936  P1=0.718 R1=0.951  (6s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[234/1560] LR        repeat 2 fold 0  macro-F1=0.9590  P1=0.949 R1=0.908  (18s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[235/1560] LR        repeat 2 fold 0  macro-F1=0.8004  P1=0.515 R1=0.972  (6s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[236/1560] LR        repeat 2 fold 0  macro-F1=0.9574  P1=0.940 R1=0.911  (18s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[237/1560] LR        repeat 2 fold 0  macro-F1=0.5632  P1=0.250 R1=0.985  (6s)  [ratio 0.5, orig^1.5, C=0, rho=9.11]

[238/1560] LR        repeat 2 fold 0  macro-F1=0.9574  P1=0.940 R1=0.911  (19s)  [ratio 0.5, orig^1.5, C=1, rho=9.11]

[239/1560] LR        repeat 2 fold 0  macro-F1=0.1123  P1=0.126 R1=1.000  (6s)  [ratio 0.5, orig^2.0, C=0, rho=23.99]

[240/1560] LR        repeat 2 fold 0  macro-F1=0.9580  P1=0.949 R1=0.905  (18s)  [ratio 0.5, orig^2.0, C=1, rho=23.99]

[241/1560] LR        repeat 2 fold 0  macro-F1=0.9566  P1=0.937 R1=0.911  (6s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[242/1560] LR        repeat 2 fold 0  macro-F1=0.9566  P1=0.937 R1=0.911  (18s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[243/1560] LR        repeat 2 fold 0  macro-F1=0.9573  P1=0.943 R1=0.908  (7s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[244/1560] LR        repeat 2 fold 0  macro-F1=0.9573  P1=0.943 R1=0.908  (20s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[245/1560] LR        repeat 2 fold 0  macro-F1=0.9525  P1=0.902 R1=0.933  (6s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[246/1560] LR        repeat 2 fold 0  macro-F1=0.9573  P1=0.943 R1=0.908  (20s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[247/1560] LR        repeat 2 fold 0  macro-F1=0.9299  P1=0.824 R1=0.942  (7s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[248/1560] LR        repeat 2 fold 0  macro-F1=0.9573  P1=0.943 R1=0.908  (19s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[249/1560] LR        repeat 2 fold 0  macro-F1=0.8857  P1=0.696 R1=0.957  (7s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[250/1560] LR        repeat 2 fold 0  macro-F1=0.9582  P1=0.946 R1=0.908  (20s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[251/1560] LR        repeat 2 fold 0  macro-F1=0.7952  P1=0.506 R1=0.972  (6s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[252/1560] LR        repeat 2 fold 0  macro-F1=0.9573  P1=0.943 R1=0.908  (18s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[253/1560] LR        repeat 2 fold 0  macro-F1=0.5714  P1=0.256 R1=0.985  (7s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[254/1560] LR        repeat 2 fold 0  macro-F1=0.9578  P1=0.955 R1=0.899  (17s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[255/1560] LR        repeat 2 fold 0  macro-F1=0.2281  P1=0.141 R1=0.997  (7s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[256/1560] LR        repeat 2 fold 0  macro-F1=0.9569  P1=0.954 R1=0.896  (16s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[257/1560] LR        repeat 2 fold 0  macro-F1=0.1123  P1=0.126 R1=1.000  (7s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[258/1560] LR        repeat 2 fold 0  macro-F1=0.9591  P1=0.973 R1=0.887  (13s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[259/1560] LR        repeat 2 fold 0  macro-F1=0.9573  P1=0.943 R1=0.908  (6s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[260/1560] LR        repeat 2 fold 0  macro-F1=0.9573  P1=0.943 R1=0.908  (10s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[261/1560] LR        repeat 2 fold 1  macro-F1=0.9569  P1=0.976 R1=0.877  (6s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[262/1560] LR        repeat 2 fold 1  macro-F1=0.9586  P1=0.932 R1=0.923  (18s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[263/1560] LR        repeat 2 fold 1  macro-F1=0.9589  P1=0.973 R1=0.887  (6s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[264/1560] LR        repeat 2 fold 1  macro-F1=0.9562  P1=0.921 R1=0.926  (17s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[265/1560] LR        repeat 2 fold 1  macro-F1=0.9630  P1=0.967 R1=0.905  (6s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[266/1560] LR        repeat 2 fold 1  macro-F1=0.9552  P1=0.923 R1=0.920  (18s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[267/1560] LR        repeat 2 fold 1  macro-F1=0.9574  P1=0.937 R1=0.914  (6s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[268/1560] LR        repeat 2 fold 1  macro-F1=0.9546  P1=0.915 R1=0.926  (18s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[269/1560] LR        repeat 2 fold 1  macro-F1=0.9555  P1=0.915 R1=0.929  (6s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[270/1560] LR        repeat 2 fold 1  macro-F1=0.9555  P1=0.915 R1=0.929  (17s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[271/1560] LR        repeat 2 fold 1  macro-F1=0.9478  P1=0.884 R1=0.936  (6s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[272/1560] LR        repeat 2 fold 1  macro-F1=0.9599  P1=0.973 R1=0.890  (17s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[273/1560] LR        repeat 2 fold 1  macro-F1=0.9395  P1=0.853 R1=0.942  (5s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[274/1560] LR        repeat 2 fold 1  macro-F1=0.9589  P1=0.973 R1=0.887  (17s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[275/1560] LR        repeat 2 fold 1  macro-F1=0.8852  P1=0.696 R1=0.954  (6s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[276/1560] LR        repeat 2 fold 1  macro-F1=0.9550  P1=0.973 R1=0.874  (17s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[277/1560] LR        repeat 2 fold 1  macro-F1=0.9556  P1=0.983 R1=0.868  (7s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[278/1560] LR        repeat 2 fold 1  macro-F1=0.9558  P1=0.954 R1=0.893  (19s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[279/1560] LR        repeat 2 fold 1  macro-F1=0.9512  P1=0.927 R1=0.902  (6s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[280/1560] LR        repeat 2 fold 1  macro-F1=0.9535  P1=0.939 R1=0.899  (19s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[281/1560] LR        repeat 2 fold 1  macro-F1=0.9361  P1=0.847 R1=0.936  (6s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[282/1560] LR        repeat 2 fold 1  macro-F1=0.9551  P1=0.948 R1=0.896  (19s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[283/1560] LR        repeat 2 fold 1  macro-F1=0.8629  P1=0.641 R1=0.960  (6s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[284/1560] LR        repeat 2 fold 1  macro-F1=0.9516  P1=0.939 R1=0.893  (19s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[285/1560] LR        repeat 2 fold 1  macro-F1=0.7365  P1=0.416 R1=0.979  (6s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[286/1560] LR        repeat 2 fold 1  macro-F1=0.9508  P1=0.936 R1=0.893  (19s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[287/1560] LR        repeat 2 fold 1  macro-F1=0.4950  P1=0.213 R1=0.997  (6s)  [ratio 0.5, orig^1.25, C=0, rho=5.60]

[288/1560] LR        repeat 2 fold 1  macro-F1=0.9506  P1=0.939 R1=0.890  (18s)  [ratio 0.5, orig^1.25, C=1, rho=5.60]

[289/1560] LR        repeat 2 fold 1  macro-F1=0.1812  P1=0.134 R1=1.000  (6s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[290/1560] LR        repeat 2 fold 1  macro-F1=0.9506  P1=0.939 R1=0.890  (19s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[291/1560] LR        repeat 2 fold 1  macro-F1=0.1120  P1=0.126 R1=1.000  (6s)  [ratio 0.5, orig^2.0, C=0, rho=23.85]

[292/1560] LR        repeat 2 fold 1  macro-F1=0.9508  P1=0.956 R1=0.874  (18s)  [ratio 0.5, orig^2.0, C=1, rho=23.85]

[293/1560] LR        repeat 2 fold 1  macro-F1=0.9480  P1=0.896 R1=0.923  (6s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[294/1560] LR        repeat 2 fold 1  macro-F1=0.9559  P1=0.951 R1=0.896  (18s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[295/1560] LR        repeat 2 fold 1  macro-F1=0.9467  P1=0.886 R1=0.929  (7s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[296/1560] LR        repeat 2 fold 1  macro-F1=0.9515  P1=0.920 R1=0.911  (20s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[297/1560] LR        repeat 2 fold 1  macro-F1=0.9082  P1=0.762 R1=0.942  (7s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[298/1560] LR        repeat 2 fold 1  macro-F1=0.9506  P1=0.919 R1=0.908  (20s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[299/1560] LR        repeat 2 fold 1  macro-F1=0.8285  P1=0.569 R1=0.963  (7s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[300/1560] LR        repeat 2 fold 1  macro-F1=0.9530  P1=0.951 R1=0.887  (19s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[301/1560] LR        repeat 2 fold 1  macro-F1=0.6958  P1=0.366 R1=0.979  (7s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[302/1560] LR        repeat 2 fold 1  macro-F1=0.9533  P1=0.945 R1=0.893  (20s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[303/1560] LR        repeat 2 fold 1  macro-F1=0.4820  P1=0.207 R1=0.997  (7s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[304/1560] LR        repeat 2 fold 1  macro-F1=0.9531  P1=0.948 R1=0.890  (18s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[305/1560] LR        repeat 2 fold 1  macro-F1=0.1940  P1=0.136 R1=1.000  (7s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[306/1560] LR        repeat 2 fold 1  macro-F1=0.9523  P1=0.945 R1=0.890  (17s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[307/1560] LR        repeat 2 fold 1  macro-F1=0.1125  P1=0.126 R1=1.000  (7s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[308/1560] LR        repeat 2 fold 1  macro-F1=0.9529  P1=0.954 R1=0.883  (16s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[309/1560] LR        repeat 2 fold 1  macro-F1=0.1120  P1=0.126 R1=1.000  (6s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[310/1560] LR        repeat 2 fold 1  macro-F1=0.9531  P1=0.948 R1=0.890  (13s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[311/1560] LR        repeat 2 fold 1  macro-F1=0.9467  P1=0.886 R1=0.929  (6s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[312/1560] LR        repeat 2 fold 1  macro-F1=0.9515  P1=0.920 R1=0.911  (10s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[313/1560] LR        repeat 3 fold 0  macro-F1=0.9476  P1=0.944 R1=0.875  (6s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[314/1560] LR        repeat 3 fold 0  macro-F1=0.9486  P1=0.944 R1=0.878  (18s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[315/1560] LR        repeat 3 fold 0  macro-F1=0.9472  P1=0.932 R1=0.884  (6s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[316/1560] LR        repeat 3 fold 0  macro-F1=0.9470  P1=0.935 R1=0.881  (17s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[317/1560] LR        repeat 3 fold 0  macro-F1=0.9431  P1=0.917 R1=0.884  (6s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[318/1560] LR        repeat 3 fold 0  macro-F1=0.9479  P1=0.938 R1=0.881  (17s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[319/1560] LR        repeat 3 fold 0  macro-F1=0.9458  P1=0.921 R1=0.890  (6s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[320/1560] LR        repeat 3 fold 0  macro-F1=0.9447  P1=0.923 R1=0.884  (18s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[321/1560] LR        repeat 3 fold 0  macro-F1=0.9437  P1=0.907 R1=0.896  (6s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[322/1560] LR        repeat 3 fold 0  macro-F1=0.9470  P1=0.935 R1=0.881  (17s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[323/1560] LR        repeat 3 fold 0  macro-F1=0.9405  P1=0.896 R1=0.896  (6s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[324/1560] LR        repeat 3 fold 0  macro-F1=0.9439  P1=0.920 R1=0.884  (17s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[325/1560] LR        repeat 3 fold 0  macro-F1=0.9339  P1=0.865 R1=0.905  (5s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[326/1560] LR        repeat 3 fold 0  macro-F1=0.9449  P1=0.938 R1=0.872  (17s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[327/1560] LR        repeat 3 fold 0  macro-F1=0.9202  P1=0.806 R1=0.927  (5s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[328/1560] LR        repeat 3 fold 0  macro-F1=0.9465  P1=0.927 R1=0.887  (17s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[329/1560] LR        repeat 3 fold 0  macro-F1=0.9431  P1=0.975 R1=0.835  (6s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[330/1560] LR        repeat 3 fold 0  macro-F1=0.9475  P1=0.908 R1=0.908  (19s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[331/1560] LR        repeat 3 fold 0  macro-F1=0.9488  P1=0.938 R1=0.884  (6s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[332/1560] LR        repeat 3 fold 0  macro-F1=0.9480  P1=0.935 R1=0.884  (18s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[333/1560] LR        repeat 3 fold 0  macro-F1=0.9433  P1=0.883 R1=0.920  (6s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[334/1560] LR        repeat 3 fold 0  macro-F1=0.9498  P1=0.939 R1=0.887  (19s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[335/1560] LR        repeat 3 fold 0  macro-F1=0.9036  P1=0.744 R1=0.951  (7s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[336/1560] LR        repeat 3 fold 0  macro-F1=0.9480  P1=0.935 R1=0.884  (18s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[337/1560] LR        repeat 3 fold 0  macro-F1=0.7663  P1=0.460 R1=0.976  (6s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[338/1560] LR        repeat 3 fold 0  macro-F1=0.9464  P1=0.929 R1=0.884  (18s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[339/1560] LR        repeat 3 fold 0  macro-F1=0.4939  P1=0.213 R1=0.991  (6s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[340/1560] LR        repeat 3 fold 0  macro-F1=0.9459  P1=0.938 R1=0.875  (18s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[341/1560] LR        repeat 3 fold 0  macro-F1=0.1555  P1=0.131 R1=1.000  (6s)  [ratio 0.5, orig^1.5, C=0, rho=9.11]

[342/1560] LR        repeat 3 fold 0  macro-F1=0.9468  P1=0.941 R1=0.875  (19s)  [ratio 0.5, orig^1.5, C=1, rho=9.11]

[343/1560] LR        repeat 3 fold 0  macro-F1=0.1123  P1=0.126 R1=1.000  (6s)  [ratio 0.5, orig^2.0, C=0, rho=23.99]

[344/1560] LR        repeat 3 fold 0  macro-F1=0.9478  P1=0.959 R1=0.862  (18s)  [ratio 0.5, orig^2.0, C=1, rho=23.99]

[345/1560] LR        repeat 3 fold 0  macro-F1=0.9456  P1=0.908 R1=0.902  (6s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[346/1560] LR        repeat 3 fold 0  macro-F1=0.9488  P1=0.938 R1=0.884  (18s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[347/1560] LR        repeat 3 fold 0  macro-F1=0.9440  P1=0.902 R1=0.902  (7s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[348/1560] LR        repeat 3 fold 0  macro-F1=0.9448  P1=0.905 R1=0.902  (20s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[349/1560] LR        repeat 3 fold 0  macro-F1=0.9369  P1=0.852 R1=0.933  (6s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[350/1560] LR        repeat 3 fold 0  macro-F1=0.9438  P1=0.905 R1=0.899  (20s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[351/1560] LR        repeat 3 fold 0  macro-F1=0.8651  P1=0.649 R1=0.954  (6s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[352/1560] LR        repeat 3 fold 0  macro-F1=0.9429  P1=0.904 R1=0.896  (19s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[353/1560] LR        repeat 3 fold 0  macro-F1=0.7218  P1=0.398 R1=0.976  (7s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[354/1560] LR        repeat 3 fold 0  macro-F1=0.9461  P1=0.935 R1=0.878  (19s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[355/1560] LR        repeat 3 fold 0  macro-F1=0.4693  P1=0.201 R1=0.988  (6s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[356/1560] LR        repeat 3 fold 0  macro-F1=0.9469  P1=0.938 R1=0.878  (18s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[357/1560] LR        repeat 3 fold 0  macro-F1=0.1622  P1=0.132 R1=1.000  (7s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[358/1560] LR        repeat 3 fold 0  macro-F1=0.9469  P1=0.938 R1=0.878  (18s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[359/1560] LR        repeat 3 fold 0  macro-F1=0.1123  P1=0.126 R1=1.000  (7s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[360/1560] LR        repeat 3 fold 0  macro-F1=0.9474  P1=0.947 R1=0.872  (16s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[361/1560] LR        repeat 3 fold 0  macro-F1=0.1123  P1=0.126 R1=1.000  (6s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[362/1560] LR        repeat 3 fold 0  macro-F1=0.9427  P1=0.962 R1=0.844  (13s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[363/1560] LR        repeat 3 fold 0  macro-F1=0.9440  P1=0.902 R1=0.902  (6s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[364/1560] LR        repeat 3 fold 0  macro-F1=0.9448  P1=0.905 R1=0.902  (9s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[365/1560] LR        repeat 3 fold 1  macro-F1=0.9424  P1=0.894 R1=0.905  (6s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[366/1560] LR        repeat 3 fold 1  macro-F1=0.9464  P1=0.908 R1=0.905  (18s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[367/1560] LR        repeat 3 fold 1  macro-F1=0.9420  P1=0.884 R1=0.914  (6s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[368/1560] LR        repeat 3 fold 1  macro-F1=0.9456  P1=0.905 R1=0.905  (18s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[369/1560] LR        repeat 3 fold 1  macro-F1=0.9415  P1=0.877 R1=0.920  (6s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[370/1560] LR        repeat 3 fold 1  macro-F1=0.9448  P1=0.902 R1=0.905  (18s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[371/1560] LR        repeat 3 fold 1  macro-F1=0.9398  P1=0.874 R1=0.917  (6s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[372/1560] LR        repeat 3 fold 1  macro-F1=0.9457  P1=0.902 R1=0.908  (18s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[373/1560] LR        repeat 3 fold 1  macro-F1=0.9363  P1=0.858 R1=0.923  (6s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[374/1560] LR        repeat 3 fold 1  macro-F1=0.9448  P1=0.902 R1=0.905  (17s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[375/1560] LR        repeat 3 fold 1  macro-F1=0.9355  P1=0.855 R1=0.923  (6s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[376/1560] LR        repeat 3 fold 1  macro-F1=0.9456  P1=0.905 R1=0.905  (17s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[377/1560] LR        repeat 3 fold 1  macro-F1=0.9328  P1=0.842 R1=0.929  (5s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[378/1560] LR        repeat 3 fold 1  macro-F1=0.9456  P1=0.905 R1=0.905  (16s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[379/1560] LR        repeat 3 fold 1  macro-F1=0.9260  P1=0.812 R1=0.942  (6s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[380/1560] LR        repeat 3 fold 1  macro-F1=0.9473  P1=0.908 R1=0.908  (17s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[381/1560] LR        repeat 3 fold 1  macro-F1=0.9555  P1=0.960 R1=0.887  (7s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[382/1560] LR        repeat 3 fold 1  macro-F1=0.9487  P1=0.919 R1=0.902  (19s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[383/1560] LR        repeat 3 fold 1  macro-F1=0.9503  P1=0.925 R1=0.902  (7s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[384/1560] LR        repeat 3 fold 1  macro-F1=0.9465  P1=0.905 R1=0.908  (18s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[385/1560] LR        repeat 3 fold 1  macro-F1=0.9426  P1=0.875 R1=0.926  (7s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[386/1560] LR        repeat 3 fold 1  macro-F1=0.9488  P1=0.916 R1=0.905  (19s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[387/1560] LR        repeat 3 fold 1  macro-F1=0.9113  P1=0.774 R1=0.936  (7s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[388/1560] LR        repeat 3 fold 1  macro-F1=0.9535  P1=0.939 R1=0.899  (19s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[389/1560] LR        repeat 3 fold 1  macro-F1=0.8781  P1=0.676 R1=0.960  (6s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[390/1560] LR        repeat 3 fold 1  macro-F1=0.9480  P1=0.913 R1=0.905  (19s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[391/1560] LR        repeat 3 fold 1  macro-F1=0.8024  P1=0.518 R1=0.975  (6s)  [ratio 0.5, orig^1.25, C=0, rho=5.60]

[392/1560] LR        repeat 3 fold 1  macro-F1=0.9502  P1=0.927 R1=0.899  (19s)  [ratio 0.5, orig^1.25, C=1, rho=5.60]

[393/1560] LR        repeat 3 fold 1  macro-F1=0.6356  P1=0.305 R1=0.988  (6s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[394/1560] LR        repeat 3 fold 1  macro-F1=0.9479  P1=0.916 R1=0.902  (19s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[395/1560] LR        repeat 3 fold 1  macro-F1=0.1158  P1=0.127 R1=1.000  (6s)  [ratio 0.5, orig^2.0, C=0, rho=23.85]

[396/1560] LR        repeat 3 fold 1  macro-F1=0.9530  P1=0.951 R1=0.887  (19s)  [ratio 0.5, orig^2.0, C=1, rho=23.85]

[397/1560] LR        repeat 3 fold 1  macro-F1=0.9459  P1=0.900 R1=0.911  (6s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[398/1560] LR        repeat 3 fold 1  macro-F1=0.9479  P1=0.916 R1=0.902  (19s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[399/1560] LR        repeat 3 fold 1  macro-F1=0.9502  P1=0.909 R1=0.917  (7s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[400/1560] LR        repeat 3 fold 1  macro-F1=0.9491  P1=0.911 R1=0.911  (20s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[401/1560] LR        repeat 3 fold 1  macro-F1=0.9357  P1=0.853 R1=0.926  (7s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[402/1560] LR        repeat 3 fold 1  macro-F1=0.9500  P1=0.911 R1=0.914  (20s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[403/1560] LR        repeat 3 fold 1  macro-F1=0.9070  P1=0.757 R1=0.945  (7s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[404/1560] LR        repeat 3 fold 1  macro-F1=0.9522  P1=0.925 R1=0.908  (19s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[405/1560] LR        repeat 3 fold 1  macro-F1=0.8727  P1=0.660 R1=0.969  (7s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[406/1560] LR        repeat 3 fold 1  macro-F1=0.9476  P1=0.903 R1=0.914  (19s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[407/1560] LR        repeat 3 fold 1  macro-F1=0.7942  P1=0.504 R1=0.975  (6s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[408/1560] LR        repeat 3 fold 1  macro-F1=0.9483  P1=0.908 R1=0.911  (18s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[409/1560] LR        repeat 3 fold 1  macro-F1=0.6421  P1=0.311 R1=0.988  (7s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[410/1560] LR        repeat 3 fold 1  macro-F1=0.9475  P1=0.905 R1=0.911  (17s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[411/1560] LR        repeat 3 fold 1  macro-F1=0.3627  P1=0.167 R1=0.994  (7s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[412/1560] LR        repeat 3 fold 1  macro-F1=0.9507  P1=0.917 R1=0.911  (16s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[413/1560] LR        repeat 3 fold 1  macro-F1=0.1120  P1=0.126 R1=1.000  (6s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[414/1560] LR        repeat 3 fold 1  macro-F1=0.9534  P1=0.942 R1=0.896  (13s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[415/1560] LR        repeat 3 fold 1  macro-F1=0.9502  P1=0.909 R1=0.917  (6s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[416/1560] LR        repeat 3 fold 1  macro-F1=0.9491  P1=0.911 R1=0.911  (9s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[417/1560] LR        repeat 4 fold 0  macro-F1=0.9653  P1=0.990 R1=0.893  (6s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[418/1560] LR        repeat 4 fold 0  macro-F1=0.9660  P1=0.965 R1=0.917  (17s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[419/1560] LR        repeat 4 fold 0  macro-F1=0.9648  P1=0.974 R1=0.905  (6s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[420/1560] LR        repeat 4 fold 0  macro-F1=0.9660  P1=0.965 R1=0.917  (18s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[421/1560] LR        repeat 4 fold 0  macro-F1=0.9641  P1=0.964 R1=0.911  (6s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[422/1560] LR        repeat 4 fold 0  macro-F1=0.9644  P1=0.956 R1=0.920  (18s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[423/1560] LR        repeat 4 fold 0  macro-F1=0.9620  P1=0.944 R1=0.924  (6s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[424/1560] LR        repeat 4 fold 0  macro-F1=0.9634  P1=0.958 R1=0.914  (17s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[425/1560] LR        repeat 4 fold 0  macro-F1=0.9583  P1=0.919 R1=0.936  (6s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[426/1560] LR        repeat 4 fold 0  macro-F1=0.9626  P1=0.955 R1=0.914  (17s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[427/1560] LR        repeat 4 fold 0  macro-F1=0.9512  P1=0.892 R1=0.939  (6s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[428/1560] LR        repeat 4 fold 0  macro-F1=0.9624  P1=0.933 R1=0.936  (17s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[429/1560] LR        repeat 4 fold 0  macro-F1=0.9435  P1=0.865 R1=0.942  (5s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[430/1560] LR        repeat 4 fold 0  macro-F1=0.9591  P1=0.922 R1=0.936  (17s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[431/1560] LR        repeat 4 fold 0  macro-F1=0.9114  P1=0.756 R1=0.966  (5s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[432/1560] LR        repeat 4 fold 0  macro-F1=0.9581  P1=0.924 R1=0.930  (17s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[433/1560] LR        repeat 4 fold 0  macro-F1=0.9463  P1=0.993 R1=0.832  (6s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[434/1560] LR        repeat 4 fold 0  macro-F1=0.9634  P1=0.958 R1=0.914  (19s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[435/1560] LR        repeat 4 fold 0  macro-F1=0.9600  P1=0.973 R1=0.890  (6s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[436/1560] LR        repeat 4 fold 0  macro-F1=0.9639  P1=0.970 R1=0.905  (18s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[437/1560] LR        repeat 4 fold 0  macro-F1=0.9478  P1=0.871 R1=0.951  (6s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[438/1560] LR        repeat 4 fold 0  macro-F1=0.9622  P1=0.964 R1=0.905  (19s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[439/1560] LR        repeat 4 fold 0  macro-F1=0.8424  P1=0.593 R1=0.976  (6s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[440/1560] LR        repeat 4 fold 0  macro-F1=0.9621  P1=0.967 R1=0.902  (18s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[441/1560] LR        repeat 4 fold 0  macro-F1=0.5659  P1=0.253 R1=0.994  (6s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[442/1560] LR        repeat 4 fold 0  macro-F1=0.9611  P1=0.970 R1=0.896  (19s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[443/1560] LR        repeat 4 fold 0  macro-F1=0.1684  P1=0.133 R1=1.000  (6s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[444/1560] LR        repeat 4 fold 0  macro-F1=0.9611  P1=0.970 R1=0.896  (18s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[445/1560] LR        repeat 4 fold 0  macro-F1=0.1123  P1=0.126 R1=1.000  (6s)  [ratio 0.5, orig^1.5, C=0, rho=9.12]

[446/1560] LR        repeat 4 fold 0  macro-F1=0.9600  P1=0.973 R1=0.890  (18s)  [ratio 0.5, orig^1.5, C=1, rho=9.12]

[447/1560] LR        repeat 4 fold 0  macro-F1=0.1123  P1=0.126 R1=1.000  (6s)  [ratio 0.5, orig^2.0, C=0, rho=24.00]

[448/1560] LR        repeat 4 fold 0  macro-F1=0.9587  P1=0.983 R1=0.878  (18s)  [ratio 0.5, orig^2.0, C=1, rho=24.00]

[449/1560] LR        repeat 4 fold 0  macro-F1=0.9637  P1=0.950 R1=0.924  (6s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[450/1560] LR        repeat 4 fold 0  macro-F1=0.9622  P1=0.964 R1=0.905  (18s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[451/1560] LR        repeat 4 fold 0  macro-F1=0.9604  P1=0.938 R1=0.924  (7s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[452/1560] LR        repeat 4 fold 0  macro-F1=0.9612  P1=0.941 R1=0.924  (20s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[453/1560] LR        repeat 4 fold 0  macro-F1=0.9213  P1=0.788 R1=0.957  (6s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[454/1560] LR        repeat 4 fold 0  macro-F1=0.9603  P1=0.964 R1=0.899  (20s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[455/1560] LR        repeat 4 fold 0  macro-F1=0.7894  P1=0.496 R1=0.976  (6s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[456/1560] LR        repeat 4 fold 0  macro-F1=0.9605  P1=0.961 R1=0.902  (19s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[457/1560] LR        repeat 4 fold 0  macro-F1=0.5223  P1=0.227 R1=0.994  (7s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[458/1560] LR        repeat 4 fold 0  macro-F1=0.9594  P1=0.964 R1=0.896  (19s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[459/1560] LR        repeat 4 fold 0  macro-F1=0.1693  P1=0.133 R1=1.000  (6s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[460/1560] LR        repeat 4 fold 0  macro-F1=0.9610  P1=0.973 R1=0.893  (18s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[461/1560] LR        repeat 4 fold 0  macro-F1=0.1123  P1=0.126 R1=1.000  (7s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[462/1560] LR        repeat 4 fold 0  macro-F1=0.9584  P1=0.964 R1=0.893  (17s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[463/1560] LR        repeat 4 fold 0  macro-F1=0.1123  P1=0.126 R1=1.000  (7s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[464/1560] LR        repeat 4 fold 0  macro-F1=0.9601  P1=0.970 R1=0.893  (16s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[465/1560] LR        repeat 4 fold 0  macro-F1=0.1123  P1=0.126 R1=1.000  (6s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[466/1560] LR        repeat 4 fold 0  macro-F1=0.9577  P1=0.983 R1=0.875  (12s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[467/1560] LR        repeat 4 fold 0  macro-F1=0.9604  P1=0.938 R1=0.924  (6s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[468/1560] LR        repeat 4 fold 0  macro-F1=0.9612  P1=0.941 R1=0.924  (9s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[469/1560] LR        repeat 4 fold 1  macro-F1=0.9441  P1=0.883 R1=0.923  (6s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[470/1560] LR        repeat 4 fold 1  macro-F1=0.9441  P1=0.883 R1=0.923  (18s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[471/1560] LR        repeat 4 fold 1  macro-F1=0.9425  P1=0.878 R1=0.923  (6s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[472/1560] LR        repeat 4 fold 1  macro-F1=0.9441  P1=0.883 R1=0.923  (18s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[473/1560] LR        repeat 4 fold 1  macro-F1=0.9409  P1=0.872 R1=0.923  (6s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[474/1560] LR        repeat 4 fold 1  macro-F1=0.9425  P1=0.878 R1=0.923  (18s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[475/1560] LR        repeat 4 fold 1  macro-F1=0.9418  P1=0.873 R1=0.926  (6s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[476/1560] LR        repeat 4 fold 1  macro-F1=0.9471  P1=0.896 R1=0.920  (18s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[477/1560] LR        repeat 4 fold 1  macro-F1=0.9387  P1=0.863 R1=0.926  (6s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[478/1560] LR        repeat 4 fold 1  macro-F1=0.9441  P1=0.883 R1=0.923  (17s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[479/1560] LR        repeat 4 fold 1  macro-F1=0.9364  P1=0.856 R1=0.926  (6s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[480/1560] LR        repeat 4 fold 1  macro-F1=0.9471  P1=0.896 R1=0.920  (17s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[481/1560] LR        repeat 4 fold 1  macro-F1=0.9303  P1=0.837 R1=0.926  (5s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[482/1560] LR        repeat 4 fold 1  macro-F1=0.9486  P1=0.903 R1=0.917  (16s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[483/1560] LR        repeat 4 fold 1  macro-F1=0.9253  P1=0.819 R1=0.929  (5s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[484/1560] LR        repeat 4 fold 1  macro-F1=0.9463  P1=0.893 R1=0.920  (17s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[485/1560] LR        repeat 4 fold 1  macro-F1=0.9578  P1=0.951 R1=0.902  (6s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[486/1560] LR        repeat 4 fold 1  macro-F1=0.9476  P1=0.903 R1=0.914  (19s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[487/1560] LR        repeat 4 fold 1  macro-F1=0.9514  P1=0.922 R1=0.908  (6s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[488/1560] LR        repeat 4 fold 1  macro-F1=0.9475  P1=0.905 R1=0.911  (18s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[489/1560] LR        repeat 4 fold 1  macro-F1=0.9447  P1=0.888 R1=0.920  (7s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[490/1560] LR        repeat 4 fold 1  macro-F1=0.9467  P1=0.903 R1=0.911  (19s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[491/1560] LR        repeat 4 fold 1  macro-F1=0.9397  P1=0.863 R1=0.929  (7s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[492/1560] LR        repeat 4 fold 1  macro-F1=0.9505  P1=0.922 R1=0.905  (19s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[493/1560] LR        repeat 4 fold 1  macro-F1=0.9249  P1=0.813 R1=0.936  (6s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[494/1560] LR        repeat 4 fold 1  macro-F1=0.9528  P1=0.933 R1=0.902  (18s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[495/1560] LR        repeat 4 fold 1  macro-F1=0.8905  P1=0.707 R1=0.957  (6s)  [ratio 0.5, orig^1.25, C=0, rho=5.59]

[496/1560] LR        repeat 4 fold 1  macro-F1=0.9520  P1=0.930 R1=0.902  (18s)  [ratio 0.5, orig^1.25, C=1, rho=5.59]

[497/1560] LR        repeat 4 fold 1  macro-F1=0.8298  P1=0.572 R1=0.960  (6s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[498/1560] LR        repeat 4 fold 1  macro-F1=0.9528  P1=0.933 R1=0.902  (18s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[499/1560] LR        repeat 4 fold 1  macro-F1=0.5225  P1=0.227 R1=0.994  (6s)  [ratio 0.5, orig^2.0, C=0, rho=23.84]

[500/1560] LR        repeat 4 fold 1  macro-F1=0.9513  P1=0.925 R1=0.905  (18s)  [ratio 0.5, orig^2.0, C=1, rho=23.84]

[501/1560] LR        repeat 4 fold 1  macro-F1=0.9467  P1=0.903 R1=0.911  (6s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[502/1560] LR        repeat 4 fold 1  macro-F1=0.9467  P1=0.903 R1=0.911  (18s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[503/1560] LR        repeat 4 fold 1  macro-F1=0.9475  P1=0.905 R1=0.911  (7s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[504/1560] LR        repeat 4 fold 1  macro-F1=0.9559  P1=0.951 R1=0.896  (20s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[505/1560] LR        repeat 4 fold 1  macro-F1=0.9409  P1=0.872 R1=0.923  (7s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[506/1560] LR        repeat 4 fold 1  macro-F1=0.9569  P1=0.951 R1=0.899  (20s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[507/1560] LR        repeat 4 fold 1  macro-F1=0.9345  P1=0.844 R1=0.933  (7s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[508/1560] LR        repeat 4 fold 1  macro-F1=0.9577  P1=0.954 R1=0.899  (19s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[509/1560] LR        repeat 4 fold 1  macro-F1=0.9177  P1=0.784 R1=0.948  (7s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[510/1560] LR        repeat 4 fold 1  macro-F1=0.9557  P1=0.957 R1=0.890  (19s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[511/1560] LR        repeat 4 fold 1  macro-F1=0.8785  P1=0.678 R1=0.957  (6s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[512/1560] LR        repeat 4 fold 1  macro-F1=0.9557  P1=0.957 R1=0.890  (18s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[513/1560] LR        repeat 4 fold 1  macro-F1=0.8183  P1=0.550 R1=0.960  (7s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[514/1560] LR        repeat 4 fold 1  macro-F1=0.9548  P1=0.954 R1=0.890  (18s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[515/1560] LR        repeat 4 fold 1  macro-F1=0.7095  P1=0.382 R1=0.982  (7s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[516/1560] LR        repeat 4 fold 1  macro-F1=0.9548  P1=0.954 R1=0.890  (15s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[517/1560] LR        repeat 4 fold 1  macro-F1=0.2452  P1=0.143 R1=0.997  (6s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[518/1560] LR        repeat 4 fold 1  macro-F1=0.9554  P1=0.963 R1=0.883  (12s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[519/1560] LR        repeat 4 fold 1  macro-F1=0.9475  P1=0.905 R1=0.911  (6s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[520/1560] LR        repeat 4 fold 1  macro-F1=0.9559  P1=0.951 R1=0.896  (9s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[521/1560] RF        repeat 0 fold 0  macro-F1=0.8894  P1=1.000 R1=0.670  (43s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[522/1560] RF        repeat 0 fold 0  macro-F1=0.9132  P1=0.881 R1=0.817  (119s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[523/1560] RF        repeat 0 fold 0  macro-F1=0.9001  P1=1.000 R1=0.697  (38s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[524/1560] RF        repeat 0 fold 0  macro-F1=0.9259  P1=0.918 R1=0.826  (105s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[525/1560] RF        repeat 0 fold 0  macro-F1=0.9079  P1=0.988 R1=0.725  (32s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[526/1560] RF        repeat 0 fold 0  macro-F1=0.9337  P1=0.941 R1=0.832  (89s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[527/1560] RF        repeat 0 fold 0  macro-F1=0.9201  P1=0.988 R1=0.758  (27s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[528/1560] RF        repeat 0 fold 0  macro-F1=0.9325  P1=0.883 R1=0.881  (74s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[529/1560] RF        repeat 0 fold 0  macro-F1=0.9188  P1=0.929 R1=0.795  (22s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[530/1560] RF        repeat 0 fold 0  macro-F1=0.9281  P1=0.889 R1=0.859  (64s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[531/1560] RF        repeat 0 fold 0  macro-F1=0.9293  P1=0.900 R1=0.853  (19s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[532/1560] RF        repeat 0 fold 0  macro-F1=0.9273  P1=0.899 R1=0.847  (57s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[533/1560] RF        repeat 0 fold 0  macro-F1=0.9211  P1=0.843 R1=0.884  (19s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[534/1560] RF        repeat 0 fold 0  macro-F1=0.9201  P1=0.886 R1=0.835  (54s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[535/1560] RF        repeat 0 fold 0  macro-F1=0.8710  P1=0.660 R1=0.960  (17s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[536/1560] RF        repeat 0 fold 0  macro-F1=0.9115  P1=0.889 R1=0.804  (49s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[537/1560] RF        repeat 0 fold 0  macro-F1=0.9232  P1=0.973 R1=0.777  (20s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[538/1560] RF        repeat 0 fold 0  macro-F1=0.9352  P1=0.932 R1=0.844  (59s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[539/1560] RF        repeat 0 fold 0  macro-F1=0.9250  P1=0.930 R1=0.813  (20s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[540/1560] RF        repeat 0 fold 0  macro-F1=0.9281  P1=0.902 R1=0.847  (59s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[541/1560] RF        repeat 0 fold 0  macro-F1=0.9142  P1=0.850 R1=0.850  (20s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[542/1560] RF        repeat 0 fold 0  macro-F1=0.9093  P1=0.857 R1=0.826  (59s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[543/1560] RF        repeat 0 fold 0  macro-F1=0.8987  P1=0.785 R1=0.869  (20s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[544/1560] RF        repeat 0 fold 0  macro-F1=0.9108  P1=0.853 R1=0.835  (58s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[545/1560] RF        repeat 0 fold 0  macro-F1=0.8829  P1=0.714 R1=0.908  (20s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[546/1560] RF        repeat 0 fold 0  macro-F1=0.9012  P1=0.835 R1=0.820  (58s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[547/1560] RF        repeat 0 fold 0  macro-F1=0.8117  P1=0.546 R1=0.930  (19s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[548/1560] RF        repeat 0 fold 0  macro-F1=0.8798  P1=0.836 R1=0.746  (57s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[549/1560] RF        repeat 0 fold 0  macro-F1=0.7469  P1=0.435 R1=0.942  (19s)  [ratio 0.5, orig^1.5, C=0, rho=9.12]

[550/1560] RF        repeat 0 fold 0  macro-F1=0.8694  P1=0.767 R1=0.777  (56s)  [ratio 0.5, orig^1.5, C=1, rho=9.12]

[551/1560] RF        repeat 0 fold 0  macro-F1=0.5848  P1=0.265 R1=0.991  (18s)  [ratio 0.5, orig^2.0, C=0, rho=24.00]

[552/1560] RF        repeat 0 fold 0  macro-F1=0.8579  P1=0.781 R1=0.722  (53s)  [ratio 0.5, orig^2.0, C=1, rho=24.00]

[553/1560] RF        repeat 0 fold 0  macro-F1=0.9195  P1=0.894 R1=0.826  (20s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[554/1560] RF        repeat 0 fold 0  macro-F1=0.9175  P1=0.904 R1=0.810  (58s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[555/1560] RF        repeat 0 fold 0  macro-F1=0.9150  P1=0.884 R1=0.820  (28s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[556/1560] RF        repeat 0 fold 0  macro-F1=0.9166  P1=0.890 R1=0.820  (81s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[557/1560] RF        repeat 0 fold 0  macro-F1=0.9064  P1=0.819 R1=0.856  (29s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[558/1560] RF        repeat 0 fold 0  macro-F1=0.9084  P1=0.820 R1=0.862  (84s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[559/1560] RF        repeat 0 fold 0  macro-F1=0.8934  P1=0.760 R1=0.881  (30s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[560/1560] RF        repeat 0 fold 0  macro-F1=0.8972  P1=0.824 R1=0.817  (87s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[561/1560] RF        repeat 0 fold 0  macro-F1=0.8483  P1=0.627 R1=0.914  (30s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[562/1560] RF        repeat 0 fold 0  macro-F1=0.8857  P1=0.766 R1=0.841  (87s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[563/1560] RF        repeat 0 fold 0  macro-F1=0.8024  P1=0.528 R1=0.933  (30s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[564/1560] RF        repeat 0 fold 0  macro-F1=0.8757  P1=0.824 R1=0.743  (85s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[565/1560] RF        repeat 0 fold 0  macro-F1=0.7410  P1=0.426 R1=0.948  (30s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[566/1560] RF        repeat 0 fold 0  macro-F1=0.8707  P1=0.761 R1=0.789  (80s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[567/1560] RF        repeat 0 fold 0  macro-F1=0.6637  P1=0.332 R1=0.976  (30s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[568/1560] RF        repeat 0 fold 0  macro-F1=0.8498  P1=0.722 R1=0.755  (68s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[569/1560] RF        repeat 0 fold 0  macro-F1=0.5349  P1=0.234 R1=0.994  (30s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[570/1560] RF        repeat 0 fold 0  macro-F1=0.8128  P1=0.653 R1=0.697  (60s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[571/1560] RF        repeat 0 fold 0  macro-F1=0.9150  P1=0.884 R1=0.820  (26s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[572/1560] RF        repeat 0 fold 0  macro-F1=0.9166  P1=0.890 R1=0.820  (48s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[573/1560] RF        repeat 0 fold 1  macro-F1=0.9104  P1=0.996 R1=0.727  (23s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[574/1560] RF        repeat 0 fold 1  macro-F1=0.9220  P1=0.874 R1=0.853  (63s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[575/1560] RF        repeat 0 fold 1  macro-F1=0.9229  P1=0.992 R1=0.764  (20s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[576/1560] RF        repeat 0 fold 1  macro-F1=0.9210  P1=0.862 R1=0.862  (57s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[577/1560] RF        repeat 0 fold 1  macro-F1=0.9212  P1=0.984 R1=0.764  (19s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[578/1560] RF        repeat 0 fold 1  macro-F1=0.9155  P1=0.835 R1=0.871  (49s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[579/1560] RF        repeat 0 fold 1  macro-F1=0.9300  P1=0.963 R1=0.804  (16s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[580/1560] RF        repeat 0 fold 1  macro-F1=0.9245  P1=0.857 R1=0.880  (43s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[581/1560] RF        repeat 0 fold 1  macro-F1=0.9283  P1=0.910 R1=0.840  (13s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[582/1560] RF        repeat 0 fold 1  macro-F1=0.9247  P1=0.866 R1=0.871  (37s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[583/1560] RF        repeat 0 fold 1  macro-F1=0.9241  P1=0.873 R1=0.862  (12s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[584/1560] RF        repeat 0 fold 1  macro-F1=0.9243  P1=0.870 R1=0.865  (35s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[585/1560] RF        repeat 0 fold 1  macro-F1=0.9163  P1=0.820 R1=0.893  (11s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[586/1560] RF        repeat 0 fold 1  macro-F1=0.9130  P1=0.805 R1=0.899  (34s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[587/1560] RF        repeat 0 fold 1  macro-F1=0.8691  P1=0.663 R1=0.942  (11s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[588/1560] RF        repeat 0 fold 1  macro-F1=0.9122  P1=0.838 R1=0.856  (31s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[589/1560] RF        repeat 0 fold 1  macro-F1=0.9325  P1=0.957 R1=0.816  (21s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[590/1560] RF        repeat 0 fold 1  macro-F1=0.9284  P1=0.882 R1=0.868  (57s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[591/1560] RF        repeat 0 fold 1  macro-F1=0.9275  P1=0.907 R1=0.840  (20s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[592/1560] RF        repeat 0 fold 1  macro-F1=0.9271  P1=0.899 R1=0.847  (58s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[593/1560] RF        repeat 0 fold 1  macro-F1=0.9206  P1=0.866 R1=0.856  (20s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[594/1560] RF        repeat 0 fold 1  macro-F1=0.9201  P1=0.850 R1=0.871  (58s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[595/1560] RF        repeat 0 fold 1  macro-F1=0.9095  P1=0.801 R1=0.890  (20s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[596/1560] RF        repeat 0 fold 1  macro-F1=0.9037  P1=0.784 R1=0.890  (57s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[597/1560] RF        repeat 0 fold 1  macro-F1=0.8853  P1=0.720 R1=0.908  (19s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[598/1560] RF        repeat 0 fold 1  macro-F1=0.9057  P1=0.814 R1=0.859  (57s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[599/1560] RF        repeat 0 fold 1  macro-F1=0.8560  P1=0.638 R1=0.929  (19s)  [ratio 0.5, orig^1.25, C=0, rho=5.60]

[600/1560] RF        repeat 0 fold 1  macro-F1=0.8973  P1=0.805 R1=0.837  (56s)  [ratio 0.5, orig^1.25, C=1, rho=5.60]

[601/1560] RF        repeat 0 fold 1  macro-F1=0.8081  P1=0.536 R1=0.942  (19s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[602/1560] RF        repeat 0 fold 1  macro-F1=0.8872  P1=0.799 R1=0.807  (55s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[603/1560] RF        repeat 0 fold 1  macro-F1=0.6846  P1=0.354 R1=0.957  (18s)  [ratio 0.5, orig^2.0, C=0, rho=23.85]

[604/1560] RF        repeat 0 fold 1  macro-F1=0.8863  P1=0.805 R1=0.798  (53s)  [ratio 0.5, orig^2.0, C=1, rho=23.85]

[605/1560] RF        repeat 0 fold 1  macro-F1=0.9231  P1=0.885 R1=0.847  (20s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[606/1560] RF        repeat 0 fold 1  macro-F1=0.9253  P1=0.871 R1=0.868  (57s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[607/1560] RF        repeat 0 fold 1  macro-F1=0.9223  P1=0.882 R1=0.847  (28s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[608/1560] RF        repeat 0 fold 1  macro-F1=0.9231  P1=0.885 R1=0.847  (81s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[609/1560] RF        repeat 0 fold 1  macro-F1=0.9159  P1=0.842 R1=0.865  (29s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[610/1560] RF        repeat 0 fold 1  macro-F1=0.9113  P1=0.819 R1=0.874  (85s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[611/1560] RF        repeat 0 fold 1  macro-F1=0.9097  P1=0.799 R1=0.893  (30s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[612/1560] RF        repeat 0 fold 1  macro-F1=0.9170  P1=0.851 R1=0.859  (87s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[613/1560] RF        repeat 0 fold 1  macro-F1=0.8761  P1=0.693 R1=0.914  (30s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[614/1560] RF        repeat 0 fold 1  macro-F1=0.9079  P1=0.829 R1=0.850  (87s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[615/1560] RF        repeat 0 fold 1  macro-F1=0.8332  P1=0.587 R1=0.936  (30s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[616/1560] RF        repeat 0 fold 1  macro-F1=0.9045  P1=0.841 R1=0.825  (86s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[617/1560] RF        repeat 0 fold 1  macro-F1=0.7841  P1=0.492 R1=0.948  (30s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[618/1560] RF        repeat 0 fold 1  macro-F1=0.8880  P1=0.857 R1=0.755  (79s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[619/1560] RF        repeat 0 fold 1  macro-F1=0.7480  P1=0.435 R1=0.954  (30s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[620/1560] RF        repeat 0 fold 1  macro-F1=0.8816  P1=0.836 R1=0.752  (68s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[621/1560] RF        repeat 0 fold 1  macro-F1=0.6074  P1=0.281 R1=0.982  (29s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[622/1560] RF        repeat 0 fold 1  macro-F1=0.8606  P1=0.761 R1=0.752  (60s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[623/1560] RF        repeat 0 fold 1  macro-F1=0.9223  P1=0.882 R1=0.847  (26s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[624/1560] RF        repeat 0 fold 1  macro-F1=0.9231  P1=0.885 R1=0.847  (47s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[625/1560] RF        repeat 1 fold 0  macro-F1=0.9087  P1=0.992 R1=0.725  (44s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[626/1560] RF        repeat 1 fold 0  macro-F1=0.9233  P1=0.898 R1=0.835  (120s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[627/1560] RF        repeat 1 fold 0  macro-F1=0.9179  P1=0.988 R1=0.752  (38s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[628/1560] RF        repeat 1 fold 0  macro-F1=0.9279  P1=0.934 R1=0.820  (103s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[629/1560] RF        repeat 1 fold 0  macro-F1=0.9144  P1=0.992 R1=0.740  (32s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[630/1560] RF        repeat 1 fold 0  macro-F1=0.9337  P1=0.957 R1=0.820  (88s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[631/1560] RF        repeat 1 fold 0  macro-F1=0.9167  P1=0.958 R1=0.768  (28s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[632/1560] RF        repeat 1 fold 0  macro-F1=0.9359  P1=0.892 R1=0.884  (75s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[633/1560] RF        repeat 1 fold 0  macro-F1=0.9231  P1=0.942 R1=0.798  (22s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[634/1560] RF        repeat 1 fold 0  macro-F1=0.9345  P1=0.912 R1=0.859  (64s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[635/1560] RF        repeat 1 fold 0  macro-F1=0.9336  P1=0.926 R1=0.844  (21s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[636/1560] RF        repeat 1 fold 0  macro-F1=0.9356  P1=0.910 R1=0.865  (60s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[637/1560] RF        repeat 1 fold 0  macro-F1=0.9240  P1=0.866 R1=0.869  (19s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[638/1560] RF        repeat 1 fold 0  macro-F1=0.9273  P1=0.899 R1=0.847  (57s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[639/1560] RF        repeat 1 fold 0  macro-F1=0.8794  P1=0.698 R1=0.920  (18s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[640/1560] RF        repeat 1 fold 0  macro-F1=0.9120  P1=0.851 R1=0.841  (55s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[641/1560] RF        repeat 1 fold 0  macro-F1=0.9166  P1=0.992 R1=0.746  (19s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[642/1560] RF        repeat 1 fold 0  macro-F1=0.9424  P1=0.949 R1=0.853  (54s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[643/1560] RF        repeat 1 fold 0  macro-F1=0.9356  P1=0.961 R1=0.823  (18s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[644/1560] RF        repeat 1 fold 0  macro-F1=0.9325  P1=0.960 R1=0.813  (54s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[645/1560] RF        repeat 1 fold 0  macro-F1=0.9249  P1=0.891 R1=0.847  (19s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[646/1560] RF        repeat 1 fold 0  macro-F1=0.9203  P1=0.897 R1=0.826  (55s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[647/1560] RF        repeat 1 fold 0  macro-F1=0.9137  P1=0.827 R1=0.875  (20s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[648/1560] RF        repeat 1 fold 0  macro-F1=0.9173  P1=0.861 R1=0.850  (56s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[649/1560] RF        repeat 1 fold 0  macro-F1=0.8673  P1=0.676 R1=0.905  (19s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[650/1560] RF        repeat 1 fold 0  macro-F1=0.9086  P1=0.885 R1=0.798  (55s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[651/1560] RF        repeat 1 fold 0  macro-F1=0.8121  P1=0.551 R1=0.914  (19s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[652/1560] RF        repeat 1 fold 0  macro-F1=0.8972  P1=0.824 R1=0.817  (54s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[653/1560] RF        repeat 1 fold 0  macro-F1=0.7618  P1=0.457 R1=0.948  (18s)  [ratio 0.5, orig^1.5, C=0, rho=9.11]

[654/1560] RF        repeat 1 fold 0  macro-F1=0.8695  P1=0.857 R1=0.697  (54s)  [ratio 0.5, orig^1.5, C=1, rho=9.11]

[655/1560] RF        repeat 1 fold 0  macro-F1=0.6100  P1=0.283 R1=0.979  (18s)  [ratio 0.5, orig^2.0, C=0, rho=23.99]

[656/1560] RF        repeat 1 fold 0  macro-F1=0.8448  P1=0.861 R1=0.624  (50s)  [ratio 0.5, orig^2.0, C=1, rho=23.99]

[657/1560] RF        repeat 1 fold 0  macro-F1=0.9341  P1=0.951 R1=0.826  (20s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[658/1560] RF        repeat 1 fold 0  macro-F1=0.9245  P1=0.970 R1=0.783  (54s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[659/1560] RF        repeat 1 fold 0  macro-F1=0.9281  P1=0.931 R1=0.823  (27s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[660/1560] RF        repeat 1 fold 0  macro-F1=0.9291  P1=0.931 R1=0.826  (77s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[661/1560] RF        repeat 1 fold 0  macro-F1=0.9188  P1=0.866 R1=0.850  (28s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[662/1560] RF        repeat 1 fold 0  macro-F1=0.9065  P1=0.932 R1=0.755  (82s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[663/1560] RF        repeat 1 fold 0  macro-F1=0.9042  P1=0.797 R1=0.875  (29s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[664/1560] RF        repeat 1 fold 0  macro-F1=0.9095  P1=0.923 R1=0.771  (84s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[665/1560] RF        repeat 1 fold 0  macro-F1=0.8621  P1=0.664 R1=0.902  (30s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[666/1560] RF        repeat 1 fold 0  macro-F1=0.8871  P1=0.897 R1=0.722  (85s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[667/1560] RF        repeat 1 fold 0  macro-F1=0.8014  P1=0.530 R1=0.914  (30s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[668/1560] RF        repeat 1 fold 0  macro-F1=0.8761  P1=0.881 R1=0.700  (83s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[669/1560] RF        repeat 1 fold 0  macro-F1=0.7509  P1=0.442 R1=0.936  (30s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[670/1560] RF        repeat 1 fold 0  macro-F1=0.8758  P1=0.795 R1=0.771  (79s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[671/1560] RF        repeat 1 fold 0  macro-F1=0.6951  P1=0.366 R1=0.963  (30s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[672/1560] RF        repeat 1 fold 0  macro-F1=0.8734  P1=0.796 R1=0.761  (67s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[673/1560] RF        repeat 1 fold 0  macro-F1=0.5238  P1=0.228 R1=0.994  (28s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[674/1560] RF        repeat 1 fold 0  macro-F1=0.8418  P1=0.773 R1=0.676  (58s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[675/1560] RF        repeat 1 fold 0  macro-F1=0.9281  P1=0.931 R1=0.823  (25s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[676/1560] RF        repeat 1 fold 0  macro-F1=0.9291  P1=0.931 R1=0.826  (46s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[677/1560] RF        repeat 1 fold 1  macro-F1=0.9059  P1=0.996 R1=0.715  (40s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[678/1560] RF        repeat 1 fold 1  macro-F1=0.9420  P1=0.934 R1=0.865  (116s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[679/1560] RF        repeat 1 fold 1  macro-F1=0.9185  P1=0.992 R1=0.752  (36s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[680/1560] RF        repeat 1 fold 1  macro-F1=0.9408  P1=0.919 R1=0.874  (103s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[681/1560] RF        repeat 1 fold 1  macro-F1=0.9324  P1=0.996 R1=0.788  (32s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[682/1560] RF        repeat 1 fold 1  macro-F1=0.9462  P1=0.949 R1=0.865  (87s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[683/1560] RF        repeat 1 fold 1  macro-F1=0.9395  P1=0.982 R1=0.819  (28s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[684/1560] RF        repeat 1 fold 1  macro-F1=0.9424  P1=0.909 R1=0.890  (76s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[685/1560] RF        repeat 1 fold 1  macro-F1=0.9319  P1=0.917 R1=0.847  (23s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[686/1560] RF        repeat 1 fold 1  macro-F1=0.9323  P1=0.883 R1=0.880  (66s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[687/1560] RF        repeat 1 fold 1  macro-F1=0.9298  P1=0.877 R1=0.877  (21s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[688/1560] RF        repeat 1 fold 1  macro-F1=0.9286  P1=0.879 R1=0.871  (60s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[689/1560] RF        repeat 1 fold 1  macro-F1=0.9202  P1=0.830 R1=0.896  (20s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[690/1560] RF        repeat 1 fold 1  macro-F1=0.9265  P1=0.869 R1=0.874  (58s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[691/1560] RF        repeat 1 fold 1  macro-F1=0.8710  P1=0.670 R1=0.936  (18s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[692/1560] RF        repeat 1 fold 1  macro-F1=0.9236  P1=0.868 R1=0.865  (54s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[693/1560] RF        repeat 1 fold 1  macro-F1=0.9332  P1=0.964 R1=0.813  (37s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[694/1560] RF        repeat 1 fold 1  macro-F1=0.9437  P1=0.904 R1=0.899  (102s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[695/1560] RF        repeat 1 fold 1  macro-F1=0.9357  P1=0.938 R1=0.840  (38s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[696/1560] RF        repeat 1 fold 1  macro-F1=0.9386  P1=0.908 R1=0.877  (107s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[697/1560] RF        repeat 1 fold 1  macro-F1=0.9342  P1=0.899 R1=0.871  (40s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[698/1560] RF        repeat 1 fold 1  macro-F1=0.9323  P1=0.911 R1=0.853  (113s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[699/1560] RF        repeat 1 fold 1  macro-F1=0.9208  P1=0.834 R1=0.893  (43s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[700/1560] RF        repeat 1 fold 1  macro-F1=0.9231  P1=0.898 R1=0.834  (120s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[701/1560] RF        repeat 1 fold 1  macro-F1=0.8928  P1=0.744 R1=0.902  (45s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[702/1560] RF        repeat 1 fold 1  macro-F1=0.9234  P1=0.870 R1=0.862  (127s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[703/1560] RF        repeat 1 fold 1  macro-F1=0.8702  P1=0.670 R1=0.933  (46s)  [ratio 0.5, orig^1.25, C=0, rho=5.60]

[704/1560] RF        repeat 1 fold 1  macro-F1=0.9138  P1=0.884 R1=0.816  (128s)  [ratio 0.5, orig^1.25, C=1, rho=5.60]

[705/1560] RF        repeat 1 fold 1  macro-F1=0.8299  P1=0.575 R1=0.951  (47s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[706/1560] RF        repeat 1 fold 1  macro-F1=0.9063  P1=0.853 R1=0.819  (129s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[707/1560] RF        repeat 1 fold 1  macro-F1=0.6857  P1=0.355 R1=0.969  (44s)  [ratio 0.5, orig^2.0, C=0, rho=23.85]

[708/1560] RF        repeat 1 fold 1  macro-F1=0.8903  P1=0.816 R1=0.801  (117s)  [ratio 0.5, orig^2.0, C=1, rho=23.85]

[709/1560] RF        repeat 1 fold 1  macro-F1=0.9339  P1=0.917 R1=0.853  (39s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[710/1560] RF        repeat 1 fold 1  macro-F1=0.9364  P1=0.927 R1=0.853  (108s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[711/1560] RF        repeat 1 fold 1  macro-F1=0.9307  P1=0.906 R1=0.853  (59s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[712/1560] RF        repeat 1 fold 1  macro-F1=0.9305  P1=0.908 R1=0.850  (164s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[713/1560] RF        repeat 1 fold 1  macro-F1=0.9220  P1=0.851 R1=0.877  (70s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[714/1560] RF        repeat 1 fold 1  macro-F1=0.9229  P1=0.887 R1=0.844  (189s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[715/1560] RF        repeat 1 fold 1  macro-F1=0.9092  P1=0.796 R1=0.896  (78s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[716/1560] RF        repeat 1 fold 1  macro-F1=0.9172  P1=0.870 R1=0.840  (214s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[717/1560] RF        repeat 1 fold 1  macro-F1=0.8894  P1=0.735 R1=0.902  (84s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[718/1560] RF        repeat 1 fold 1  macro-F1=0.9085  P1=0.843 R1=0.837  (231s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[719/1560] RF        repeat 1 fold 1  macro-F1=0.8599  P1=0.651 R1=0.920  (87s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[720/1560] RF        repeat 1 fold 1  macro-F1=0.9057  P1=0.839 R1=0.831  (234s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[721/1560] RF        repeat 1 fold 1  macro-F1=0.8073  P1=0.535 R1=0.939  (91s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[722/1560] RF        repeat 1 fold 1  macro-F1=0.9002  P1=0.823 R1=0.828  (212s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[723/1560] RF        repeat 1 fold 1  macro-F1=0.7404  P1=0.424 R1=0.960  (91s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[724/1560] RF        repeat 1 fold 1  macro-F1=0.8945  P1=0.810 R1=0.822  (202s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[725/1560] RF        repeat 1 fold 1  macro-F1=0.5965  P1=0.273 R1=0.979  (79s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[726/1560] RF        repeat 1 fold 1  macro-F1=0.8725  P1=0.762 R1=0.794  (163s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[727/1560] RF        repeat 1 fold 1  macro-F1=0.9307  P1=0.906 R1=0.853  (56s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[728/1560] RF        repeat 1 fold 1  macro-F1=0.9305  P1=0.908 R1=0.850  (116s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[729/1560] RF        repeat 2 fold 0  macro-F1=0.9212  P1=0.988 R1=0.761  (43s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[730/1560] RF        repeat 2 fold 0  macro-F1=0.9199  P1=0.889 R1=0.832  (118s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[731/1560] RF        repeat 2 fold 0  macro-F1=0.9162  P1=0.980 R1=0.752  (36s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[732/1560] RF        repeat 2 fold 0  macro-F1=0.9351  P1=0.918 R1=0.856  (102s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[733/1560] RF        repeat 2 fold 0  macro-F1=0.9195  P1=0.980 R1=0.761  (31s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[734/1560] RF        repeat 2 fold 0  macro-F1=0.9433  P1=0.949 R1=0.856  (86s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[735/1560] RF        repeat 2 fold 0  macro-F1=0.9302  P1=0.963 R1=0.804  (27s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[736/1560] RF        repeat 2 fold 0  macro-F1=0.9447  P1=0.923 R1=0.884  (74s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[737/1560] RF        repeat 2 fold 0  macro-F1=0.9356  P1=0.961 R1=0.823  (22s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[738/1560] RF        repeat 2 fold 0  macro-F1=0.9402  P1=0.901 R1=0.890  (64s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[739/1560] RF        repeat 2 fold 0  macro-F1=0.9309  P1=0.906 R1=0.853  (20s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[740/1560] RF        repeat 2 fold 0  macro-F1=0.9332  P1=0.901 R1=0.865  (60s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[741/1560] RF        repeat 2 fold 0  macro-F1=0.9282  P1=0.863 R1=0.887  (20s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[742/1560] RF        repeat 2 fold 0  macro-F1=0.9338  P1=0.923 R1=0.847  (58s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[743/1560] RF        repeat 2 fold 0  macro-F1=0.8782  P1=0.681 R1=0.951  (19s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[744/1560] RF        repeat 2 fold 0  macro-F1=0.9057  P1=0.904 R1=0.774  (55s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[745/1560] RF        repeat 2 fold 0  macro-F1=0.9225  P1=0.952 R1=0.789  (20s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[746/1560] RF        repeat 2 fold 0  macro-F1=0.9438  P1=0.923 R1=0.881  (58s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[747/1560] RF        repeat 2 fold 0  macro-F1=0.9349  P1=0.938 R1=0.838  (20s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[748/1560] RF        repeat 2 fold 0  macro-F1=0.9410  P1=0.920 R1=0.875  (58s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[749/1560] RF        repeat 2 fold 0  macro-F1=0.9311  P1=0.903 R1=0.856  (20s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[750/1560] RF        repeat 2 fold 0  macro-F1=0.9329  P1=0.879 R1=0.887  (58s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[751/1560] RF        repeat 2 fold 0  macro-F1=0.9294  P1=0.873 R1=0.881  (20s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[752/1560] RF        repeat 2 fold 0  macro-F1=0.9255  P1=0.924 R1=0.820  (59s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[753/1560] RF        repeat 2 fold 0  macro-F1=0.9085  P1=0.774 R1=0.924  (19s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[754/1560] RF        repeat 2 fold 0  macro-F1=0.9210  P1=0.914 R1=0.813  (57s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[755/1560] RF        repeat 2 fold 0  macro-F1=0.8678  P1=0.656 R1=0.951  (19s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[756/1560] RF        repeat 2 fold 0  macro-F1=0.9168  P1=0.845 R1=0.865  (56s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[757/1560] RF        repeat 2 fold 0  macro-F1=0.8047  P1=0.526 R1=0.957  (19s)  [ratio 0.5, orig^1.5, C=0, rho=9.11]

[758/1560] RF        repeat 2 fold 0  macro-F1=0.9047  P1=0.860 R1=0.807  (55s)  [ratio 0.5, orig^1.5, C=1, rho=9.11]

[759/1560] RF        repeat 2 fold 0  macro-F1=0.6317  P1=0.302 R1=0.982  (18s)  [ratio 0.5, orig^2.0, C=0, rho=23.99]

[760/1560] RF        repeat 2 fold 0  macro-F1=0.8906  P1=0.816 R1=0.801  (52s)  [ratio 0.5, orig^2.0, C=1, rho=23.99]

[761/1560] RF        repeat 2 fold 0  macro-F1=0.9370  P1=0.936 R1=0.847  (20s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[762/1560] RF        repeat 2 fold 0  macro-F1=0.9345  P1=0.897 R1=0.875  (58s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[763/1560] RF        repeat 2 fold 0  macro-F1=0.9326  P1=0.926 R1=0.841  (28s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[764/1560] RF        repeat 2 fold 0  macro-F1=0.9326  P1=0.926 R1=0.841  (81s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[765/1560] RF        repeat 2 fold 0  macro-F1=0.9327  P1=0.881 R1=0.884  (30s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[766/1560] RF        repeat 2 fold 0  macro-F1=0.9337  P1=0.881 R1=0.887  (85s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[767/1560] RF        repeat 2 fold 0  macro-F1=0.9221  P1=0.833 R1=0.899  (30s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[768/1560] RF        repeat 2 fold 0  macro-F1=0.9188  P1=0.878 R1=0.838  (88s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[769/1560] RF        repeat 2 fold 0  macro-F1=0.8975  P1=0.744 R1=0.924  (30s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[770/1560] RF        repeat 2 fold 0  macro-F1=0.9148  P1=0.835 R1=0.869  (87s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[771/1560] RF        repeat 2 fold 0  macro-F1=0.8580  P1=0.638 R1=0.942  (30s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[772/1560] RF        repeat 2 fold 0  macro-F1=0.9063  P1=0.866 R1=0.807  (84s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[773/1560] RF        repeat 2 fold 0  macro-F1=0.8024  P1=0.523 R1=0.954  (30s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[774/1560] RF        repeat 2 fold 0  macro-F1=0.9007  P1=0.822 R1=0.832  (79s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[775/1560] RF        repeat 2 fold 0  macro-F1=0.7588  P1=0.450 R1=0.963  (30s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[776/1560] RF        repeat 2 fold 0  macro-F1=0.8931  P1=0.847 R1=0.780  (69s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[777/1560] RF        repeat 2 fold 0  macro-F1=0.5873  P1=0.266 R1=0.982  (29s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[778/1560] RF        repeat 2 fold 0  macro-F1=0.8818  P1=0.822 R1=0.765  (59s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[779/1560] RF        repeat 2 fold 0  macro-F1=0.9326  P1=0.926 R1=0.841  (26s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[780/1560] RF        repeat 2 fold 0  macro-F1=0.9326  P1=0.926 R1=0.841  (48s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[781/1560] RF        repeat 2 fold 1  macro-F1=0.8718  P1=1.000 R1=0.626  (23s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[782/1560] RF        repeat 2 fold 1  macro-F1=0.9196  P1=0.902 R1=0.819  (65s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[783/1560] RF        repeat 2 fold 1  macro-F1=0.8862  P1=0.991 R1=0.666  (21s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[784/1560] RF        repeat 2 fold 1  macro-F1=0.9165  P1=0.877 R1=0.831  (58s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[785/1560] RF        repeat 2 fold 1  macro-F1=0.8924  P1=0.947 R1=0.706  (19s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[786/1560] RF        repeat 2 fold 1  macro-F1=0.9338  P1=0.904 R1=0.865  (51s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[787/1560] RF        repeat 2 fold 1  macro-F1=0.9098  P1=0.943 R1=0.758  (17s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[788/1560] RF        repeat 2 fold 1  macro-F1=0.9356  P1=0.907 R1=0.868  (45s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[789/1560] RF        repeat 2 fold 1  macro-F1=0.9275  P1=0.937 R1=0.816  (13s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[790/1560] RF        repeat 2 fold 1  macro-F1=0.9324  P1=0.896 R1=0.868  (38s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[791/1560] RF        repeat 2 fold 1  macro-F1=0.9301  P1=0.900 R1=0.856  (12s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[792/1560] RF        repeat 2 fold 1  macro-F1=0.9279  P1=0.902 R1=0.847  (36s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[793/1560] RF        repeat 2 fold 1  macro-F1=0.9236  P1=0.845 R1=0.890  (12s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[794/1560] RF        repeat 2 fold 1  macro-F1=0.9255  P1=0.893 R1=0.847  (35s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[795/1560] RF        repeat 2 fold 1  macro-F1=0.8735  P1=0.676 R1=0.936  (12s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[796/1560] RF        repeat 2 fold 1  macro-F1=0.9055  P1=0.850 R1=0.819  (33s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[797/1560] RF        repeat 2 fold 1  macro-F1=0.9218  P1=0.959 R1=0.782  (21s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[798/1560] RF        repeat 2 fold 1  macro-F1=0.9251  P1=0.885 R1=0.853  (58s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[799/1560] RF        repeat 2 fold 1  macro-F1=0.9191  P1=0.908 R1=0.813  (22s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[800/1560] RF        repeat 2 fold 1  macro-F1=0.9205  P1=0.879 R1=0.844  (62s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[801/1560] RF        repeat 2 fold 1  macro-F1=0.9146  P1=0.864 R1=0.837  (23s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[802/1560] RF        repeat 2 fold 1  macro-F1=0.9146  P1=0.864 R1=0.837  (65s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[803/1560] RF        repeat 2 fold 1  macro-F1=0.9008  P1=0.796 R1=0.862  (25s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[804/1560] RF        repeat 2 fold 1  macro-F1=0.9055  P1=0.824 R1=0.847  (71s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[805/1560] RF        repeat 2 fold 1  macro-F1=0.8905  P1=0.740 R1=0.899  (27s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[806/1560] RF        repeat 2 fold 1  macro-F1=0.8983  P1=0.847 R1=0.798  (76s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[807/1560] RF        repeat 2 fold 1  macro-F1=0.8693  P1=0.672 R1=0.923  (28s)  [ratio 0.5, orig^1.25, C=0, rho=5.60]

[808/1560] RF        repeat 2 fold 1  macro-F1=0.8866  P1=0.834 R1=0.770  (79s)  [ratio 0.5, orig^1.25, C=1, rho=5.60]

[809/1560] RF        repeat 2 fold 1  macro-F1=0.8227  P1=0.566 R1=0.933  (29s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[810/1560] RF        repeat 2 fold 1  macro-F1=0.8862  P1=0.836 R1=0.767  (80s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[811/1560] RF        repeat 2 fold 1  macro-F1=0.6849  P1=0.354 R1=0.966  (27s)  [ratio 0.5, orig^2.0, C=0, rho=23.85]

[812/1560] RF        repeat 2 fold 1  macro-F1=0.8771  P1=0.779 R1=0.791  (71s)  [ratio 0.5, orig^2.0, C=1, rho=23.85]

[813/1560] RF        repeat 2 fold 1  macro-F1=0.9169  P1=0.885 R1=0.825  (22s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[814/1560] RF        repeat 2 fold 1  macro-F1=0.9183  P1=0.858 R1=0.856  (62s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[815/1560] RF        repeat 2 fold 1  macro-F1=0.9243  P1=0.909 R1=0.828  (34s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[816/1560] RF        repeat 2 fold 1  macro-F1=0.9231  P1=0.898 R1=0.834  (92s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[817/1560] RF        repeat 2 fold 1  macro-F1=0.9057  P1=0.822 R1=0.850  (40s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[818/1560] RF        repeat 2 fold 1  macro-F1=0.9100  P1=0.848 R1=0.837  (109s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[819/1560] RF        repeat 2 fold 1  macro-F1=0.8925  P1=0.768 R1=0.865  (46s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[820/1560] RF        repeat 2 fold 1  macro-F1=0.8997  P1=0.827 R1=0.822  (124s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[821/1560] RF        repeat 2 fold 1  macro-F1=0.8854  P1=0.724 R1=0.902  (50s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[822/1560] RF        repeat 2 fold 1  macro-F1=0.8911  P1=0.834 R1=0.785  (136s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[823/1560] RF        repeat 2 fold 1  macro-F1=0.8575  P1=0.645 R1=0.920  (54s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[824/1560] RF        repeat 2 fold 1  macro-F1=0.8886  P1=0.812 R1=0.798  (142s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[825/1560] RF        repeat 2 fold 1  macro-F1=0.8172  P1=0.555 R1=0.936  (53s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[826/1560] RF        repeat 2 fold 1  macro-F1=0.8854  P1=0.811 R1=0.788  (127s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[827/1560] RF        repeat 2 fold 1  macro-F1=0.7623  P1=0.457 R1=0.948  (52s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[828/1560] RF        repeat 2 fold 1  macro-F1=0.8845  P1=0.840 R1=0.758  (118s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[829/1560] RF        repeat 2 fold 1  macro-F1=0.5900  P1=0.268 R1=0.985  (44s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[830/1560] RF        repeat 2 fold 1  macro-F1=0.8734  P1=0.793 R1=0.764  (92s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[831/1560] RF        repeat 2 fold 1  macro-F1=0.9243  P1=0.909 R1=0.828  (31s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[832/1560] RF        repeat 2 fold 1  macro-F1=0.9231  P1=0.898 R1=0.834  (67s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[833/1560] RF        repeat 3 fold 0  macro-F1=0.8942  P1=1.000 R1=0.682  (24s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[834/1560] RF        repeat 3 fold 0  macro-F1=0.9221  P1=0.887 R1=0.841  (65s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[835/1560] RF        repeat 3 fold 0  macro-F1=0.9019  P1=0.991 R1=0.706  (21s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[836/1560] RF        repeat 3 fold 0  macro-F1=0.9326  P1=0.896 R1=0.869  (58s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[837/1560] RF        repeat 3 fold 0  macro-F1=0.9096  P1=0.996 R1=0.725  (19s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[838/1560] RF        repeat 3 fold 0  macro-F1=0.9347  P1=0.894 R1=0.878  (50s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[839/1560] RF        repeat 3 fold 0  macro-F1=0.9138  P1=0.984 R1=0.743  (16s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[840/1560] RF        repeat 3 fold 0  macro-F1=0.9291  P1=0.916 R1=0.838  (44s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[841/1560] RF        repeat 3 fold 0  macro-F1=0.9198  P1=0.945 R1=0.786  (13s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[842/1560] RF        repeat 3 fold 0  macro-F1=0.9356  P1=0.927 R1=0.850  (38s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[843/1560] RF        repeat 3 fold 0  macro-F1=0.9259  P1=0.918 R1=0.826  (12s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[844/1560] RF        repeat 3 fold 0  macro-F1=0.9251  P1=0.915 R1=0.826  (36s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[845/1560] RF        repeat 3 fold 0  macro-F1=0.9232  P1=0.852 R1=0.881  (11s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[846/1560] RF        repeat 3 fold 0  macro-F1=0.9082  P1=0.926 R1=0.765  (35s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[847/1560] RF        repeat 3 fold 0  macro-F1=0.8732  P1=0.675 R1=0.936  (11s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[848/1560] RF        repeat 3 fold 0  macro-F1=0.9015  P1=0.890 R1=0.771  (32s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[849/1560] RF        repeat 3 fold 0  macro-F1=0.9159  P1=0.969 R1=0.758  (34s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[850/1560] RF        repeat 3 fold 0  macro-F1=0.9267  P1=0.894 R1=0.850  (95s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[851/1560] RF        repeat 3 fold 0  macro-F1=0.9206  P1=0.948 R1=0.786  (34s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[852/1560] RF        repeat 3 fold 0  macro-F1=0.9249  P1=0.918 R1=0.823  (98s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[853/1560] RF        repeat 3 fold 0  macro-F1=0.9238  P1=0.918 R1=0.820  (36s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[854/1560] RF        repeat 3 fold 0  macro-F1=0.9219  P1=0.890 R1=0.838  (104s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[855/1560] RF        repeat 3 fold 0  macro-F1=0.9172  P1=0.852 R1=0.859  (38s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[856/1560] RF        repeat 3 fold 0  macro-F1=0.9187  P1=0.916 R1=0.804  (107s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[857/1560] RF        repeat 3 fold 0  macro-F1=0.8963  P1=0.756 R1=0.899  (40s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[858/1560] RF        repeat 3 fold 0  macro-F1=0.9129  P1=0.909 R1=0.792  (111s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[859/1560] RF        repeat 3 fold 0  macro-F1=0.8533  P1=0.634 R1=0.924  (40s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[860/1560] RF        repeat 3 fold 0  macro-F1=0.9004  P1=0.890 R1=0.768  (113s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[861/1560] RF        repeat 3 fold 0  macro-F1=0.7819  P1=0.490 R1=0.942  (41s)  [ratio 0.5, orig^1.5, C=0, rho=9.11]

[862/1560] RF        repeat 3 fold 0  macro-F1=0.8905  P1=0.859 R1=0.761  (111s)  [ratio 0.5, orig^1.5, C=1, rho=9.11]

[863/1560] RF        repeat 3 fold 0  macro-F1=0.5950  P1=0.272 R1=0.985  (35s)  [ratio 0.5, orig^2.0, C=0, rho=23.99]

[864/1560] RF        repeat 3 fold 0  macro-F1=0.8724  P1=0.808 R1=0.746  (94s)  [ratio 0.5, orig^2.0, C=1, rho=23.99]

[865/1560] RF        repeat 3 fold 0  macro-F1=0.9213  P1=0.939 R1=0.795  (35s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[866/1560] RF        repeat 3 fold 0  macro-F1=0.9223  P1=0.898 R1=0.832  (99s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[867/1560] RF        repeat 3 fold 0  macro-F1=0.9190  P1=0.926 R1=0.798  (54s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[868/1560] RF        repeat 3 fold 0  macro-F1=0.9220  P1=0.914 R1=0.817  (151s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[869/1560] RF        repeat 3 fold 0  macro-F1=0.9211  P1=0.887 R1=0.838  (62s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[870/1560] RF        repeat 3 fold 0  macro-F1=0.9210  P1=0.914 R1=0.813  (172s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[871/1560] RF        repeat 3 fold 0  macro-F1=0.9088  P1=0.816 R1=0.869  (67s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[872/1560] RF        repeat 3 fold 0  macro-F1=0.9126  P1=0.912 R1=0.789  (192s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[873/1560] RF        repeat 3 fold 0  macro-F1=0.8905  P1=0.742 R1=0.896  (72s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[874/1560] RF        repeat 3 fold 0  macro-F1=0.9076  P1=0.874 R1=0.804  (202s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[875/1560] RF        repeat 3 fold 0  macro-F1=0.8443  P1=0.616 R1=0.920  (77s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[876/1560] RF        repeat 3 fold 0  macro-F1=0.8905  P1=0.898 R1=0.731  (205s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[877/1560] RF        repeat 3 fold 0  macro-F1=0.7795  P1=0.486 R1=0.942  (77s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[878/1560] RF        repeat 3 fold 0  macro-F1=0.8816  P1=0.865 R1=0.728  (184s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[879/1560] RF        repeat 3 fold 0  macro-F1=0.7212  P1=0.398 R1=0.963  (77s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[880/1560] RF        repeat 3 fold 0  macro-F1=0.8797  P1=0.828 R1=0.752  (169s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[881/1560] RF        repeat 3 fold 0  macro-F1=0.4722  P1=0.203 R1=0.994  (63s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[882/1560] RF        repeat 3 fold 0  macro-F1=0.8610  P1=0.767 R1=0.746  (131s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[883/1560] RF        repeat 3 fold 0  macro-F1=0.9190  P1=0.926 R1=0.798  (49s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[884/1560] RF        repeat 3 fold 0  macro-F1=0.9220  P1=0.914 R1=0.817  (96s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[885/1560] RF        repeat 3 fold 1  macro-F1=0.9144  P1=0.988 R1=0.742  (40s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[886/1560] RF        repeat 3 fold 1  macro-F1=0.9056  P1=0.799 R1=0.877  (113s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[887/1560] RF        repeat 3 fold 1  macro-F1=0.9211  P1=0.969 R1=0.773  (35s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[888/1560] RF        repeat 3 fold 1  macro-F1=0.9167  P1=0.853 R1=0.856  (101s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[889/1560] RF        repeat 3 fold 1  macro-F1=0.9313  P1=0.977 R1=0.798  (31s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[890/1560] RF        repeat 3 fold 1  macro-F1=0.9138  P1=0.807 R1=0.899  (88s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[891/1560] RF        repeat 3 fold 1  macro-F1=0.9281  P1=0.943 R1=0.813  (28s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[892/1560] RF        repeat 3 fold 1  macro-F1=0.9295  P1=0.895 R1=0.859  (75s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[893/1560] RF        repeat 3 fold 1  macro-F1=0.9302  P1=0.928 R1=0.831  (23s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[894/1560] RF        repeat 3 fold 1  macro-F1=0.9265  P1=0.858 R1=0.887  (65s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[895/1560] RF        repeat 3 fold 1  macro-F1=0.9353  P1=0.897 R1=0.877  (21s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[896/1560] RF        repeat 3 fold 1  macro-F1=0.9346  P1=0.907 R1=0.865  (59s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[897/1560] RF        repeat 3 fold 1  macro-F1=0.9216  P1=0.826 R1=0.905  (19s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[898/1560] RF        repeat 3 fold 1  macro-F1=0.9251  P1=0.898 R1=0.840  (57s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[899/1560] RF        repeat 3 fold 1  macro-F1=0.8616  P1=0.652 R1=0.926  (18s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[900/1560] RF        repeat 3 fold 1  macro-F1=0.9240  P1=0.912 R1=0.825  (54s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[901/1560] RF        repeat 3 fold 1  macro-F1=0.9185  P1=0.992 R1=0.752  (10s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[902/1560] RF        repeat 3 fold 1  macro-F1=0.9289  P1=0.902 R1=0.850  (32s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[903/1560] RF        repeat 3 fold 1  macro-F1=0.9316  P1=0.938 R1=0.828  (11s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[904/1560] RF        repeat 3 fold 1  macro-F1=0.9338  P1=0.935 R1=0.837  (33s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[905/1560] RF        repeat 3 fold 1  macro-F1=0.9267  P1=0.855 R1=0.890  (11s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[906/1560] RF        repeat 3 fold 1  macro-F1=0.9308  P1=0.890 R1=0.868  (31s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[907/1560] RF        repeat 3 fold 1  macro-F1=0.8789  P1=0.691 R1=0.933  (10s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[908/1560] RF        repeat 3 fold 1  macro-F1=0.9267  P1=0.891 R1=0.853  (31s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[909/1560] RF        repeat 3 fold 1  macro-F1=0.7860  P1=0.494 R1=0.957  (10s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[910/1560] RF        repeat 3 fold 1  macro-F1=0.9210  P1=0.911 R1=0.816  (30s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[911/1560] RF        repeat 3 fold 1  macro-F1=0.6842  P1=0.353 R1=0.969  (9s)  [ratio 0.5, orig^1.25, C=0, rho=5.60]

[912/1560] RF        repeat 3 fold 1  macro-F1=0.9205  P1=0.891 R1=0.831  (29s)  [ratio 0.5, orig^1.25, C=1, rho=5.60]

[913/1560] RF        repeat 3 fold 1  macro-F1=0.5337  P1=0.232 R1=0.985  (9s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[914/1560] RF        repeat 3 fold 1  macro-F1=0.9170  P1=0.872 R1=0.837  (28s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[915/1560] RF        repeat 3 fold 1  macro-F1=0.2250  P1=0.140 R1=1.000  (9s)  [ratio 0.5, orig^2.0, C=0, rho=23.85]

[916/1560] RF        repeat 3 fold 1  macro-F1=0.9055  P1=0.832 R1=0.837  (27s)  [ratio 0.5, orig^2.0, C=1, rho=23.85]

[917/1560] RF        repeat 3 fold 1  macro-F1=0.9263  P1=0.896 R1=0.847  (11s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[918/1560] RF        repeat 3 fold 1  macro-F1=0.9284  P1=0.858 R1=0.893  (33s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[919/1560] RF        repeat 3 fold 1  macro-F1=0.9315  P1=0.908 R1=0.853  (14s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[920/1560] RF        repeat 3 fold 1  macro-F1=0.9279  P1=0.889 R1=0.859  (41s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[921/1560] RF        repeat 3 fold 1  macro-F1=0.9117  P1=0.792 R1=0.911  (14s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[922/1560] RF        repeat 3 fold 1  macro-F1=0.9329  P1=0.917 R1=0.850  (41s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[923/1560] RF        repeat 3 fold 1  macro-F1=0.8384  P1=0.598 R1=0.933  (13s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[924/1560] RF        repeat 3 fold 1  macro-F1=0.9263  P1=0.924 R1=0.822  (40s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[925/1560] RF        repeat 3 fold 1  macro-F1=0.7508  P1=0.438 R1=0.963  (13s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[926/1560] RF        repeat 3 fold 1  macro-F1=0.9243  P1=0.895 R1=0.840  (39s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[927/1560] RF        repeat 3 fold 1  macro-F1=0.5725  P1=0.256 R1=0.985  (13s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[928/1560] RF        repeat 3 fold 1  macro-F1=0.9135  P1=0.854 R1=0.844  (37s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[929/1560] RF        repeat 3 fold 1  macro-F1=0.5056  P1=0.218 R1=0.988  (13s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[930/1560] RF        repeat 3 fold 1  macro-F1=0.9037  P1=0.847 R1=0.816  (34s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[931/1560] RF        repeat 3 fold 1  macro-F1=0.3385  P1=0.161 R1=0.994  (12s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[932/1560] RF        repeat 3 fold 1  macro-F1=0.9007  P1=0.819 R1=0.834  (28s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[933/1560] RF        repeat 3 fold 1  macro-F1=0.1677  P1=0.132 R1=1.000  (12s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[934/1560] RF        repeat 3 fold 1  macro-F1=0.8941  P1=0.820 R1=0.810  (25s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[935/1560] RF        repeat 3 fold 1  macro-F1=0.9315  P1=0.908 R1=0.853  (13s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[936/1560] RF        repeat 3 fold 1  macro-F1=0.9279  P1=0.889 R1=0.859  (21s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[937/1560] RF        repeat 4 fold 0  macro-F1=0.9028  P1=0.979 R1=0.716  (26s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[938/1560] RF        repeat 4 fold 0  macro-F1=0.9169  P1=0.865 R1=0.844  (72s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[939/1560] RF        repeat 4 fold 0  macro-F1=0.9134  P1=0.958 R1=0.758  (23s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[940/1560] RF        repeat 4 fold 0  macro-F1=0.9287  P1=0.922 R1=0.832  (62s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[941/1560] RF        repeat 4 fold 0  macro-F1=0.9284  P1=0.960 R1=0.801  (20s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[942/1560] RF        repeat 4 fold 0  macro-F1=0.9435  P1=0.910 R1=0.893  (53s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[943/1560] RF        repeat 4 fold 0  macro-F1=0.9351  P1=0.951 R1=0.829  (17s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[944/1560] RF        repeat 4 fold 0  macro-F1=0.9341  P1=0.889 R1=0.881  (45s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[945/1560] RF        repeat 4 fold 0  macro-F1=0.9332  P1=0.932 R1=0.838  (13s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[946/1560] RF        repeat 4 fold 0  macro-F1=0.9342  P1=0.902 R1=0.869  (38s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[947/1560] RF        repeat 4 fold 0  macro-F1=0.9299  P1=0.866 R1=0.890  (12s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[948/1560] RF        repeat 4 fold 0  macro-F1=0.9292  P1=0.864 R1=0.890  (36s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[949/1560] RF        repeat 4 fold 0  macro-F1=0.9229  P1=0.825 R1=0.911  (12s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[950/1560] RF        repeat 4 fold 0  macro-F1=0.9257  P1=0.858 R1=0.884  (36s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[951/1560] RF        repeat 4 fold 0  macro-F1=0.8778  P1=0.685 R1=0.939  (11s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[952/1560] RF        repeat 4 fold 0  macro-F1=0.9108  P1=0.794 R1=0.905  (33s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[953/1560] RF        repeat 4 fold 0  macro-F1=0.9298  P1=0.937 R1=0.823  (22s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[954/1560] RF        repeat 4 fold 0  macro-F1=0.9335  P1=0.884 R1=0.884  (60s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[955/1560] RF        repeat 4 fold 0  macro-F1=0.9324  P1=0.898 R1=0.865  (22s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[956/1560] RF        repeat 4 fold 0  macro-F1=0.9263  P1=0.851 R1=0.893  (62s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[957/1560] RF        repeat 4 fold 0  macro-F1=0.9257  P1=0.869 R1=0.872  (24s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[958/1560] RF        repeat 4 fold 0  macro-F1=0.9286  P1=0.882 R1=0.869  (66s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[959/1560] RF        repeat 4 fold 0  macro-F1=0.9110  P1=0.792 R1=0.908  (26s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[960/1560] RF        repeat 4 fold 0  macro-F1=0.9162  P1=0.814 R1=0.899  (72s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[961/1560] RF        repeat 4 fold 0  macro-F1=0.8954  P1=0.738 R1=0.924  (27s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[962/1560] RF        repeat 4 fold 0  macro-F1=0.9089  P1=0.824 R1=0.859  (76s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[963/1560] RF        repeat 4 fold 0  macro-F1=0.8706  P1=0.667 R1=0.942  (29s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[964/1560] RF        repeat 4 fold 0  macro-F1=0.9017  P1=0.849 R1=0.807  (78s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[965/1560] RF        repeat 4 fold 0  macro-F1=0.8244  P1=0.564 R1=0.951  (30s)  [ratio 0.5, orig^1.5, C=0, rho=9.12]

[966/1560] RF        repeat 4 fold 0  macro-F1=0.8915  P1=0.825 R1=0.795  (79s)  [ratio 0.5, orig^1.5, C=1, rho=9.12]

[967/1560] RF        repeat 4 fold 0  macro-F1=0.7361  P1=0.416 R1=0.976  (26s)  [ratio 0.5, orig^2.0, C=0, rho=24.00]

[968/1560] RF        repeat 4 fold 0  macro-F1=0.8824  P1=0.760 R1=0.835  (70s)  [ratio 0.5, orig^2.0, C=1, rho=24.00]

[969/1560] RF        repeat 4 fold 0  macro-F1=0.9330  P1=0.891 R1=0.875  (22s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[970/1560] RF        repeat 4 fold 0  macro-F1=0.9180  P1=0.825 R1=0.893  (63s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[971/1560] RF        repeat 4 fold 0  macro-F1=0.9300  P1=0.878 R1=0.878  (34s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[972/1560] RF        repeat 4 fold 0  macro-F1=0.9306  P1=0.883 R1=0.875  (94s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[973/1560] RF        repeat 4 fold 0  macro-F1=0.9246  P1=0.848 R1=0.890  (39s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[974/1560] RF        repeat 4 fold 0  macro-F1=0.9300  P1=0.878 R1=0.878  (109s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[975/1560] RF        repeat 4 fold 0  macro-F1=0.9072  P1=0.783 R1=0.905  (46s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[976/1560] RF        repeat 4 fold 0  macro-F1=0.9168  P1=0.826 R1=0.887  (124s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[977/1560] RF        repeat 4 fold 0  macro-F1=0.8890  P1=0.720 R1=0.927  (48s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[978/1560] RF        repeat 4 fold 0  macro-F1=0.9088  P1=0.808 R1=0.878  (133s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[979/1560] RF        repeat 4 fold 0  macro-F1=0.8568  P1=0.633 R1=0.948  (54s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[980/1560] RF        repeat 4 fold 0  macro-F1=0.8963  P1=0.780 R1=0.865  (137s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[981/1560] RF        repeat 4 fold 0  macro-F1=0.8178  P1=0.553 R1=0.948  (54s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[982/1560] RF        repeat 4 fold 0  macro-F1=0.8913  P1=0.771 R1=0.856  (121s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[983/1560] RF        repeat 4 fold 0  macro-F1=0.7790  P1=0.482 R1=0.957  (52s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[984/1560] RF        repeat 4 fold 0  macro-F1=0.8835  P1=0.766 R1=0.832  (114s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[985/1560] RF        repeat 4 fold 0  macro-F1=0.6305  P1=0.301 R1=0.991  (42s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[986/1560] RF        repeat 4 fold 0  macro-F1=0.8713  P1=0.743 R1=0.813  (89s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[987/1560] RF        repeat 4 fold 0  macro-F1=0.9300  P1=0.878 R1=0.878  (33s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[988/1560] RF        repeat 4 fold 0  macro-F1=0.9306  P1=0.883 R1=0.875  (67s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[989/1560] RF        repeat 4 fold 1  macro-F1=0.9215  P1=0.980 R1=0.767  (23s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[990/1560] RF        repeat 4 fold 1  macro-F1=0.9133  P1=0.856 R1=0.840  (66s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[991/1560] RF        repeat 4 fold 1  macro-F1=0.9243  P1=0.970 R1=0.782  (21s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[992/1560] RF        repeat 4 fold 1  macro-F1=0.9054  P1=0.793 R1=0.883  (59s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[993/1560] RF        repeat 4 fold 1  macro-F1=0.9298  P1=0.967 R1=0.801  (19s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[994/1560] RF        repeat 4 fold 1  macro-F1=0.9234  P1=0.858 R1=0.874  (51s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[995/1560] RF        repeat 4 fold 1  macro-F1=0.9330  P1=0.967 R1=0.810  (17s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[996/1560] RF        repeat 4 fold 1  macro-F1=0.9356  P1=0.880 R1=0.896  (44s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[997/1560] RF        repeat 4 fold 1  macro-F1=0.9383  P1=0.964 R1=0.828  (13s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[998/1560] RF        repeat 4 fold 1  macro-F1=0.9484  P1=0.944 R1=0.877  (38s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[999/1560] RF        repeat 4 fold 1  macro-F1=0.9386  P1=0.908 R1=0.877  (12s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[1000/1560] RF        repeat 4 fold 1  macro-F1=0.9399  P1=0.903 R1=0.887  (36s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[1001/1560] RF        repeat 4 fold 1  macro-F1=0.9307  P1=0.866 R1=0.893  (11s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[1002/1560] RF        repeat 4 fold 1  macro-F1=0.9275  P1=0.907 R1=0.840  (35s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[1003/1560] RF        repeat 4 fold 1  macro-F1=0.8736  P1=0.679 R1=0.929  (11s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[1004/1560] RF        repeat 4 fold 1  macro-F1=0.9162  P1=0.893 R1=0.816  (32s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[1005/1560] RF        repeat 4 fold 1  macro-F1=0.9118  P1=0.992 R1=0.733  (22s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1006/1560] RF        repeat 4 fold 1  macro-F1=0.9365  P1=0.894 R1=0.883  (62s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1007/1560] RF        repeat 4 fold 1  macro-F1=0.9357  P1=0.974 R1=0.813  (22s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[1008/1560] RF        repeat 4 fold 1  macro-F1=0.9438  P1=0.920 R1=0.883  (63s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[1009/1560] RF        repeat 4 fold 1  macro-F1=0.9422  P1=0.949 R1=0.853  (22s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[1010/1560] RF        repeat 4 fold 1  macro-F1=0.9465  P1=0.944 R1=0.871  (62s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[1011/1560] RF        repeat 4 fold 1  macro-F1=0.9360  P1=0.887 R1=0.890  (21s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[1012/1560] RF        repeat 4 fold 1  macro-F1=0.9355  P1=0.894 R1=0.880  (61s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[1013/1560] RF        repeat 4 fold 1  macro-F1=0.9152  P1=0.796 R1=0.920  (20s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[1014/1560] RF        repeat 4 fold 1  macro-F1=0.9224  P1=0.906 R1=0.825  (61s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[1015/1560] RF        repeat 4 fold 1  macro-F1=0.8545  P1=0.633 R1=0.933  (20s)  [ratio 0.5, orig^1.25, C=0, rho=5.59]

[1016/1560] RF        repeat 4 fold 1  macro-F1=0.9231  P1=0.885 R1=0.847  (60s)  [ratio 0.5, orig^1.25, C=1, rho=5.59]

[1017/1560] RF        repeat 4 fold 1  macro-F1=0.7572  P1=0.448 R1=0.960  (20s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[1018/1560] RF        repeat 4 fold 1  macro-F1=0.9076  P1=0.871 R1=0.807  (58s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[1019/1560] RF        repeat 4 fold 1  macro-F1=0.5337  P1=0.232 R1=0.988  (19s)  [ratio 0.5, orig^2.0, C=0, rho=23.84]

[1020/1560] RF        repeat 4 fold 1  macro-F1=0.8943  P1=0.852 R1=0.779  (56s)  [ratio 0.5, orig^2.0, C=1, rho=23.84]

[1021/1560] RF        repeat 4 fold 1  macro-F1=0.9369  P1=0.971 R1=0.819  (21s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1022/1560] RF        repeat 4 fold 1  macro-F1=0.9456  P1=0.940 R1=0.871  (61s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1023/1560] RF        repeat 4 fold 1  macro-F1=0.9434  P1=0.965 R1=0.844  (30s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1024/1560] RF        repeat 4 fold 1  macro-F1=0.9477  P1=0.918 R1=0.899  (84s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1025/1560] RF        repeat 4 fold 1  macro-F1=0.9444  P1=0.926 R1=0.880  (30s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[1026/1560] RF        repeat 4 fold 1  macro-F1=0.9417  P1=0.940 R1=0.859  (88s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[1027/1560] RF        repeat 4 fold 1  macro-F1=0.9295  P1=0.846 R1=0.911  (31s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[1028/1560] RF        repeat 4 fold 1  macro-F1=0.9294  P1=0.940 R1=0.819  (90s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[1029/1560] RF        repeat 4 fold 1  macro-F1=0.8981  P1=0.744 R1=0.926  (31s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[1030/1560] RF        repeat 4 fold 1  macro-F1=0.9301  P1=0.900 R1=0.856  (90s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[1031/1560] RF        repeat 4 fold 1  macro-F1=0.8271  P1=0.571 R1=0.945  (31s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[1032/1560] RF        repeat 4 fold 1  macro-F1=0.9147  P1=0.898 R1=0.807  (87s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[1033/1560] RF        repeat 4 fold 1  macro-F1=0.7420  P1=0.425 R1=0.963  (31s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[1034/1560] RF        repeat 4 fold 1  macro-F1=0.9115  P1=0.886 R1=0.807  (82s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[1035/1560] RF        repeat 4 fold 1  macro-F1=0.6287  P1=0.299 R1=0.975  (30s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[1036/1560] RF        repeat 4 fold 1  macro-F1=0.8938  P1=0.876 R1=0.758  (69s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[1037/1560] RF        repeat 4 fold 1  macro-F1=0.4350  P1=0.188 R1=0.991  (30s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[1038/1560] RF        repeat 4 fold 1  macro-F1=0.8834  P1=0.896 R1=0.712  (61s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[1039/1560] RF        repeat 4 fold 1  macro-F1=0.9434  P1=0.965 R1=0.844  (27s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1040/1560] RF        repeat 4 fold 1  macro-F1=0.9477  P1=0.918 R1=0.899  (49s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1041/1560] XGB       repeat 0 fold 0  macro-F1=0.9442  P1=0.952 R1=0.856  (15s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[1042/1560] XGB       repeat 0 fold 0  macro-F1=0.9465  P1=0.947 R1=0.869  (46s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[1043/1560] XGB       repeat 0 fold 0  macro-F1=0.9390  P1=0.936 R1=0.853  (15s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[1044/1560] XGB       repeat 0 fold 0  macro-F1=0.9400  P1=0.936 R1=0.856  (46s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[1045/1560] XGB       repeat 0 fold 0  macro-F1=0.9487  P1=0.941 R1=0.881  (15s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[1046/1560] XGB       repeat 0 fold 0  macro-F1=0.9509  P1=0.957 R1=0.875  (47s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[1047/1560] XGB       repeat 0 fold 0  macro-F1=0.9533  P1=0.948 R1=0.890  (15s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[1048/1560] XGB       repeat 0 fold 0  macro-F1=0.9537  P1=0.960 R1=0.881  (47s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[1049/1560] XGB       repeat 0 fold 0  macro-F1=0.9460  P1=0.918 R1=0.893  (15s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1050/1560] XGB       repeat 0 fold 0  macro-F1=0.9512  P1=0.950 R1=0.881  (46s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1051/1560] XGB       repeat 0 fold 0  macro-F1=0.9367  P1=0.880 R1=0.899  (15s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[1052/1560] XGB       repeat 0 fold 0  macro-F1=0.9378  P1=0.893 R1=0.890  (46s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[1053/1560] XGB       repeat 0 fold 0  macro-F1=0.9409  P1=0.889 R1=0.905  (15s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[1054/1560] XGB       repeat 0 fold 0  macro-F1=0.9467  P1=0.962 R1=0.856  (44s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[1055/1560] XGB       repeat 0 fold 0  macro-F1=0.9347  P1=0.855 R1=0.920  (13s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[1056/1560] XGB       repeat 0 fold 0  macro-F1=0.9426  P1=0.926 R1=0.875  (42s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[1057/1560] XGB       repeat 0 fold 0  macro-F1=0.9522  P1=0.910 R1=0.924  (30s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1058/1560] XGB       repeat 0 fold 0  macro-F1=0.9506  P1=0.942 R1=0.887  (91s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1059/1560] XGB       repeat 0 fold 0  macro-F1=0.9434  P1=0.880 R1=0.924  (30s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[1060/1560] XGB       repeat 0 fold 0  macro-F1=0.9543  P1=0.926 R1=0.914  (91s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[1061/1560] XGB       repeat 0 fold 0  macro-F1=0.9401  P1=0.872 R1=0.920  (30s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[1062/1560] XGB       repeat 0 fold 0  macro-F1=0.9557  P1=0.937 R1=0.908  (92s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[1063/1560] XGB       repeat 0 fold 0  macro-F1=0.9364  P1=0.858 R1=0.924  (29s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[1064/1560] XGB       repeat 0 fold 0  macro-F1=0.9529  P1=0.957 R1=0.881  (90s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[1065/1560] XGB       repeat 0 fold 0  macro-F1=0.9231  P1=0.815 R1=0.927  (29s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[1066/1560] XGB       repeat 0 fold 0  macro-F1=0.9431  P1=0.885 R1=0.917  (88s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[1067/1560] XGB       repeat 0 fold 0  macro-F1=0.9130  P1=0.785 R1=0.927  (28s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[1068/1560] XGB       repeat 0 fold 0  macro-F1=0.9502  P1=0.930 R1=0.896  (87s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[1069/1560] XGB       repeat 0 fold 0  macro-F1=0.9106  P1=0.774 R1=0.933  (27s)  [ratio 0.5, orig^1.5, C=0, rho=9.12]

[1070/1560] XGB       repeat 0 fold 0  macro-F1=0.9495  P1=0.944 R1=0.881  (86s)  [ratio 0.5, orig^1.5, C=1, rho=9.12]

[1071/1560] XGB       repeat 0 fold 0  macro-F1=0.8742  P1=0.679 R1=0.933  (26s)  [ratio 0.5, orig^2.0, C=0, rho=24.00]

[1072/1560] XGB       repeat 0 fold 0  macro-F1=0.9508  P1=0.939 R1=0.890  (82s)  [ratio 0.5, orig^2.0, C=1, rho=24.00]

[1073/1560] XGB       repeat 0 fold 0  macro-F1=0.9416  P1=0.880 R1=0.917  (29s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1074/1560] XGB       repeat 0 fold 0  macro-F1=0.9495  P1=0.925 R1=0.899  (91s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1075/1560] XGB       repeat 0 fold 0  macro-F1=0.9391  P1=0.874 R1=0.914  (34s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1076/1560] XGB       repeat 0 fold 0  macro-F1=0.9464  P1=0.910 R1=0.902  (104s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1077/1560] XGB       repeat 0 fold 0  macro-F1=0.9361  P1=0.850 R1=0.933  (33s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[1078/1560] XGB       repeat 0 fold 0  macro-F1=0.9469  P1=0.938 R1=0.878  (104s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[1079/1560] XGB       repeat 0 fold 0  macro-F1=0.9320  P1=0.842 R1=0.927  (34s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[1080/1560] XGB       repeat 0 fold 0  macro-F1=0.9482  P1=0.914 R1=0.905  (103s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[1081/1560] XGB       repeat 0 fold 0  macro-F1=0.9331  P1=0.840 R1=0.933  (33s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[1082/1560] XGB       repeat 0 fold 0  macro-F1=0.9475  P1=0.927 R1=0.890  (101s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[1083/1560] XGB       repeat 0 fold 0  macro-F1=0.9094  P1=0.769 R1=0.936  (33s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[1084/1560] XGB       repeat 0 fold 0  macro-F1=0.9534  P1=0.945 R1=0.893  (96s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[1085/1560] XGB       repeat 0 fold 0  macro-F1=0.9068  P1=0.760 R1=0.939  (32s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[1086/1560] XGB       repeat 0 fold 0  macro-F1=0.9457  P1=0.905 R1=0.905  (86s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[1087/1560] XGB       repeat 0 fold 0  macro-F1=0.8959  P1=0.731 R1=0.939  (31s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[1088/1560] XGB       repeat 0 fold 0  macro-F1=0.9435  P1=0.895 R1=0.908  (70s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[1089/1560] XGB       repeat 0 fold 0  macro-F1=0.8542  P1=0.626 R1=0.951  (32s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[1090/1560] XGB       repeat 0 fold 0  macro-F1=0.9486  P1=0.944 R1=0.878  (61s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[1091/1560] XGB       repeat 0 fold 0  macro-F1=0.9391  P1=0.874 R1=0.914  (32s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1092/1560] XGB       repeat 0 fold 0  macro-F1=0.9464  P1=0.910 R1=0.902  (53s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1093/1560] XGB       repeat 0 fold 1  macro-F1=0.9422  P1=0.931 R1=0.868  (12s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[1094/1560] XGB       repeat 0 fold 1  macro-F1=0.9384  P1=0.911 R1=0.874  (38s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[1095/1560] XGB       repeat 0 fold 1  macro-F1=0.9442  P1=0.912 R1=0.893  (13s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[1096/1560] XGB       repeat 0 fold 1  macro-F1=0.9455  P1=0.923 R1=0.887  (38s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[1097/1560] XGB       repeat 0 fold 1  macro-F1=0.9426  P1=0.907 R1=0.893  (13s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[1098/1560] XGB       repeat 0 fold 1  macro-F1=0.9410  P1=0.901 R1=0.893  (38s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[1099/1560] XGB       repeat 0 fold 1  macro-F1=0.9446  P1=0.905 R1=0.902  (13s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[1100/1560] XGB       repeat 0 fold 1  macro-F1=0.9429  P1=0.917 R1=0.883  (39s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[1101/1560] XGB       repeat 0 fold 1  macro-F1=0.9278  P1=0.854 R1=0.896  (12s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1102/1560] XGB       repeat 0 fold 1  macro-F1=0.9445  P1=0.943 R1=0.865  (38s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1103/1560] XGB       repeat 0 fold 1  macro-F1=0.9356  P1=0.866 R1=0.911  (12s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[1104/1560] XGB       repeat 0 fold 1  macro-F1=0.9417  P1=0.940 R1=0.859  (38s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[1105/1560] XGB       repeat 0 fold 1  macro-F1=0.9335  P1=0.844 R1=0.929  (11s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[1106/1560] XGB       repeat 0 fold 1  macro-F1=0.9381  P1=0.858 R1=0.929  (37s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[1107/1560] XGB       repeat 0 fold 1  macro-F1=0.9273  P1=0.827 R1=0.926  (11s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[1108/1560] XGB       repeat 0 fold 1  macro-F1=0.9317  P1=0.866 R1=0.896  (36s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[1109/1560] XGB       repeat 0 fold 1  macro-F1=0.9384  P1=0.881 R1=0.905  (45s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1110/1560] XGB       repeat 0 fold 1  macro-F1=0.9442  P1=0.912 R1=0.893  (141s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1111/1560] XGB       repeat 0 fold 1  macro-F1=0.9420  P1=0.884 R1=0.914  (45s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[1112/1560] XGB       repeat 0 fold 1  macro-F1=0.9421  P1=0.899 R1=0.899  (141s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[1113/1560] XGB       repeat 0 fold 1  macro-F1=0.9306  P1=0.845 R1=0.917  (45s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[1114/1560] XGB       repeat 0 fold 1  macro-F1=0.9379  P1=0.888 R1=0.896  (142s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[1115/1560] XGB       repeat 0 fold 1  macro-F1=0.9294  P1=0.836 R1=0.923  (44s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[1116/1560] XGB       repeat 0 fold 1  macro-F1=0.9460  P1=0.915 R1=0.896  (139s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[1117/1560] XGB       repeat 0 fold 1  macro-F1=0.9216  P1=0.799 R1=0.942  (43s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[1118/1560] XGB       repeat 0 fold 1  macro-F1=0.9435  P1=0.907 R1=0.896  (135s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[1119/1560] XGB       repeat 0 fold 1  macro-F1=0.9213  P1=0.794 R1=0.948  (41s)  [ratio 0.5, orig^1.25, C=0, rho=5.60]

[1120/1560] XGB       repeat 0 fold 1  macro-F1=0.9439  P1=0.917 R1=0.887  (128s)  [ratio 0.5, orig^1.25, C=1, rho=5.60]

[1121/1560] XGB       repeat 0 fold 1  macro-F1=0.9130  P1=0.769 R1=0.951  (39s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[1122/1560] XGB       repeat 0 fold 1  macro-F1=0.9452  P1=0.929 R1=0.880  (122s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[1123/1560] XGB       repeat 0 fold 1  macro-F1=0.8842  P1=0.688 R1=0.966  (34s)  [ratio 0.5, orig^2.0, C=0, rho=23.85]

[1124/1560] XGB       repeat 0 fold 1  macro-F1=0.9413  P1=0.911 R1=0.883  (107s)  [ratio 0.5, orig^2.0, C=1, rho=23.85]

[1125/1560] XGB       repeat 0 fold 1  macro-F1=0.9359  P1=0.862 R1=0.917  (45s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1126/1560] XGB       repeat 0 fold 1  macro-F1=0.9464  P1=0.926 R1=0.887  (140s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1127/1560] XGB       repeat 0 fold 1  macro-F1=0.9329  P1=0.852 R1=0.917  (53s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1128/1560] XGB       repeat 0 fold 1  macro-F1=0.9413  P1=0.896 R1=0.899  (163s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1129/1560] XGB       repeat 0 fold 1  macro-F1=0.9366  P1=0.854 R1=0.929  (52s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[1130/1560] XGB       repeat 0 fold 1  macro-F1=0.9459  P1=0.935 R1=0.877  (162s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[1131/1560] XGB       repeat 0 fold 1  macro-F1=0.9281  P1=0.830 R1=0.926  (51s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[1132/1560] XGB       repeat 0 fold 1  macro-F1=0.9490  P1=0.932 R1=0.890  (159s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[1133/1560] XGB       repeat 0 fold 1  macro-F1=0.9260  P1=0.812 R1=0.942  (49s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[1134/1560] XGB       repeat 0 fold 1  macro-F1=0.9487  P1=0.938 R1=0.883  (152s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[1135/1560] XGB       repeat 0 fold 1  macro-F1=0.9148  P1=0.784 R1=0.936  (47s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[1136/1560] XGB       repeat 0 fold 1  macro-F1=0.9461  P1=0.932 R1=0.880  (142s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[1137/1560] XGB       repeat 0 fold 1  macro-F1=0.9125  P1=0.766 R1=0.954  (45s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[1138/1560] XGB       repeat 0 fold 1  macro-F1=0.9464  P1=0.926 R1=0.887  (118s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[1139/1560] XGB       repeat 0 fold 1  macro-F1=0.8966  P1=0.721 R1=0.960  (43s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[1140/1560] XGB       repeat 0 fold 1  macro-F1=0.9449  P1=0.918 R1=0.890  (103s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[1141/1560] XGB       repeat 0 fold 1  macro-F1=0.8496  P1=0.610 R1=0.966  (38s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[1142/1560] XGB       repeat 0 fold 1  macro-F1=0.9391  P1=0.886 R1=0.902  (82s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[1143/1560] XGB       repeat 0 fold 1  macro-F1=0.9329  P1=0.852 R1=0.917  (44s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1144/1560] XGB       repeat 0 fold 1  macro-F1=0.9413  P1=0.896 R1=0.899  (70s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1145/1560] XGB       repeat 1 fold 0  macro-F1=0.9543  P1=0.969 R1=0.875  (30s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[1146/1560] XGB       repeat 1 fold 0  macro-F1=0.9543  P1=0.969 R1=0.875  (96s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[1147/1560] XGB       repeat 1 fold 0  macro-F1=0.9525  P1=0.966 R1=0.872  (31s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[1148/1560] XGB       repeat 1 fold 0  macro-F1=0.9557  P1=0.960 R1=0.887  (99s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[1149/1560] XGB       repeat 1 fold 0  macro-F1=0.9509  P1=0.957 R1=0.875  (32s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[1150/1560] XGB       repeat 1 fold 0  macro-F1=0.9508  P1=0.960 R1=0.872  (101s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[1151/1560] XGB       repeat 1 fold 0  macro-F1=0.9549  P1=0.954 R1=0.890  (33s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[1152/1560] XGB       repeat 1 fold 0  macro-F1=0.9524  P1=0.969 R1=0.869  (103s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[1153/1560] XGB       repeat 1 fold 0  macro-F1=0.9469  P1=0.918 R1=0.896  (32s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1154/1560] XGB       repeat 1 fold 0  macro-F1=0.9536  P1=0.963 R1=0.878  (102s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1155/1560] XGB       repeat 1 fold 0  macro-F1=0.9457  P1=0.905 R1=0.905  (32s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[1156/1560] XGB       repeat 1 fold 0  macro-F1=0.9483  P1=0.972 R1=0.853  (101s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[1157/1560] XGB       repeat 1 fold 0  macro-F1=0.9456  P1=0.908 R1=0.902  (31s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[1158/1560] XGB       repeat 1 fold 0  macro-F1=0.9501  P1=0.976 R1=0.856  (99s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[1159/1560] XGB       repeat 1 fold 0  macro-F1=0.9431  P1=0.885 R1=0.917  (29s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[1160/1560] XGB       repeat 1 fold 0  macro-F1=0.9458  P1=0.982 R1=0.838  (95s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[1161/1560] XGB       repeat 1 fold 0  macro-F1=0.9588  P1=0.955 R1=0.902  (25s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1162/1560] XGB       repeat 1 fold 0  macro-F1=0.9515  P1=0.966 R1=0.869  (76s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1163/1560] XGB       repeat 1 fold 0  macro-F1=0.9510  P1=0.933 R1=0.896  (25s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[1164/1560] XGB       repeat 1 fold 0  macro-F1=0.9446  P1=0.965 R1=0.847  (77s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[1165/1560] XGB       repeat 1 fold 0  macro-F1=0.9557  P1=0.937 R1=0.908  (26s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[1166/1560] XGB       repeat 1 fold 0  macro-F1=0.9461  P1=0.975 R1=0.844  (78s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[1167/1560] XGB       repeat 1 fold 0  macro-F1=0.9448  P1=0.905 R1=0.902  (25s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[1168/1560] XGB       repeat 1 fold 0  macro-F1=0.9490  P1=0.956 R1=0.869  (77s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[1169/1560] XGB       repeat 1 fold 0  macro-F1=0.9423  P1=0.882 R1=0.917  (25s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[1170/1560] XGB       repeat 1 fold 0  macro-F1=0.9466  P1=0.965 R1=0.853  (76s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[1171/1560] XGB       repeat 1 fold 0  macro-F1=0.9415  P1=0.866 R1=0.933  (25s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[1172/1560] XGB       repeat 1 fold 0  macro-F1=0.9480  P1=0.956 R1=0.865  (75s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[1173/1560] XGB       repeat 1 fold 0  macro-F1=0.9313  P1=0.839 R1=0.927  (24s)  [ratio 0.5, orig^1.5, C=0, rho=9.11]

[1174/1560] XGB       repeat 1 fold 0  macro-F1=0.9533  P1=0.969 R1=0.872  (74s)  [ratio 0.5, orig^1.5, C=1, rho=9.11]

[1175/1560] XGB       repeat 1 fold 0  macro-F1=0.9052  P1=0.752 R1=0.945  (24s)  [ratio 0.5, orig^2.0, C=0, rho=23.99]

[1176/1560] XGB       repeat 1 fold 0  macro-F1=0.9469  P1=0.959 R1=0.859  (71s)  [ratio 0.5, orig^2.0, C=1, rho=23.99]

[1177/1560] XGB       repeat 1 fold 0  macro-F1=0.9548  P1=0.934 R1=0.908  (25s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1178/1560] XGB       repeat 1 fold 0  macro-F1=0.9483  P1=0.972 R1=0.853  (76s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1179/1560] XGB       repeat 1 fold 0  macro-F1=0.9474  P1=0.911 R1=0.905  (29s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1180/1560] XGB       repeat 1 fold 0  macro-F1=0.9447  P1=0.962 R1=0.850  (88s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1181/1560] XGB       repeat 1 fold 0  macro-F1=0.9476  P1=0.906 R1=0.911  (30s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[1182/1560] XGB       repeat 1 fold 0  macro-F1=0.9485  P1=0.966 R1=0.859  (89s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[1183/1560] XGB       repeat 1 fold 0  macro-F1=0.9436  P1=0.892 R1=0.911  (29s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[1184/1560] XGB       repeat 1 fold 0  macro-F1=0.9474  P1=0.947 R1=0.872  (87s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[1185/1560] XGB       repeat 1 fold 0  macro-F1=0.9441  P1=0.885 R1=0.920  (29s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[1186/1560] XGB       repeat 1 fold 0  macro-F1=0.9431  P1=0.975 R1=0.835  (86s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[1187/1560] XGB       repeat 1 fold 0  macro-F1=0.9288  P1=0.834 R1=0.924  (29s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[1188/1560] XGB       repeat 1 fold 0  macro-F1=0.9473  P1=0.950 R1=0.869  (84s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[1189/1560] XGB       repeat 1 fold 0  macro-F1=0.9260  P1=0.814 R1=0.939  (29s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[1190/1560] XGB       repeat 1 fold 0  macro-F1=0.9560  P1=0.951 R1=0.896  (75s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[1191/1560] XGB       repeat 1 fold 0  macro-F1=0.9199  P1=0.792 R1=0.945  (29s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[1192/1560] XGB       repeat 1 fold 0  macro-F1=0.9491  P1=0.953 R1=0.872  (64s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[1193/1560] XGB       repeat 1 fold 0  macro-F1=0.8624  P1=0.641 R1=0.957  (28s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[1194/1560] XGB       repeat 1 fold 0  macro-F1=0.9525  P1=0.966 R1=0.872  (48s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[1195/1560] XGB       repeat 1 fold 0  macro-F1=0.9474  P1=0.911 R1=0.905  (26s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1196/1560] XGB       repeat 1 fold 0  macro-F1=0.9447  P1=0.962 R1=0.850  (41s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1197/1560] XGB       repeat 1 fold 1  macro-F1=0.9512  P1=0.947 R1=0.883  (33s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[1198/1560] XGB       repeat 1 fold 1  macro-F1=0.9513  P1=0.944 R1=0.887  (108s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[1199/1560] XGB       repeat 1 fold 1  macro-F1=0.9481  P1=0.929 R1=0.890  (33s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[1200/1560] XGB       repeat 1 fold 1  macro-F1=0.9481  P1=0.929 R1=0.890  (109s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[1201/1560] XGB       repeat 1 fold 1  macro-F1=0.9509  P1=0.933 R1=0.896  (33s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[1202/1560] XGB       repeat 1 fold 1  macro-F1=0.9508  P1=0.936 R1=0.893  (109s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[1203/1560] XGB       repeat 1 fold 1  macro-F1=0.9529  P1=0.931 R1=0.905  (33s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[1204/1560] XGB       repeat 1 fold 1  macro-F1=0.9428  P1=0.873 R1=0.929  (110s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[1205/1560] XGB       repeat 1 fold 1  macro-F1=0.9504  P1=0.904 R1=0.923  (32s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1206/1560] XGB       repeat 1 fold 1  macro-F1=0.9490  P1=0.932 R1=0.890  (110s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1207/1560] XGB       repeat 1 fold 1  macro-F1=0.9459  P1=0.883 R1=0.929  (32s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[1208/1560] XGB       repeat 1 fold 1  macro-F1=0.9460  P1=0.898 R1=0.914  (109s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[1209/1560] XGB       repeat 1 fold 1  macro-F1=0.9401  P1=0.870 R1=0.923  (32s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[1210/1560] XGB       repeat 1 fold 1  macro-F1=0.9326  P1=0.844 R1=0.926  (110s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[1211/1560] XGB       repeat 1 fold 1  macro-F1=0.9357  P1=0.841 R1=0.942  (31s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[1212/1560] XGB       repeat 1 fold 1  macro-F1=0.9451  P1=0.897 R1=0.911  (110s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[1213/1560] XGB       repeat 1 fold 1  macro-F1=0.9555  P1=0.915 R1=0.929  (29s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1214/1560] XGB       repeat 1 fold 1  macro-F1=0.9580  P1=0.946 R1=0.908  (89s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1215/1560] XGB       repeat 1 fold 1  macro-F1=0.9507  P1=0.899 R1=0.929  (29s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[1216/1560] XGB       repeat 1 fold 1  macro-F1=0.9577  P1=0.954 R1=0.899  (89s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[1217/1560] XGB       repeat 1 fold 1  macro-F1=0.9501  P1=0.892 R1=0.936  (29s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[1218/1560] XGB       repeat 1 fold 1  macro-F1=0.9537  P1=0.915 R1=0.923  (91s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[1219/1560] XGB       repeat 1 fold 1  macro-F1=0.9465  P1=0.875 R1=0.942  (29s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[1220/1560] XGB       repeat 1 fold 1  macro-F1=0.9544  P1=0.920 R1=0.920  (90s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[1221/1560] XGB       repeat 1 fold 1  macro-F1=0.9297  P1=0.823 R1=0.942  (28s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[1222/1560] XGB       repeat 1 fold 1  macro-F1=0.9480  P1=0.896 R1=0.923  (90s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[1223/1560] XGB       repeat 1 fold 1  macro-F1=0.9300  P1=0.820 R1=0.948  (28s)  [ratio 0.5, orig^1.25, C=0, rho=5.60]

[1224/1560] XGB       repeat 1 fold 1  macro-F1=0.9561  P1=0.923 R1=0.923  (89s)  [ratio 0.5, orig^1.25, C=1, rho=5.60]

[1225/1560] XGB       repeat 1 fold 1  macro-F1=0.9146  P1=0.772 R1=0.954  (28s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[1226/1560] XGB       repeat 1 fold 1  macro-F1=0.9526  P1=0.917 R1=0.917  (87s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[1227/1560] XGB       repeat 1 fold 1  macro-F1=0.8762  P1=0.672 R1=0.960  (27s)  [ratio 0.5, orig^2.0, C=0, rho=23.85]

[1228/1560] XGB       repeat 1 fold 1  macro-F1=0.9525  P1=0.920 R1=0.914  (83s)  [ratio 0.5, orig^2.0, C=1, rho=23.85]

[1229/1560] XGB       repeat 1 fold 1  macro-F1=0.9501  P1=0.892 R1=0.936  (29s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1230/1560] XGB       repeat 1 fold 1  macro-F1=0.9578  P1=0.929 R1=0.923  (90s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1231/1560] XGB       repeat 1 fold 1  macro-F1=0.9463  P1=0.877 R1=0.939  (35s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1232/1560] XGB       repeat 1 fold 1  macro-F1=0.9454  P1=0.893 R1=0.917  (106s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1233/1560] XGB       repeat 1 fold 1  macro-F1=0.9449  P1=0.870 R1=0.942  (35s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[1234/1560] XGB       repeat 1 fold 1  macro-F1=0.9567  P1=0.931 R1=0.917  (105s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[1235/1560] XGB       repeat 1 fold 1  macro-F1=0.9372  P1=0.846 R1=0.942  (34s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[1236/1560] XGB       repeat 1 fold 1  macro-F1=0.9468  P1=0.900 R1=0.914  (105s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[1237/1560] XGB       repeat 1 fold 1  macro-F1=0.9327  P1=0.832 R1=0.942  (34s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[1238/1560] XGB       repeat 1 fold 1  macro-F1=0.9510  P1=0.912 R1=0.917  (103s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[1239/1560] XGB       repeat 1 fold 1  macro-F1=0.9191  P1=0.788 R1=0.948  (34s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[1240/1560] XGB       repeat 1 fold 1  macro-F1=0.9560  P1=0.926 R1=0.920  (99s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[1241/1560] XGB       repeat 1 fold 1  macro-F1=0.9063  P1=0.749 R1=0.954  (33s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[1242/1560] XGB       repeat 1 fold 1  macro-F1=0.9512  P1=0.927 R1=0.902  (87s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[1243/1560] XGB       repeat 1 fold 1  macro-F1=0.8873  P1=0.700 R1=0.957  (32s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[1244/1560] XGB       repeat 1 fold 1  macro-F1=0.9532  P1=0.925 R1=0.911  (71s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[1245/1560] XGB       repeat 1 fold 1  macro-F1=0.8395  P1=0.592 R1=0.960  (31s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[1246/1560] XGB       repeat 1 fold 1  macro-F1=0.9492  P1=0.909 R1=0.914  (58s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[1247/1560] XGB       repeat 1 fold 1  macro-F1=0.9463  P1=0.877 R1=0.939  (31s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1248/1560] XGB       repeat 1 fold 1  macro-F1=0.9454  P1=0.893 R1=0.917  (48s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1249/1560] XGB       repeat 2 fold 0  macro-F1=0.9495  P1=0.944 R1=0.881  (31s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[1250/1560] XGB       repeat 2 fold 0  macro-F1=0.9513  P1=0.928 R1=0.902  (99s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[1251/1560] XGB       repeat 2 fold 0  macro-F1=0.9506  P1=0.942 R1=0.887  (33s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[1252/1560] XGB       repeat 2 fold 0  macro-F1=0.9499  P1=0.936 R1=0.890  (101s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[1253/1560] XGB       repeat 2 fold 0  macro-F1=0.9491  P1=0.933 R1=0.890  (33s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[1254/1560] XGB       repeat 2 fold 0  macro-F1=0.9522  P1=0.928 R1=0.905  (104s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[1255/1560] XGB       repeat 2 fold 0  macro-F1=0.9508  P1=0.939 R1=0.890  (33s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[1256/1560] XGB       repeat 2 fold 0  macro-F1=0.9457  P1=0.905 R1=0.905  (104s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[1257/1560] XGB       repeat 2 fold 0  macro-F1=0.9502  P1=0.930 R1=0.896  (32s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1258/1560] XGB       repeat 2 fold 0  macro-F1=0.9466  P1=0.944 R1=0.872  (103s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1259/1560] XGB       repeat 2 fold 0  macro-F1=0.9487  P1=0.922 R1=0.899  (32s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[1260/1560] XGB       repeat 2 fold 0  macro-F1=0.9466  P1=0.944 R1=0.872  (103s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[1261/1560] XGB       repeat 2 fold 0  macro-F1=0.9490  P1=0.916 R1=0.905  (31s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[1262/1560] XGB       repeat 2 fold 0  macro-F1=0.9520  P1=0.933 R1=0.899  (101s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[1263/1560] XGB       repeat 2 fold 0  macro-F1=0.9384  P1=0.870 R1=0.917  (30s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[1264/1560] XGB       repeat 2 fold 0  macro-F1=0.9502  P1=0.930 R1=0.896  (95s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[1265/1560] XGB       repeat 2 fold 0  macro-F1=0.9522  P1=0.928 R1=0.905  (22s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1266/1560] XGB       repeat 2 fold 0  macro-F1=0.9470  P1=0.956 R1=0.862  (68s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1267/1560] XGB       repeat 2 fold 0  macro-F1=0.9474  P1=0.911 R1=0.905  (23s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[1268/1560] XGB       repeat 2 fold 0  macro-F1=0.9399  P1=0.958 R1=0.838  (69s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[1269/1560] XGB       repeat 2 fold 0  macro-F1=0.9465  P1=0.908 R1=0.905  (23s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[1270/1560] XGB       repeat 2 fold 0  macro-F1=0.9526  P1=0.942 R1=0.893  (69s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[1271/1560] XGB       repeat 2 fold 0  macro-F1=0.9403  P1=0.884 R1=0.908  (22s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[1272/1560] XGB       repeat 2 fold 0  macro-F1=0.9529  P1=0.957 R1=0.881  (69s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[1273/1560] XGB       repeat 2 fold 0  macro-F1=0.9400  P1=0.875 R1=0.917  (22s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[1274/1560] XGB       repeat 2 fold 0  macro-F1=0.9508  P1=0.939 R1=0.890  (66s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[1275/1560] XGB       repeat 2 fold 0  macro-F1=0.9354  P1=0.847 R1=0.933  (20s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[1276/1560] XGB       repeat 2 fold 0  macro-F1=0.9482  P1=0.914 R1=0.905  (63s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[1277/1560] XGB       repeat 2 fold 0  macro-F1=0.9242  P1=0.813 R1=0.933  (20s)  [ratio 0.5, orig^1.5, C=0, rho=9.11]

[1278/1560] XGB       repeat 2 fold 0  macro-F1=0.9491  P1=0.933 R1=0.890  (60s)  [ratio 0.5, orig^1.5, C=1, rho=9.11]

[1279/1560] XGB       repeat 2 fold 0  macro-F1=0.8864  P1=0.700 R1=0.951  (18s)  [ratio 0.5, orig^2.0, C=0, rho=23.99]

[1280/1560] XGB       repeat 2 fold 0  macro-F1=0.9395  P1=0.911 R1=0.878  (53s)  [ratio 0.5, orig^2.0, C=1, rho=23.99]

[1281/1560] XGB       repeat 2 fold 0  macro-F1=0.9482  P1=0.914 R1=0.905  (22s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1282/1560] XGB       repeat 2 fold 0  macro-F1=0.9480  P1=0.916 R1=0.902  (69s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1283/1560] XGB       repeat 2 fold 0  macro-F1=0.9464  P1=0.893 R1=0.920  (26s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1284/1560] XGB       repeat 2 fold 0  macro-F1=0.9473  P1=0.929 R1=0.887  (79s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1285/1560] XGB       repeat 2 fold 0  macro-F1=0.9456  P1=0.891 R1=0.920  (26s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[1286/1560] XGB       repeat 2 fold 0  macro-F1=0.9479  P1=0.919 R1=0.899  (79s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[1287/1560] XGB       repeat 2 fold 0  macro-F1=0.9380  P1=0.863 R1=0.924  (26s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[1288/1560] XGB       repeat 2 fold 0  macro-F1=0.9463  P1=0.913 R1=0.899  (78s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[1289/1560] XGB       repeat 2 fold 0  macro-F1=0.9383  P1=0.859 R1=0.930  (24s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[1290/1560] XGB       repeat 2 fold 0  macro-F1=0.9520  P1=0.954 R1=0.881  (74s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[1291/1560] XGB       repeat 2 fold 0  macro-F1=0.9387  P1=0.853 R1=0.939  (24s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[1292/1560] XGB       repeat 2 fold 0  macro-F1=0.9499  P1=0.936 R1=0.890  (69s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[1293/1560] XGB       repeat 2 fold 0  macro-F1=0.9294  P1=0.829 R1=0.933  (22s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[1294/1560] XGB       repeat 2 fold 0  macro-F1=0.9486  P1=0.924 R1=0.896  (62s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[1295/1560] XGB       repeat 2 fold 0  macro-F1=0.9144  P1=0.775 R1=0.948  (21s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[1296/1560] XGB       repeat 2 fold 0  macro-F1=0.9455  P1=0.910 R1=0.899  (48s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[1297/1560] XGB       repeat 2 fold 0  macro-F1=0.8627  P1=0.643 R1=0.954  (20s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[1298/1560] XGB       repeat 2 fold 0  macro-F1=0.9386  P1=0.911 R1=0.875  (43s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[1299/1560] XGB       repeat 2 fold 0  macro-F1=0.9464  P1=0.893 R1=0.920  (23s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1300/1560] XGB       repeat 2 fold 0  macro-F1=0.9473  P1=0.929 R1=0.887  (37s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1301/1560] XGB       repeat 2 fold 1  macro-F1=0.9533  P1=0.966 R1=0.874  (25s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[1302/1560] XGB       repeat 2 fold 1  macro-F1=0.9519  P1=0.953 R1=0.880  (76s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[1303/1560] XGB       repeat 2 fold 1  macro-F1=0.9553  P1=0.966 R1=0.880  (25s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[1304/1560] XGB       repeat 2 fold 1  macro-F1=0.9533  P1=0.966 R1=0.874  (77s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[1305/1560] XGB       repeat 2 fold 1  macro-F1=0.9551  P1=0.948 R1=0.896  (25s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[1306/1560] XGB       repeat 2 fold 1  macro-F1=0.9452  P1=0.912 R1=0.896  (80s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[1307/1560] XGB       repeat 2 fold 1  macro-F1=0.9460  P1=0.915 R1=0.896  (26s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[1308/1560] XGB       repeat 2 fold 1  macro-F1=0.9554  P1=0.963 R1=0.883  (80s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[1309/1560] XGB       repeat 2 fold 1  macro-F1=0.9453  P1=0.910 R1=0.899  (25s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1310/1560] XGB       repeat 2 fold 1  macro-F1=0.9466  P1=0.921 R1=0.893  (81s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1311/1560] XGB       repeat 2 fold 1  macro-F1=0.9441  P1=0.897 R1=0.908  (25s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[1312/1560] XGB       repeat 2 fold 1  macro-F1=0.9444  P1=0.926 R1=0.880  (80s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[1313/1560] XGB       repeat 2 fold 1  macro-F1=0.9398  P1=0.874 R1=0.917  (25s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[1314/1560] XGB       repeat 2 fold 1  macro-F1=0.9509  P1=0.933 R1=0.896  (79s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[1315/1560] XGB       repeat 2 fold 1  macro-F1=0.9303  P1=0.837 R1=0.926  (24s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[1316/1560] XGB       repeat 2 fold 1  macro-F1=0.9465  P1=0.924 R1=0.890  (77s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[1317/1560] XGB       repeat 2 fold 1  macro-F1=0.9466  P1=0.921 R1=0.893  (57s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1318/1560] XGB       repeat 2 fold 1  macro-F1=0.9487  P1=0.938 R1=0.883  (185s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1319/1560] XGB       repeat 2 fold 1  macro-F1=0.9443  P1=0.910 R1=0.896  (58s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[1320/1560] XGB       repeat 2 fold 1  macro-F1=0.9483  P1=0.969 R1=0.856  (189s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[1321/1560] XGB       repeat 2 fold 1  macro-F1=0.9351  P1=0.872 R1=0.902  (59s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[1322/1560] XGB       repeat 2 fold 1  macro-F1=0.9474  P1=0.965 R1=0.856  (189s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[1323/1560] XGB       repeat 2 fold 1  macro-F1=0.9314  P1=0.858 R1=0.905  (58s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[1324/1560] XGB       repeat 2 fold 1  macro-F1=0.9471  P1=0.972 R1=0.850  (185s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[1325/1560] XGB       repeat 2 fold 1  macro-F1=0.9257  P1=0.834 R1=0.911  (56s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[1326/1560] XGB       repeat 2 fold 1  macro-F1=0.9475  P1=0.962 R1=0.859  (177s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[1327/1560] XGB       repeat 2 fold 1  macro-F1=0.9184  P1=0.810 R1=0.914  (54s)  [ratio 0.5, orig^1.25, C=0, rho=5.60]

[1328/1560] XGB       repeat 2 fold 1  macro-F1=0.9485  P1=0.962 R1=0.862  (167s)  [ratio 0.5, orig^1.25, C=1, rho=5.60]

[1329/1560] XGB       repeat 2 fold 1  macro-F1=0.9136  P1=0.793 R1=0.917  (50s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[1330/1560] XGB       repeat 2 fold 1  macro-F1=0.9485  P1=0.962 R1=0.862  (155s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[1331/1560] XGB       repeat 2 fold 1  macro-F1=0.8810  P1=0.691 R1=0.942  (43s)  [ratio 0.5, orig^2.0, C=0, rho=23.85]

[1332/1560] XGB       repeat 2 fold 1  macro-F1=0.9339  P1=0.889 R1=0.880  (133s)  [ratio 0.5, orig^2.0, C=1, rho=23.85]

[1333/1560] XGB       repeat 2 fold 1  macro-F1=0.9315  P1=0.869 R1=0.893  (59s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1334/1560] XGB       repeat 2 fold 1  macro-F1=0.9338  P1=0.877 R1=0.893  (188s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1335/1560] XGB       repeat 2 fold 1  macro-F1=0.9381  P1=0.885 R1=0.899  (69s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1336/1560] XGB       repeat 2 fold 1  macro-F1=0.9495  P1=0.962 R1=0.865  (217s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1337/1560] XGB       repeat 2 fold 1  macro-F1=0.9266  P1=0.845 R1=0.902  (68s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[1338/1560] XGB       repeat 2 fold 1  macro-F1=0.9481  P1=0.950 R1=0.871  (216s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[1339/1560] XGB       repeat 2 fold 1  macro-F1=0.9231  P1=0.831 R1=0.905  (66s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[1340/1560] XGB       repeat 2 fold 1  macro-F1=0.9453  P1=0.946 R1=0.865  (210s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[1341/1560] XGB       repeat 2 fold 1  macro-F1=0.9177  P1=0.808 R1=0.914  (64s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[1342/1560] XGB       repeat 2 fold 1  macro-F1=0.9467  P1=0.938 R1=0.877  (198s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[1343/1560] XGB       repeat 2 fold 1  macro-F1=0.9143  P1=0.795 R1=0.917  (60s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[1344/1560] XGB       repeat 2 fold 1  macro-F1=0.9435  P1=0.943 R1=0.862  (183s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[1345/1560] XGB       repeat 2 fold 1  macro-F1=0.9094  P1=0.773 R1=0.929  (56s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[1346/1560] XGB       repeat 2 fold 1  macro-F1=0.9442  P1=0.949 R1=0.859  (160s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[1347/1560] XGB       repeat 2 fold 1  macro-F1=0.8950  P1=0.734 R1=0.929  (52s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[1348/1560] XGB       repeat 2 fold 1  macro-F1=0.9317  P1=0.878 R1=0.883  (134s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[1349/1560] XGB       repeat 2 fold 1  macro-F1=0.8453  P1=0.607 R1=0.951  (45s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[1350/1560] XGB       repeat 2 fold 1  macro-F1=0.9366  P1=0.907 R1=0.871  (98s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[1351/1560] XGB       repeat 2 fold 1  macro-F1=0.9381  P1=0.885 R1=0.899  (55s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1352/1560] XGB       repeat 2 fold 1  macro-F1=0.9495  P1=0.962 R1=0.865  (94s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1353/1560] XGB       repeat 3 fold 0  macro-F1=0.9527  P1=0.960 R1=0.878  (22s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[1354/1560] XGB       repeat 3 fold 0  macro-F1=0.9569  P1=0.954 R1=0.896  (67s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[1355/1560] XGB       repeat 3 fold 0  macro-F1=0.9529  P1=0.957 R1=0.881  (23s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[1356/1560] XGB       repeat 3 fold 0  macro-F1=0.9505  P1=0.966 R1=0.865  (70s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[1357/1560] XGB       repeat 3 fold 0  macro-F1=0.9508  P1=0.939 R1=0.890  (23s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[1358/1560] XGB       repeat 3 fold 0  macro-F1=0.9504  P1=0.947 R1=0.881  (73s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[1359/1560] XGB       repeat 3 fold 0  macro-F1=0.9520  P1=0.933 R1=0.899  (24s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[1360/1560] XGB       repeat 3 fold 0  macro-F1=0.9483  P1=0.950 R1=0.872  (74s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[1361/1560] XGB       repeat 3 fold 0  macro-F1=0.9507  P1=0.920 R1=0.908  (23s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1362/1560] XGB       repeat 3 fold 0  macro-F1=0.9515  P1=0.966 R1=0.869  (73s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1363/1560] XGB       repeat 3 fold 0  macro-F1=0.9430  P1=0.887 R1=0.914  (23s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[1364/1560] XGB       repeat 3 fold 0  macro-F1=0.9454  P1=0.969 R1=0.847  (72s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[1365/1560] XGB       repeat 3 fold 0  macro-F1=0.9352  P1=0.849 R1=0.930  (23s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[1366/1560] XGB       repeat 3 fold 0  macro-F1=0.9507  P1=0.963 R1=0.869  (71s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[1367/1560] XGB       repeat 3 fold 0  macro-F1=0.9327  P1=0.834 R1=0.939  (22s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[1368/1560] XGB       repeat 3 fold 0  macro-F1=0.9393  P1=0.968 R1=0.829  (69s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[1369/1560] XGB       repeat 3 fold 0  macro-F1=0.9443  P1=0.897 R1=0.908  (14s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1370/1560] XGB       repeat 3 fold 0  macro-F1=0.9400  P1=0.936 R1=0.856  (44s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1371/1560] XGB       repeat 3 fold 0  macro-F1=0.9480  P1=0.899 R1=0.920  (14s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[1372/1560] XGB       repeat 3 fold 0  macro-F1=0.9409  P1=0.958 R1=0.841  (45s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[1373/1560] XGB       repeat 3 fold 0  macro-F1=0.9414  P1=0.882 R1=0.914  (14s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[1374/1560] XGB       repeat 3 fold 0  macro-F1=0.9468  P1=0.921 R1=0.893  (45s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[1375/1560] XGB       repeat 3 fold 0  macro-F1=0.9401  P1=0.872 R1=0.920  (14s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[1376/1560] XGB       repeat 3 fold 0  macro-F1=0.9379  P1=0.922 R1=0.862  (45s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[1377/1560] XGB       repeat 3 fold 0  macro-F1=0.9292  P1=0.831 R1=0.930  (14s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[1378/1560] XGB       repeat 3 fold 0  macro-F1=0.9421  P1=0.917 R1=0.881  (44s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[1379/1560] XGB       repeat 3 fold 0  macro-F1=0.9247  P1=0.808 R1=0.942  (14s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[1380/1560] XGB       repeat 3 fold 0  macro-F1=0.9389  P1=0.922 R1=0.865  (43s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[1381/1560] XGB       repeat 3 fold 0  macro-F1=0.9211  P1=0.798 R1=0.942  (14s)  [ratio 0.5, orig^1.5, C=0, rho=9.11]

[1382/1560] XGB       repeat 3 fold 0  macro-F1=0.9351  P1=0.951 R1=0.829  (42s)  [ratio 0.5, orig^1.5, C=1, rho=9.11]

[1383/1560] XGB       repeat 3 fold 0  macro-F1=0.8893  P1=0.702 R1=0.963  (13s)  [ratio 0.5, orig^2.0, C=0, rho=23.99]

[1384/1560] XGB       repeat 3 fold 0  macro-F1=0.9376  P1=0.911 R1=0.872  (39s)  [ratio 0.5, orig^2.0, C=1, rho=23.99]

[1385/1560] XGB       repeat 3 fold 0  macro-F1=0.9454  P1=0.895 R1=0.914  (14s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1386/1560] XGB       repeat 3 fold 0  macro-F1=0.9352  P1=0.967 R1=0.817  (44s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1387/1560] XGB       repeat 3 fold 0  macro-F1=0.9409  P1=0.875 R1=0.920  (16s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1388/1560] XGB       repeat 3 fold 0  macro-F1=0.9390  P1=0.955 R1=0.838  (50s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1389/1560] XGB       repeat 3 fold 0  macro-F1=0.9372  P1=0.860 R1=0.924  (16s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[1390/1560] XGB       repeat 3 fold 0  macro-F1=0.9353  P1=0.948 R1=0.832  (49s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[1391/1560] XGB       repeat 3 fold 0  macro-F1=0.9371  P1=0.850 R1=0.936  (16s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[1392/1560] XGB       repeat 3 fold 0  macro-F1=0.9524  P1=0.925 R1=0.908  (50s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[1393/1560] XGB       repeat 3 fold 0  macro-F1=0.9327  P1=0.834 R1=0.939  (16s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[1394/1560] XGB       repeat 3 fold 0  macro-F1=0.9384  P1=0.948 R1=0.841  (48s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[1395/1560] XGB       repeat 3 fold 0  macro-F1=0.9197  P1=0.794 R1=0.942  (16s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[1396/1560] XGB       repeat 3 fold 0  macro-F1=0.9426  P1=0.926 R1=0.875  (47s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[1397/1560] XGB       repeat 3 fold 0  macro-F1=0.9099  P1=0.759 R1=0.954  (15s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[1398/1560] XGB       repeat 3 fold 0  macro-F1=0.9454  P1=0.929 R1=0.881  (42s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[1399/1560] XGB       repeat 3 fold 0  macro-F1=0.8975  P1=0.728 R1=0.951  (15s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[1400/1560] XGB       repeat 3 fold 0  macro-F1=0.9296  P1=0.957 R1=0.807  (34s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[1401/1560] XGB       repeat 3 fold 0  macro-F1=0.8479  P1=0.608 R1=0.963  (14s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[1402/1560] XGB       repeat 3 fold 0  macro-F1=0.9263  P1=0.899 R1=0.844  (28s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[1403/1560] XGB       repeat 3 fold 0  macro-F1=0.9409  P1=0.875 R1=0.920  (16s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1404/1560] XGB       repeat 3 fold 0  macro-F1=0.9390  P1=0.955 R1=0.838  (24s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1405/1560] XGB       repeat 3 fold 1  macro-F1=0.9353  P1=0.912 R1=0.862  (13s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[1406/1560] XGB       repeat 3 fold 1  macro-F1=0.9310  P1=0.887 R1=0.871  (40s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[1407/1560] XGB       repeat 3 fold 1  macro-F1=0.9395  P1=0.908 R1=0.880  (14s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[1408/1560] XGB       repeat 3 fold 1  macro-F1=0.9305  P1=0.868 R1=0.890  (40s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[1409/1560] XGB       repeat 3 fold 1  macro-F1=0.9364  P1=0.910 R1=0.868  (14s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[1410/1560] XGB       repeat 3 fold 1  macro-F1=0.9379  P1=0.936 R1=0.850  (42s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[1411/1560] XGB       repeat 3 fold 1  macro-F1=0.9361  P1=0.899 R1=0.877  (14s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[1412/1560] XGB       repeat 3 fold 1  macro-F1=0.9360  P1=0.887 R1=0.890  (43s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[1413/1560] XGB       repeat 3 fold 1  macro-F1=0.9294  P1=0.882 R1=0.871  (14s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1414/1560] XGB       repeat 3 fold 1  macro-F1=0.9323  P1=0.883 R1=0.880  (42s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1415/1560] XGB       repeat 3 fold 1  macro-F1=0.9236  P1=0.868 R1=0.865  (14s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[1416/1560] XGB       repeat 3 fold 1  macro-F1=0.9291  P1=0.900 R1=0.853  (41s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[1417/1560] XGB       repeat 3 fold 1  macro-F1=0.9257  P1=0.855 R1=0.887  (13s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[1418/1560] XGB       repeat 3 fold 1  macro-F1=0.9298  P1=0.877 R1=0.877  (39s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[1419/1560] XGB       repeat 3 fold 1  macro-F1=0.9259  P1=0.842 R1=0.902  (12s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[1420/1560] XGB       repeat 3 fold 1  macro-F1=0.9378  P1=0.890 R1=0.893  (37s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[1421/1560] XGB       repeat 3 fold 1  macro-F1=0.9402  P1=0.898 R1=0.893  (34s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1422/1560] XGB       repeat 3 fold 1  macro-F1=0.9424  P1=0.909 R1=0.890  (108s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1423/1560] XGB       repeat 3 fold 1  macro-F1=0.9383  P1=0.883 R1=0.902  (34s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[1424/1560] XGB       repeat 3 fold 1  macro-F1=0.9359  P1=0.875 R1=0.902  (108s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[1425/1560] XGB       repeat 3 fold 1  macro-F1=0.9330  P1=0.863 R1=0.905  (34s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[1426/1560] XGB       repeat 3 fold 1  macro-F1=0.9375  P1=0.880 R1=0.902  (108s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[1427/1560] XGB       repeat 3 fold 1  macro-F1=0.9310  P1=0.851 R1=0.911  (34s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[1428/1560] XGB       repeat 3 fold 1  macro-F1=0.9365  P1=0.880 R1=0.899  (107s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[1429/1560] XGB       repeat 3 fold 1  macro-F1=0.9304  P1=0.847 R1=0.914  (33s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[1430/1560] XGB       repeat 3 fold 1  macro-F1=0.9378  P1=0.890 R1=0.893  (107s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[1431/1560] XGB       repeat 3 fold 1  macro-F1=0.9270  P1=0.831 R1=0.920  (33s)  [ratio 0.5, orig^1.25, C=0, rho=5.60]

[1432/1560] XGB       repeat 3 fold 1  macro-F1=0.9342  P1=0.872 R1=0.899  (105s)  [ratio 0.5, orig^1.25, C=1, rho=5.60]

[1433/1560] XGB       repeat 3 fold 1  macro-F1=0.9174  P1=0.802 R1=0.920  (32s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[1434/1560] XGB       repeat 3 fold 1  macro-F1=0.9357  P1=0.892 R1=0.883  (102s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[1435/1560] XGB       repeat 3 fold 1  macro-F1=0.8834  P1=0.702 R1=0.933  (30s)  [ratio 0.5, orig^2.0, C=0, rho=23.85]

[1436/1560] XGB       repeat 3 fold 1  macro-F1=0.9269  P1=0.876 R1=0.868  (95s)  [ratio 0.5, orig^2.0, C=1, rho=23.85]

[1437/1560] XGB       repeat 3 fold 1  macro-F1=0.9350  P1=0.875 R1=0.899  (33s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1438/1560] XGB       repeat 3 fold 1  macro-F1=0.9342  P1=0.872 R1=0.899  (107s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1439/1560] XGB       repeat 3 fold 1  macro-F1=0.9345  P1=0.868 R1=0.905  (40s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1440/1560] XGB       repeat 3 fold 1  macro-F1=0.9419  P1=0.901 R1=0.896  (123s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1441/1560] XGB       repeat 3 fold 1  macro-F1=0.9308  P1=0.853 R1=0.908  (40s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[1442/1560] XGB       repeat 3 fold 1  macro-F1=0.9371  P1=0.885 R1=0.896  (123s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[1443/1560] XGB       repeat 3 fold 1  macro-F1=0.9295  P1=0.846 R1=0.911  (39s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[1444/1560] XGB       repeat 3 fold 1  macro-F1=0.9421  P1=0.899 R1=0.899  (122s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[1445/1560] XGB       repeat 3 fold 1  macro-F1=0.9274  P1=0.837 R1=0.914  (39s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[1446/1560] XGB       repeat 3 fold 1  macro-F1=0.9348  P1=0.877 R1=0.896  (120s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[1447/1560] XGB       repeat 3 fold 1  macro-F1=0.9233  P1=0.820 R1=0.920  (38s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[1448/1560] XGB       repeat 3 fold 1  macro-F1=0.9346  P1=0.879 R1=0.893  (114s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[1449/1560] XGB       repeat 3 fold 1  macro-F1=0.9151  P1=0.789 R1=0.929  (37s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[1450/1560] XGB       repeat 3 fold 1  macro-F1=0.9387  P1=0.905 R1=0.880  (99s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[1451/1560] XGB       repeat 3 fold 1  macro-F1=0.9054  P1=0.754 R1=0.942  (37s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[1452/1560] XGB       repeat 3 fold 1  macro-F1=0.9373  P1=0.883 R1=0.899  (81s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[1453/1560] XGB       repeat 3 fold 1  macro-F1=0.8685  P1=0.659 R1=0.948  (34s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[1454/1560] XGB       repeat 3 fold 1  macro-F1=0.9302  P1=0.885 R1=0.871  (67s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[1455/1560] XGB       repeat 3 fold 1  macro-F1=0.9345  P1=0.868 R1=0.905  (35s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1456/1560] XGB       repeat 3 fold 1  macro-F1=0.9419  P1=0.901 R1=0.896  (60s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1457/1560] XGB       repeat 4 fold 0  macro-F1=0.9538  P1=0.957 R1=0.884  (30s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[1458/1560] XGB       repeat 4 fold 0  macro-F1=0.9544  P1=0.966 R1=0.878  (95s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[1459/1560] XGB       repeat 4 fold 0  macro-F1=0.9492  P1=0.930 R1=0.893  (30s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[1460/1560] XGB       repeat 4 fold 0  macro-F1=0.9484  P1=0.927 R1=0.893  (97s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[1461/1560] XGB       repeat 4 fold 0  macro-F1=0.9510  P1=0.933 R1=0.896  (31s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[1462/1560] XGB       repeat 4 fold 0  macro-F1=0.9499  P1=0.917 R1=0.908  (99s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[1463/1560] XGB       repeat 4 fold 0  macro-F1=0.9480  P1=0.916 R1=0.902  (32s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[1464/1560] XGB       repeat 4 fold 0  macro-F1=0.9497  P1=0.922 R1=0.902  (100s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[1465/1560] XGB       repeat 4 fold 0  macro-F1=0.9491  P1=0.914 R1=0.908  (31s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1466/1560] XGB       repeat 4 fold 0  macro-F1=0.9483  P1=0.911 R1=0.908  (99s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1467/1560] XGB       repeat 4 fold 0  macro-F1=0.9419  P1=0.889 R1=0.908  (31s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[1468/1560] XGB       repeat 4 fold 0  macro-F1=0.9482  P1=0.914 R1=0.905  (99s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[1469/1560] XGB       repeat 4 fold 0  macro-F1=0.9454  P1=0.895 R1=0.914  (31s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[1470/1560] XGB       repeat 4 fold 0  macro-F1=0.9506  P1=0.942 R1=0.887  (96s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[1471/1560] XGB       repeat 4 fold 0  macro-F1=0.9308  P1=0.845 R1=0.917  (28s)  [ratio 0.0, orig^2.0, C=0, rho=6.93]

[1472/1560] XGB       repeat 4 fold 0  macro-F1=0.9513  P1=0.928 R1=0.902  (90s)  [ratio 0.0, orig^2.0, C=1, rho=6.93]

[1473/1560] XGB       repeat 4 fold 0  macro-F1=0.9474  P1=0.893 R1=0.924  (31s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1474/1560] XGB       repeat 4 fold 0  macro-F1=0.9530  P1=0.954 R1=0.884  (94s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1475/1560] XGB       repeat 4 fold 0  macro-F1=0.9449  P1=0.872 R1=0.939  (31s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[1476/1560] XGB       repeat 4 fold 0  macro-F1=0.9539  P1=0.934 R1=0.905  (94s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[1477/1560] XGB       repeat 4 fold 0  macro-F1=0.9407  P1=0.864 R1=0.933  (31s)  [ratio 0.5, orig^0.5, C=0, rho=1.32]

[1478/1560] XGB       repeat 4 fold 0  macro-F1=0.9599  P1=0.949 R1=0.911  (94s)  [ratio 0.5, orig^0.5, C=1, rho=1.32]

[1479/1560] XGB       repeat 4 fold 0  macro-F1=0.9409  P1=0.862 R1=0.936  (31s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[1480/1560] XGB       repeat 4 fold 0  macro-F1=0.9498  P1=0.919 R1=0.905  (94s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[1481/1560] XGB       repeat 4 fold 0  macro-F1=0.9343  P1=0.837 R1=0.942  (30s)  [ratio 0.5, orig^1.0, C=0, rho=3.46]

[1482/1560] XGB       repeat 4 fold 0  macro-F1=0.9488  P1=0.901 R1=0.920  (93s)  [ratio 0.5, orig^1.0, C=1, rho=3.46]

[1483/1560] XGB       repeat 4 fold 0  macro-F1=0.9309  P1=0.822 R1=0.948  (30s)  [ratio 0.5, orig^1.25, C=0, rho=5.62]

[1484/1560] XGB       repeat 4 fold 0  macro-F1=0.9533  P1=0.925 R1=0.911  (91s)  [ratio 0.5, orig^1.25, C=1, rho=5.62]

[1485/1560] XGB       repeat 4 fold 0  macro-F1=0.9245  P1=0.802 R1=0.951  (29s)  [ratio 0.5, orig^1.5, C=0, rho=9.12]

[1486/1560] XGB       repeat 4 fold 0  macro-F1=0.9467  P1=0.905 R1=0.908  (90s)  [ratio 0.5, orig^1.5, C=1, rho=9.12]

[1487/1560] XGB       repeat 4 fold 0  macro-F1=0.9004  P1=0.729 R1=0.963  (28s)  [ratio 0.5, orig^2.0, C=0, rho=24.00]

[1488/1560] XGB       repeat 4 fold 0  macro-F1=0.9456  P1=0.891 R1=0.920  (86s)  [ratio 0.5, orig^2.0, C=1, rho=24.00]

[1489/1560] XGB       repeat 4 fold 0  macro-F1=0.9383  P1=0.859 R1=0.930  (31s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1490/1560] XGB       repeat 4 fold 0  macro-F1=0.9548  P1=0.934 R1=0.908  (92s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1491/1560] XGB       repeat 4 fold 0  macro-F1=0.9380  P1=0.850 R1=0.939  (37s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1492/1560] XGB       repeat 4 fold 0  macro-F1=0.9543  P1=0.926 R1=0.914  (108s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1493/1560] XGB       repeat 4 fold 0  macro-F1=0.9273  P1=0.830 R1=0.924  (37s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[1494/1560] XGB       repeat 4 fold 0  macro-F1=0.9552  P1=0.948 R1=0.896  (108s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[1495/1560] XGB       repeat 4 fold 0  macro-F1=0.9331  P1=0.840 R1=0.933  (38s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[1496/1560] XGB       repeat 4 fold 0  macro-F1=0.9478  P1=0.903 R1=0.914  (107s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[1497/1560] XGB       repeat 4 fold 0  macro-F1=0.9314  P1=0.828 R1=0.942  (35s)  [ratio 1.0, orig^0.75, C=0, rho=4.27]

[1498/1560] XGB       repeat 4 fold 0  macro-F1=0.9483  P1=0.930 R1=0.890  (106s)  [ratio 1.0, orig^0.75, C=1, rho=4.27]

[1499/1560] XGB       repeat 4 fold 0  macro-F1=0.9255  P1=0.811 R1=0.942  (34s)  [ratio 1.0, orig^1.0, C=0, rho=6.93]

[1500/1560] XGB       repeat 4 fold 0  macro-F1=0.9578  P1=0.955 R1=0.899  (100s)  [ratio 1.0, orig^1.0, C=1, rho=6.93]

[1501/1560] XGB       repeat 4 fold 0  macro-F1=0.9157  P1=0.787 R1=0.936  (34s)  [ratio 1.0, orig^1.25, C=0, rho=11.24]

[1502/1560] XGB       repeat 4 fold 0  macro-F1=0.9498  P1=0.919 R1=0.905  (91s)  [ratio 1.0, orig^1.25, C=1, rho=11.24]

[1503/1560] XGB       repeat 4 fold 0  macro-F1=0.9090  P1=0.759 R1=0.951  (33s)  [ratio 1.0, orig^1.5, C=0, rho=18.24]

[1504/1560] XGB       repeat 4 fold 0  macro-F1=0.9443  P1=0.897 R1=0.908  (80s)  [ratio 1.0, orig^1.5, C=1, rho=18.24]

[1505/1560] XGB       repeat 4 fold 0  macro-F1=0.8746  P1=0.665 R1=0.966  (32s)  [ratio 1.0, orig^2.0, C=0, rho=48.02]

[1506/1560] XGB       repeat 4 fold 0  macro-F1=0.9438  P1=0.905 R1=0.899  (60s)  [ratio 1.0, orig^2.0, C=1, rho=48.02]

[1507/1560] XGB       repeat 4 fold 0  macro-F1=0.9380  P1=0.850 R1=0.939  (32s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1508/1560] XGB       repeat 4 fold 0  macro-F1=0.9543  P1=0.926 R1=0.914  (50s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

[1509/1560] XGB       repeat 4 fold 1  macro-F1=0.9314  P1=0.895 R1=0.865  (14s)  [ratio 0.0, orig^0.0, C=0, rho=0.14]

[1510/1560] XGB       repeat 4 fold 1  macro-F1=0.9291  P1=0.887 R1=0.865  (43s)  [ratio 0.0, orig^0.0, C=1, rho=0.14]

[1511/1560] XGB       repeat 4 fold 1  macro-F1=0.9328  P1=0.891 R1=0.874  (15s)  [ratio 0.0, orig^0.25, C=0, rho=0.23]

[1512/1560] XGB       repeat 4 fold 1  macro-F1=0.9317  P1=0.878 R1=0.883  (45s)  [ratio 0.0, orig^0.25, C=1, rho=0.23]

[1513/1560] XGB       repeat 4 fold 1  macro-F1=0.9310  P1=0.887 R1=0.871  (15s)  [ratio 0.0, orig^0.5, C=0, rho=0.38]

[1514/1560] XGB       repeat 4 fold 1  macro-F1=0.9310  P1=0.887 R1=0.871  (47s)  [ratio 0.0, orig^0.5, C=1, rho=0.38]

[1515/1560] XGB       repeat 4 fold 1  macro-F1=0.9306  P1=0.880 R1=0.877  (16s)  [ratio 0.0, orig^0.75, C=0, rho=0.62]

[1516/1560] XGB       repeat 4 fold 1  macro-F1=0.9308  P1=0.878 R1=0.880  (48s)  [ratio 0.0, orig^0.75, C=1, rho=0.62]

[1517/1560] XGB       repeat 4 fold 1  macro-F1=0.9297  P1=0.866 R1=0.890  (15s)  [ratio 0.0, orig^1.0, C=0, rho=1.00]

[1518/1560] XGB       repeat 4 fold 1  macro-F1=0.9291  P1=0.887 R1=0.865  (47s)  [ratio 0.0, orig^1.0, C=1, rho=1.00]

[1519/1560] XGB       repeat 4 fold 1  macro-F1=0.9270  P1=0.851 R1=0.896  (15s)  [ratio 0.0, orig^1.25, C=0, rho=1.62]

[1520/1560] XGB       repeat 4 fold 1  macro-F1=0.9290  P1=0.875 R1=0.877  (46s)  [ratio 0.0, orig^1.25, C=1, rho=1.62]

[1521/1560] XGB       repeat 4 fold 1  macro-F1=0.9204  P1=0.838 R1=0.887  (14s)  [ratio 0.0, orig^1.5, C=0, rho=2.63]

[1522/1560] XGB       repeat 4 fold 1  macro-F1=0.9346  P1=0.907 R1=0.865  (45s)  [ratio 0.0, orig^1.5, C=1, rho=2.63]

[1523/1560] XGB       repeat 4 fold 1  macro-F1=0.9096  P1=0.786 R1=0.911  (13s)  [ratio 0.0, orig^2.0, C=0, rho=6.91]

[1524/1560] XGB       repeat 4 fold 1  macro-F1=0.9330  P1=0.901 R1=0.865  (42s)  [ratio 0.0, orig^2.0, C=1, rho=6.91]

[1525/1560] XGB       repeat 4 fold 1  macro-F1=0.9324  P1=0.869 R1=0.896  (26s)  [ratio 0.5, orig^0.0, C=0, rho=0.50]

[1526/1560] XGB       repeat 4 fold 1  macro-F1=0.9347  P1=0.891 R1=0.880  (80s)  [ratio 0.5, orig^0.0, C=1, rho=0.50]

[1527/1560] XGB       repeat 4 fold 1  macro-F1=0.9343  P1=0.870 R1=0.902  (26s)  [ratio 0.5, orig^0.25, C=0, rho=0.81]

[1528/1560] XGB       repeat 4 fold 1  macro-F1=0.9384  P1=0.895 R1=0.890  (81s)  [ratio 0.5, orig^0.25, C=1, rho=0.81]

[1529/1560] XGB       repeat 4 fold 1  macro-F1=0.9330  P1=0.874 R1=0.893  (26s)  [ratio 0.5, orig^0.5, C=0, rho=1.31]

[1530/1560] XGB       repeat 4 fold 1  macro-F1=0.9301  P1=0.861 R1=0.896  (82s)  [ratio 0.5, orig^0.5, C=1, rho=1.31]

[1531/1560] XGB       repeat 4 fold 1  macro-F1=0.9299  P1=0.853 R1=0.905  (26s)  [ratio 0.5, orig^0.75, C=0, rho=2.13]

[1532/1560] XGB       repeat 4 fold 1  macro-F1=0.9326  P1=0.867 R1=0.899  (81s)  [ratio 0.5, orig^0.75, C=1, rho=2.13]

[1533/1560] XGB       repeat 4 fold 1  macro-F1=0.9257  P1=0.825 R1=0.923  (25s)  [ratio 0.5, orig^1.0, C=0, rho=3.45]

[1534/1560] XGB       repeat 4 fold 1  macro-F1=0.9387  P1=0.890 R1=0.896  (79s)  [ratio 0.5, orig^1.0, C=1, rho=3.45]

[1535/1560] XGB       repeat 4 fold 1  macro-F1=0.9153  P1=0.803 R1=0.911  (25s)  [ratio 0.5, orig^1.25, C=0, rho=5.59]

[1536/1560] XGB       repeat 4 fold 1  macro-F1=0.9400  P1=0.916 R1=0.874  (78s)  [ratio 0.5, orig^1.25, C=1, rho=5.59]

[1537/1560] XGB       repeat 4 fold 1  macro-F1=0.9106  P1=0.778 R1=0.926  (24s)  [ratio 0.5, orig^1.5, C=0, rho=9.07]

[1538/1560] XGB       repeat 4 fold 1  macro-F1=0.9379  P1=0.903 R1=0.880  (75s)  [ratio 0.5, orig^1.5, C=1, rho=9.07]

[1539/1560] XGB       repeat 4 fold 1  macro-F1=0.8742  P1=0.681 R1=0.929  (23s)  [ratio 0.5, orig^2.0, C=0, rho=23.84]

[1540/1560] XGB       repeat 4 fold 1  macro-F1=0.9236  P1=0.835 R1=0.902  (69s)  [ratio 0.5, orig^2.0, C=1, rho=23.84]

[1541/1560] XGB       repeat 4 fold 1  macro-F1=0.9368  P1=0.875 R1=0.905  (26s)  [ratio 0.5, recalc^1.0, C=0, rho=1.00]

[1542/1560] XGB       repeat 4 fold 1  macro-F1=0.9390  P1=0.916 R1=0.871  (81s)  [ratio 0.5, recalc^1.0, C=1, rho=1.00]

[1543/1560] XGB       repeat 4 fold 1  macro-F1=0.9287  P1=0.854 R1=0.899  (30s)  [ratio 1.0, orig^0.0, C=0, rho=1.00]

[1544/1560] XGB       repeat 4 fold 1  macro-F1=0.9330  P1=0.874 R1=0.893  (95s)  [ratio 1.0, orig^0.0, C=1, rho=1.00]

[1545/1560] XGB       repeat 4 fold 1  macro-F1=0.9306  P1=0.855 R1=0.905  (30s)  [ratio 1.0, orig^0.25, C=0, rho=1.62]

[1546/1560] XGB       repeat 4 fold 1  macro-F1=0.9386  P1=0.893 R1=0.893  (94s)  [ratio 1.0, orig^0.25, C=1, rho=1.62]

[1547/1560] XGB       repeat 4 fold 1  macro-F1=0.9319  P1=0.851 R1=0.914  (30s)  [ratio 1.0, orig^0.5, C=0, rho=2.63]

[1548/1560] XGB       repeat 4 fold 1  macro-F1=0.9370  P1=0.887 R1=0.893  (93s)  [ratio 1.0, orig^0.5, C=1, rho=2.63]

[1549/1560] XGB       repeat 4 fold 1  macro-F1=0.9281  P1=0.839 R1=0.914  (30s)  [ratio 1.0, orig^0.75, C=0, rho=4.26]

[1550/1560] XGB       repeat 4 fold 1  macro-F1=0.9462  P1=0.929 R1=0.883  (90s)  [ratio 1.0, orig^0.75, C=1, rho=4.26]

[1551/1560] XGB       repeat 4 fold 1  macro-F1=0.9174  P1=0.802 R1=0.920  (29s)  [ratio 1.0, orig^1.0, C=0, rho=6.91]

[1552/1560] XGB       repeat 4 fold 1  macro-F1=0.9415  P1=0.909 R1=0.887  (86s)  [ratio 1.0, orig^1.0, C=1, rho=6.91]

[1553/1560] XGB       repeat 4 fold 1  macro-F1=0.9079  P1=0.777 R1=0.917  (28s)  [ratio 1.0, orig^1.25, C=0, rho=11.20]

[1554/1560] XGB       repeat 4 fold 1  macro-F1=0.9379  P1=0.903 R1=0.880  (74s)  [ratio 1.0, orig^1.25, C=1, rho=11.20]

[1555/1560] XGB       repeat 4 fold 1  macro-F1=0.8968  P1=0.740 R1=0.926  (28s)  [ratio 1.0, orig^1.5, C=0, rho=18.16]

[1556/1560] XGB       repeat 4 fold 1  macro-F1=0.9386  P1=0.893 R1=0.893  (59s)  [ratio 1.0, orig^1.5, C=1, rho=18.16]

[1557/1560] XGB       repeat 4 fold 1  macro-F1=0.8478  P1=0.620 R1=0.929  (26s)  [ratio 1.0, orig^2.0, C=0, rho=47.72]

[1558/1560] XGB       repeat 4 fold 1  macro-F1=0.9261  P1=0.851 R1=0.893  (52s)  [ratio 1.0, orig^2.0, C=1, rho=47.72]

[1559/1560] XGB       repeat 4 fold 1  macro-F1=0.9287  P1=0.854 R1=0.899  (28s)  [ratio 1.0, recalc^1.0, C=0, rho=1.00]

[1560/1560] XGB       repeat 4 fold 1  macro-F1=0.9330  P1=0.874 R1=0.893  (44s)  [ratio 1.0, recalc^1.0, C=1, rho=1.00]

## Macro-F1 by resampling ratio, weight setting and threshold tuning

In [4]:
results.pivot_table(index=["sampling_ratio", "weight_mode", "weight_power"],
                    columns=["classifier", "C"], values="macro_f1").round(4)

classifier                                   LR              RF          \
C                                             0       1       0       1
sampling_ratio weight_mode weight_power
0.0            orig        0.00          0.9512  0.9517  0.9040  0.9198
                           0.25          0.9506  0.9510  0.9123  0.9251
                           0.50          0.9504  0.9497  0.9187  0.9322
                           0.75          0.9497  0.9509  0.9256  0.9344
                           1.00          0.9469  0.9501  0.9287  0.9337
                           1.25          0.9431  0.9495  0.9307  0.9306
                           1.50          0.9374  0.9497  0.9232  0.9233
                           2.00          0.9178  0.9509  0.8729  0.9123
0.5            orig        0.00          0.9522  0.9535  0.9226  0.9344
                           0.25          0.9527  0.9527  0.9298  0.9317
                           0.50          0.9435  0.9527  0.9258  0.9257
                           0.75          0.9059  0.9527  0.9116  0.9183
                           1.00          0.8184  0.9526  0.8820  0.9123
                           1.25          0.6631  0.9524  0.8350  0.9037
                           1.50          0.4858  0.9515  0.7671  0.8930
                           2.00          0.2407  0.9527  0.5971  0.8802
               recalc      1.00          0.9498  0.9536  0.9282  0.9271
1.0            orig        0.00          0.9494  0.9526  0.9277  0.9283
                           0.25          0.9333  0.9516  0.9203  0.9218
                           0.50          0.8861  0.9517  0.9015  0.9144
                           0.75          0.7969  0.9519  0.8687  0.9066
                           1.00          0.6518  0.9516  0.8113  0.8972
                           1.25          0.4841  0.9512  0.7548  0.8909
                           1.50          0.3539  0.9517  0.6836  0.8835
                           2.00          0.1520  0.9516  0.5145  0.8653
               recalc      1.00          0.9494  0.9526  0.9277  0.9283

classifier                                  XGB
C                                             0       1
sampling_ratio weight_mode weight_power
0.0            orig        0.00          0.9468  0.9465
                           0.25          0.9464  0.9454
                           0.50          0.9467  0.9460
                           0.75          0.9469  0.9458
                           1.00          0.9426  0.9453
                           1.25          0.9392  0.9416
                           1.50          0.9376  0.9436
                           2.00          0.9309  0.9423
0.5            orig        0.00          0.9468  0.9470
                           0.25          0.9444  0.9456
                           0.50          0.9406  0.9468
                           0.75          0.9371  0.9459
                           1.00          0.9302  0.9447
                           1.25          0.9258  0.9461
                           1.50          0.9181  0.9454
                           2.00          0.8855  0.9399
               recalc      1.00          0.9418  0.9447
1.0            orig        0.00          0.9392  0.9443
                           0.25          0.9364  0.9460
                           0.50          0.9333  0.9462
                           0.75          0.9311  0.9457
                           1.00          0.9211  0.9473
                           1.25          0.9139  0.9464
                           1.50          0.9018  0.9418
                           2.00          0.8552  0.9391
               recalc      1.00          0.9392  0.9443

In [5]:
results.groupby(["sampling_ratio", "weight_mode", "weight_power"])[["rho_eff", "precision_1", "recall_1", "ppr_ratio"]].mean().round(3)

                                         rho_eff  precision_1  recall_1  \
sampling_ratio weight_mode weight_power
0.0            orig        0.00            0.145        0.936     0.851
                           0.25            0.234        0.932     0.860
                           0.50            0.380        0.930     0.868
                           0.75            0.617        0.923     0.878
                           1.00            1.000        0.914     0.882
                           1.25            1.622        0.901     0.888
                           1.50            2.630        0.884     0.894
                           2.00            6.919        0.837     0.902
0.5            orig        0.00            0.500        0.935     0.870
                           0.25            0.810        0.922     0.880
                           0.50            1.314        0.897     0.892
                           0.75            2.132        0.860     0.899
                           1.00            3.457        0.810     0.904
                           1.25            5.607        0.759     0.908
                           1.50            9.094        0.712     0.906
                           2.00           23.920        0.636     0.912
               recalc      1.00            1.000        0.910     0.885
1.0            orig        0.00            1.000        0.908     0.885
                           0.25            1.622        0.883     0.893
                           0.50            2.630        0.844     0.899
                           0.75            4.266        0.798     0.904
                           1.00            6.919        0.748     0.905
                           1.25           11.221        0.702     0.909
                           1.50           18.199        0.664     0.911
                           2.00           47.871        0.606     0.909
               recalc      1.00            1.000        0.908     0.885

                                         ppr_ratio
sampling_ratio weight_mode weight_power
0.0            orig        0.00              0.912
                           0.25              0.926
                           0.50              0.937
                           0.75              0.953
                           1.00              0.966
                           1.25              0.987
                           1.50              1.013
                           2.00              1.095
0.5            orig        0.00              0.933
                           0.25              0.956
                           0.50              0.996
                           0.75              1.057
                           1.00              1.194
                           1.25              1.468
                           1.50              1.796
                           2.00              2.446
               recalc      1.00              0.973
1.0            orig        0.00              0.976
                           0.25              1.016
                           0.50              1.086
                           0.75              1.234
                           1.00              1.512
                           1.25              1.824
                           1.50              2.132
                           2.00              2.738
               recalc      1.00              0.976